// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00000800;

// Working space registers
rx unsigned short R0  absolute 0x0070;
rx unsigned short R1  absolute 0x0071;
rx unsigned short R2  absolute 0x0072;
rx unsigned short R3  absolute 0x0073;
rx unsigned short R4  absolute 0x0074;
rx unsigned short R5  absolute 0x0075;
rx unsigned short R6  absolute 0x0076;
rx unsigned short R7  absolute 0x0077;
rx unsigned short R8  absolute 0x0078;
rx unsigned short R9  absolute 0x0079;
rx unsigned short R10 absolute 0x007A;
rx unsigned short R11 absolute 0x007B;
rx unsigned short R12 absolute 0x007C;
rx unsigned short R13 absolute 0x007D;
rx unsigned short R14 absolute 0x007E;
rx unsigned short R15 absolute 0x007F;

const register unsigned short int W = 0;
const register unsigned short int F = 1;

// Special function registers (SFRs)

const signed int   PORT_TO_TRIS_OFFSET    =     128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

sfr unsigned short volatile INDF0            absolute 0x000;
sfr unsigned short volatile INDF1            absolute 0x001;
sfr unsigned short volatile PCL              absolute 0x002;
sfr unsigned short volatile STATUS           absolute 0x003;
    const register unsigned short int CARRY = 0;
    const register unsigned short int C = 0;
    sbit  CARRY_bit at STATUS.B0;
    sbit  C_bit at STATUS.B0;
    const register unsigned short int DC = 1;
    sbit  DC_bit at STATUS.B1;
    const register unsigned short int ZERO = 2;
    const register unsigned short int Z = 2;
    sbit  ZERO_bit at STATUS.B2;
    sbit  Z_bit at STATUS.B2;
    const register unsigned short int nPD = 3;
    sbit  nPD_bit at STATUS.B3;
    const register unsigned short int nTO = 4;
    sbit  nTO_bit at STATUS.B4;

sfr unsigned int            FSR0             absolute 0x004;
sfr unsigned short          FSR0L            absolute 0x004;
register unsigned short     *FSR0PTR         absolute 0x004;
sfr unsigned short          FSR0H            absolute 0x005;
sfr unsigned int            FSR1             absolute 0x006;
sfr unsigned short          FSR1L            absolute 0x006;
register unsigned short     *FSR1PTR         absolute 0x006;
sfr unsigned short          FSR1H            absolute 0x007;
sfr unsigned short          BSR              absolute 0x008;
    const register unsigned short int BSR0 = 0;
    sbit  BSR0_bit at BSR.B0;
    const register unsigned short int BSR1 = 1;
    sbit  BSR1_bit at BSR.B1;
    const register unsigned short int BSR2 = 2;
    sbit  BSR2_bit at BSR.B2;
    const register unsigned short int BSR3 = 3;
    sbit  BSR3_bit at BSR.B3;
    const register unsigned short int BSR4 = 4;
    sbit  BSR4_bit at BSR.B4;

sfr unsigned short volatile WREG             absolute 0x009;
sfr unsigned short volatile PCLATH           absolute 0x00A;
sfr unsigned short volatile INTCON           absolute 0x00B;
    const register unsigned short int IOCIF = 0;
    sbit  IOCIF_bit at INTCON.B0;
    const register unsigned short int INTF = 1;
    sbit  INTF_bit at INTCON.B1;
    const register unsigned short int T0IF = 2;
    sbit  T0IF_bit at INTCON.B2;
    const register unsigned short int IOCIE = 3;
    sbit  IOCIE_bit at INTCON.B3;
    const register unsigned short int INTE = 4;
    sbit  INTE_bit at INTCON.B4;
    const register unsigned short int T0IE = 5;
    sbit  T0IE_bit at INTCON.B5;
    const register unsigned short int PEIE = 6;
    sbit  PEIE_bit at INTCON.B6;
    const register unsigned short int GIE = 7;
    sbit  GIE_bit at INTCON.B7;
    const register unsigned short int TMR0IE = 5;
    sbit  TMR0IE_bit at INTCON.B5;
    const register unsigned short int TMR0IF = 2;
    sbit  TMR0IF_bit at INTCON.B2;

sfr unsigned short volatile PORTA            absolute 0x00C;
    const register unsigned short int RA0 = 0;
    sbit  RA0_bit at PORTA.B0;
    const register unsigned short int RA1 = 1;
    sbit  RA1_bit at PORTA.B1;
    const register unsigned short int RA2 = 2;
    sbit  RA2_bit at PORTA.B2;
    const register unsigned short int RA3 = 3;
    sbit  RA3_bit at PORTA.B3;
    const register unsigned short int RA4 = 4;
    sbit  RA4_bit at PORTA.B4;
    const register unsigned short int RA5 = 5;
    sbit  RA5_bit at PORTA.B5;

sfr unsigned short volatile PORTB            absolute 0x00D;
    const register unsigned short int RB4 = 4;
    sbit  RB4_bit at PORTB.B4;
    const register unsigned short int RB5 = 5;
    sbit  RB5_bit at PORTB.B5;
    const register unsigned short int RB6 = 6;
    sbit  RB6_bit at PORTB.B6;
    const register unsigned short int RB7 = 7;
    sbit  RB7_bit at PORTB.B7;

sfr unsigned short volatile PORTC            absolute 0x00E;
    const register unsigned short int RC0 = 0;
    sbit  RC0_bit at PORTC.B0;
    const register unsigned short int RC1 = 1;
    sbit  RC1_bit at PORTC.B1;
    const register unsigned short int RC2 = 2;
    sbit  RC2_bit at PORTC.B2;
    const register unsigned short int RC3 = 3;
    sbit  RC3_bit at PORTC.B3;
    const register unsigned short int RC4 = 4;
    sbit  RC4_bit at PORTC.B4;
    const register unsigned short int RC5 = 5;
    sbit  RC5_bit at PORTC.B5;
    const register unsigned short int RC6 = 6;
    sbit  RC6_bit at PORTC.B6;
    const register unsigned short int RC7 = 7;
    sbit  RC7_bit at PORTC.B7;

sfr unsigned short volatile PIR1             absolute 0x011;
    const register unsigned short int TMR1IF = 0;
    sbit  TMR1IF_bit at PIR1.B0;
    const register unsigned short int TMR2IF = 1;
    sbit  TMR2IF_bit at PIR1.B1;
    const register unsigned short int CCP1IF = 2;
    sbit  CCP1IF_bit at PIR1.B2;
    const register unsigned short int SSP1IF = 3;
    sbit  SSP1IF_bit at PIR1.B3;
    const register unsigned short int ADIF = 6;
    sbit  ADIF_bit at PIR1.B6;
    const register unsigned short int TMR1GIF = 7;
    sbit  TMR1GIF_bit at PIR1.B7;
    const register unsigned short int CCPIF = 2;
    sbit  CCPIF_bit at PIR1.B2;

sfr unsigned short volatile PIR2             absolute 0x012;
    const register unsigned short int CCP2IF = 0;
    sbit  CCP2IF_bit at PIR2.B0;
    const register unsigned short int BCL1IF = 3;
    sbit  BCL1IF_bit at PIR2.B3;

sfr unsigned short volatile PIR3             absolute 0x013;
    const register unsigned short int ZCDIF = 4;
    sbit  ZCDIF_bit at PIR3.B4;

sfr unsigned short volatile TMR0             absolute 0x015;
sfr unsigned int   volatile TMR1             absolute 0x016;
sfr unsigned short volatile TMR1L            absolute 0x016;
sfr unsigned short volatile TMR1H            absolute 0x017;
sfr unsigned short volatile T1CON            absolute 0x018;
    const register unsigned short int TMR1ON = 0;
    sbit  TMR1ON_bit at T1CON.B0;
    const register unsigned short int nT1SYNC = 2;
    sbit  nT1SYNC_bit at T1CON.B2;
    const register unsigned short int T1OSCEN = 3;
    sbit  T1OSCEN_bit at T1CON.B3;
    const register unsigned short int T1CKPS0 = 4;
    sbit  T1CKPS0_bit at T1CON.B4;
    const register unsigned short int T1CKPS1 = 5;
    sbit  T1CKPS1_bit at T1CON.B5;
    const register unsigned short int TMR1CS0 = 6;
    sbit  TMR1CS0_bit at T1CON.B6;
    const register unsigned short int TMR1CS1 = 7;
    sbit  TMR1CS1_bit at T1CON.B7;

sfr unsigned short volatile T1GCON           absolute 0x019;
    const register unsigned short int T1GSS0 = 0;
    sbit  T1GSS0_bit at T1GCON.B0;
    const register unsigned short int T1GSS1 = 1;
    sbit  T1GSS1_bit at T1GCON.B1;
    const register unsigned short int T1GVAL = 2;
    sbit  T1GVAL_bit at T1GCON.B2;
    const register unsigned short int T1GGO_nDONE = 3;
    sbit  T1GGO_nDONE_bit at T1GCON.B3;
    const register unsigned short int T1GSPM = 4;
    sbit  T1GSPM_bit at T1GCON.B4;
    const register unsigned short int T1GTM = 5;
    sbit  T1GTM_bit at T1GCON.B5;
    const register unsigned short int T1GPOL = 6;
    sbit  T1GPOL_bit at T1GCON.B6;
    const register unsigned short int TMR1GE = 7;
    sbit  TMR1GE_bit at T1GCON.B7;

sfr unsigned short volatile TMR2             absolute 0x01A;
sfr unsigned short volatile PR2              absolute 0x01B;
sfr unsigned short volatile T2CON            absolute 0x01C;
    const register unsigned short int T2CKPS0 = 0;
    sbit  T2CKPS0_bit at T2CON.B0;
    const register unsigned short int T2CKPS1 = 1;
    sbit  T2CKPS1_bit at T2CON.B1;
    const register unsigned short int TMR2ON = 2;
    sbit  TMR2ON_bit at T2CON.B2;
    const register unsigned short int T2OUTPS0 = 3;
    sbit  T2OUTPS0_bit at T2CON.B3;
    const register unsigned short int T2OUTPS1 = 4;
    sbit  T2OUTPS1_bit at T2CON.B4;
    const register unsigned short int T2OUTPS2 = 5;
    sbit  T2OUTPS2_bit at T2CON.B5;
    const register unsigned short int T2OUTPS3 = 6;
    sbit  T2OUTPS3_bit at T2CON.B6;

sfr unsigned short volatile TRISA            absolute 0x08C;
    const register unsigned short int TRISA0 = 0;
    sbit  TRISA0_bit at TRISA.B0;
    const register unsigned short int TRISA1 = 1;
    sbit  TRISA1_bit at TRISA.B1;
    const register unsigned short int TRISA2 = 2;
    sbit  TRISA2_bit at TRISA.B2;
    const register unsigned short int TRISA4 = 4;
    sbit  TRISA4_bit at TRISA.B4;
    const register unsigned short int TRISA5 = 5;
    sbit  TRISA5_bit at TRISA.B5;

sfr unsigned short volatile TRISB            absolute 0x08D;
    const register unsigned short int TRISB4 = 4;
    sbit  TRISB4_bit at TRISB.B4;
    const register unsigned short int TRISB5 = 5;
    sbit  TRISB5_bit at TRISB.B5;
    const register unsigned short int TRISB6 = 6;
    sbit  TRISB6_bit at TRISB.B6;
    const register unsigned short int TRISB7 = 7;
    sbit  TRISB7_bit at TRISB.B7;

sfr unsigned short volatile TRISC            absolute 0x08E;
    const register unsigned short int TRISC0 = 0;
    sbit  TRISC0_bit at TRISC.B0;
    const register unsigned short int TRISC1 = 1;
    sbit  TRISC1_bit at TRISC.B1;
    const register unsigned short int TRISC2 = 2;
    sbit  TRISC2_bit at TRISC.B2;
    const register unsigned short int TRISC3 = 3;
    sbit  TRISC3_bit at TRISC.B3;
    const register unsigned short int TRISC4 = 4;
    sbit  TRISC4_bit at TRISC.B4;
    const register unsigned short int TRISC5 = 5;
    sbit  TRISC5_bit at TRISC.B5;
    const register unsigned short int TRISC6 = 6;
    sbit  TRISC6_bit at TRISC.B6;
    const register unsigned short int TRISC7 = 7;
    sbit  TRISC7_bit at TRISC.B7;

sfr unsigned short volatile PIE1             absolute 0x091;
    const register unsigned short int TMR1IE = 0;
    sbit  TMR1IE_bit at PIE1.B0;
    const register unsigned short int TMR2IE = 1;
    sbit  TMR2IE_bit at PIE1.B1;
    const register unsigned short int CCP1IE = 2;
    sbit  CCP1IE_bit at PIE1.B2;
    const register unsigned short int SSP1IE = 3;
    sbit  SSP1IE_bit at PIE1.B3;
    const register unsigned short int ADIE = 6;
    sbit  ADIE_bit at PIE1.B6;
    const register unsigned short int TMR1GIE = 7;
    sbit  TMR1GIE_bit at PIE1.B7;
    const register unsigned short int CCPIE = 2;
    sbit  CCPIE_bit at PIE1.B2;

sfr unsigned short volatile PIE2             absolute 0x092;
    const register unsigned short int CCP2IE = 0;
    sbit  CCP2IE_bit at PIE2.B0;
    const register unsigned short int BCL1IE = 3;
    sbit  BCL1IE_bit at PIE2.B3;

sfr unsigned short volatile PIE3             absolute 0x093;
    const register unsigned short int ZCDIE = 4;
    sbit  ZCDIE_bit at PIE3.B4;

sfr unsigned short volatile OPTION_REG       absolute 0x095;
    const register unsigned short int PS0 = 0;
    sbit  PS0_bit at OPTION_REG.B0;
    const register unsigned short int PS1 = 1;
    sbit  PS1_bit at OPTION_REG.B1;
    const register unsigned short int PS2 = 2;
    sbit  PS2_bit at OPTION_REG.B2;
    const register unsigned short int PSA = 3;
    sbit  PSA_bit at OPTION_REG.B3;
    const register unsigned short int T0SE = 4;
    sbit  T0SE_bit at OPTION_REG.B4;
    const register unsigned short int T0CS = 5;
    sbit  T0CS_bit at OPTION_REG.B5;
    const register unsigned short int INTEDG = 6;
    sbit  INTEDG_bit at OPTION_REG.B6;
    const register unsigned short int nWPUEN = 7;
    sbit  nWPUEN_bit at OPTION_REG.B7;
    const register unsigned short int TMR0CS = 5;
    sbit  TMR0CS_bit at OPTION_REG.B5;
    const register unsigned short int TMR0SE = 4;
    sbit  TMR0SE_bit at OPTION_REG.B4;

sfr unsigned short volatile PCON             absolute 0x096;
    const register unsigned short int nBOR = 0;
    sbit  nBOR_bit at PCON.B0;
    const register unsigned short int nPOR = 1;
    sbit  nPOR_bit at PCON.B1;
    const register unsigned short int nRI = 2;
    sbit  nRI_bit at PCON.B2;
    const register unsigned short int nRMCLR = 3;
    sbit  nRMCLR_bit at PCON.B3;
    const register unsigned short int nRWDT = 4;
    sbit  nRWDT_bit at PCON.B4;
    const register unsigned short int STKUNF = 6;
    sbit  STKUNF_bit at PCON.B6;
    const register unsigned short int STKOVF = 7;
    sbit  STKOVF_bit at PCON.B7;

sfr unsigned short          WDTCON           absolute 0x097;
    const register unsigned short int SWDTEN = 0;
    sbit  SWDTEN_bit at WDTCON.B0;
    const register unsigned short int WDTPS0 = 1;
    sbit  WDTPS0_bit at WDTCON.B1;
    const register unsigned short int WDTPS1 = 2;
    sbit  WDTPS1_bit at WDTCON.B2;
    const register unsigned short int WDTPS2 = 3;
    sbit  WDTPS2_bit at WDTCON.B3;
    const register unsigned short int WDTPS3 = 4;
    sbit  WDTPS3_bit at WDTCON.B4;
    const register unsigned short int WDTPS4 = 5;
    sbit  WDTPS4_bit at WDTCON.B5;

sfr unsigned short volatile OSCTUNE          absolute 0x098;
    const register unsigned short int TUN0 = 0;
    sbit  TUN0_bit at OSCTUNE.B0;
    const register unsigned short int TUN1 = 1;
    sbit  TUN1_bit at OSCTUNE.B1;
    const register unsigned short int TUN2 = 2;
    sbit  TUN2_bit at OSCTUNE.B2;
    const register unsigned short int TUN3 = 3;
    sbit  TUN3_bit at OSCTUNE.B3;
    const register unsigned short int TUN4 = 4;
    sbit  TUN4_bit at OSCTUNE.B4;
    const register unsigned short int TUN5 = 5;
    sbit  TUN5_bit at OSCTUNE.B5;

sfr unsigned short volatile OSCCON           absolute 0x099;
    const register unsigned short int SCS0 = 0;
    sbit  SCS0_bit at OSCCON.B0;
    const register unsigned short int SCS1 = 1;
    sbit  SCS1_bit at OSCCON.B1;
    const register unsigned short int IRCF0 = 3;
    sbit  IRCF0_bit at OSCCON.B3;
    const register unsigned short int IRCF1 = 4;
    sbit  IRCF1_bit at OSCCON.B4;
    const register unsigned short int IRCF2 = 5;
    sbit  IRCF2_bit at OSCCON.B5;
    const register unsigned short int IRCF3 = 6;
    sbit  IRCF3_bit at OSCCON.B6;
    const register unsigned short int SPLLEN = 7;
    sbit  SPLLEN_bit at OSCCON.B7;

sfr unsigned short volatile OSCSTAT          absolute 0x09A;
    const register unsigned short int HFIOFS = 0;
    sbit  HFIOFS_bit at OSCSTAT.B0;
    const register unsigned short int LFIOFR = 1;
    sbit  LFIOFR_bit at OSCSTAT.B1;
    const register unsigned short int MFIOFR = 2;
    sbit  MFIOFR_bit at OSCSTAT.B2;
    const register unsigned short int HFIOFL = 3;
    sbit  HFIOFL_bit at OSCSTAT.B3;
    const register unsigned short int HFIOFR = 4;
    sbit  HFIOFR_bit at OSCSTAT.B4;
    const register unsigned short int OSTS = 5;
    sbit  OSTS_bit at OSCSTAT.B5;
    const register unsigned short int PLLR = 6;
    sbit  PLLR_bit at OSCSTAT.B6;
    const register unsigned short int SOSCR = 7;
    sbit  SOSCR_bit at OSCSTAT.B7;

sfr unsigned int   volatile ADRES            absolute 0x09B;
sfr unsigned short volatile ADRESL           absolute 0x09B;
sfr unsigned short volatile ADRESH           absolute 0x09C;
sfr unsigned short volatile ADCON0           absolute 0x09D;
    const register unsigned short int ADON = 0;
    sbit  ADON_bit at ADCON0.B0;
    const register unsigned short int ADGO = 1;
    sbit  ADGO_bit at ADCON0.B1;
    const register unsigned short int CHS0 = 2;
    sbit  CHS0_bit at ADCON0.B2;
    const register unsigned short int CHS1 = 3;
    sbit  CHS1_bit at ADCON0.B3;
    const register unsigned short int CHS2 = 4;
    sbit  CHS2_bit at ADCON0.B4;
    const register unsigned short int CHS3 = 5;
    sbit  CHS3_bit at ADCON0.B5;
    const register unsigned short int CHS4 = 6;
    sbit  CHS4_bit at ADCON0.B6;
    const register unsigned short int GO = 1;
    sbit  GO_bit at ADCON0.B1;
    const register unsigned short int GO_nDONE = 1;
    sbit  GO_nDONE_bit at ADCON0.B1;
    const register unsigned short int GO_NOT_DONE = 1;
    sbit  GO_NOT_DONE_bit at ADCON0.B1;

sfr unsigned short volatile ADCON1           absolute 0x09E;
    const register unsigned short int ADPREF0 = 0;
    sbit  ADPREF0_bit at ADCON1.B0;
    const register unsigned short int ADPREF1 = 1;
    sbit  ADPREF1_bit at ADCON1.B1;
    const register unsigned short int ADNREF = 2;
    sbit  ADNREF_bit at ADCON1.B2;
    const register unsigned short int ADFM = 7;
    sbit  ADFM_bit at ADCON1.B7;

sfr unsigned short volatile ADCON2           absolute 0x09F;
    const register unsigned short int TRIGSEL0 = 4;
    sbit  TRIGSEL0_bit at ADCON2.B4;
    const register unsigned short int TRIGSEL1 = 5;
    sbit  TRIGSEL1_bit at ADCON2.B5;
    const register unsigned short int TRIGSEL2 = 6;
    sbit  TRIGSEL2_bit at ADCON2.B6;
    const register unsigned short int TRIGSEL3 = 7;
    sbit  TRIGSEL3_bit at ADCON2.B7;

sfr unsigned short volatile LATA             absolute 0x10C;
    const register unsigned short int LATA0 = 0;
    sbit  LATA0_bit at LATA.B0;
    const register unsigned short int LATA1 = 1;
    sbit  LATA1_bit at LATA.B1;
    const register unsigned short int LATA2 = 2;
    sbit  LATA2_bit at LATA.B2;
    const register unsigned short int LATA4 = 4;
    sbit  LATA4_bit at LATA.B4;
    const register unsigned short int LATA5 = 5;
    sbit  LATA5_bit at LATA.B5;

sfr unsigned short volatile LATB             absolute 0x10D;
    const register unsigned short int LATB4 = 4;
    sbit  LATB4_bit at LATB.B4;
    const register unsigned short int LATB5 = 5;
    sbit  LATB5_bit at LATB.B5;
    const register unsigned short int LATB6 = 6;
    sbit  LATB6_bit at LATB.B6;
    const register unsigned short int LATB7 = 7;
    sbit  LATB7_bit at LATB.B7;

sfr unsigned short volatile LATC             absolute 0x10E;
    const register unsigned short int LATC0 = 0;
    sbit  LATC0_bit at LATC.B0;
    const register unsigned short int LATC1 = 1;
    sbit  LATC1_bit at LATC.B1;
    const register unsigned short int LATC2 = 2;
    sbit  LATC2_bit at LATC.B2;
    const register unsigned short int LATC3 = 3;
    sbit  LATC3_bit at LATC.B3;
    const register unsigned short int LATC4 = 4;
    sbit  LATC4_bit at LATC.B4;
    const register unsigned short int LATC5 = 5;
    sbit  LATC5_bit at LATC.B5;
    const register unsigned short int LATC6 = 6;
    sbit  LATC6_bit at LATC.B6;
    const register unsigned short int LATC7 = 7;
    sbit  LATC7_bit at LATC.B7;

sfr unsigned short volatile BORCON           absolute 0x116;
    const register unsigned short int BORRDY = 0;
    sbit  BORRDY_bit at BORCON.B0;
    const register unsigned short int BORFS = 6;
    sbit  BORFS_bit at BORCON.B6;
    const register unsigned short int SBOREN = 7;
    sbit  SBOREN_bit at BORCON.B7;

sfr unsigned short volatile FVRCON           absolute 0x117;
    const register unsigned short int ADFVR0 = 0;
    sbit  ADFVR0_bit at FVRCON.B0;
    const register unsigned short int ADFVR1 = 1;
    sbit  ADFVR1_bit at FVRCON.B1;
    const register unsigned short int CDAFVR0 = 2;
    sbit  CDAFVR0_bit at FVRCON.B2;
    const register unsigned short int CDAFVR1 = 3;
    sbit  CDAFVR1_bit at FVRCON.B3;
    const register unsigned short int TSRNG = 4;
    sbit  TSRNG_bit at FVRCON.B4;
    const register unsigned short int TSEN = 5;
    sbit  TSEN_bit at FVRCON.B5;
    const register unsigned short int FVRRDY = 6;
    sbit  FVRRDY_bit at FVRCON.B6;
    const register unsigned short int FVREN = 7;
    sbit  FVREN_bit at FVRCON.B7;

sfr unsigned short volatile ZCD1CON          absolute 0x11C;
    const register unsigned short int ZCD1INTN = 0;
    sbit  ZCD1INTN_bit at ZCD1CON.B0;
    const register unsigned short int ZCD1INTP = 1;
    sbit  ZCD1INTP_bit at ZCD1CON.B1;
    const register unsigned short int ZCD1POL = 4;
    sbit  ZCD1POL_bit at ZCD1CON.B4;
    const register unsigned short int ZCD1OUT = 5;
    sbit  ZCD1OUT_bit at ZCD1CON.B5;
    const register unsigned short int ZCD1EN = 7;
    sbit  ZCD1EN_bit at ZCD1CON.B7;

sfr unsigned short volatile ANSELA           absolute 0x18C;
    const register unsigned short int ANSA0 = 0;
    sbit  ANSA0_bit at ANSELA.B0;
    const register unsigned short int ANSA1 = 1;
    sbit  ANSA1_bit at ANSELA.B1;
    const register unsigned short int ANSA2 = 2;
    sbit  ANSA2_bit at ANSELA.B2;
    const register unsigned short int ANSA4 = 4;
    sbit  ANSA4_bit at ANSELA.B4;

sfr unsigned short volatile ANSELB           absolute 0x18D;
    const register unsigned short int ANSB4 = 4;
    sbit  ANSB4_bit at ANSELB.B4;
    const register unsigned short int ANSB5 = 5;
    sbit  ANSB5_bit at ANSELB.B5;

sfr unsigned short volatile ANSELC           absolute 0x18E;
    const register unsigned short int ANSC0 = 0;
    sbit  ANSC0_bit at ANSELC.B0;
    const register unsigned short int ANSC1 = 1;
    sbit  ANSC1_bit at ANSELC.B1;
    const register unsigned short int ANSC2 = 2;
    sbit  ANSC2_bit at ANSELC.B2;
    const register unsigned short int ANSC3 = 3;
    sbit  ANSC3_bit at ANSELC.B3;
    const register unsigned short int ANSC6 = 6;
    sbit  ANSC6_bit at ANSELC.B6;
    const register unsigned short int ANSC7 = 7;
    sbit  ANSC7_bit at ANSELC.B7;

sfr unsigned int   volatile PMADR            absolute 0x191;
sfr unsigned short volatile PMADRL           absolute 0x191;
sfr unsigned short volatile PMADRH           absolute 0x192;
sfr unsigned int   volatile PMDAT            absolute 0x193;
sfr unsigned short volatile PMDATL           absolute 0x193;
sfr unsigned short volatile PMDATH           absolute 0x194;
sfr unsigned short volatile PMCON1           absolute 0x195;
    const register unsigned short int RD = 0;
    sbit  RD_bit at PMCON1.B0;
    const register unsigned short int WR = 1;
    sbit  WR_bit at PMCON1.B1;
    const register unsigned short int WREN = 2;
    sbit  WREN_bit at PMCON1.B2;
    const register unsigned short int WRERR = 3;
    sbit  WRERR_bit at PMCON1.B3;
    const register unsigned short int FREE = 4;
    sbit  FREE_bit at PMCON1.B4;
    const register unsigned short int LWLO = 5;
    sbit  LWLO_bit at PMCON1.B5;
    const register unsigned short int CFGS = 6;
    sbit  CFGS_bit at PMCON1.B6;

sfr unsigned short volatile PMCON2           absolute 0x196;
sfr unsigned short volatile VREGCON          absolute 0x197;
    const register unsigned short int VREGPM = 1;
    sbit  VREGPM_bit at VREGCON.B1;

sfr unsigned short          WPUA             absolute 0x20C;
    const register unsigned short int WPUA0 = 0;
    sbit  WPUA0_bit at WPUA.B0;
    const register unsigned short int WPUA1 = 1;
    sbit  WPUA1_bit at WPUA.B1;
    const register unsigned short int WPUA2 = 2;
    sbit  WPUA2_bit at WPUA.B2;
    const register unsigned short int WPUA3 = 3;
    sbit  WPUA3_bit at WPUA.B3;
    const register unsigned short int WPUA4 = 4;
    sbit  WPUA4_bit at WPUA.B4;
    const register unsigned short int WPUA5 = 5;
    sbit  WPUA5_bit at WPUA.B5;

sfr unsigned short          WPUB             absolute 0x20D;
    const register unsigned short int WPUB4 = 4;
    sbit  WPUB4_bit at WPUB.B4;
    const register unsigned short int WPUB5 = 5;
    sbit  WPUB5_bit at WPUB.B5;
    const register unsigned short int WPUB6 = 6;
    sbit  WPUB6_bit at WPUB.B6;
    const register unsigned short int WPUB7 = 7;
    sbit  WPUB7_bit at WPUB.B7;

sfr unsigned short volatile WPUC             absolute 0x20E;
    const register unsigned short int WPUC0 = 0;
    sbit  WPUC0_bit at WPUC.B0;
    const register unsigned short int WPUC1 = 1;
    sbit  WPUC1_bit at WPUC.B1;
    const register unsigned short int WPUC2 = 2;
    sbit  WPUC2_bit at WPUC.B2;
    const register unsigned short int WPUC3 = 3;
    sbit  WPUC3_bit at WPUC.B3;
    const register unsigned short int WPUC4 = 4;
    sbit  WPUC4_bit at WPUC.B4;
    const register unsigned short int WPUC5 = 5;
    sbit  WPUC5_bit at WPUC.B5;
    const register unsigned short int WPUC6 = 6;
    sbit  WPUC6_bit at WPUC.B6;
    const register unsigned short int WPUC7 = 7;
    sbit  WPUC7_bit at WPUC.B7;

sfr unsigned short volatile SSP1BUF          absolute 0x211;
    const register unsigned short int BUF0 = 0;
    sbit  BUF0_bit at SSP1BUF.B0;
    const register unsigned short int BUF1 = 1;
    sbit  BUF1_bit at SSP1BUF.B1;
    const register unsigned short int BUF2 = 2;
    sbit  BUF2_bit at SSP1BUF.B2;
    const register unsigned short int BUF3 = 3;
    sbit  BUF3_bit at SSP1BUF.B3;
    const register unsigned short int BUF4 = 4;
    sbit  BUF4_bit at SSP1BUF.B4;
    const register unsigned short int BUF5 = 5;
    sbit  BUF5_bit at SSP1BUF.B5;
    const register unsigned short int BUF6 = 6;
    sbit  BUF6_bit at SSP1BUF.B6;
    const register unsigned short int BUF7 = 7;
    sbit  BUF7_bit at SSP1BUF.B7;
    const register unsigned short int SSP1BUF0 = 0;
    sbit  SSP1BUF0_bit at SSP1BUF.B0;
    const register unsigned short int SSP1BUF1 = 1;
    sbit  SSP1BUF1_bit at SSP1BUF.B1;
    const register unsigned short int SSP1BUF2 = 2;
    sbit  SSP1BUF2_bit at SSP1BUF.B2;
    const register unsigned short int SSP1BUF3 = 3;
    sbit  SSP1BUF3_bit at SSP1BUF.B3;
    const register unsigned short int SSP1BUF4 = 4;
    sbit  SSP1BUF4_bit at SSP1BUF.B4;
    const register unsigned short int SSP1BUF5 = 5;
    sbit  SSP1BUF5_bit at SSP1BUF.B5;
    const register unsigned short int SSP1BUF6 = 6;
    sbit  SSP1BUF6_bit at SSP1BUF.B6;
    const register unsigned short int SSP1BUF7 = 7;
    sbit  SSP1BUF7_bit at SSP1BUF.B7;

sfr unsigned short volatile SSPBUF           absolute 0x211;
sfr unsigned short volatile SSP1ADD          absolute 0x212;
    const register unsigned short int ADD0 = 0;
    sbit  ADD0_bit at SSP1ADD.B0;
    const register unsigned short int ADD1 = 1;
    sbit  ADD1_bit at SSP1ADD.B1;
    const register unsigned short int ADD2 = 2;
    sbit  ADD2_bit at SSP1ADD.B2;
    const register unsigned short int ADD3 = 3;
    sbit  ADD3_bit at SSP1ADD.B3;
    const register unsigned short int ADD4 = 4;
    sbit  ADD4_bit at SSP1ADD.B4;
    const register unsigned short int ADD5 = 5;
    sbit  ADD5_bit at SSP1ADD.B5;
    const register unsigned short int ADD6 = 6;
    sbit  ADD6_bit at SSP1ADD.B6;
    const register unsigned short int ADD7 = 7;
    sbit  ADD7_bit at SSP1ADD.B7;
    const register unsigned short int SSP1ADD0 = 0;
    sbit  SSP1ADD0_bit at SSP1ADD.B0;
    const register unsigned short int SSP1ADD1 = 1;
    sbit  SSP1ADD1_bit at SSP1ADD.B1;
    const register unsigned short int SSP1ADD2 = 2;
    sbit  SSP1ADD2_bit at SSP1ADD.B2;
    const register unsigned short int SSP1ADD3 = 3;
    sbit  SSP1ADD3_bit at SSP1ADD.B3;
    const register unsigned short int SSP1ADD4 = 4;
    sbit  SSP1ADD4_bit at SSP1ADD.B4;
    const register unsigned short int SSP1ADD5 = 5;
    sbit  SSP1ADD5_bit at SSP1ADD.B5;
    const register unsigned short int SSP1ADD6 = 6;
    sbit  SSP1ADD6_bit at SSP1ADD.B6;
    const register unsigned short int SSP1ADD7 = 7;
    sbit  SSP1ADD7_bit at SSP1ADD.B7;

sfr unsigned short volatile SSPADD           absolute 0x212;
sfr unsigned short volatile SSP1MSK          absolute 0x213;
    const register unsigned short int MSK0 = 0;
    sbit  MSK0_bit at SSP1MSK.B0;
    const register unsigned short int MSK1 = 1;
    sbit  MSK1_bit at SSP1MSK.B1;
    const register unsigned short int MSK2 = 2;
    sbit  MSK2_bit at SSP1MSK.B2;
    const register unsigned short int MSK3 = 3;
    sbit  MSK3_bit at SSP1MSK.B3;
    const register unsigned short int MSK4 = 4;
    sbit  MSK4_bit at SSP1MSK.B4;
    const register unsigned short int MSK5 = 5;
    sbit  MSK5_bit at SSP1MSK.B5;
    const register unsigned short int MSK6 = 6;
    sbit  MSK6_bit at SSP1MSK.B6;
    const register unsigned short int MSK7 = 7;
    sbit  MSK7_bit at SSP1MSK.B7;
    const register unsigned short int SSP1MSK0 = 0;
    sbit  SSP1MSK0_bit at SSP1MSK.B0;
    const register unsigned short int SSP1MSK1 = 1;
    sbit  SSP1MSK1_bit at SSP1MSK.B1;
    const register unsigned short int SSP1MSK2 = 2;
    sbit  SSP1MSK2_bit at SSP1MSK.B2;
    const register unsigned short int SSP1MSK3 = 3;
    sbit  SSP1MSK3_bit at SSP1MSK.B3;
    const register unsigned short int SSP1MSK4 = 4;
    sbit  SSP1MSK4_bit at SSP1MSK.B4;
    const register unsigned short int SSP1MSK5 = 5;
    sbit  SSP1MSK5_bit at SSP1MSK.B5;
    const register unsigned short int SSP1MSK6 = 6;
    sbit  SSP1MSK6_bit at SSP1MSK.B6;
    const register unsigned short int SSP1MSK7 = 7;
    sbit  SSP1MSK7_bit at SSP1MSK.B7;

sfr unsigned short volatile SSPMSK           absolute 0x213;
sfr unsigned short volatile SSP1STAT         absolute 0x214;
    const register unsigned short int BF = 0;
    sbit  BF_bit at SSP1STAT.B0;
    const register unsigned short int UA = 1;
    sbit  UA_bit at SSP1STAT.B1;
    const register unsigned short int R_nW = 2;
    sbit  R_nW_bit at SSP1STAT.B2;
    const register unsigned short int D_nA = 5;
    sbit  D_nA_bit at SSP1STAT.B5;
    const register unsigned short int CKE = 6;
    sbit  CKE_bit at SSP1STAT.B6;
    const register unsigned short int SMP = 7;
    sbit  SMP_bit at SSP1STAT.B7;

sfr unsigned short volatile SSPSTAT          absolute 0x214;
sfr unsigned short volatile SSP1CON1         absolute 0x215;
    const register unsigned short int SSPM0 = 0;
    sbit  SSPM0_bit at SSP1CON1.B0;
    const register unsigned short int SSPM1 = 1;
    sbit  SSPM1_bit at SSP1CON1.B1;
    const register unsigned short int SSPM2 = 2;
    sbit  SSPM2_bit at SSP1CON1.B2;
    const register unsigned short int SSPM3 = 3;
    sbit  SSPM3_bit at SSP1CON1.B3;
    const register unsigned short int CKP = 4;
    sbit  CKP_bit at SSP1CON1.B4;
    const register unsigned short int SSPEN = 5;
    sbit  SSPEN_bit at SSP1CON1.B5;
    const register unsigned short int SSPOV = 6;
    sbit  SSPOV_bit at SSP1CON1.B6;
    const register unsigned short int WCOL = 7;
    sbit  WCOL_bit at SSP1CON1.B7;

sfr unsigned short volatile SSPCON           absolute 0x215;
sfr unsigned short volatile SSPCON1          absolute 0x215;
sfr unsigned short volatile SSP1CON          absolute 0x215;
sfr unsigned short volatile SSP1CON2         absolute 0x216;
    const register unsigned short int SEN = 0;
    sbit  SEN_bit at SSP1CON2.B0;
    const register unsigned short int RSEN = 1;
    sbit  RSEN_bit at SSP1CON2.B1;
    const register unsigned short int PEN = 2;
    sbit  PEN_bit at SSP1CON2.B2;
    const register unsigned short int RCEN = 3;
    sbit  RCEN_bit at SSP1CON2.B3;
    const register unsigned short int ACKEN = 4;
    sbit  ACKEN_bit at SSP1CON2.B4;
    const register unsigned short int ACKDT = 5;
    sbit  ACKDT_bit at SSP1CON2.B5;
    const register unsigned short int ACKSTAT = 6;
    sbit  ACKSTAT_bit at SSP1CON2.B6;
    const register unsigned short int GCEN = 7;
    sbit  GCEN_bit at SSP1CON2.B7;

sfr unsigned short volatile SSPCON2          absolute 0x216;
sfr unsigned short volatile SSP1CON3         absolute 0x217;
    const register unsigned short int DHEN = 0;
    sbit  DHEN_bit at SSP1CON3.B0;
    const register unsigned short int AHEN = 1;
    sbit  AHEN_bit at SSP1CON3.B1;
    const register unsigned short int SBCDE = 2;
    sbit  SBCDE_bit at SSP1CON3.B2;
    const register unsigned short int SDAHT = 3;
    sbit  SDAHT_bit at SSP1CON3.B3;
    const register unsigned short int BOEN = 4;
    sbit  BOEN_bit at SSP1CON3.B4;
    const register unsigned short int SCIE = 5;
    sbit  SCIE_bit at SSP1CON3.B5;
    const register unsigned short int PCIE = 6;
    sbit  PCIE_bit at SSP1CON3.B6;
    const register unsigned short int ACKTIM = 7;
    sbit  ACKTIM_bit at SSP1CON3.B7;

sfr unsigned short volatile SSPCON3          absolute 0x217;
sfr unsigned short volatile ODCONA           absolute 0x28C;
    const register unsigned short int ODA0 = 0;
    sbit  ODA0_bit at ODCONA.B0;
    const register unsigned short int ODA1 = 1;
    sbit  ODA1_bit at ODCONA.B1;
    const register unsigned short int ODA2 = 2;
    sbit  ODA2_bit at ODCONA.B2;
    const register unsigned short int ODA4 = 4;
    sbit  ODA4_bit at ODCONA.B4;
    const register unsigned short int ODA5 = 5;
    sbit  ODA5_bit at ODCONA.B5;

sfr unsigned short volatile ODCONB           absolute 0x28D;
    const register unsigned short int ODB4 = 4;
    sbit  ODB4_bit at ODCONB.B4;
    const register unsigned short int ODB5 = 5;
    sbit  ODB5_bit at ODCONB.B5;
    const register unsigned short int ODB6 = 6;
    sbit  ODB6_bit at ODCONB.B6;
    const register unsigned short int ODB7 = 7;
    sbit  ODB7_bit at ODCONB.B7;

sfr unsigned short volatile ODCONC           absolute 0x28E;
    const register unsigned short int ODC0 = 0;
    sbit  ODC0_bit at ODCONC.B0;
    const register unsigned short int ODC1 = 1;
    sbit  ODC1_bit at ODCONC.B1;
    const register unsigned short int ODC2 = 2;
    sbit  ODC2_bit at ODCONC.B2;
    const register unsigned short int ODC3 = 3;
    sbit  ODC3_bit at ODCONC.B3;
    const register unsigned short int ODC4 = 4;
    sbit  ODC4_bit at ODCONC.B4;
    const register unsigned short int ODC5 = 5;
    sbit  ODC5_bit at ODCONC.B5;
    const register unsigned short int ODC6 = 6;
    sbit  ODC6_bit at ODCONC.B6;
    const register unsigned short int ODC7 = 7;
    sbit  ODC7_bit at ODCONC.B7;

sfr unsigned int   volatile CCPR1            absolute 0x291;
sfr unsigned short volatile CCPR1L           absolute 0x291;
sfr unsigned short volatile CCPR1H           absolute 0x292;
sfr unsigned short volatile CCP1CON          absolute 0x293;
    const register unsigned short int CCP1M0 = 0;
    sbit  CCP1M0_bit at CCP1CON.B0;
    const register unsigned short int CCP1M1 = 1;
    sbit  CCP1M1_bit at CCP1CON.B1;
    const register unsigned short int CCP1M2 = 2;
    sbit  CCP1M2_bit at CCP1CON.B2;
    const register unsigned short int CCP1M3 = 3;
    sbit  CCP1M3_bit at CCP1CON.B3;
    const register unsigned short int CCP1Y = 4;
    sbit  CCP1Y_bit at CCP1CON.B4;
    const register unsigned short int CCP1X = 5;
    sbit  CCP1X_bit at CCP1CON.B5;
    const register unsigned short int DC1B0 = 4;
    sbit  DC1B0_bit at CCP1CON.B4;
    const register unsigned short int DC1B1 = 5;
    sbit  DC1B1_bit at CCP1CON.B5;

sfr unsigned short volatile ECCP1CON         absolute 0x293;
sfr unsigned int   volatile CCPR2            absolute 0x298;
sfr unsigned short volatile CCPR2L           absolute 0x298;
sfr unsigned short volatile CCPR2H           absolute 0x299;
sfr unsigned short volatile CCP2CON          absolute 0x29A;
    const register unsigned short int CCP2M0 = 0;
    sbit  CCP2M0_bit at CCP2CON.B0;
    const register unsigned short int CCP2M1 = 1;
    sbit  CCP2M1_bit at CCP2CON.B1;
    const register unsigned short int CCP2M2 = 2;
    sbit  CCP2M2_bit at CCP2CON.B2;
    const register unsigned short int CCP2M3 = 3;
    sbit  CCP2M3_bit at CCP2CON.B3;
    const register unsigned short int CCP2Y = 4;
    sbit  CCP2Y_bit at CCP2CON.B4;
    const register unsigned short int CCP2X = 5;
    sbit  CCP2X_bit at CCP2CON.B5;
    const register unsigned short int DC2B0 = 4;
    sbit  DC2B0_bit at CCP2CON.B4;
    const register unsigned short int DC2B1 = 5;
    sbit  DC2B1_bit at CCP2CON.B5;

sfr unsigned short volatile ECCP2CON         absolute 0x29A;
sfr unsigned short volatile SLRCONA          absolute 0x30C;
    const register unsigned short int SLRA0 = 0;
    sbit  SLRA0_bit at SLRCONA.B0;
    const register unsigned short int SLRA1 = 1;
    sbit  SLRA1_bit at SLRCONA.B1;
    const register unsigned short int SLRA2 = 2;
    sbit  SLRA2_bit at SLRCONA.B2;
    const register unsigned short int SLRA4 = 4;
    sbit  SLRA4_bit at SLRCONA.B4;
    const register unsigned short int SLRA5 = 5;
    sbit  SLRA5_bit at SLRCONA.B5;

sfr unsigned short volatile SLRCONB          absolute 0x30D;
    const register unsigned short int SLRB4 = 4;
    sbit  SLRB4_bit at SLRCONB.B4;
    const register unsigned short int SLRB5 = 5;
    sbit  SLRB5_bit at SLRCONB.B5;
    const register unsigned short int SLRB6 = 6;
    sbit  SLRB6_bit at SLRCONB.B6;
    const register unsigned short int SLRB7 = 7;
    sbit  SLRB7_bit at SLRCONB.B7;

sfr unsigned short volatile SLRCONC          absolute 0x30E;
    const register unsigned short int SLRC0 = 0;
    sbit  SLRC0_bit at SLRCONC.B0;
    const register unsigned short int SLRC1 = 1;
    sbit  SLRC1_bit at SLRCONC.B1;
    const register unsigned short int SLRC2 = 2;
    sbit  SLRC2_bit at SLRCONC.B2;
    const register unsigned short int SLRC3 = 3;
    sbit  SLRC3_bit at SLRCONC.B3;
    const register unsigned short int SLRC4 = 4;
    sbit  SLRC4_bit at SLRCONC.B4;
    const register unsigned short int SLRC5 = 5;
    sbit  SLRC5_bit at SLRCONC.B5;
    const register unsigned short int SLRC6 = 6;
    sbit  SLRC6_bit at SLRCONC.B6;
    const register unsigned short int SLRC7 = 7;
    sbit  SLRC7_bit at SLRCONC.B7;

sfr unsigned short volatile INLVLA           absolute 0x38C;
    const register unsigned short int INLVLA0 = 0;
    sbit  INLVLA0_bit at INLVLA.B0;
    const register unsigned short int INLVLA1 = 1;
    sbit  INLVLA1_bit at INLVLA.B1;
    const register unsigned short int INLVLA2 = 2;
    sbit  INLVLA2_bit at INLVLA.B2;
    const register unsigned short int INLVLA3 = 3;
    sbit  INLVLA3_bit at INLVLA.B3;
    const register unsigned short int INLVLA4 = 4;
    sbit  INLVLA4_bit at INLVLA.B4;
    const register unsigned short int INLVLA5 = 5;
    sbit  INLVLA5_bit at INLVLA.B5;

sfr unsigned short volatile INLVLB           absolute 0x38D;
    const register unsigned short int INLVLB4 = 4;
    sbit  INLVLB4_bit at INLVLB.B4;
    const register unsigned short int INLVLB5 = 5;
    sbit  INLVLB5_bit at INLVLB.B5;
    const register unsigned short int INLVLB6 = 6;
    sbit  INLVLB6_bit at INLVLB.B6;
    const register unsigned short int INLVLB7 = 7;
    sbit  INLVLB7_bit at INLVLB.B7;

sfr unsigned short volatile INLVLC           absolute 0x38E;
    const register unsigned short int INLVLC0 = 0;
    sbit  INLVLC0_bit at INLVLC.B0;
    const register unsigned short int INLVLC1 = 1;
    sbit  INLVLC1_bit at INLVLC.B1;
    const register unsigned short int INLVLC2 = 2;
    sbit  INLVLC2_bit at INLVLC.B2;
    const register unsigned short int INLVLC3 = 3;
    sbit  INLVLC3_bit at INLVLC.B3;
    const register unsigned short int INLVLC4 = 4;
    sbit  INLVLC4_bit at INLVLC.B4;
    const register unsigned short int INLVLC5 = 5;
    sbit  INLVLC5_bit at INLVLC.B5;
    const register unsigned short int INLVLC6 = 6;
    sbit  INLVLC6_bit at INLVLC.B6;
    const register unsigned short int INLVLC7 = 7;
    sbit  INLVLC7_bit at INLVLC.B7;

sfr unsigned short volatile IOCAP            absolute 0x391;
    const register unsigned short int IOCAP0 = 0;
    sbit  IOCAP0_bit at IOCAP.B0;
    const register unsigned short int IOCAP1 = 1;
    sbit  IOCAP1_bit at IOCAP.B1;
    const register unsigned short int IOCAP2 = 2;
    sbit  IOCAP2_bit at IOCAP.B2;
    const register unsigned short int IOCAP3 = 3;
    sbit  IOCAP3_bit at IOCAP.B3;
    const register unsigned short int IOCAP4 = 4;
    sbit  IOCAP4_bit at IOCAP.B4;
    const register unsigned short int IOCAP5 = 5;
    sbit  IOCAP5_bit at IOCAP.B5;

sfr unsigned short volatile IOCAN            absolute 0x392;
    const register unsigned short int IOCAN0 = 0;
    sbit  IOCAN0_bit at IOCAN.B0;
    const register unsigned short int IOCAN1 = 1;
    sbit  IOCAN1_bit at IOCAN.B1;
    const register unsigned short int IOCAN2 = 2;
    sbit  IOCAN2_bit at IOCAN.B2;
    const register unsigned short int IOCAN3 = 3;
    sbit  IOCAN3_bit at IOCAN.B3;
    const register unsigned short int IOCAN4 = 4;
    sbit  IOCAN4_bit at IOCAN.B4;
    const register unsigned short int IOCAN5 = 5;
    sbit  IOCAN5_bit at IOCAN.B5;

sfr unsigned short volatile IOCAF            absolute 0x393;
    const register unsigned short int IOCAF0 = 0;
    sbit  IOCAF0_bit at IOCAF.B0;
    const register unsigned short int IOCAF1 = 1;
    sbit  IOCAF1_bit at IOCAF.B1;
    const register unsigned short int IOCAF2 = 2;
    sbit  IOCAF2_bit at IOCAF.B2;
    const register unsigned short int IOCAF3 = 3;
    sbit  IOCAF3_bit at IOCAF.B3;
    const register unsigned short int IOCAF4 = 4;
    sbit  IOCAF4_bit at IOCAF.B4;
    const register unsigned short int IOCAF5 = 5;
    sbit  IOCAF5_bit at IOCAF.B5;

sfr unsigned short volatile IOCBP            absolute 0x394;
    const register unsigned short int IOCBP4 = 4;
    sbit  IOCBP4_bit at IOCBP.B4;
    const register unsigned short int IOCBP5 = 5;
    sbit  IOCBP5_bit at IOCBP.B5;
    const register unsigned short int IOCBP6 = 6;
    sbit  IOCBP6_bit at IOCBP.B6;
    const register unsigned short int IOCBP7 = 7;
    sbit  IOCBP7_bit at IOCBP.B7;

sfr unsigned short volatile IOCBN            absolute 0x395;
    const register unsigned short int IOCBN4 = 4;
    sbit  IOCBN4_bit at IOCBN.B4;
    const register unsigned short int IOCBN5 = 5;
    sbit  IOCBN5_bit at IOCBN.B5;
    const register unsigned short int IOCBN6 = 6;
    sbit  IOCBN6_bit at IOCBN.B6;
    const register unsigned short int IOCBN7 = 7;
    sbit  IOCBN7_bit at IOCBN.B7;

sfr unsigned short volatile IOCBF            absolute 0x396;
    const register unsigned short int IOCBF4 = 4;
    sbit  IOCBF4_bit at IOCBF.B4;
    const register unsigned short int IOCBF5 = 5;
    sbit  IOCBF5_bit at IOCBF.B5;
    const register unsigned short int IOCBF6 = 6;
    sbit  IOCBF6_bit at IOCBF.B6;
    const register unsigned short int IOCBF7 = 7;
    sbit  IOCBF7_bit at IOCBF.B7;

sfr unsigned short volatile IOCCP            absolute 0x397;
    const register unsigned short int IOCCP0 = 0;
    sbit  IOCCP0_bit at IOCCP.B0;
    const register unsigned short int IOCCP1 = 1;
    sbit  IOCCP1_bit at IOCCP.B1;
    const register unsigned short int IOCCP2 = 2;
    sbit  IOCCP2_bit at IOCCP.B2;
    const register unsigned short int IOCCP3 = 3;
    sbit  IOCCP3_bit at IOCCP.B3;
    const register unsigned short int IOCCP4 = 4;
    sbit  IOCCP4_bit at IOCCP.B4;
    const register unsigned short int IOCCP5 = 5;
    sbit  IOCCP5_bit at IOCCP.B5;
    const register unsigned short int IOCCP6 = 6;
    sbit  IOCCP6_bit at IOCCP.B6;
    const register unsigned short int IOCCP7 = 7;
    sbit  IOCCP7_bit at IOCCP.B7;

sfr unsigned short volatile IOCCN            absolute 0x398;
    const register unsigned short int IOCCN0 = 0;
    sbit  IOCCN0_bit at IOCCN.B0;
    const register unsigned short int IOCCN1 = 1;
    sbit  IOCCN1_bit at IOCCN.B1;
    const register unsigned short int IOCCN2 = 2;
    sbit  IOCCN2_bit at IOCCN.B2;
    const register unsigned short int IOCCN3 = 3;
    sbit  IOCCN3_bit at IOCCN.B3;
    const register unsigned short int IOCCN4 = 4;
    sbit  IOCCN4_bit at IOCCN.B4;
    const register unsigned short int IOCCN5 = 5;
    sbit  IOCCN5_bit at IOCCN.B5;
    const register unsigned short int IOCCN6 = 6;
    sbit  IOCCN6_bit at IOCCN.B6;
    const register unsigned short int IOCCN7 = 7;
    sbit  IOCCN7_bit at IOCCN.B7;

sfr unsigned short volatile IOCCF            absolute 0x399;
    const register unsigned short int IOCCF0 = 0;
    sbit  IOCCF0_bit at IOCCF.B0;
    const register unsigned short int IOCCF1 = 1;
    sbit  IOCCF1_bit at IOCCF.B1;
    const register unsigned short int IOCCF2 = 2;
    sbit  IOCCF2_bit at IOCCF.B2;
    const register unsigned short int IOCCF3 = 3;
    sbit  IOCCF3_bit at IOCCF.B3;
    const register unsigned short int IOCCF4 = 4;
    sbit  IOCCF4_bit at IOCCF.B4;
    const register unsigned short int IOCCF5 = 5;
    sbit  IOCCF5_bit at IOCCF.B5;
    const register unsigned short int IOCCF6 = 6;
    sbit  IOCCF6_bit at IOCCF.B6;
    const register unsigned short int IOCCF7 = 7;
    sbit  IOCCF7_bit at IOCCF.B7;

sfr unsigned short volatile OPA1CON          absolute 0x511;
    const register unsigned short int OPA1PCH0 = 0;
    sbit  OPA1PCH0_bit at OPA1CON.B0;
    const register unsigned short int OPA1PCH1 = 1;
    sbit  OPA1PCH1_bit at OPA1CON.B1;
    const register unsigned short int OPA1UG = 4;
    sbit  OPA1UG_bit at OPA1CON.B4;
    const register unsigned short int OPA1SP = 6;
    sbit  OPA1SP_bit at OPA1CON.B6;
    const register unsigned short int OPA1EN = 7;
    sbit  OPA1EN_bit at OPA1CON.B7;

sfr unsigned short volatile OPA2CON          absolute 0x515;
    const register unsigned short int OPA2PCH0 = 0;
    sbit  OPA2PCH0_bit at OPA2CON.B0;
    const register unsigned short int OPA2PCH1 = 1;
    sbit  OPA2PCH1_bit at OPA2CON.B1;
    const register unsigned short int OPA2UG = 4;
    sbit  OPA2UG_bit at OPA2CON.B4;
    const register unsigned short int OPA2SP = 6;
    sbit  OPA2SP_bit at OPA2CON.B6;
    const register unsigned short int OPA2EN = 7;
    sbit  OPA2EN_bit at OPA2CON.B7;

sfr unsigned short volatile PPSLOCK          absolute 0xE0F;
    const register unsigned short int PPSLOCKED = 0;
    sbit  PPSLOCKED_bit at PPSLOCK.B0;

sfr unsigned short volatile INTPPS           absolute 0xE10;
sfr unsigned short volatile T0CKIPPS         absolute 0xE11;
sfr unsigned short volatile T1CKIPPS         absolute 0xE12;
sfr unsigned short volatile T1GPPS           absolute 0xE13;
sfr unsigned short volatile CCP1PPS          absolute 0xE14;
sfr unsigned short volatile CCP2PPS          absolute 0xE15;
sfr unsigned short volatile SSPCLKPPS        absolute 0xE20;
sfr unsigned short volatile SSPDATPPS        absolute 0xE21;
sfr unsigned short volatile SSPSSPPS         absolute 0xE22;
sfr unsigned short volatile RA0PPS           absolute 0xE90;
sfr unsigned short volatile RA1PPS           absolute 0xE91;
sfr unsigned short volatile RA2PPS           absolute 0xE92;
sfr unsigned short volatile RA4PPS           absolute 0xE94;
sfr unsigned short volatile RA5PPS           absolute 0xE95;
sfr unsigned short volatile RB4PPS           absolute 0xE9C;
sfr unsigned short volatile RB5PPS           absolute 0xE9D;
sfr unsigned short volatile RB6PPS           absolute 0xE9E;
sfr unsigned short volatile RB7PPS           absolute 0xE9F;
sfr unsigned short volatile RC0PPS           absolute 0xEA0;
sfr unsigned short volatile RC1PPS           absolute 0xEA1;
sfr unsigned short volatile RC2PPS           absolute 0xEA2;
sfr unsigned short volatile RC3PPS           absolute 0xEA3;
sfr unsigned short volatile RC4PPS           absolute 0xEA4;
sfr unsigned short volatile RC5PPS           absolute 0xEA5;
sfr unsigned short volatile RC6PPS           absolute 0xEA6;
sfr unsigned short volatile RC7PPS           absolute 0xEA7;
sfr unsigned short volatile ICDBK0H          absolute 0xF9E;
    const register unsigned short int BKA8 = 0;
    sbit  BKA8_bit at ICDBK0H.B0;
    const register unsigned short int BKA9 = 1;
    sbit  BKA9_bit at ICDBK0H.B1;
    const register unsigned short int BKA10 = 2;
    sbit  BKA10_bit at ICDBK0H.B2;
    const register unsigned short int BKA11 = 3;
    sbit  BKA11_bit at ICDBK0H.B3;
    const register unsigned short int BKA12 = 4;
    sbit  BKA12_bit at ICDBK0H.B4;
    const register unsigned short int BKA13 = 5;
    sbit  BKA13_bit at ICDBK0H.B5;
    const register unsigned short int BKA14 = 6;
    sbit  BKA14_bit at ICDBK0H.B6;

sfr unsigned short volatile STATUS_SHAD      absolute 0xFE4;
    const register unsigned short int C_SHAD = 0;
    sbit  C_SHAD_bit at STATUS_SHAD.B0;
    const register unsigned short int DC_SHAD = 1;
    sbit  DC_SHAD_bit at STATUS_SHAD.B1;
    const register unsigned short int Z_SHAD = 2;
    sbit  Z_SHAD_bit at STATUS_SHAD.B2;

sfr unsigned short volatile WREG_SHAD        absolute 0xFE5;
sfr unsigned short volatile BSR_SHAD         absolute 0xFE6;
sfr unsigned short volatile PCLATH_SHAD      absolute 0xFE7;
sfr unsigned short volatile FSR0L_SHAD       absolute 0xFE8;
sfr unsigned short volatile FSR0H_SHAD       absolute 0xFE9;
sfr unsigned short volatile FSR1L_SHAD       absolute 0xFEA;
sfr unsigned short volatile FSR1H_SHAD       absolute 0xFEB;
sfr unsigned short volatile STKPTR           absolute 0xFED;
sfr unsigned short volatile TOSL             absolute 0xFEE;
sfr unsigned short volatile TOSH             absolute 0xFEF;
