// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00004000;

// Working space registers
rx unsigned short R0;
rx unsigned short R1;
rx unsigned short R2;
rx unsigned short R3;
rx unsigned short R4;
rx unsigned short R5;
rx unsigned short R6;
rx unsigned short R7;
rx unsigned short R8;
rx unsigned short R9;
rx unsigned short R10;
rx unsigned short R11;
rx unsigned short R12;
rx unsigned short R13;
rx unsigned short R14;
rx unsigned short R15;
rx unsigned short R16;
rx unsigned short R17;
rx unsigned short R18;
rx unsigned short R19;
rx unsigned short R20;

const register unsigned short int W = 0;
const register unsigned short int F = 1;
const register unsigned short int FAST   = 1;
const register unsigned short int A      = 0;
const register unsigned short int ACCESS = 0;
const register unsigned short int BANKED = 1;

// Special function registers (SFRs)

const signed int   PORT_TO_TRIS_OFFSET    =     18;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

sfr unsigned short volatile RCSTA2           absolute 0xF6B;
    const register unsigned short int RCD82 = 0;
    sbit  RCD82_bit at RCSTA2.B0;
    const register unsigned short int OERR2 = 1;
    sbit  OERR2_bit at RCSTA2.B1;
    const register unsigned short int FERR2 = 2;
    sbit  FERR2_bit at RCSTA2.B2;
    const register unsigned short int ADDEN2 = 3;
    sbit  ADDEN2_bit at RCSTA2.B3;
    const register unsigned short int CREN2 = 4;
    sbit  CREN2_bit at RCSTA2.B4;
    const register unsigned short int SREN2 = 5;
    sbit  SREN2_bit at RCSTA2.B5;
    const register unsigned short int NOT_RC8 = 6;
    sbit  NOT_RC8_bit at RCSTA2.B6;
    const register unsigned short int SPEN2 = 7;
    sbit  SPEN2_bit at RCSTA2.B7;
    const register unsigned short int RC8_92 = 6;
    sbit  RC8_92_bit at RCSTA2.B6;
    const register unsigned short int RC92 = 6;
    sbit  RC92_bit at RCSTA2.B6;
    const register unsigned short int RX92 = 6;
    sbit  RX92_bit at RCSTA2.B6;
    const register unsigned short int RX9D2 = 0;
    sbit  RX9D2_bit at RCSTA2.B0;
    const register unsigned short int nRC8 = 6;
    sbit  nRC8_bit at RCSTA2.B6;

sfr unsigned short volatile TXSTA2           absolute 0xF6C;
    const register unsigned short int TX9D2 = 0;
    sbit  TX9D2_bit at TXSTA2.B0;
    const register unsigned short int TRMT2 = 1;
    sbit  TRMT2_bit at TXSTA2.B1;
    const register unsigned short int BRGH2 = 2;
    sbit  BRGH2_bit at TXSTA2.B2;
    const register unsigned short int SENDB2 = 3;
    sbit  SENDB2_bit at TXSTA2.B3;
    const register unsigned short int SYNC2 = 4;
    sbit  SYNC2_bit at TXSTA2.B4;
    const register unsigned short int TXEN2 = 5;
    sbit  TXEN2_bit at TXSTA2.B5;
    const register unsigned short int NOT_TX8 = 6;
    sbit  NOT_TX8_bit at TXSTA2.B6;
    const register unsigned short int CSRC2 = 7;
    sbit  CSRC2_bit at TXSTA2.B7;
    const register unsigned short int TX8_92 = 6;
    sbit  TX8_92_bit at TXSTA2.B6;
    const register unsigned short int TX92 = 6;
    sbit  TX92_bit at TXSTA2.B6;
    const register unsigned short int TXD82 = 0;
    sbit  TXD82_bit at TXSTA2.B0;
    const register unsigned short int nTX8 = 6;
    sbit  nTX8_bit at TXSTA2.B6;

sfr unsigned short volatile TXREG2           absolute 0xF6D;
sfr unsigned short volatile RCREG2           absolute 0xF6E;
sfr unsigned int            SPBRG2           absolute 0xF6F;
sfr unsigned short          BAUDCON1         absolute 0xF7E;
    const register unsigned short int ABDEN = 0;
    sbit  ABDEN_bit at BAUDCON1.B0;
    const register unsigned short int WUE = 1;
    sbit  WUE_bit at BAUDCON1.B1;
    const register unsigned short int BRG16 = 3;
    sbit  BRG16_bit at BAUDCON1.B3;
    const register unsigned short int CKTXP = 4;
    sbit  CKTXP_bit at BAUDCON1.B4;
    const register unsigned short int RCIDL = 6;
    sbit  RCIDL_bit at BAUDCON1.B6;
    const register unsigned short int ABDOVF = 7;
    sbit  ABDOVF_bit at BAUDCON1.B7;
    const register unsigned short int ABDEN1 = 0;
    sbit  ABDEN1_bit at BAUDCON1.B0;
    const register unsigned short int ABDOVF1 = 7;
    sbit  ABDOVF1_bit at BAUDCON1.B7;
    const register unsigned short int BRG161 = 3;
    sbit  BRG161_bit at BAUDCON1.B3;
    const register unsigned short int RCIDL1 = 6;
    sbit  RCIDL1_bit at BAUDCON1.B6;
    const register unsigned short int RCMT = 6;
    sbit  RCMT_bit at BAUDCON1.B6;
    const register unsigned short int RCMT1 = 6;
    sbit  RCMT1_bit at BAUDCON1.B6;
    const register unsigned short int SCKP = 4;
    sbit  SCKP_bit at BAUDCON1.B4;
    const register unsigned short int SCKP1 = 4;
    sbit  SCKP1_bit at BAUDCON1.B4;
    const register unsigned short int TXCKP = 4;
    sbit  TXCKP_bit at BAUDCON1.B4;
    const register unsigned short int TXCKP1 = 4;
    sbit  TXCKP1_bit at BAUDCON1.B4;
    const register unsigned short int WUE1 = 1;
    sbit  WUE1_bit at BAUDCON1.B1;

sfr unsigned short          BAUDCTL1         absolute 0xF7E;
sfr unsigned short          SPBRGH1          absolute 0xF7F;
sfr unsigned short volatile PORTA            absolute 0xF80;
    const register unsigned short int AN0 = 0;
    sbit  AN0_bit at PORTA.B0;
    const register unsigned short int AN1 = 1;
    sbit  AN1_bit at PORTA.B1;
    const register unsigned short int AN2 = 2;
    sbit  AN2_bit at PORTA.B2;
    const register unsigned short int AN3 = 3;
    sbit  AN3_bit at PORTA.B3;
    const register unsigned short int T0CKI = 4;
    sbit  T0CKI_bit at PORTA.B4;
    const register unsigned short int AN4 = 5;
    sbit  AN4_bit at PORTA.B5;
    const register unsigned short int CLKO = 6;
    sbit  CLKO_bit at PORTA.B6;
    const register unsigned short int CLKI = 7;
    sbit  CLKI_bit at PORTA.B7;
    const register unsigned short int LVDIN = 5;
    sbit  LVDIN_bit at PORTA.B5;
    const register unsigned short int OSC1 = 7;
    sbit  OSC1_bit at PORTA.B7;
    const register unsigned short int OSC2 = 6;
    sbit  OSC2_bit at PORTA.B6;
    const register unsigned short int ULPWUIN = 0;
    sbit  ULPWUIN_bit at PORTA.B0;
    const register unsigned short int VREFM = 2;
    sbit  VREFM_bit at PORTA.B2;
    const register unsigned short int VREFP = 3;
    sbit  VREFP_bit at PORTA.B3;

sfr unsigned short volatile PORTB            absolute 0xF81;
    const register unsigned short int INT0 = 0;
    sbit  INT0_bit at PORTB.B0;
    const register unsigned short int INT1 = 1;
    sbit  INT1_bit at PORTB.B1;
    const register unsigned short int INT2 = 2;
    sbit  INT2_bit at PORTB.B2;
    const register unsigned short int CCP2B = 3;
    sbit  CCP2B_bit at PORTB.B3;
    const register unsigned short int KBI0 = 4;
    sbit  KBI0_bit at PORTB.B4;
    const register unsigned short int KBI1 = 5;
    sbit  KBI1_bit at PORTB.B5;
    const register unsigned short int KBI2 = 6;
    sbit  KBI2_bit at PORTB.B6;
    const register unsigned short int KBI3 = 7;
    sbit  KBI3_bit at PORTB.B7;
    const register unsigned short int CCP2_PA2 = 3;
    sbit  CCP2_PA2_bit at PORTB.B3;
    const register unsigned short int INT3 = 3;
    sbit  INT3_bit at PORTB.B3;
    const register unsigned short int PGC = 6;
    sbit  PGC_bit at PORTB.B6;
    const register unsigned short int PGD = 7;
    sbit  PGD_bit at PORTB.B7;
    const register unsigned short int PGM = 5;
    sbit  PGM_bit at PORTB.B5;

sfr unsigned short volatile PORTC            absolute 0xF82;
    const register unsigned short int T13CKI = 0;
    sbit  T13CKI_bit at PORTC.B0;
    const register unsigned short int CCP2 = 1;
    sbit  CCP2_bit at PORTC.B1;
    const register unsigned short int CCP1 = 2;
    sbit  CCP1_bit at PORTC.B2;
    const register unsigned short int SCK = 3;
    sbit  SCK_bit at PORTC.B3;
    const register unsigned short int SDA = 4;
    sbit  SDA_bit at PORTC.B4;
    const register unsigned short int SDO = 5;
    sbit  SDO_bit at PORTC.B5;
    const register unsigned short int CK = 6;
    sbit  CK_bit at PORTC.B6;
    const register unsigned short int DT = 7;
    sbit  DT_bit at PORTC.B7;
    const register unsigned short int CCP2C = 1;
    sbit  CCP2C_bit at PORTC.B1;
    const register unsigned short int PA1 = 2;
    sbit  PA1_bit at PORTC.B2;
    const register unsigned short int PA2 = 1;
    sbit  PA2_bit at PORTC.B1;
    const register unsigned short int RX_ = 7;
    sbit  RX_bit at PORTC.B7;
    const register unsigned short int SCL = 3;
    sbit  SCL_bit at PORTC.B3;
    const register unsigned short int SDI = 4;
    sbit  SDI_bit at PORTC.B4;
    const register unsigned short int T1OSI = 1;
    sbit  T1OSI_bit at PORTC.B1;
    const register unsigned short int T1OSO = 0;
    sbit  T1OSO_bit at PORTC.B0;
    const register unsigned short int TX = 6;
    sbit  TX_bit at PORTC.B6;

sfr unsigned short volatile PORTD            absolute 0xF83;
    const register unsigned short int AD0 = 0;
    sbit  AD0_bit at PORTD.B0;
    const register unsigned short int AD1 = 1;
    sbit  AD1_bit at PORTD.B1;
    const register unsigned short int AD2 = 2;
    sbit  AD2_bit at PORTD.B2;
    const register unsigned short int AD3 = 3;
    sbit  AD3_bit at PORTD.B3;
    const register unsigned short int AD4 = 4;
    sbit  AD4_bit at PORTD.B4;
    const register unsigned short int AD5 = 5;
    sbit  AD5_bit at PORTD.B5;
    const register unsigned short int AD6 = 6;
    sbit  AD6_bit at PORTD.B6;
    const register unsigned short int AD7 = 7;
    sbit  AD7_bit at PORTD.B7;
    const register unsigned short int PSP0 = 0;
    sbit  PSP0_bit at PORTD.B0;
    const register unsigned short int PSP1 = 1;
    sbit  PSP1_bit at PORTD.B1;
    const register unsigned short int PSP2 = 2;
    sbit  PSP2_bit at PORTD.B2;
    const register unsigned short int PSP3 = 3;
    sbit  PSP3_bit at PORTD.B3;
    const register unsigned short int PSP4 = 4;
    sbit  PSP4_bit at PORTD.B4;
    const register unsigned short int PSP5 = 5;
    sbit  PSP5_bit at PORTD.B5;
    const register unsigned short int PSP6 = 6;
    sbit  PSP6_bit at PORTD.B6;
    const register unsigned short int PSP7 = 7;
    sbit  PSP7_bit at PORTD.B7;
    const register unsigned short int SS2 = 7;
    sbit  SS2_bit at PORTD.B7;

sfr unsigned short volatile PORTE            absolute 0xF84;
    const register unsigned short int AD8 = 0;
    sbit  AD8_bit at PORTE.B0;
    const register unsigned short int AD9 = 1;
    sbit  AD9_bit at PORTE.B1;
    const register unsigned short int AD10 = 2;
    sbit  AD10_bit at PORTE.B2;
    const register unsigned short int AD11 = 3;
    sbit  AD11_bit at PORTE.B3;
    const register unsigned short int AD12 = 4;
    sbit  AD12_bit at PORTE.B4;
    const register unsigned short int AD13 = 5;
    sbit  AD13_bit at PORTE.B5;
    const register unsigned short int AD14 = 6;
    sbit  AD14_bit at PORTE.B6;
    const register unsigned short int AD15 = 7;
    sbit  AD15_bit at PORTE.B7;
    const register unsigned short int CCP10 = 2;
    sbit  CCP10_bit at PORTE.B2;
    const register unsigned short int CCP2E = 7;
    sbit  CCP2E_bit at PORTE.B7;
    const register unsigned short int CCP6E = 6;
    sbit  CCP6E_bit at PORTE.B6;
    const register unsigned short int CCP7E = 5;
    sbit  CCP7E_bit at PORTE.B5;
    const register unsigned short int CCP8E = 4;
    sbit  CCP8E_bit at PORTE.B4;
    const register unsigned short int CCP9E = 3;
    sbit  CCP9E_bit at PORTE.B3;
    const register unsigned short int CS = 2;
    sbit  CS_bit at PORTE.B2;
    const register unsigned short int PA2E = 7;
    sbit  PA2E_bit at PORTE.B7;
    const register unsigned short int PB1E = 6;
    sbit  PB1E_bit at PORTE.B6;
    const register unsigned short int PB2 = 2;
    sbit  PB2_bit at PORTE.B2;
    const register unsigned short int PB3E = 4;
    sbit  PB3E_bit at PORTE.B4;
    const register unsigned short int PC1E = 5;
    sbit  PC1E_bit at PORTE.B5;
    const register unsigned short int PC2 = 1;
    sbit  PC2_bit at PORTE.B1;
    const register unsigned short int PC3E = 3;
    sbit  PC3E_bit at PORTE.B3;
    const register unsigned short int PD2 = 0;
    sbit  PD2_bit at PORTE.B0;
    const register unsigned short int RD = 0;
    sbit  RD_bit at PORTE.B0;
    const register unsigned short int RDE = 0;
    sbit  RDE_bit at PORTE.B0;
    const register unsigned short int WR = 1;
    sbit  WR_bit at PORTE.B1;
    const register unsigned short int WRE = 1;
    sbit  WRE_bit at PORTE.B1;

sfr unsigned short volatile PORTF            absolute 0xF85;
    const register unsigned short int AN5 = 0;
    sbit  AN5_bit at PORTF.B0;
    const register unsigned short int AN6 = 1;
    sbit  AN6_bit at PORTF.B1;
    const register unsigned short int AN7 = 2;
    sbit  AN7_bit at PORTF.B2;
    const register unsigned short int AN8 = 3;
    sbit  AN8_bit at PORTF.B3;
    const register unsigned short int AN9 = 4;
    sbit  AN9_bit at PORTF.B4;
    const register unsigned short int AN10 = 5;
    sbit  AN10_bit at PORTF.B5;
    const register unsigned short int AN11 = 6;
    sbit  AN11_bit at PORTF.B6;
    const register unsigned short int SS = 7;
    sbit  SS_bit at PORTF.B7;
    const register unsigned short int C1OUTF = 2;
    sbit  C1OUTF_bit at PORTF.B2;
    const register unsigned short int C2OUTF = 1;
    sbit  C2OUTF_bit at PORTF.B1;
    const register unsigned short int CVREFF = 5;
    sbit  CVREFF_bit at PORTF.B5;

sfr unsigned short volatile PORTG            absolute 0xF86;
    const register unsigned short int CCP3 = 0;
    sbit  CCP3_bit at PORTG.B0;
    const register unsigned short int C3OUTG = 1;
    sbit  C3OUTG_bit at PORTG.B1;
    const register unsigned short int DT2 = 2;
    sbit  DT2_bit at PORTG.B2;
    const register unsigned short int MCLR = 5;
    sbit  MCLR_bit at PORTG.B5;
    const register unsigned short int CK2 = 1;
    sbit  CK2_bit at PORTG.B1;
    const register unsigned short int RG5 = 5;
    sbit  RG5_bit at PORTG.B5;
    const register unsigned short int RX2 = 2;
    sbit  RX2_bit at PORTG.B2;
    const register unsigned short int TX2 = 1;
    sbit  TX2_bit at PORTG.B1;
    const register unsigned short int VPP = 5;
    sbit  VPP_bit at PORTG.B5;

sfr unsigned short volatile PORTH            absolute 0xF87;
    const register unsigned short int A16 = 0;
    sbit  A16_bit at PORTH.B0;
    const register unsigned short int A17 = 1;
    sbit  A17_bit at PORTH.B1;
    const register unsigned short int A18 = 2;
    sbit  A18_bit at PORTH.B2;
    const register unsigned short int A19 = 3;
    sbit  A19_bit at PORTH.B3;
    const register unsigned short int CCP9 = 4;
    sbit  CCP9_bit at PORTH.B4;
    const register unsigned short int CCP8 = 5;
    sbit  CCP8_bit at PORTH.B5;
    const register unsigned short int CCP7 = 6;
    sbit  CCP7_bit at PORTH.B6;
    const register unsigned short int CCP6 = 7;
    sbit  CCP6_bit at PORTH.B7;
    const register unsigned short int PB1 = 7;
    sbit  PB1_bit at PORTH.B7;
    const register unsigned short int PB3 = 5;
    sbit  PB3_bit at PORTH.B5;
    const register unsigned short int PC1 = 6;
    sbit  PC1_bit at PORTH.B6;
    const register unsigned short int PC3 = 4;
    sbit  PC3_bit at PORTH.B4;

sfr unsigned short volatile PORTJ            absolute 0xF88;
    const register unsigned short int ALE = 0;
    sbit  ALE_bit at PORTJ.B0;
    const register unsigned short int OE = 1;
    sbit  OE_bit at PORTJ.B1;
    const register unsigned short int WRL = 2;
    sbit  WRL_bit at PORTJ.B2;
    const register unsigned short int WRH = 3;
    sbit  WRH_bit at PORTJ.B3;
    const register unsigned short int BA0 = 4;
    sbit  BA0_bit at PORTJ.B4;
    const register unsigned short int CE = 5;
    sbit  CE_bit at PORTJ.B5;
    const register unsigned short int LB = 6;
    sbit  LB_bit at PORTJ.B6;
    const register unsigned short int UB = 7;
    sbit  UB_bit at PORTJ.B7;

sfr unsigned short volatile LATA             absolute 0xF89;
    const register unsigned short int LA0 = 0;
    sbit  LA0_bit at LATA.B0;
    const register unsigned short int LA1 = 1;
    sbit  LA1_bit at LATA.B1;
    const register unsigned short int LA2 = 2;
    sbit  LA2_bit at LATA.B2;
    const register unsigned short int LA3 = 3;
    sbit  LA3_bit at LATA.B3;
    const register unsigned short int LA4 = 4;
    sbit  LA4_bit at LATA.B4;
    const register unsigned short int LA5 = 5;
    sbit  LA5_bit at LATA.B5;
    const register unsigned short int LA6 = 6;
    sbit  LA6_bit at LATA.B6;
    const register unsigned short int LA7 = 7;
    sbit  LA7_bit at LATA.B7;
    const register unsigned short int LATA0 = 0;
    sbit  LATA0_bit at LATA.B0;
    const register unsigned short int LATA1 = 1;
    sbit  LATA1_bit at LATA.B1;
    const register unsigned short int LATA2 = 2;
    sbit  LATA2_bit at LATA.B2;
    const register unsigned short int LATA3 = 3;
    sbit  LATA3_bit at LATA.B3;
    const register unsigned short int LATA4 = 4;
    sbit  LATA4_bit at LATA.B4;
    const register unsigned short int LATA5 = 5;
    sbit  LATA5_bit at LATA.B5;
    const register unsigned short int LATA6 = 6;
    sbit  LATA6_bit at LATA.B6;
    const register unsigned short int LATA7 = 7;
    sbit  LATA7_bit at LATA.B7;

sfr unsigned short volatile LATB             absolute 0xF8A;
    const register unsigned short int LATB0 = 0;
    sbit  LATB0_bit at LATB.B0;
    const register unsigned short int LATB1 = 1;
    sbit  LATB1_bit at LATB.B1;
    const register unsigned short int LATB2 = 2;
    sbit  LATB2_bit at LATB.B2;
    const register unsigned short int LATB3 = 3;
    sbit  LATB3_bit at LATB.B3;
    const register unsigned short int LATB4 = 4;
    sbit  LATB4_bit at LATB.B4;
    const register unsigned short int LATB5 = 5;
    sbit  LATB5_bit at LATB.B5;
    const register unsigned short int LATB6 = 6;
    sbit  LATB6_bit at LATB.B6;
    const register unsigned short int LATB7 = 7;
    sbit  LATB7_bit at LATB.B7;
    const register unsigned short int LB0 = 0;
    sbit  LB0_bit at LATB.B0;
    const register unsigned short int LB1 = 1;
    sbit  LB1_bit at LATB.B1;
    const register unsigned short int LB2 = 2;
    sbit  LB2_bit at LATB.B2;
    const register unsigned short int LB3 = 3;
    sbit  LB3_bit at LATB.B3;
    const register unsigned short int LB4 = 4;
    sbit  LB4_bit at LATB.B4;
    const register unsigned short int LB5 = 5;
    sbit  LB5_bit at LATB.B5;
    const register unsigned short int LB6 = 6;
    sbit  LB6_bit at LATB.B6;
    const register unsigned short int LB7 = 7;
    sbit  LB7_bit at LATB.B7;

sfr unsigned short volatile LATC             absolute 0xF8B;
    const register unsigned short int LATC0 = 0;
    sbit  LATC0_bit at LATC.B0;
    const register unsigned short int LATC1 = 1;
    sbit  LATC1_bit at LATC.B1;
    const register unsigned short int LATC2 = 2;
    sbit  LATC2_bit at LATC.B2;
    const register unsigned short int LATC3 = 3;
    sbit  LATC3_bit at LATC.B3;
    const register unsigned short int LATC4 = 4;
    sbit  LATC4_bit at LATC.B4;
    const register unsigned short int LATC5 = 5;
    sbit  LATC5_bit at LATC.B5;
    const register unsigned short int LATC6 = 6;
    sbit  LATC6_bit at LATC.B6;
    const register unsigned short int LATC7 = 7;
    sbit  LATC7_bit at LATC.B7;
    const register unsigned short int LC0 = 0;
    sbit  LC0_bit at LATC.B0;
    const register unsigned short int LC1 = 1;
    sbit  LC1_bit at LATC.B1;
    const register unsigned short int LC2 = 2;
    sbit  LC2_bit at LATC.B2;
    const register unsigned short int LC3 = 3;
    sbit  LC3_bit at LATC.B3;
    const register unsigned short int LC4 = 4;
    sbit  LC4_bit at LATC.B4;
    const register unsigned short int LC5 = 5;
    sbit  LC5_bit at LATC.B5;
    const register unsigned short int LC6 = 6;
    sbit  LC6_bit at LATC.B6;
    const register unsigned short int LC7 = 7;
    sbit  LC7_bit at LATC.B7;

sfr unsigned short volatile LATD             absolute 0xF8C;
    const register unsigned short int LATD0 = 0;
    sbit  LATD0_bit at LATD.B0;
    const register unsigned short int LATD1 = 1;
    sbit  LATD1_bit at LATD.B1;
    const register unsigned short int LATD2 = 2;
    sbit  LATD2_bit at LATD.B2;
    const register unsigned short int LATD3 = 3;
    sbit  LATD3_bit at LATD.B3;
    const register unsigned short int LATD4 = 4;
    sbit  LATD4_bit at LATD.B4;
    const register unsigned short int LATD5 = 5;
    sbit  LATD5_bit at LATD.B5;
    const register unsigned short int LATD6 = 6;
    sbit  LATD6_bit at LATD.B6;
    const register unsigned short int LATD7 = 7;
    sbit  LATD7_bit at LATD.B7;
    const register unsigned short int LD0 = 0;
    sbit  LD0_bit at LATD.B0;
    const register unsigned short int LD1 = 1;
    sbit  LD1_bit at LATD.B1;
    const register unsigned short int LD2 = 2;
    sbit  LD2_bit at LATD.B2;
    const register unsigned short int LD3 = 3;
    sbit  LD3_bit at LATD.B3;
    const register unsigned short int LD4 = 4;
    sbit  LD4_bit at LATD.B4;
    const register unsigned short int LD5 = 5;
    sbit  LD5_bit at LATD.B5;
    const register unsigned short int LD6 = 6;
    sbit  LD6_bit at LATD.B6;
    const register unsigned short int LD7 = 7;
    sbit  LD7_bit at LATD.B7;

sfr unsigned short volatile LATE             absolute 0xF8D;
    const register unsigned short int LATE0 = 0;
    sbit  LATE0_bit at LATE.B0;
    const register unsigned short int LATE1 = 1;
    sbit  LATE1_bit at LATE.B1;
    const register unsigned short int LATE2 = 2;
    sbit  LATE2_bit at LATE.B2;
    const register unsigned short int LATE3 = 3;
    sbit  LATE3_bit at LATE.B3;
    const register unsigned short int LATE4 = 4;
    sbit  LATE4_bit at LATE.B4;
    const register unsigned short int LATE5 = 5;
    sbit  LATE5_bit at LATE.B5;
    const register unsigned short int LATE6 = 6;
    sbit  LATE6_bit at LATE.B6;
    const register unsigned short int LATE7 = 7;
    sbit  LATE7_bit at LATE.B7;
    const register unsigned short int LE0 = 0;
    sbit  LE0_bit at LATE.B0;
    const register unsigned short int LE1 = 1;
    sbit  LE1_bit at LATE.B1;
    const register unsigned short int LE2 = 2;
    sbit  LE2_bit at LATE.B2;
    const register unsigned short int LE3 = 3;
    sbit  LE3_bit at LATE.B3;
    const register unsigned short int LE4 = 4;
    sbit  LE4_bit at LATE.B4;
    const register unsigned short int LE5 = 5;
    sbit  LE5_bit at LATE.B5;
    const register unsigned short int LE6 = 6;
    sbit  LE6_bit at LATE.B6;
    const register unsigned short int LE7 = 7;
    sbit  LE7_bit at LATE.B7;

sfr unsigned short volatile LATF             absolute 0xF8E;
    const register unsigned short int LATF0 = 0;
    sbit  LATF0_bit at LATF.B0;
    const register unsigned short int LATF1 = 1;
    sbit  LATF1_bit at LATF.B1;
    const register unsigned short int LATF2 = 2;
    sbit  LATF2_bit at LATF.B2;
    const register unsigned short int LATF3 = 3;
    sbit  LATF3_bit at LATF.B3;
    const register unsigned short int LATF4 = 4;
    sbit  LATF4_bit at LATF.B4;
    const register unsigned short int LATF5 = 5;
    sbit  LATF5_bit at LATF.B5;
    const register unsigned short int LATF6 = 6;
    sbit  LATF6_bit at LATF.B6;
    const register unsigned short int LATF7 = 7;
    sbit  LATF7_bit at LATF.B7;
    const register unsigned short int LF0 = 0;
    sbit  LF0_bit at LATF.B0;
    const register unsigned short int LF1 = 1;
    sbit  LF1_bit at LATF.B1;
    const register unsigned short int LF2 = 2;
    sbit  LF2_bit at LATF.B2;
    const register unsigned short int LF3 = 3;
    sbit  LF3_bit at LATF.B3;
    const register unsigned short int LF4 = 4;
    sbit  LF4_bit at LATF.B4;
    const register unsigned short int LF5 = 5;
    sbit  LF5_bit at LATF.B5;
    const register unsigned short int LF6 = 6;
    sbit  LF6_bit at LATF.B6;
    const register unsigned short int LF7 = 7;
    sbit  LF7_bit at LATF.B7;

sfr unsigned short volatile LATG             absolute 0xF8F;
    const register unsigned short int LATG0 = 0;
    sbit  LATG0_bit at LATG.B0;
    const register unsigned short int LATG1 = 1;
    sbit  LATG1_bit at LATG.B1;
    const register unsigned short int LATG2 = 2;
    sbit  LATG2_bit at LATG.B2;
    const register unsigned short int LATG3 = 3;
    sbit  LATG3_bit at LATG.B3;
    const register unsigned short int LATG4 = 4;
    sbit  LATG4_bit at LATG.B4;
    const register unsigned short int LG0 = 0;
    sbit  LG0_bit at LATG.B0;
    const register unsigned short int LG1 = 1;
    sbit  LG1_bit at LATG.B1;
    const register unsigned short int LG2 = 2;
    sbit  LG2_bit at LATG.B2;
    const register unsigned short int LG3 = 3;
    sbit  LG3_bit at LATG.B3;
    const register unsigned short int LG4 = 4;
    sbit  LG4_bit at LATG.B4;

sfr unsigned short volatile LATH             absolute 0xF90;
    const register unsigned short int LATH0 = 0;
    sbit  LATH0_bit at LATH.B0;
    const register unsigned short int LATH1 = 1;
    sbit  LATH1_bit at LATH.B1;
    const register unsigned short int LATH2 = 2;
    sbit  LATH2_bit at LATH.B2;
    const register unsigned short int LATH3 = 3;
    sbit  LATH3_bit at LATH.B3;
    const register unsigned short int LATH4 = 4;
    sbit  LATH4_bit at LATH.B4;
    const register unsigned short int LATH5 = 5;
    sbit  LATH5_bit at LATH.B5;
    const register unsigned short int LATH6 = 6;
    sbit  LATH6_bit at LATH.B6;
    const register unsigned short int LATH7 = 7;
    sbit  LATH7_bit at LATH.B7;
    const register unsigned short int LH0 = 0;
    sbit  LH0_bit at LATH.B0;
    const register unsigned short int LH1 = 1;
    sbit  LH1_bit at LATH.B1;
    const register unsigned short int LH2 = 2;
    sbit  LH2_bit at LATH.B2;
    const register unsigned short int LH3 = 3;
    sbit  LH3_bit at LATH.B3;
    const register unsigned short int LH4 = 4;
    sbit  LH4_bit at LATH.B4;
    const register unsigned short int LH5 = 5;
    sbit  LH5_bit at LATH.B5;
    const register unsigned short int LH6 = 6;
    sbit  LH6_bit at LATH.B6;
    const register unsigned short int LH7 = 7;
    sbit  LH7_bit at LATH.B7;

sfr unsigned short volatile LATJ             absolute 0xF91;
    const register unsigned short int LATJ0 = 0;
    sbit  LATJ0_bit at LATJ.B0;
    const register unsigned short int LATJ1 = 1;
    sbit  LATJ1_bit at LATJ.B1;
    const register unsigned short int LATJ2 = 2;
    sbit  LATJ2_bit at LATJ.B2;
    const register unsigned short int LATJ3 = 3;
    sbit  LATJ3_bit at LATJ.B3;
    const register unsigned short int LATJ4 = 4;
    sbit  LATJ4_bit at LATJ.B4;
    const register unsigned short int LATJ5 = 5;
    sbit  LATJ5_bit at LATJ.B5;
    const register unsigned short int LATJ6 = 6;
    sbit  LATJ6_bit at LATJ.B6;
    const register unsigned short int LATJ7 = 7;
    sbit  LATJ7_bit at LATJ.B7;
    const register unsigned short int LJ0 = 0;
    sbit  LJ0_bit at LATJ.B0;
    const register unsigned short int LJ1 = 1;
    sbit  LJ1_bit at LATJ.B1;
    const register unsigned short int LJ2 = 2;
    sbit  LJ2_bit at LATJ.B2;
    const register unsigned short int LJ3 = 3;
    sbit  LJ3_bit at LATJ.B3;
    const register unsigned short int LJ4 = 4;
    sbit  LJ4_bit at LATJ.B4;
    const register unsigned short int LJ5 = 5;
    sbit  LJ5_bit at LATJ.B5;
    const register unsigned short int LJ6 = 6;
    sbit  LJ6_bit at LATJ.B6;
    const register unsigned short int LJ7 = 7;
    sbit  LJ7_bit at LATJ.B7;

sfr unsigned short volatile TRISA            absolute 0xF92;
    const register unsigned short int TRISA0 = 0;
    sbit  TRISA0_bit at TRISA.B0;
    const register unsigned short int TRISA1 = 1;
    sbit  TRISA1_bit at TRISA.B1;
    const register unsigned short int TRISA2 = 2;
    sbit  TRISA2_bit at TRISA.B2;
    const register unsigned short int TRISA3 = 3;
    sbit  TRISA3_bit at TRISA.B3;
    const register unsigned short int TRISA4 = 4;
    sbit  TRISA4_bit at TRISA.B4;
    const register unsigned short int TRISA5 = 5;
    sbit  TRISA5_bit at TRISA.B5;
    const register unsigned short int TRISA6 = 6;
    sbit  TRISA6_bit at TRISA.B6;
    const register unsigned short int TRISA7 = 7;
    sbit  TRISA7_bit at TRISA.B7;

sfr unsigned short volatile DDRA             absolute 0xF92;
sfr unsigned short volatile TRISB            absolute 0xF93;
    const register unsigned short int TRISB0 = 0;
    sbit  TRISB0_bit at TRISB.B0;
    const register unsigned short int TRISB1 = 1;
    sbit  TRISB1_bit at TRISB.B1;
    const register unsigned short int TRISB2 = 2;
    sbit  TRISB2_bit at TRISB.B2;
    const register unsigned short int TRISB3 = 3;
    sbit  TRISB3_bit at TRISB.B3;
    const register unsigned short int TRISB4 = 4;
    sbit  TRISB4_bit at TRISB.B4;
    const register unsigned short int TRISB5 = 5;
    sbit  TRISB5_bit at TRISB.B5;
    const register unsigned short int TRISB6 = 6;
    sbit  TRISB6_bit at TRISB.B6;
    const register unsigned short int TRISB7 = 7;
    sbit  TRISB7_bit at TRISB.B7;

sfr unsigned short volatile DDRB             absolute 0xF93;
sfr unsigned short volatile TRISC            absolute 0xF94;
    const register unsigned short int TRISC0 = 0;
    sbit  TRISC0_bit at TRISC.B0;
    const register unsigned short int TRISC1 = 1;
    sbit  TRISC1_bit at TRISC.B1;
    const register unsigned short int TRISC2 = 2;
    sbit  TRISC2_bit at TRISC.B2;
    const register unsigned short int TRISC3 = 3;
    sbit  TRISC3_bit at TRISC.B3;
    const register unsigned short int TRISC4 = 4;
    sbit  TRISC4_bit at TRISC.B4;
    const register unsigned short int TRISC5 = 5;
    sbit  TRISC5_bit at TRISC.B5;
    const register unsigned short int TRISC6 = 6;
    sbit  TRISC6_bit at TRISC.B6;
    const register unsigned short int TRISC7 = 7;
    sbit  TRISC7_bit at TRISC.B7;

sfr unsigned short volatile DDRC             absolute 0xF94;
sfr unsigned short volatile TRISD            absolute 0xF95;
    const register unsigned short int TRISD0 = 0;
    sbit  TRISD0_bit at TRISD.B0;
    const register unsigned short int TRISD1 = 1;
    sbit  TRISD1_bit at TRISD.B1;
    const register unsigned short int TRISD2 = 2;
    sbit  TRISD2_bit at TRISD.B2;
    const register unsigned short int TRISD3 = 3;
    sbit  TRISD3_bit at TRISD.B3;
    const register unsigned short int TRISD4 = 4;
    sbit  TRISD4_bit at TRISD.B4;
    const register unsigned short int TRISD5 = 5;
    sbit  TRISD5_bit at TRISD.B5;
    const register unsigned short int TRISD6 = 6;
    sbit  TRISD6_bit at TRISD.B6;
    const register unsigned short int TRISD7 = 7;
    sbit  TRISD7_bit at TRISD.B7;

sfr unsigned short volatile DDRD             absolute 0xF95;
sfr unsigned short volatile TRISE            absolute 0xF96;
    const register unsigned short int TRISE0 = 0;
    sbit  TRISE0_bit at TRISE.B0;
    const register unsigned short int TRISE1 = 1;
    sbit  TRISE1_bit at TRISE.B1;
    const register unsigned short int TRISE2 = 2;
    sbit  TRISE2_bit at TRISE.B2;
    const register unsigned short int TRISE3 = 3;
    sbit  TRISE3_bit at TRISE.B3;
    const register unsigned short int TRISE4 = 4;
    sbit  TRISE4_bit at TRISE.B4;
    const register unsigned short int TRISE5 = 5;
    sbit  TRISE5_bit at TRISE.B5;
    const register unsigned short int TRISE6 = 6;
    sbit  TRISE6_bit at TRISE.B6;
    const register unsigned short int TRISE7 = 7;
    sbit  TRISE7_bit at TRISE.B7;

sfr unsigned short volatile DDRE             absolute 0xF96;
sfr unsigned short volatile TRISF            absolute 0xF97;
    const register unsigned short int TRISF0 = 0;
    sbit  TRISF0_bit at TRISF.B0;
    const register unsigned short int TRISF1 = 1;
    sbit  TRISF1_bit at TRISF.B1;
    const register unsigned short int TRISF2 = 2;
    sbit  TRISF2_bit at TRISF.B2;
    const register unsigned short int TRISF3 = 3;
    sbit  TRISF3_bit at TRISF.B3;
    const register unsigned short int TRISF4 = 4;
    sbit  TRISF4_bit at TRISF.B4;
    const register unsigned short int TRISF5 = 5;
    sbit  TRISF5_bit at TRISF.B5;
    const register unsigned short int TRISF6 = 6;
    sbit  TRISF6_bit at TRISF.B6;
    const register unsigned short int TRISF7 = 7;
    sbit  TRISF7_bit at TRISF.B7;

sfr unsigned short volatile DDRF             absolute 0xF97;
sfr unsigned short volatile TRISG            absolute 0xF98;
    const register unsigned short int TRISG0 = 0;
    sbit  TRISG0_bit at TRISG.B0;
    const register unsigned short int TRISG1 = 1;
    sbit  TRISG1_bit at TRISG.B1;
    const register unsigned short int TRISG2 = 2;
    sbit  TRISG2_bit at TRISG.B2;
    const register unsigned short int TRISG3 = 3;
    sbit  TRISG3_bit at TRISG.B3;
    const register unsigned short int TRISG4 = 4;
    sbit  TRISG4_bit at TRISG.B4;

sfr unsigned short volatile DDRG             absolute 0xF98;
sfr unsigned short volatile TRISH            absolute 0xF99;
    const register unsigned short int TRISH0 = 0;
    sbit  TRISH0_bit at TRISH.B0;
    const register unsigned short int TRISH1 = 1;
    sbit  TRISH1_bit at TRISH.B1;
    const register unsigned short int TRISH2 = 2;
    sbit  TRISH2_bit at TRISH.B2;
    const register unsigned short int TRISH3 = 3;
    sbit  TRISH3_bit at TRISH.B3;
    const register unsigned short int TRISH4 = 4;
    sbit  TRISH4_bit at TRISH.B4;
    const register unsigned short int TRISH5 = 5;
    sbit  TRISH5_bit at TRISH.B5;
    const register unsigned short int TRISH6 = 6;
    sbit  TRISH6_bit at TRISH.B6;
    const register unsigned short int TRISH7 = 7;
    sbit  TRISH7_bit at TRISH.B7;

sfr unsigned short volatile DDRH             absolute 0xF99;
sfr unsigned short volatile TRISJ            absolute 0xF9A;
    const register unsigned short int TRISJ0 = 0;
    sbit  TRISJ0_bit at TRISJ.B0;
    const register unsigned short int TRISJ1 = 1;
    sbit  TRISJ1_bit at TRISJ.B1;
    const register unsigned short int TRISJ2 = 2;
    sbit  TRISJ2_bit at TRISJ.B2;
    const register unsigned short int TRISJ3 = 3;
    sbit  TRISJ3_bit at TRISJ.B3;
    const register unsigned short int TRISJ4 = 4;
    sbit  TRISJ4_bit at TRISJ.B4;
    const register unsigned short int TRISJ5 = 5;
    sbit  TRISJ5_bit at TRISJ.B5;
    const register unsigned short int TRISJ6 = 6;
    sbit  TRISJ6_bit at TRISJ.B6;
    const register unsigned short int TRISJ7 = 7;
    sbit  TRISJ7_bit at TRISJ.B7;

sfr unsigned short volatile DDRJ             absolute 0xF9A;
sfr unsigned short volatile OSCTUNE          absolute 0xF9B;
    const register unsigned short int TUN0 = 0;
    sbit  TUN0_bit at OSCTUNE.B0;
    const register unsigned short int TUN1 = 1;
    sbit  TUN1_bit at OSCTUNE.B1;
    const register unsigned short int TUN2 = 2;
    sbit  TUN2_bit at OSCTUNE.B2;
    const register unsigned short int TUN3 = 3;
    sbit  TUN3_bit at OSCTUNE.B3;
    const register unsigned short int TUN4 = 4;
    sbit  TUN4_bit at OSCTUNE.B4;
    const register unsigned short int PLLEN = 6;
    sbit  PLLEN_bit at OSCTUNE.B6;
    const register unsigned short int INTSRC = 7;
    sbit  INTSRC_bit at OSCTUNE.B7;

sfr unsigned short volatile MEMCON           absolute 0xF9C;
    const register unsigned short int WM0 = 0;
    sbit  WM0_bit at MEMCON.B0;
    const register unsigned short int WM1 = 1;
    sbit  WM1_bit at MEMCON.B1;
    const register unsigned short int WAIT0 = 4;
    sbit  WAIT0_bit at MEMCON.B4;
    const register unsigned short int WAIT1 = 5;
    sbit  WAIT1_bit at MEMCON.B5;
    const register unsigned short int EBDIS = 7;
    sbit  EBDIS_bit at MEMCON.B7;

sfr unsigned short volatile PIE1             absolute 0xF9D;
    const register unsigned short int TMR1IE = 0;
    sbit  TMR1IE_bit at PIE1.B0;
    const register unsigned short int TMR2IE = 1;
    sbit  TMR2IE_bit at PIE1.B1;
    const register unsigned short int CCP1IE = 2;
    sbit  CCP1IE_bit at PIE1.B2;
    const register unsigned short int SSPIE = 3;
    sbit  SSPIE_bit at PIE1.B3;
    const register unsigned short int TX1IE = 4;
    sbit  TX1IE_bit at PIE1.B4;
    const register unsigned short int RC1IE = 5;
    sbit  RC1IE_bit at PIE1.B5;
    const register unsigned short int ADIE = 6;
    sbit  ADIE_bit at PIE1.B6;
    const register unsigned short int PSPIE = 7;
    sbit  PSPIE_bit at PIE1.B7;
    const register unsigned short int RCIE = 5;
    sbit  RCIE_bit at PIE1.B5;
    const register unsigned short int TXIE = 4;
    sbit  TXIE_bit at PIE1.B4;

sfr unsigned short volatile PIR1             absolute 0xF9E;
    const register unsigned short int TMR1IF = 0;
    sbit  TMR1IF_bit at PIR1.B0;
    const register unsigned short int TMR2IF = 1;
    sbit  TMR2IF_bit at PIR1.B1;
    const register unsigned short int CCP1IF = 2;
    sbit  CCP1IF_bit at PIR1.B2;
    const register unsigned short int SSPIF = 3;
    sbit  SSPIF_bit at PIR1.B3;
    const register unsigned short int TX1IF = 4;
    sbit  TX1IF_bit at PIR1.B4;
    const register unsigned short int RC1IF = 5;
    sbit  RC1IF_bit at PIR1.B5;
    const register unsigned short int ADIF = 6;
    sbit  ADIF_bit at PIR1.B6;
    const register unsigned short int PSPIF = 7;
    sbit  PSPIF_bit at PIR1.B7;
    const register unsigned short int RCIF = 5;
    sbit  RCIF_bit at PIR1.B5;
    const register unsigned short int TXIF = 4;
    sbit  TXIF_bit at PIR1.B4;

sfr unsigned short volatile IPR1             absolute 0xF9F;
    const register unsigned short int TMR1IP = 0;
    sbit  TMR1IP_bit at IPR1.B0;
    const register unsigned short int TMR2IP = 1;
    sbit  TMR2IP_bit at IPR1.B1;
    const register unsigned short int CCP1IP = 2;
    sbit  CCP1IP_bit at IPR1.B2;
    const register unsigned short int SSPIP = 3;
    sbit  SSPIP_bit at IPR1.B3;
    const register unsigned short int TX1IP = 4;
    sbit  TX1IP_bit at IPR1.B4;
    const register unsigned short int RC1IP = 5;
    sbit  RC1IP_bit at IPR1.B5;
    const register unsigned short int ADIP = 6;
    sbit  ADIP_bit at IPR1.B6;
    const register unsigned short int PSPIP = 7;
    sbit  PSPIP_bit at IPR1.B7;
    const register unsigned short int RCIP = 5;
    sbit  RCIP_bit at IPR1.B5;
    const register unsigned short int TXIP = 4;
    sbit  TXIP_bit at IPR1.B4;

sfr unsigned short volatile PIE2             absolute 0xFA0;
    const register unsigned short int CCP2IE = 0;
    sbit  CCP2IE_bit at PIE2.B0;
    const register unsigned short int TMR3IE = 1;
    sbit  TMR3IE_bit at PIE2.B1;
    const register unsigned short int HLVDIE = 2;
    sbit  HLVDIE_bit at PIE2.B2;
    const register unsigned short int BCLIE = 3;
    sbit  BCLIE_bit at PIE2.B3;
    const register unsigned short int CMIE = 6;
    sbit  CMIE_bit at PIE2.B6;
    const register unsigned short int OSCFIE = 7;
    sbit  OSCFIE_bit at PIE2.B7;
    const register unsigned short int LVDIE = 2;
    sbit  LVDIE_bit at PIE2.B2;

sfr unsigned short volatile PIR2             absolute 0xFA1;
    const register unsigned short int CCP2IF = 0;
    sbit  CCP2IF_bit at PIR2.B0;
    const register unsigned short int TMR3IF = 1;
    sbit  TMR3IF_bit at PIR2.B1;
    const register unsigned short int HLVDIF = 2;
    sbit  HLVDIF_bit at PIR2.B2;
    const register unsigned short int BCLIF = 3;
    sbit  BCLIF_bit at PIR2.B3;
    const register unsigned short int CMIF = 6;
    sbit  CMIF_bit at PIR2.B6;
    const register unsigned short int OSCFIF = 7;
    sbit  OSCFIF_bit at PIR2.B7;
    const register unsigned short int LVDIF = 2;
    sbit  LVDIF_bit at PIR2.B2;

sfr unsigned short volatile IPR2             absolute 0xFA2;
    const register unsigned short int CCP2IP = 0;
    sbit  CCP2IP_bit at IPR2.B0;
    const register unsigned short int TMR3IP = 1;
    sbit  TMR3IP_bit at IPR2.B1;
    const register unsigned short int HLVDIP = 2;
    sbit  HLVDIP_bit at IPR2.B2;
    const register unsigned short int BCLIP = 3;
    sbit  BCLIP_bit at IPR2.B3;
    const register unsigned short int CMIP = 6;
    sbit  CMIP_bit at IPR2.B6;
    const register unsigned short int OSCFIP = 7;
    sbit  OSCFIP_bit at IPR2.B7;
    const register unsigned short int LVDIP = 2;
    sbit  LVDIP_bit at IPR2.B2;

sfr unsigned short volatile PIE3             absolute 0xFA3;
    const register unsigned short int CCP3IE = 0;
    sbit  CCP3IE_bit at PIE3.B0;
    const register unsigned short int TX2IE = 4;
    sbit  TX2IE_bit at PIE3.B4;
    const register unsigned short int RC2IE = 5;
    sbit  RC2IE_bit at PIE3.B5;
    const register unsigned short int RXB0IE = 0;
    sbit  RXB0IE_bit at PIE3.B0;
    const register unsigned short int TXB2IE = 4;
    sbit  TXB2IE_bit at PIE3.B4;
    const register unsigned short int TXBNIE = 4;
    sbit  TXBNIE_bit at PIE3.B4;

sfr unsigned short volatile PIR3             absolute 0xFA4;
    const register unsigned short int CCP3IF = 0;
    sbit  CCP3IF_bit at PIR3.B0;
    const register unsigned short int TX2IF = 4;
    sbit  TX2IF_bit at PIR3.B4;
    const register unsigned short int RC2IF = 5;
    sbit  RC2IF_bit at PIR3.B5;
    const register unsigned short int TXBNIF = 4;
    sbit  TXBNIF_bit at PIR3.B4;

sfr unsigned short volatile IPR3             absolute 0xFA5;
    const register unsigned short int CCP3IP = 0;
    sbit  CCP3IP_bit at IPR3.B0;
    const register unsigned short int TX2IP = 4;
    sbit  TX2IP_bit at IPR3.B4;
    const register unsigned short int RC2IP = 5;
    sbit  RC2IP_bit at IPR3.B5;
    const register unsigned short int TXBNIP = 4;
    sbit  TXBNIP_bit at IPR3.B4;

sfr unsigned short volatile RCSTA1           absolute 0xFAB;
    const register unsigned short int RX9D1 = 0;
    sbit  RX9D1_bit at RCSTA1.B0;
    const register unsigned short int OERR = 1;
    sbit  OERR_bit at RCSTA1.B1;
    const register unsigned short int FERR1 = 2;
    sbit  FERR1_bit at RCSTA1.B2;
    const register unsigned short int ADDEN1 = 3;
    sbit  ADDEN1_bit at RCSTA1.B3;
    const register unsigned short int CREN = 4;
    sbit  CREN_bit at RCSTA1.B4;
    const register unsigned short int SREN1 = 5;
    sbit  SREN1_bit at RCSTA1.B5;
    const register unsigned short int RX91 = 6;
    sbit  RX91_bit at RCSTA1.B6;
    const register unsigned short int SPEN1 = 7;
    sbit  SPEN1_bit at RCSTA1.B7;
    const register unsigned short int CREN1 = 4;
    sbit  CREN1_bit at RCSTA1.B4;
    const register unsigned short int OERR1 = 1;
    sbit  OERR1_bit at RCSTA1.B1;
    const register unsigned short int SRENA = 5;
    sbit  SRENA_bit at RCSTA1.B5;

sfr unsigned short volatile RCSTA            absolute 0xFAB;
sfr unsigned short volatile TXSTA1           absolute 0xFAC;
    const register unsigned short int TX9D1 = 0;
    sbit  TX9D1_bit at TXSTA1.B0;
    const register unsigned short int TRMT = 1;
    sbit  TRMT_bit at TXSTA1.B1;
    const register unsigned short int BRGH1 = 2;
    sbit  BRGH1_bit at TXSTA1.B2;
    const register unsigned short int SENDB = 3;
    sbit  SENDB_bit at TXSTA1.B3;
    const register unsigned short int SYNC1 = 4;
    sbit  SYNC1_bit at TXSTA1.B4;
    const register unsigned short int TXEN = 5;
    sbit  TXEN_bit at TXSTA1.B5;
    const register unsigned short int TX91 = 6;
    sbit  TX91_bit at TXSTA1.B6;
    const register unsigned short int CSRC1 = 7;
    sbit  CSRC1_bit at TXSTA1.B7;
    const register unsigned short int SENDB1 = 3;
    sbit  SENDB1_bit at TXSTA1.B3;
    const register unsigned short int TRMT1 = 1;
    sbit  TRMT1_bit at TXSTA1.B1;
    const register unsigned short int TXEN1 = 5;
    sbit  TXEN1_bit at TXSTA1.B5;

sfr unsigned short volatile TXSTA            absolute 0xFAC;
sfr unsigned short volatile TXREG1           absolute 0xFAD;
sfr unsigned short volatile TXREG            absolute 0xFAD;
sfr unsigned short volatile RCREG1           absolute 0xFAE;
sfr unsigned short volatile RCREG            absolute 0xFAE;
sfr unsigned int            SPBRG1           absolute 0xFAF;
sfr unsigned int            SPBRG            absolute 0xFAF;
sfr unsigned short volatile PSPCON           absolute 0xFB0;
    const register unsigned short int PSPMODE = 4;
    sbit  PSPMODE_bit at PSPCON.B4;
    const register unsigned short int IBOV = 5;
    sbit  IBOV_bit at PSPCON.B5;
    const register unsigned short int OBF = 6;
    sbit  OBF_bit at PSPCON.B6;
    const register unsigned short int IBF = 7;
    sbit  IBF_bit at PSPCON.B7;

sfr unsigned short volatile T3CON            absolute 0xFB1;
    const register unsigned short int TMR3ON = 0;
    sbit  TMR3ON_bit at T3CON.B0;
    const register unsigned short int TMR3CS = 1;
    sbit  TMR3CS_bit at T3CON.B1;
    const register unsigned short int NOT_T3SYNC = 2;
    sbit  NOT_T3SYNC_bit at T3CON.B2;
    const register unsigned short int SOSCEN3 = 3;
    sbit  SOSCEN3_bit at T3CON.B3;
    const register unsigned short int T3CKPS0 = 4;
    sbit  T3CKPS0_bit at T3CON.B4;
    const register unsigned short int T3CKPS1 = 5;
    sbit  T3CKPS1_bit at T3CON.B5;
    const register unsigned short int T3CCP2 = 6;
    sbit  T3CCP2_bit at T3CON.B6;
    const register unsigned short int RD163 = 7;
    sbit  RD163_bit at T3CON.B7;
    const register unsigned short int T3CCP1 = 3;
    sbit  T3CCP1_bit at T3CON.B3;
    const register unsigned short int T3INSYNC = 2;
    sbit  T3INSYNC_bit at T3CON.B2;
    const register unsigned short int T3RD16 = 7;
    sbit  T3RD16_bit at T3CON.B7;
    const register unsigned short int T3SYNC = 2;
    sbit  T3SYNC_bit at T3CON.B2;
    const register unsigned short int nT3SYNC = 2;
    sbit  nT3SYNC_bit at T3CON.B2;

sfr unsigned int   volatile TMR3             absolute 0xFB2;
sfr unsigned short volatile TMR3L            absolute 0xFB2;
sfr unsigned short volatile TMR3H            absolute 0xFB3;
sfr unsigned short volatile CMCON            absolute 0xFB4;
    const register unsigned short int CM0 = 0;
    sbit  CM0_bit at CMCON.B0;
    const register unsigned short int CM1 = 1;
    sbit  CM1_bit at CMCON.B1;
    const register unsigned short int CM2 = 2;
    sbit  CM2_bit at CMCON.B2;
    const register unsigned short int CIS = 3;
    sbit  CIS_bit at CMCON.B3;
    const register unsigned short int C1INV = 4;
    sbit  C1INV_bit at CMCON.B4;
    const register unsigned short int C2INV = 5;
    sbit  C2INV_bit at CMCON.B5;
    const register unsigned short int C1OUT = 6;
    sbit  C1OUT_bit at CMCON.B6;
    const register unsigned short int C2OUT = 7;
    sbit  C2OUT_bit at CMCON.B7;
    const register unsigned short int CMEN0 = 0;
    sbit  CMEN0_bit at CMCON.B0;
    const register unsigned short int CMEN1 = 1;
    sbit  CMEN1_bit at CMCON.B1;
    const register unsigned short int CMEN2 = 2;
    sbit  CMEN2_bit at CMCON.B2;

sfr unsigned short volatile CVRCON           absolute 0xFB5;
    const register unsigned short int CVR0 = 0;
    sbit  CVR0_bit at CVRCON.B0;
    const register unsigned short int CVR1 = 1;
    sbit  CVR1_bit at CVRCON.B1;
    const register unsigned short int CVR2 = 2;
    sbit  CVR2_bit at CVRCON.B2;
    const register unsigned short int CVR3 = 3;
    sbit  CVR3_bit at CVRCON.B3;
    const register unsigned short int CVREF = 4;
    sbit  CVREF_bit at CVRCON.B4;
    const register unsigned short int CVRR = 5;
    sbit  CVRR_bit at CVRCON.B5;
    const register unsigned short int CVROE = 6;
    sbit  CVROE_bit at CVRCON.B6;
    const register unsigned short int CVREN = 7;
    sbit  CVREN_bit at CVRCON.B7;
    const register unsigned short int CVROEN = 6;
    sbit  CVROEN_bit at CVRCON.B6;
    const register unsigned short int CVRSS = 4;
    sbit  CVRSS_bit at CVRCON.B4;

sfr unsigned short volatile CCP3CON          absolute 0xFB7;
    const register unsigned short int CCP3M0 = 0;
    sbit  CCP3M0_bit at CCP3CON.B0;
    const register unsigned short int CCP3M1 = 1;
    sbit  CCP3M1_bit at CCP3CON.B1;
    const register unsigned short int CCP3M2 = 2;
    sbit  CCP3M2_bit at CCP3CON.B2;
    const register unsigned short int CCP3M3 = 3;
    sbit  CCP3M3_bit at CCP3CON.B3;
    const register unsigned short int DC3B0 = 4;
    sbit  DC3B0_bit at CCP3CON.B4;
    const register unsigned short int DC3B1 = 5;
    sbit  DC3B1_bit at CCP3CON.B5;
    const register unsigned short int DCCP3X = 5;
    sbit  DCCP3X_bit at CCP3CON.B5;
    const register unsigned short int DCCP3Y = 4;
    sbit  DCCP3Y_bit at CCP3CON.B4;

sfr unsigned int   volatile CCPR3            absolute 0xFB8;
sfr unsigned short volatile CCPR3L           absolute 0xFB8;
sfr unsigned short volatile CCPR3H           absolute 0xFB9;
sfr unsigned short volatile CCP2CON          absolute 0xFBA;
    const register unsigned short int CCP2M0 = 0;
    sbit  CCP2M0_bit at CCP2CON.B0;
    const register unsigned short int CCP2M1 = 1;
    sbit  CCP2M1_bit at CCP2CON.B1;
    const register unsigned short int CCP2M2 = 2;
    sbit  CCP2M2_bit at CCP2CON.B2;
    const register unsigned short int CCP2M3 = 3;
    sbit  CCP2M3_bit at CCP2CON.B3;
    const register unsigned short int CCP2Y = 4;
    sbit  CCP2Y_bit at CCP2CON.B4;
    const register unsigned short int CCP2X = 5;
    sbit  CCP2X_bit at CCP2CON.B5;
    const register unsigned short int DC2B0 = 4;
    sbit  DC2B0_bit at CCP2CON.B4;
    const register unsigned short int DC2B1 = 5;
    sbit  DC2B1_bit at CCP2CON.B5;
    const register unsigned short int DCCP2X = 5;
    sbit  DCCP2X_bit at CCP2CON.B5;
    const register unsigned short int DCCP2Y = 4;
    sbit  DCCP2Y_bit at CCP2CON.B4;

sfr unsigned int   volatile CCPR2            absolute 0xFBB;
sfr unsigned short volatile CCPR2L           absolute 0xFBB;
sfr unsigned short volatile CCPR2H           absolute 0xFBC;
sfr unsigned short volatile CCP1CON          absolute 0xFBD;
    const register unsigned short int CCP1M0 = 0;
    sbit  CCP1M0_bit at CCP1CON.B0;
    const register unsigned short int CCP1M1 = 1;
    sbit  CCP1M1_bit at CCP1CON.B1;
    const register unsigned short int CCP1M2 = 2;
    sbit  CCP1M2_bit at CCP1CON.B2;
    const register unsigned short int CCP1M3 = 3;
    sbit  CCP1M3_bit at CCP1CON.B3;
    const register unsigned short int CCP1Y = 4;
    sbit  CCP1Y_bit at CCP1CON.B4;
    const register unsigned short int CCP1X = 5;
    sbit  CCP1X_bit at CCP1CON.B5;
    const register unsigned short int DC1B0 = 4;
    sbit  DC1B0_bit at CCP1CON.B4;
    const register unsigned short int DC1B1 = 5;
    sbit  DC1B1_bit at CCP1CON.B5;
    const register unsigned short int DCCP1X = 5;
    sbit  DCCP1X_bit at CCP1CON.B5;
    const register unsigned short int DCCP1Y = 4;
    sbit  DCCP1Y_bit at CCP1CON.B4;

sfr unsigned int   volatile CCPR1            absolute 0xFBE;
sfr unsigned short volatile CCPR1L           absolute 0xFBE;
sfr unsigned short volatile CCPR1H           absolute 0xFBF;
sfr unsigned short volatile ADCON2           absolute 0xFC0;
    const register unsigned short int ADCS0 = 0;
    sbit  ADCS0_bit at ADCON2.B0;
    const register unsigned short int ADCS1 = 1;
    sbit  ADCS1_bit at ADCON2.B1;
    const register unsigned short int ADCS2 = 2;
    sbit  ADCS2_bit at ADCON2.B2;
    const register unsigned short int ACQT0 = 3;
    sbit  ACQT0_bit at ADCON2.B3;
    const register unsigned short int ACQT1 = 4;
    sbit  ACQT1_bit at ADCON2.B4;
    const register unsigned short int ACQT2 = 5;
    sbit  ACQT2_bit at ADCON2.B5;
    const register unsigned short int ADFM = 7;
    sbit  ADFM_bit at ADCON2.B7;

sfr unsigned short volatile ADCON1           absolute 0xFC1;
    const register unsigned short int PCFG0 = 0;
    sbit  PCFG0_bit at ADCON1.B0;
    const register unsigned short int PCFG1 = 1;
    sbit  PCFG1_bit at ADCON1.B1;
    const register unsigned short int PCFG2 = 2;
    sbit  PCFG2_bit at ADCON1.B2;
    const register unsigned short int CHSN3 = 3;
    sbit  CHSN3_bit at ADCON1.B3;
    const register unsigned short int VCFG0 = 4;
    sbit  VCFG0_bit at ADCON1.B4;
    const register unsigned short int VCFG1 = 5;
    sbit  VCFG1_bit at ADCON1.B5;
    const register unsigned short int PCFG3 = 3;
    sbit  PCFG3_bit at ADCON1.B3;
    const register unsigned short int VCFG01 = 4;
    sbit  VCFG01_bit at ADCON1.B4;
    const register unsigned short int VCFG11 = 5;
    sbit  VCFG11_bit at ADCON1.B5;

sfr unsigned short volatile ADCON0           absolute 0xFC2;
    const register unsigned short int ADON = 0;
    sbit  ADON_bit at ADCON0.B0;
    const register unsigned short int DONE = 1;
    sbit  DONE_bit at ADCON0.B1;
    const register unsigned short int CHS0 = 2;
    sbit  CHS0_bit at ADCON0.B2;
    const register unsigned short int CHS1 = 3;
    sbit  CHS1_bit at ADCON0.B3;
    const register unsigned short int CHS2 = 4;
    sbit  CHS2_bit at ADCON0.B4;
    const register unsigned short int CHS3 = 5;
    sbit  CHS3_bit at ADCON0.B5;
    const register unsigned short int GO = 1;
    sbit  GO_bit at ADCON0.B1;
    const register unsigned short int GODONE = 1;
    sbit  GODONE_bit at ADCON0.B1;
    const register unsigned short int GO_DONE = 1;
    sbit  GO_DONE_bit at ADCON0.B1;
    const register unsigned short int GO_NOT_DONE = 1;
    sbit  GO_NOT_DONE_bit at ADCON0.B1;
    const register unsigned short int GO_nDONE = 1;
    sbit  GO_nDONE_bit at ADCON0.B1;
    const register unsigned short int NOT_DONE = 1;
    sbit  NOT_DONE_bit at ADCON0.B1;
    const register unsigned short int nDONE = 1;
    sbit  nDONE_bit at ADCON0.B1;

sfr unsigned int   volatile ADRES            absolute 0xFC3;
sfr unsigned short volatile ADRESL           absolute 0xFC3;
sfr unsigned short volatile ADRESH           absolute 0xFC4;
sfr unsigned short volatile SSPCON2          absolute 0xFC5;
    const register unsigned short int SEN = 0;
    sbit  SEN_bit at SSPCON2.B0;
    const register unsigned short int RSEN = 1;
    sbit  RSEN_bit at SSPCON2.B1;
    const register unsigned short int PEN = 2;
    sbit  PEN_bit at SSPCON2.B2;
    const register unsigned short int RCEN = 3;
    sbit  RCEN_bit at SSPCON2.B3;
    const register unsigned short int ACKEN = 4;
    sbit  ACKEN_bit at SSPCON2.B4;
    const register unsigned short int ACKDT = 5;
    sbit  ACKDT_bit at SSPCON2.B5;
    const register unsigned short int ACKSTAT = 6;
    sbit  ACKSTAT_bit at SSPCON2.B6;
    const register unsigned short int GCEN = 7;
    sbit  GCEN_bit at SSPCON2.B7;

sfr unsigned short volatile SSPCON1          absolute 0xFC6;
    const register unsigned short int SSPM0 = 0;
    sbit  SSPM0_bit at SSPCON1.B0;
    const register unsigned short int SSPM1 = 1;
    sbit  SSPM1_bit at SSPCON1.B1;
    const register unsigned short int SSPM2 = 2;
    sbit  SSPM2_bit at SSPCON1.B2;
    const register unsigned short int SSPM3 = 3;
    sbit  SSPM3_bit at SSPCON1.B3;
    const register unsigned short int CKP = 4;
    sbit  CKP_bit at SSPCON1.B4;
    const register unsigned short int SSPEN = 5;
    sbit  SSPEN_bit at SSPCON1.B5;
    const register unsigned short int SSPOV = 6;
    sbit  SSPOV_bit at SSPCON1.B6;
    const register unsigned short int WCOL = 7;
    sbit  WCOL_bit at SSPCON1.B7;

sfr unsigned short volatile SSPSTAT          absolute 0xFC7;
    const register unsigned short int BF = 0;
    sbit  BF_bit at SSPSTAT.B0;
    const register unsigned short int UA = 1;
    sbit  UA_bit at SSPSTAT.B1;
    const register unsigned short int NOT_W = 2;
    sbit  NOT_W_bit at SSPSTAT.B2;
    const register unsigned short int START = 3;
    sbit  START_bit at SSPSTAT.B3;
    const register unsigned short int STOP_ = 4;
    sbit  STOP_bit at SSPSTAT.B4;
    const register unsigned short int DA = 5;
    sbit  DA_bit at SSPSTAT.B5;
    const register unsigned short int CKE = 6;
    sbit  CKE_bit at SSPSTAT.B6;
    const register unsigned short int SMP = 7;
    sbit  SMP_bit at SSPSTAT.B7;
    const register unsigned short int DATA_ADDRESS = 5;
    sbit  DATA_ADDRESS_bit at SSPSTAT.B5;
    const register unsigned short int D_A = 5;
    sbit  D_A_bit at SSPSTAT.B5;
    const register unsigned short int D_NOT_A = 5;
    sbit  D_NOT_A_bit at SSPSTAT.B5;
    const register unsigned short int D_nA = 5;
    sbit  D_nA_bit at SSPSTAT.B5;
    const register unsigned short int I2C_DAT = 5;
    sbit  I2C_DAT_bit at SSPSTAT.B5;
    const register unsigned short int NOT_A = 5;
    sbit  NOT_A_bit at SSPSTAT.B5;
    const register unsigned short int NOT_ADDRESS = 5;
    sbit  NOT_ADDRESS_bit at SSPSTAT.B5;
    const register unsigned short int NOT_WRITE = 2;
    sbit  NOT_WRITE_bit at SSPSTAT.B2;
    const register unsigned short int READ_WRITE = 2;
    sbit  READ_WRITE_bit at SSPSTAT.B2;
    const register unsigned short int RW = 2;
    sbit  RW_bit at SSPSTAT.B2;
    const register unsigned short int R_NOT_W = 2;
    sbit  R_NOT_W_bit at SSPSTAT.B2;
    const register unsigned short int R_W = 2;
    sbit  R_W_bit at SSPSTAT.B2;
    const register unsigned short int R_nW = 2;
    sbit  R_nW_bit at SSPSTAT.B2;
    const register unsigned short int nA = 5;
    sbit  nA_bit at SSPSTAT.B5;
    const register unsigned short int nADDRESS = 5;
    sbit  nADDRESS_bit at SSPSTAT.B5;
    const register unsigned short int nW = 2;
    sbit  nW_bit at SSPSTAT.B2;
    const register unsigned short int nWRITE = 2;
    sbit  nWRITE_bit at SSPSTAT.B2;

sfr unsigned short volatile SSPADD           absolute 0xFC8;
sfr unsigned short volatile SSPBUF           absolute 0xFC9;
sfr unsigned short volatile T2CON            absolute 0xFCA;
    const register unsigned short int T2CKPS0 = 0;
    sbit  T2CKPS0_bit at T2CON.B0;
    const register unsigned short int T2CKPS1 = 1;
    sbit  T2CKPS1_bit at T2CON.B1;
    const register unsigned short int TMR2ON = 2;
    sbit  TMR2ON_bit at T2CON.B2;
    const register unsigned short int T2OUTPS0 = 3;
    sbit  T2OUTPS0_bit at T2CON.B3;
    const register unsigned short int T2OUTPS1 = 4;
    sbit  T2OUTPS1_bit at T2CON.B4;
    const register unsigned short int T2OUTPS2 = 5;
    sbit  T2OUTPS2_bit at T2CON.B5;
    const register unsigned short int T2OUTPS3 = 6;
    sbit  T2OUTPS3_bit at T2CON.B6;

sfr unsigned short volatile PR2              absolute 0xFCB;
sfr unsigned short volatile TMR2             absolute 0xFCC;
sfr unsigned short volatile T1CON            absolute 0xFCD;
    const register unsigned short int TMR1ON = 0;
    sbit  TMR1ON_bit at T1CON.B0;
    const register unsigned short int TMR1CS = 1;
    sbit  TMR1CS_bit at T1CON.B1;
    const register unsigned short int NOT_T1SYNC = 2;
    sbit  NOT_T1SYNC_bit at T1CON.B2;
    const register unsigned short int SOSCEN = 3;
    sbit  SOSCEN_bit at T1CON.B3;
    const register unsigned short int T1CKPS0 = 4;
    sbit  T1CKPS0_bit at T1CON.B4;
    const register unsigned short int T1CKPS1 = 5;
    sbit  T1CKPS1_bit at T1CON.B5;
    const register unsigned short int T1RUN = 6;
    sbit  T1RUN_bit at T1CON.B6;
    const register unsigned short int T1RD16 = 7;
    sbit  T1RD16_bit at T1CON.B7;
    const register unsigned short int T1INSYNC = 2;
    sbit  T1INSYNC_bit at T1CON.B2;
    const register unsigned short int T1OSCEN = 3;
    sbit  T1OSCEN_bit at T1CON.B3;
    const register unsigned short int T1SYNC = 2;
    sbit  T1SYNC_bit at T1CON.B2;
    const register unsigned short int nT1SYNC = 2;
    sbit  nT1SYNC_bit at T1CON.B2;

sfr unsigned int   volatile TMR1             absolute 0xFCE;
sfr unsigned short volatile TMR1L            absolute 0xFCE;
sfr unsigned short volatile TMR1H            absolute 0xFCF;
sfr unsigned short volatile RCON             absolute 0xFD0;
    const register unsigned short int BOR = 0;
    sbit  BOR_bit at RCON.B0;
    const register unsigned short int NOT_POR = 1;
    sbit  NOT_POR_bit at RCON.B1;
    const register unsigned short int NOT_PD = 2;
    sbit  NOT_PD_bit at RCON.B2;
    const register unsigned short int NOT_TO = 3;
    sbit  NOT_TO_bit at RCON.B3;
    const register unsigned short int NOT_RI = 4;
    sbit  NOT_RI_bit at RCON.B4;
    const register unsigned short int SBOREN = 6;
    sbit  SBOREN_bit at RCON.B6;
    const register unsigned short int IPEN = 7;
    sbit  IPEN_bit at RCON.B7;
    const register unsigned short int NOT_BOR = 0;
    sbit  NOT_BOR_bit at RCON.B0;
    const register unsigned short int PD = 2;
    sbit  PD_bit at RCON.B2;
    const register unsigned short int POR = 1;
    sbit  POR_bit at RCON.B1;
    const register unsigned short int RI = 4;
    sbit  RI_bit at RCON.B4;
    const register unsigned short int TO_ = 3;
    sbit  TO_bit at RCON.B3;
    const register unsigned short int nBOR = 0;
    sbit  nBOR_bit at RCON.B0;
    const register unsigned short int nPD = 2;
    sbit  nPD_bit at RCON.B2;
    const register unsigned short int nPOR = 1;
    sbit  nPOR_bit at RCON.B1;
    const register unsigned short int nRI = 4;
    sbit  nRI_bit at RCON.B4;
    const register unsigned short int nTO = 3;
    sbit  nTO_bit at RCON.B3;

sfr unsigned short          WDTCON           absolute 0xFD1;
    const register unsigned short int SWDTE = 0;
    sbit  SWDTE_bit at WDTCON.B0;
    const register unsigned short int SWDTEN = 0;
    sbit  SWDTEN_bit at WDTCON.B0;

sfr unsigned short volatile HLVDCON          absolute 0xFD2;
    const register unsigned short int HLVDL0 = 0;
    sbit  HLVDL0_bit at HLVDCON.B0;
    const register unsigned short int HLVDL1 = 1;
    sbit  HLVDL1_bit at HLVDCON.B1;
    const register unsigned short int HLVDL2 = 2;
    sbit  HLVDL2_bit at HLVDCON.B2;
    const register unsigned short int HLVDL3 = 3;
    sbit  HLVDL3_bit at HLVDCON.B3;
    const register unsigned short int HLVDEN = 4;
    sbit  HLVDEN_bit at HLVDCON.B4;
    const register unsigned short int BGST = 5;
    sbit  BGST_bit at HLVDCON.B5;
    const register unsigned short int VDIRMAG = 7;
    sbit  VDIRMAG_bit at HLVDCON.B7;
    const register unsigned short int IRVST = 5;
    sbit  IRVST_bit at HLVDCON.B5;
    const register unsigned short int LVDEN = 4;
    sbit  LVDEN_bit at HLVDCON.B4;
    const register unsigned short int LVDL0 = 0;
    sbit  LVDL0_bit at HLVDCON.B0;
    const register unsigned short int LVDL1 = 1;
    sbit  LVDL1_bit at HLVDCON.B1;
    const register unsigned short int LVDL2 = 2;
    sbit  LVDL2_bit at HLVDCON.B2;
    const register unsigned short int LVDL3 = 3;
    sbit  LVDL3_bit at HLVDCON.B3;
    const register unsigned short int LVV0 = 0;
    sbit  LVV0_bit at HLVDCON.B0;
    const register unsigned short int LVV1 = 1;
    sbit  LVV1_bit at HLVDCON.B1;
    const register unsigned short int LVV2 = 2;
    sbit  LVV2_bit at HLVDCON.B2;
    const register unsigned short int LVV3 = 3;
    sbit  LVV3_bit at HLVDCON.B3;

sfr unsigned short volatile LVDCON           absolute 0xFD2;
sfr unsigned short volatile OSCCON           absolute 0xFD3;
    const register unsigned short int SCS0 = 0;
    sbit  SCS0_bit at OSCCON.B0;
    const register unsigned short int SCS1 = 1;
    sbit  SCS1_bit at OSCCON.B1;
    const register unsigned short int FLTS = 2;
    sbit  FLTS_bit at OSCCON.B2;
    const register unsigned short int OSTS = 3;
    sbit  OSTS_bit at OSCCON.B3;
    const register unsigned short int IRCF0 = 4;
    sbit  IRCF0_bit at OSCCON.B4;
    const register unsigned short int IRCF1 = 5;
    sbit  IRCF1_bit at OSCCON.B5;
    const register unsigned short int IRCF2 = 6;
    sbit  IRCF2_bit at OSCCON.B6;
    const register unsigned short int IDLEN = 7;
    sbit  IDLEN_bit at OSCCON.B7;
    const register unsigned short int IOFS = 2;
    sbit  IOFS_bit at OSCCON.B2;

sfr unsigned short volatile T0CON            absolute 0xFD5;
    const register unsigned short int T0PS0 = 0;
    sbit  T0PS0_bit at T0CON.B0;
    const register unsigned short int T0PS1 = 1;
    sbit  T0PS1_bit at T0CON.B1;
    const register unsigned short int T0PS2 = 2;
    sbit  T0PS2_bit at T0CON.B2;
    const register unsigned short int PSA = 3;
    sbit  PSA_bit at T0CON.B3;
    const register unsigned short int T0SE = 4;
    sbit  T0SE_bit at T0CON.B4;
    const register unsigned short int T0CS = 5;
    sbit  T0CS_bit at T0CON.B5;
    const register unsigned short int T08BIT = 6;
    sbit  T08BIT_bit at T0CON.B6;
    const register unsigned short int TMR0ON = 7;
    sbit  TMR0ON_bit at T0CON.B7;

sfr unsigned int   volatile TMR0             absolute 0xFD6;
sfr unsigned short volatile TMR0L            absolute 0xFD6;
sfr unsigned short volatile TMR0H            absolute 0xFD7;
sfr unsigned short volatile STATUS           absolute 0xFD8;
    const register unsigned short int CARRY = 0;
    const register unsigned short int C = 0;
    sbit  CARRY_bit at STATUS.B0;
    sbit  C_bit at STATUS.B0;
    const register unsigned short int DC = 1;
    sbit  DC_bit at STATUS.B1;
    const register unsigned short int ZERO = 2;
    const register unsigned short int Z = 2;
    sbit  ZERO_bit at STATUS.B2;
    sbit  Z_bit at STATUS.B2;
    const register unsigned short int OV = 3;
    sbit  OV_bit at STATUS.B3;
    const register unsigned short int NEGATIVE = 4;
    sbit  NEGATIVE_bit at STATUS.B4;
    const register unsigned short int OVERFLOW = 3;
    sbit  OVERFLOW_bit at STATUS.B3;

sfr unsigned int            FSR2             absolute 0xFD9;
sfr unsigned short          FSR2L            absolute 0xFD9;
register unsigned short     *FSR2PTR         absolute 0xFD9;
sfr unsigned short          FSR2H            absolute 0xFDA;
sfr unsigned short volatile PLUSW2           absolute 0xFDB;
sfr unsigned short volatile PREINC2          absolute 0xFDC;
sfr unsigned short volatile POSTDEC2         absolute 0xFDD;
sfr unsigned short volatile POSTINC2         absolute 0xFDE;
sfr unsigned short volatile INDF2            absolute 0xFDF;
sfr unsigned short          BSR              absolute 0xFE0;
sfr unsigned int            FSR1             absolute 0xFE1;
sfr unsigned short          FSR1L            absolute 0xFE1;
register unsigned short     *FSR1PTR         absolute 0xFE1;
sfr unsigned short          FSR1H            absolute 0xFE2;
sfr unsigned short volatile PLUSW1           absolute 0xFE3;
sfr unsigned short volatile PREINC1          absolute 0xFE4;
sfr unsigned short volatile POSTDEC1         absolute 0xFE5;
sfr unsigned short volatile POSTINC1         absolute 0xFE6;
sfr unsigned short volatile INDF1            absolute 0xFE7;
sfr unsigned short volatile WREG             absolute 0xFE8;
sfr unsigned int            FSR0             absolute 0xFE9;
sfr unsigned short          FSR0L            absolute 0xFE9;
register unsigned short     *FSR0PTR         absolute 0xFE9;
sfr unsigned short          FSR0H            absolute 0xFEA;
sfr unsigned short volatile PLUSW0           absolute 0xFEB;
sfr unsigned short volatile PREINC0          absolute 0xFEC;
sfr unsigned short volatile POSTDEC0         absolute 0xFED;
sfr unsigned short volatile POSTINC0         absolute 0xFEE;
sfr unsigned short volatile INDF0            absolute 0xFEF;
sfr unsigned short volatile INTCON3          absolute 0xFF0;
    const register unsigned short int INT1F = 0;
    sbit  INT1F_bit at INTCON3.B0;
    const register unsigned short int INT2F = 1;
    sbit  INT2F_bit at INTCON3.B1;
    const register unsigned short int INT3F = 2;
    sbit  INT3F_bit at INTCON3.B2;
    const register unsigned short int INT1E = 3;
    sbit  INT1E_bit at INTCON3.B3;
    const register unsigned short int INT2E = 4;
    sbit  INT2E_bit at INTCON3.B4;
    const register unsigned short int INT3E = 5;
    sbit  INT3E_bit at INTCON3.B5;
    const register unsigned short int INT1IP = 6;
    sbit  INT1IP_bit at INTCON3.B6;
    const register unsigned short int INT2IP = 7;
    sbit  INT2IP_bit at INTCON3.B7;
    const register unsigned short int INT1IE = 3;
    sbit  INT1IE_bit at INTCON3.B3;
    const register unsigned short int INT1IF = 0;
    sbit  INT1IF_bit at INTCON3.B0;
    const register unsigned short int INT1P = 6;
    sbit  INT1P_bit at INTCON3.B6;
    const register unsigned short int INT2IE = 4;
    sbit  INT2IE_bit at INTCON3.B4;
    const register unsigned short int INT2IF = 1;
    sbit  INT2IF_bit at INTCON3.B1;
    const register unsigned short int INT2P = 7;
    sbit  INT2P_bit at INTCON3.B7;
    const register unsigned short int INT3IE = 5;
    sbit  INT3IE_bit at INTCON3.B5;
    const register unsigned short int INT3IF = 2;
    sbit  INT3IF_bit at INTCON3.B2;

sfr unsigned short volatile INTCON2          absolute 0xFF1;
    const register unsigned short int RBIP = 0;
    sbit  RBIP_bit at INTCON2.B0;
    const register unsigned short int INT3IP = 1;
    sbit  INT3IP_bit at INTCON2.B1;
    const register unsigned short int T0IP = 2;
    sbit  T0IP_bit at INTCON2.B2;
    const register unsigned short int INTEDG3 = 3;
    sbit  INTEDG3_bit at INTCON2.B3;
    const register unsigned short int INTEDG2 = 4;
    sbit  INTEDG2_bit at INTCON2.B4;
    const register unsigned short int INTEDG1 = 5;
    sbit  INTEDG1_bit at INTCON2.B5;
    const register unsigned short int INTEDG0 = 6;
    sbit  INTEDG0_bit at INTCON2.B6;
    const register unsigned short int NOT_RBPU = 7;
    sbit  NOT_RBPU_bit at INTCON2.B7;
    const register unsigned short int INT3P = 1;
    sbit  INT3P_bit at INTCON2.B1;
    const register unsigned short int RBPU = 7;
    sbit  RBPU_bit at INTCON2.B7;
    const register unsigned short int TMR0IP = 2;
    sbit  TMR0IP_bit at INTCON2.B2;
    const register unsigned short int nRBPU = 7;
    sbit  nRBPU_bit at INTCON2.B7;

sfr unsigned short volatile INTCON           absolute 0xFF2;
    const register unsigned short int RBIF = 0;
    sbit  RBIF_bit at INTCON.B0;
    const register unsigned short int INT0F = 1;
    sbit  INT0F_bit at INTCON.B1;
    const register unsigned short int T0IF = 2;
    sbit  T0IF_bit at INTCON.B2;
    const register unsigned short int RBIE = 3;
    sbit  RBIE_bit at INTCON.B3;
    const register unsigned short int INT0E = 4;
    sbit  INT0E_bit at INTCON.B4;
    const register unsigned short int T0IE = 5;
    sbit  T0IE_bit at INTCON.B5;
    const register unsigned short int GIEL = 6;
    sbit  GIEL_bit at INTCON.B6;
    const register unsigned short int GIE = 7;
    sbit  GIE_bit at INTCON.B7;
    const register unsigned short int GIEH = 7;
    sbit  GIEH_bit at INTCON.B7;
    const register unsigned short int GIE_GIEH = 7;
    sbit  GIE_GIEH_bit at INTCON.B7;
    const register unsigned short int INT0IE = 4;
    sbit  INT0IE_bit at INTCON.B4;
    const register unsigned short int INT0IF = 1;
    sbit  INT0IF_bit at INTCON.B1;
    const register unsigned short int PEIE = 6;
    sbit  PEIE_bit at INTCON.B6;
    const register unsigned short int PEIE_GIEL = 6;
    sbit  PEIE_GIEL_bit at INTCON.B6;
    const register unsigned short int TMR0IE = 5;
    sbit  TMR0IE_bit at INTCON.B5;
    const register unsigned short int TMR0IF = 2;
    sbit  TMR0IF_bit at INTCON.B2;

sfr unsigned int            PROD             absolute 0xFF3;
sfr unsigned short          PRODL            absolute 0xFF3;
sfr unsigned short          PRODH            absolute 0xFF4;
const register unsigned short *TBLPTR        absolute 0xFF6 ;
sfr unsigned short volatile TABLAT           absolute 0xFF5;
sfr unsigned short          TBLPTRL          absolute 0xFF6;
sfr unsigned short          TBLPTRH          absolute 0xFF7;
sfr unsigned short          TBLPTRU          absolute 0xFF8;
sfr unsigned short volatile PCL              absolute 0xFF9;
sfr unsigned short volatile PCLATH           absolute 0xFFA;
sfr unsigned short volatile PCLATU           absolute 0xFFB;
sfr unsigned short volatile STKPTR           absolute 0xFFC;
    const register unsigned short int STKPTR0 = 0;
    sbit  STKPTR0_bit at STKPTR.B0;
    const register unsigned short int STKPTR1 = 1;
    sbit  STKPTR1_bit at STKPTR.B1;
    const register unsigned short int STKPTR2 = 2;
    sbit  STKPTR2_bit at STKPTR.B2;
    const register unsigned short int STKPTR3 = 3;
    sbit  STKPTR3_bit at STKPTR.B3;
    const register unsigned short int STKPTR4 = 4;
    sbit  STKPTR4_bit at STKPTR.B4;
    const register unsigned short int STKUNF = 6;
    sbit  STKUNF_bit at STKPTR.B6;
    const register unsigned short int STKFUL = 7;
    sbit  STKFUL_bit at STKPTR.B7;
    const register unsigned short int STKOVF = 7;
    sbit  STKOVF_bit at STKPTR.B7;

sfr unsigned short volatile TOSL             absolute 0xFFD;
sfr unsigned short volatile TOSH             absolute 0xFFE;
sfr unsigned short volatile TOSU             absolute 0xFFF;
