// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00000800;

// Working space registers
rx unsigned short R0  absolute 0x0070;
rx unsigned short R1  absolute 0x0071;
rx unsigned short R2  absolute 0x0072;
rx unsigned short R3  absolute 0x0073;
rx unsigned short R4  absolute 0x0074;
rx unsigned short R5  absolute 0x0075;
rx unsigned short R6  absolute 0x0076;
rx unsigned short R7  absolute 0x0077;
rx unsigned short R8  absolute 0x0078;
rx unsigned short R9  absolute 0x0079;
rx unsigned short R10 absolute 0x007A;
rx unsigned short R11 absolute 0x007B;
rx unsigned short R12 absolute 0x007C;
rx unsigned short R13 absolute 0x007D;
rx unsigned short R14 absolute 0x007E;
rx unsigned short R15 absolute 0x007F;

const register unsigned short int W = 0;
const register unsigned short int F = 1;

// Special function registers (SFRs)

const signed int   PORT_TO_TRIS_OFFSET    =     128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

sfr unsigned short volatile INDF0            absolute 0x000;
sfr unsigned short volatile INDF1            absolute 0x001;
sfr unsigned short volatile PCL              absolute 0x002;
sfr unsigned short volatile STATUS           absolute 0x003;
    const register unsigned short int CARRY = 0;
    const register unsigned short int C = 0;
    sbit  CARRY_bit at STATUS.B0;
    sbit  C_bit at STATUS.B0;
    const register unsigned short int DC = 1;
    sbit  DC_bit at STATUS.B1;
    const register unsigned short int ZERO = 2;
    const register unsigned short int Z = 2;
    sbit  ZERO_bit at STATUS.B2;
    sbit  Z_bit at STATUS.B2;
    const register unsigned short int nPD = 3;
    sbit  nPD_bit at STATUS.B3;
    const register unsigned short int nTO = 4;
    sbit  nTO_bit at STATUS.B4;

sfr unsigned int            FSR0             absolute 0x004;
sfr unsigned short          FSR0L            absolute 0x004;
register unsigned short     *FSR0PTR         absolute 0x004;
sfr unsigned short          FSR0H            absolute 0x005;
sfr unsigned int            FSR1             absolute 0x006;
sfr unsigned short          FSR1L            absolute 0x006;
register unsigned short     *FSR1PTR         absolute 0x006;
sfr unsigned short          FSR1H            absolute 0x007;
sfr unsigned short          BSR              absolute 0x008;
    const register unsigned short int BSR0 = 0;
    sbit  BSR0_bit at BSR.B0;
    const register unsigned short int BSR1 = 1;
    sbit  BSR1_bit at BSR.B1;
    const register unsigned short int BSR2 = 2;
    sbit  BSR2_bit at BSR.B2;
    const register unsigned short int BSR3 = 3;
    sbit  BSR3_bit at BSR.B3;
    const register unsigned short int BSR4 = 4;
    sbit  BSR4_bit at BSR.B4;

sfr unsigned short volatile WREG             absolute 0x009;
sfr unsigned short volatile PCLATH           absolute 0x00A;
sfr unsigned short volatile INTCON           absolute 0x00B;
    const register unsigned short int IOCIF = 0;
    sbit  IOCIF_bit at INTCON.B0;
    const register unsigned short int INTF = 1;
    sbit  INTF_bit at INTCON.B1;
    const register unsigned short int T0IF = 2;
    sbit  T0IF_bit at INTCON.B2;
    const register unsigned short int IOCIE = 3;
    sbit  IOCIE_bit at INTCON.B3;
    const register unsigned short int INTE = 4;
    sbit  INTE_bit at INTCON.B4;
    const register unsigned short int T0IE = 5;
    sbit  T0IE_bit at INTCON.B5;
    const register unsigned short int PEIE = 6;
    sbit  PEIE_bit at INTCON.B6;
    const register unsigned short int GIE = 7;
    sbit  GIE_bit at INTCON.B7;
    const register unsigned short int TMR0IE = 5;
    sbit  TMR0IE_bit at INTCON.B5;
    const register unsigned short int TMR0IF = 2;
    sbit  TMR0IF_bit at INTCON.B2;

sfr unsigned short volatile PORTA            absolute 0x00C;
    const register unsigned short int RA0 = 0;
    sbit  RA0_bit at PORTA.B0;
    const register unsigned short int RA1 = 1;
    sbit  RA1_bit at PORTA.B1;
    const register unsigned short int RA2 = 2;
    sbit  RA2_bit at PORTA.B2;
    const register unsigned short int RA3 = 3;
    sbit  RA3_bit at PORTA.B3;
    const register unsigned short int RA4 = 4;
    sbit  RA4_bit at PORTA.B4;
    const register unsigned short int RA5 = 5;
    sbit  RA5_bit at PORTA.B5;

sfr unsigned short volatile PIR1             absolute 0x011;
    const register unsigned short int TMR1IF = 0;
    sbit  TMR1IF_bit at PIR1.B0;
    const register unsigned short int TMR2IF = 1;
    sbit  TMR2IF_bit at PIR1.B1;
    const register unsigned short int CCP1IF = 2;
    sbit  CCP1IF_bit at PIR1.B2;
    const register unsigned short int ADIF = 6;
    sbit  ADIF_bit at PIR1.B6;
    const register unsigned short int TMR1GIF = 7;
    sbit  TMR1GIF_bit at PIR1.B7;

sfr unsigned short volatile PIR2             absolute 0x012;
    const register unsigned short int CCP2IF = 0;
    sbit  CCP2IF_bit at PIR2.B0;
    const register unsigned short int TMR4IF = 1;
    sbit  TMR4IF_bit at PIR2.B1;
    const register unsigned short int TMR6IF = 2;
    sbit  TMR6IF_bit at PIR2.B2;
    const register unsigned short int C1IF = 5;
    sbit  C1IF_bit at PIR2.B5;
    const register unsigned short int C2IF = 6;
    sbit  C2IF_bit at PIR2.B6;

sfr unsigned short volatile PIR3             absolute 0x013;
    const register unsigned short int ZCDIF = 4;
    sbit  ZCDIF_bit at PIR3.B4;
    const register unsigned short int CWGIF = 5;
    sbit  CWGIF_bit at PIR3.B5;

sfr unsigned short volatile PIR4             absolute 0x014;
    const register unsigned short int SMT1IF = 0;
    sbit  SMT1IF_bit at PIR4.B0;
    const register unsigned short int SMT1PRAIF = 1;
    sbit  SMT1PRAIF_bit at PIR4.B1;
    const register unsigned short int SMT1PWAIF = 2;
    sbit  SMT1PWAIF_bit at PIR4.B2;
    const register unsigned short int SMT2IF = 3;
    sbit  SMT2IF_bit at PIR4.B3;
    const register unsigned short int SMT2PRAIF = 4;
    sbit  SMT2PRAIF_bit at PIR4.B4;
    const register unsigned short int SMT2PWAIF = 5;
    sbit  SMT2PWAIF_bit at PIR4.B5;
    const register unsigned short int CRCIF = 6;
    sbit  CRCIF_bit at PIR4.B6;
    const register unsigned short int SCANIF = 7;
    sbit  SCANIF_bit at PIR4.B7;

sfr unsigned short volatile TMR0             absolute 0x015;
sfr unsigned int   volatile TMR1             absolute 0x016;
sfr unsigned short volatile TMR1L            absolute 0x016;
sfr unsigned short volatile TMR1H            absolute 0x017;
sfr unsigned short volatile T1CON            absolute 0x018;
    const register unsigned short int TMR1ON = 0;
    sbit  TMR1ON_bit at T1CON.B0;
    const register unsigned short int nT1SYNC = 2;
    sbit  nT1SYNC_bit at T1CON.B2;
    const register unsigned short int T1CKPS0 = 4;
    sbit  T1CKPS0_bit at T1CON.B4;
    const register unsigned short int T1CKPS1 = 5;
    sbit  T1CKPS1_bit at T1CON.B5;
    const register unsigned short int TMR1CS0 = 6;
    sbit  TMR1CS0_bit at T1CON.B6;
    const register unsigned short int TMR1CS1 = 7;
    sbit  TMR1CS1_bit at T1CON.B7;

sfr unsigned short volatile T1GCON           absolute 0x019;
    const register unsigned short int T1GSS0 = 0;
    sbit  T1GSS0_bit at T1GCON.B0;
    const register unsigned short int T1GSS1 = 1;
    sbit  T1GSS1_bit at T1GCON.B1;
    const register unsigned short int T1GVAL = 2;
    sbit  T1GVAL_bit at T1GCON.B2;
    const register unsigned short int T1GGO_nDONE = 3;
    sbit  T1GGO_nDONE_bit at T1GCON.B3;
    const register unsigned short int T1GSPM = 4;
    sbit  T1GSPM_bit at T1GCON.B4;
    const register unsigned short int T1GTM = 5;
    sbit  T1GTM_bit at T1GCON.B5;
    const register unsigned short int T1GPOL = 6;
    sbit  T1GPOL_bit at T1GCON.B6;
    const register unsigned short int TMR1GE = 7;
    sbit  TMR1GE_bit at T1GCON.B7;

sfr unsigned short volatile T2TMR            absolute 0x01A;
sfr unsigned short volatile TMR2             absolute 0x01A;
sfr unsigned short volatile T2PR             absolute 0x01B;
sfr unsigned short volatile PR2              absolute 0x01B;
sfr unsigned short volatile T2CON            absolute 0x01C;
    const register unsigned short int T2OUTPS0 = 0;
    sbit  T2OUTPS0_bit at T2CON.B0;
    const register unsigned short int T2OUTPS1 = 1;
    sbit  T2OUTPS1_bit at T2CON.B1;
    const register unsigned short int T2OUTPS2 = 2;
    sbit  T2OUTPS2_bit at T2CON.B2;
    const register unsigned short int T2OUTPS3 = 3;
    sbit  T2OUTPS3_bit at T2CON.B3;
    const register unsigned short int T2CKPS0 = 4;
    sbit  T2CKPS0_bit at T2CON.B4;
    const register unsigned short int T2CKPS1 = 5;
    sbit  T2CKPS1_bit at T2CON.B5;
    const register unsigned short int T2CKPS2 = 6;
    sbit  T2CKPS2_bit at T2CON.B6;
    const register unsigned short int T2ON = 7;
    sbit  T2ON_bit at T2CON.B7;
    const register unsigned short int TMR2ON = 7;
    sbit  TMR2ON_bit at T2CON.B7;

sfr unsigned short volatile T2HLT            absolute 0x01D;
    const register unsigned short int T2MODE0 = 0;
    sbit  T2MODE0_bit at T2HLT.B0;
    const register unsigned short int T2MODE1 = 1;
    sbit  T2MODE1_bit at T2HLT.B1;
    const register unsigned short int T2MODE2 = 2;
    sbit  T2MODE2_bit at T2HLT.B2;
    const register unsigned short int T2MODE3 = 3;
    sbit  T2MODE3_bit at T2HLT.B3;
    const register unsigned short int T2CKSYNC = 5;
    sbit  T2CKSYNC_bit at T2HLT.B5;
    const register unsigned short int T2CKPOL = 6;
    sbit  T2CKPOL_bit at T2HLT.B6;
    const register unsigned short int T2PSYNC = 7;
    sbit  T2PSYNC_bit at T2HLT.B7;

sfr unsigned short volatile T2CLKCON         absolute 0x01E;
    const register unsigned short int T2CS0 = 0;
    sbit  T2CS0_bit at T2CLKCON.B0;
    const register unsigned short int T2CS1 = 1;
    sbit  T2CS1_bit at T2CLKCON.B1;
    const register unsigned short int T2CS2 = 2;
    sbit  T2CS2_bit at T2CLKCON.B2;

sfr unsigned short volatile T2RST            absolute 0x01F;
    const register unsigned short int T2RSEL0 = 0;
    sbit  T2RSEL0_bit at T2RST.B0;
    const register unsigned short int T2RSEL1 = 1;
    sbit  T2RSEL1_bit at T2RST.B1;
    const register unsigned short int T2RSEL2 = 2;
    sbit  T2RSEL2_bit at T2RST.B2;
    const register unsigned short int T2RSEL3 = 3;
    sbit  T2RSEL3_bit at T2RST.B3;

sfr unsigned short volatile TRISA            absolute 0x08C;
    const register unsigned short int TRISA0 = 0;
    sbit  TRISA0_bit at TRISA.B0;
    const register unsigned short int TRISA1 = 1;
    sbit  TRISA1_bit at TRISA.B1;
    const register unsigned short int TRISA2 = 2;
    sbit  TRISA2_bit at TRISA.B2;
    const register unsigned short int TRISA3 = 3;
    sbit  TRISA3_bit at TRISA.B3;
    const register unsigned short int TRISA4 = 4;
    sbit  TRISA4_bit at TRISA.B4;
    const register unsigned short int TRISA5 = 5;
    sbit  TRISA5_bit at TRISA.B5;

sfr unsigned short volatile PIE1             absolute 0x091;
    const register unsigned short int TMR1IE = 0;
    sbit  TMR1IE_bit at PIE1.B0;
    const register unsigned short int TMR2IE = 1;
    sbit  TMR2IE_bit at PIE1.B1;
    const register unsigned short int CCP1IE = 2;
    sbit  CCP1IE_bit at PIE1.B2;
    const register unsigned short int ADIE = 6;
    sbit  ADIE_bit at PIE1.B6;
    const register unsigned short int TMR1GIE = 7;
    sbit  TMR1GIE_bit at PIE1.B7;

sfr unsigned short volatile PIE2             absolute 0x092;
    const register unsigned short int CCP2IE = 0;
    sbit  CCP2IE_bit at PIE2.B0;
    const register unsigned short int TMR4IE = 1;
    sbit  TMR4IE_bit at PIE2.B1;
    const register unsigned short int TMR6IE = 2;
    sbit  TMR6IE_bit at PIE2.B2;
    const register unsigned short int C1IE = 5;
    sbit  C1IE_bit at PIE2.B5;
    const register unsigned short int C2IE = 6;
    sbit  C2IE_bit at PIE2.B6;

sfr unsigned short volatile PIE3             absolute 0x093;
    const register unsigned short int ZCDIE = 4;
    sbit  ZCDIE_bit at PIE3.B4;
    const register unsigned short int CWGIE = 5;
    sbit  CWGIE_bit at PIE3.B5;

sfr unsigned short volatile PIE4             absolute 0x094;
    const register unsigned short int SMT1IE = 0;
    sbit  SMT1IE_bit at PIE4.B0;
    const register unsigned short int SMT1PRAIE = 1;
    sbit  SMT1PRAIE_bit at PIE4.B1;
    const register unsigned short int SMT1PWAIE = 2;
    sbit  SMT1PWAIE_bit at PIE4.B2;
    const register unsigned short int SMT2IE = 3;
    sbit  SMT2IE_bit at PIE4.B3;
    const register unsigned short int SMT2PRAIE = 4;
    sbit  SMT2PRAIE_bit at PIE4.B4;
    const register unsigned short int SMT2PWAIE = 5;
    sbit  SMT2PWAIE_bit at PIE4.B5;
    const register unsigned short int CRCIE = 6;
    sbit  CRCIE_bit at PIE4.B6;
    const register unsigned short int SCANIE = 7;
    sbit  SCANIE_bit at PIE4.B7;

sfr unsigned short volatile OPTION_REG       absolute 0x095;
    const register unsigned short int PS0 = 0;
    sbit  PS0_bit at OPTION_REG.B0;
    const register unsigned short int PS1 = 1;
    sbit  PS1_bit at OPTION_REG.B1;
    const register unsigned short int PS2 = 2;
    sbit  PS2_bit at OPTION_REG.B2;
    const register unsigned short int PSA = 3;
    sbit  PSA_bit at OPTION_REG.B3;
    const register unsigned short int T0SE = 4;
    sbit  T0SE_bit at OPTION_REG.B4;
    const register unsigned short int T0CS = 5;
    sbit  T0CS_bit at OPTION_REG.B5;
    const register unsigned short int INTEDG = 6;
    sbit  INTEDG_bit at OPTION_REG.B6;
    const register unsigned short int nWPUEN = 7;
    sbit  nWPUEN_bit at OPTION_REG.B7;
    const register unsigned short int TMR0CS = 5;
    sbit  TMR0CS_bit at OPTION_REG.B5;
    const register unsigned short int TMR0SE = 4;
    sbit  TMR0SE_bit at OPTION_REG.B4;

sfr unsigned short volatile PCON             absolute 0x096;
    const register unsigned short int nBOR = 0;
    sbit  nBOR_bit at PCON.B0;
    const register unsigned short int nPOR = 1;
    sbit  nPOR_bit at PCON.B1;
    const register unsigned short int nRI = 2;
    sbit  nRI_bit at PCON.B2;
    const register unsigned short int nRMCLR = 3;
    sbit  nRMCLR_bit at PCON.B3;
    const register unsigned short int nRWDT = 4;
    sbit  nRWDT_bit at PCON.B4;
    const register unsigned short int nWDTWV = 5;
    sbit  nWDTWV_bit at PCON.B5;
    const register unsigned short int STKUNF = 6;
    sbit  STKUNF_bit at PCON.B6;
    const register unsigned short int STKOVF = 7;
    sbit  STKOVF_bit at PCON.B7;

sfr unsigned short volatile OSCTUNE          absolute 0x098;
    const register unsigned short int TUN0 = 0;
    sbit  TUN0_bit at OSCTUNE.B0;
    const register unsigned short int TUN1 = 1;
    sbit  TUN1_bit at OSCTUNE.B1;
    const register unsigned short int TUN2 = 2;
    sbit  TUN2_bit at OSCTUNE.B2;
    const register unsigned short int TUN3 = 3;
    sbit  TUN3_bit at OSCTUNE.B3;
    const register unsigned short int TUN4 = 4;
    sbit  TUN4_bit at OSCTUNE.B4;
    const register unsigned short int TUN5 = 5;
    sbit  TUN5_bit at OSCTUNE.B5;

sfr unsigned short volatile OSCCON           absolute 0x099;
    const register unsigned short int SCS0 = 0;
    sbit  SCS0_bit at OSCCON.B0;
    const register unsigned short int SCS1 = 1;
    sbit  SCS1_bit at OSCCON.B1;
    const register unsigned short int IRCF0 = 3;
    sbit  IRCF0_bit at OSCCON.B3;
    const register unsigned short int IRCF1 = 4;
    sbit  IRCF1_bit at OSCCON.B4;
    const register unsigned short int IRCF2 = 5;
    sbit  IRCF2_bit at OSCCON.B5;
    const register unsigned short int IRCF3 = 6;
    sbit  IRCF3_bit at OSCCON.B6;
    const register unsigned short int SPLLEN = 7;
    sbit  SPLLEN_bit at OSCCON.B7;

sfr unsigned short volatile OSCSTAT          absolute 0x09A;
    const register unsigned short int HFIOFS = 0;
    sbit  HFIOFS_bit at OSCSTAT.B0;
    const register unsigned short int LFIOFR = 1;
    sbit  LFIOFR_bit at OSCSTAT.B1;
    const register unsigned short int MFIOFR = 2;
    sbit  MFIOFR_bit at OSCSTAT.B2;
    const register unsigned short int HFIOFL = 3;
    sbit  HFIOFL_bit at OSCSTAT.B3;
    const register unsigned short int HFIOFR = 4;
    sbit  HFIOFR_bit at OSCSTAT.B4;
    const register unsigned short int PLLR = 6;
    sbit  PLLR_bit at OSCSTAT.B6;

sfr unsigned int   volatile ADRES            absolute 0x09B;
sfr unsigned short volatile ADRESL           absolute 0x09B;
sfr unsigned short volatile ADRESH           absolute 0x09C;
sfr unsigned short volatile ADCON0           absolute 0x09D;
    const register unsigned short int ADON = 0;
    sbit  ADON_bit at ADCON0.B0;
    const register unsigned short int ADGO = 1;
    sbit  ADGO_bit at ADCON0.B1;
    const register unsigned short int CHS0 = 2;
    sbit  CHS0_bit at ADCON0.B2;
    const register unsigned short int CHS1 = 3;
    sbit  CHS1_bit at ADCON0.B3;
    const register unsigned short int CHS2 = 4;
    sbit  CHS2_bit at ADCON0.B4;
    const register unsigned short int CHS3 = 5;
    sbit  CHS3_bit at ADCON0.B5;
    const register unsigned short int CHS4 = 6;
    sbit  CHS4_bit at ADCON0.B6;
    const register unsigned short int GO = 1;
    sbit  GO_bit at ADCON0.B1;
    const register unsigned short int GO_nDONE = 1;
    sbit  GO_nDONE_bit at ADCON0.B1;
    const register unsigned short int GO_NOT_DONE = 1;
    sbit  GO_NOT_DONE_bit at ADCON0.B1;

sfr unsigned short volatile ADCON1           absolute 0x09E;
    const register unsigned short int ADPREF0 = 0;
    sbit  ADPREF0_bit at ADCON1.B0;
    const register unsigned short int ADPREF1 = 1;
    sbit  ADPREF1_bit at ADCON1.B1;
    const register unsigned short int ADCS0 = 4;
    sbit  ADCS0_bit at ADCON1.B4;
    const register unsigned short int ADCS1 = 5;
    sbit  ADCS1_bit at ADCON1.B5;
    const register unsigned short int ADCS2 = 6;
    sbit  ADCS2_bit at ADCON1.B6;
    const register unsigned short int ADFM = 7;
    sbit  ADFM_bit at ADCON1.B7;

sfr unsigned short volatile ADCON2           absolute 0x09F;
    const register unsigned short int TRIGSEL0 = 4;
    sbit  TRIGSEL0_bit at ADCON2.B4;
    const register unsigned short int TRIGSEL1 = 5;
    sbit  TRIGSEL1_bit at ADCON2.B5;
    const register unsigned short int TRIGSEL2 = 6;
    sbit  TRIGSEL2_bit at ADCON2.B6;
    const register unsigned short int TRIGSEL3 = 7;
    sbit  TRIGSEL3_bit at ADCON2.B7;

sfr unsigned short volatile LATA             absolute 0x10C;
    const register unsigned short int LATA0 = 0;
    sbit  LATA0_bit at LATA.B0;
    const register unsigned short int LATA1 = 1;
    sbit  LATA1_bit at LATA.B1;
    const register unsigned short int LATA2 = 2;
    sbit  LATA2_bit at LATA.B2;
    const register unsigned short int LATA3 = 3;
    sbit  LATA3_bit at LATA.B3;
    const register unsigned short int LATA4 = 4;
    sbit  LATA4_bit at LATA.B4;
    const register unsigned short int LATA5 = 5;
    sbit  LATA5_bit at LATA.B5;

sfr unsigned short volatile CM1CON0          absolute 0x111;
    const register unsigned short int C1SYNC = 0;
    sbit  C1SYNC_bit at CM1CON0.B0;
    const register unsigned short int C1HYS = 1;
    sbit  C1HYS_bit at CM1CON0.B1;
    const register unsigned short int C1SP = 2;
    sbit  C1SP_bit at CM1CON0.B2;
    const register unsigned short int C1POL = 4;
    sbit  C1POL_bit at CM1CON0.B4;
    const register unsigned short int C1OE = 5;
    sbit  C1OE_bit at CM1CON0.B5;
    const register unsigned short int C1OUT = 6;
    sbit  C1OUT_bit at CM1CON0.B6;
    const register unsigned short int C1ON = 7;
    sbit  C1ON_bit at CM1CON0.B7;

sfr unsigned short volatile CM1CON1          absolute 0x112;
    const register unsigned short int C1NCH0 = 0;
    sbit  C1NCH0_bit at CM1CON1.B0;
    const register unsigned short int C1NCH1 = 1;
    sbit  C1NCH1_bit at CM1CON1.B1;
    const register unsigned short int C1NCH2 = 2;
    sbit  C1NCH2_bit at CM1CON1.B2;
    const register unsigned short int C1PCH0 = 4;
    sbit  C1PCH0_bit at CM1CON1.B4;
    const register unsigned short int C1PCH1 = 5;
    sbit  C1PCH1_bit at CM1CON1.B5;
    const register unsigned short int C1INTN = 6;
    sbit  C1INTN_bit at CM1CON1.B6;
    const register unsigned short int C1INTP = 7;
    sbit  C1INTP_bit at CM1CON1.B7;

sfr unsigned short volatile CMOUT            absolute 0x115;
    const register unsigned short int MC1OUT = 0;
    sbit  MC1OUT_bit at CMOUT.B0;

sfr unsigned short volatile BORCON           absolute 0x116;
    const register unsigned short int BORRDY = 0;
    sbit  BORRDY_bit at BORCON.B0;
    const register unsigned short int BORFS = 6;
    sbit  BORFS_bit at BORCON.B6;
    const register unsigned short int SBOREN = 7;
    sbit  SBOREN_bit at BORCON.B7;

sfr unsigned short volatile FVRCON           absolute 0x117;
    const register unsigned short int ADFVR0 = 0;
    sbit  ADFVR0_bit at FVRCON.B0;
    const register unsigned short int ADFVR1 = 1;
    sbit  ADFVR1_bit at FVRCON.B1;
    const register unsigned short int CDAFVR0 = 2;
    sbit  CDAFVR0_bit at FVRCON.B2;
    const register unsigned short int CDAFVR1 = 3;
    sbit  CDAFVR1_bit at FVRCON.B3;
    const register unsigned short int TSRNG = 4;
    sbit  TSRNG_bit at FVRCON.B4;
    const register unsigned short int TSEN = 5;
    sbit  TSEN_bit at FVRCON.B5;
    const register unsigned short int FVRRDY = 6;
    sbit  FVRRDY_bit at FVRCON.B6;
    const register unsigned short int FVREN = 7;
    sbit  FVREN_bit at FVRCON.B7;

sfr unsigned short volatile DAC1CON0         absolute 0x118;
    const register unsigned short int D1PSS0 = 2;
    sbit  D1PSS0_bit at DAC1CON0.B2;
    const register unsigned short int D1PSS1 = 3;
    sbit  D1PSS1_bit at DAC1CON0.B3;
    const register unsigned short int DAC1OE = 5;
    sbit  DAC1OE_bit at DAC1CON0.B5;
    const register unsigned short int DAC1EN = 7;
    sbit  DAC1EN_bit at DAC1CON0.B7;

sfr unsigned short volatile DAC1CON1         absolute 0x119;
    const register unsigned short int DAC1R0 = 0;
    sbit  DAC1R0_bit at DAC1CON1.B0;
    const register unsigned short int DAC1R1 = 1;
    sbit  DAC1R1_bit at DAC1CON1.B1;
    const register unsigned short int DAC1R2 = 2;
    sbit  DAC1R2_bit at DAC1CON1.B2;
    const register unsigned short int DAC1R3 = 3;
    sbit  DAC1R3_bit at DAC1CON1.B3;
    const register unsigned short int DAC1R4 = 4;
    sbit  DAC1R4_bit at DAC1CON1.B4;
    const register unsigned short int DAC1R5 = 5;
    sbit  DAC1R5_bit at DAC1CON1.B5;
    const register unsigned short int DAC1R6 = 6;
    sbit  DAC1R6_bit at DAC1CON1.B6;
    const register unsigned short int DAC1R7 = 7;
    sbit  DAC1R7_bit at DAC1CON1.B7;

sfr unsigned short volatile ZCD1CON          absolute 0x11C;
    const register unsigned short int ZCD1INTN = 0;
    sbit  ZCD1INTN_bit at ZCD1CON.B0;
    const register unsigned short int ZCD1INTP = 1;
    sbit  ZCD1INTP_bit at ZCD1CON.B1;
    const register unsigned short int ZCD1POL = 4;
    sbit  ZCD1POL_bit at ZCD1CON.B4;
    const register unsigned short int ZCD1OUT = 5;
    sbit  ZCD1OUT_bit at ZCD1CON.B5;
    const register unsigned short int ZCD1OE = 6;
    sbit  ZCD1OE_bit at ZCD1CON.B6;
    const register unsigned short int ZCD1EN = 7;
    sbit  ZCD1EN_bit at ZCD1CON.B7;

sfr unsigned short          APFCON           absolute 0x11D;
    const register unsigned short int CCP1SEL = 0;
    sbit  CCP1SEL_bit at APFCON.B0;
    const register unsigned short int T1GSEL = 3;
    sbit  T1GSEL_bit at APFCON.B3;
    const register unsigned short int CWGBSEL = 5;
    sbit  CWGBSEL_bit at APFCON.B5;
    const register unsigned short int CWGASEL = 6;
    sbit  CWGASEL_bit at APFCON.B6;

sfr unsigned short volatile ANSELA           absolute 0x18C;
    const register unsigned short int ANSA0 = 0;
    sbit  ANSA0_bit at ANSELA.B0;
    const register unsigned short int ANSA1 = 1;
    sbit  ANSA1_bit at ANSELA.B1;
    const register unsigned short int ANSA2 = 2;
    sbit  ANSA2_bit at ANSELA.B2;
    const register unsigned short int ANSA4 = 4;
    sbit  ANSA4_bit at ANSELA.B4;

sfr unsigned int   volatile PMADR            absolute 0x191;
sfr unsigned short volatile PMADRL           absolute 0x191;
sfr unsigned short volatile PMADRH           absolute 0x192;
sfr unsigned int   volatile PMDAT            absolute 0x193;
sfr unsigned short volatile PMDATL           absolute 0x193;
sfr unsigned short volatile PMDATH           absolute 0x194;
sfr unsigned short volatile PMCON1           absolute 0x195;
    const register unsigned short int RD = 0;
    sbit  RD_bit at PMCON1.B0;
    const register unsigned short int WR = 1;
    sbit  WR_bit at PMCON1.B1;
    const register unsigned short int WREN = 2;
    sbit  WREN_bit at PMCON1.B2;
    const register unsigned short int WRERR = 3;
    sbit  WRERR_bit at PMCON1.B3;
    const register unsigned short int FREE = 4;
    sbit  FREE_bit at PMCON1.B4;
    const register unsigned short int LWLO = 5;
    sbit  LWLO_bit at PMCON1.B5;
    const register unsigned short int CFGS = 6;
    sbit  CFGS_bit at PMCON1.B6;

sfr unsigned short volatile PMCON2           absolute 0x196;
sfr unsigned short volatile VREGCON          absolute 0x197;
    const register unsigned short int VREGPM0 = 0;
    sbit  VREGPM0_bit at VREGCON.B0;
    const register unsigned short int VREGPM1 = 1;
    sbit  VREGPM1_bit at VREGCON.B1;

sfr unsigned short          WPUA             absolute 0x20C;
    const register unsigned short int WPUA0 = 0;
    sbit  WPUA0_bit at WPUA.B0;
    const register unsigned short int WPUA1 = 1;
    sbit  WPUA1_bit at WPUA.B1;
    const register unsigned short int WPUA2 = 2;
    sbit  WPUA2_bit at WPUA.B2;
    const register unsigned short int WPUA3 = 3;
    sbit  WPUA3_bit at WPUA.B3;
    const register unsigned short int WPUA4 = 4;
    sbit  WPUA4_bit at WPUA.B4;
    const register unsigned short int WPUA5 = 5;
    sbit  WPUA5_bit at WPUA.B5;

sfr unsigned short volatile ODCONA           absolute 0x28C;
    const register unsigned short int ODA0 = 0;
    sbit  ODA0_bit at ODCONA.B0;
    const register unsigned short int ODA1 = 1;
    sbit  ODA1_bit at ODCONA.B1;
    const register unsigned short int ODA2 = 2;
    sbit  ODA2_bit at ODCONA.B2;
    const register unsigned short int ODA4 = 4;
    sbit  ODA4_bit at ODCONA.B4;
    const register unsigned short int ODA5 = 5;
    sbit  ODA5_bit at ODCONA.B5;

sfr unsigned int   volatile CCPR1            absolute 0x291;
sfr unsigned short volatile CCPR1L           absolute 0x291;
sfr unsigned short volatile CCPR1H           absolute 0x292;
sfr unsigned short volatile CCP1CON          absolute 0x293;
    const register unsigned short int CCP1MODE0 = 0;
    sbit  CCP1MODE0_bit at CCP1CON.B0;
    const register unsigned short int CCP1MODE1 = 1;
    sbit  CCP1MODE1_bit at CCP1CON.B1;
    const register unsigned short int CCP1MODE2 = 2;
    sbit  CCP1MODE2_bit at CCP1CON.B2;
    const register unsigned short int CCP1MODE3 = 3;
    sbit  CCP1MODE3_bit at CCP1CON.B3;
    const register unsigned short int CCP1FMT = 4;
    sbit  CCP1FMT_bit at CCP1CON.B4;
    const register unsigned short int CCP1OUT = 5;
    sbit  CCP1OUT_bit at CCP1CON.B5;
    const register unsigned short int CCP1OE = 6;
    sbit  CCP1OE_bit at CCP1CON.B6;
    const register unsigned short int CCP1EN = 7;
    sbit  CCP1EN_bit at CCP1CON.B7;
    const register unsigned short int P1M0 = 6;
    sbit  P1M0_bit at CCP1CON.B6;
    const register unsigned short int P1M1 = 7;
    sbit  P1M1_bit at CCP1CON.B7;

sfr unsigned short volatile CCP1CAP          absolute 0x294;
    const register unsigned short int CCP1CTS0 = 0;
    sbit  CCP1CTS0_bit at CCP1CAP.B0;
    const register unsigned short int CCP1CTS1 = 1;
    sbit  CCP1CTS1_bit at CCP1CAP.B1;

sfr unsigned int   volatile CCPR2            absolute 0x298;
sfr unsigned short volatile CCPR2L           absolute 0x298;
sfr unsigned short volatile CCPR2H           absolute 0x299;
sfr unsigned short volatile CCP2CON          absolute 0x29A;
    const register unsigned short int CCP2MODE0 = 0;
    sbit  CCP2MODE0_bit at CCP2CON.B0;
    const register unsigned short int CCP2MODE1 = 1;
    sbit  CCP2MODE1_bit at CCP2CON.B1;
    const register unsigned short int CCP2MODE2 = 2;
    sbit  CCP2MODE2_bit at CCP2CON.B2;
    const register unsigned short int CCP2MODE3 = 3;
    sbit  CCP2MODE3_bit at CCP2CON.B3;
    const register unsigned short int CCP2FMT = 4;
    sbit  CCP2FMT_bit at CCP2CON.B4;
    const register unsigned short int CCP2OUT = 5;
    sbit  CCP2OUT_bit at CCP2CON.B5;
    const register unsigned short int CCP2OE = 6;
    sbit  CCP2OE_bit at CCP2CON.B6;
    const register unsigned short int CCP2EN = 7;
    sbit  CCP2EN_bit at CCP2CON.B7;
    const register unsigned short int P2M0 = 6;
    sbit  P2M0_bit at CCP2CON.B6;
    const register unsigned short int P2M1 = 7;
    sbit  P2M1_bit at CCP2CON.B7;

sfr unsigned short volatile CCP2CAP          absolute 0x29B;
    const register unsigned short int CCP2CTS0 = 0;
    sbit  CCP2CTS0_bit at CCP2CAP.B0;
    const register unsigned short int CCP2CTS1 = 1;
    sbit  CCP2CTS1_bit at CCP2CAP.B1;

sfr unsigned short volatile CCPTMRS          absolute 0x29E;
    const register unsigned short int CCP1TSEL0 = 0;
    sbit  CCP1TSEL0_bit at CCPTMRS.B0;
    const register unsigned short int CCP1TSEL1 = 1;
    sbit  CCP1TSEL1_bit at CCPTMRS.B1;
    const register unsigned short int CCP2TSEL0 = 2;
    sbit  CCP2TSEL0_bit at CCPTMRS.B2;
    const register unsigned short int CCP2TSEL1 = 3;
    sbit  CCP2TSEL1_bit at CCPTMRS.B3;

sfr unsigned short volatile SLRCONA          absolute 0x30C;
    const register unsigned short int SLRA0 = 0;
    sbit  SLRA0_bit at SLRCONA.B0;
    const register unsigned short int SLRA1 = 1;
    sbit  SLRA1_bit at SLRCONA.B1;
    const register unsigned short int SLRA2 = 2;
    sbit  SLRA2_bit at SLRCONA.B2;
    const register unsigned short int SLRA4 = 4;
    sbit  SLRA4_bit at SLRCONA.B4;
    const register unsigned short int SLRA5 = 5;
    sbit  SLRA5_bit at SLRCONA.B5;

sfr unsigned short volatile INLVLA           absolute 0x38C;
    const register unsigned short int INLVLA0 = 0;
    sbit  INLVLA0_bit at INLVLA.B0;
    const register unsigned short int INLVLA1 = 1;
    sbit  INLVLA1_bit at INLVLA.B1;
    const register unsigned short int INLVLA2 = 2;
    sbit  INLVLA2_bit at INLVLA.B2;
    const register unsigned short int INLVLA3 = 3;
    sbit  INLVLA3_bit at INLVLA.B3;
    const register unsigned short int INLVLA4 = 4;
    sbit  INLVLA4_bit at INLVLA.B4;
    const register unsigned short int INLVLA5 = 5;
    sbit  INLVLA5_bit at INLVLA.B5;

sfr unsigned short volatile IOCAP            absolute 0x391;
    const register unsigned short int IOCAP0 = 0;
    sbit  IOCAP0_bit at IOCAP.B0;
    const register unsigned short int IOCAP1 = 1;
    sbit  IOCAP1_bit at IOCAP.B1;
    const register unsigned short int IOCAP2 = 2;
    sbit  IOCAP2_bit at IOCAP.B2;
    const register unsigned short int IOCAP3 = 3;
    sbit  IOCAP3_bit at IOCAP.B3;
    const register unsigned short int IOCAP4 = 4;
    sbit  IOCAP4_bit at IOCAP.B4;
    const register unsigned short int IOCAP5 = 5;
    sbit  IOCAP5_bit at IOCAP.B5;

sfr unsigned short volatile IOCAN            absolute 0x392;
    const register unsigned short int IOCAN0 = 0;
    sbit  IOCAN0_bit at IOCAN.B0;
    const register unsigned short int IOCAN1 = 1;
    sbit  IOCAN1_bit at IOCAN.B1;
    const register unsigned short int IOCAN2 = 2;
    sbit  IOCAN2_bit at IOCAN.B2;
    const register unsigned short int IOCAN3 = 3;
    sbit  IOCAN3_bit at IOCAN.B3;
    const register unsigned short int IOCAN4 = 4;
    sbit  IOCAN4_bit at IOCAN.B4;
    const register unsigned short int IOCAN5 = 5;
    sbit  IOCAN5_bit at IOCAN.B5;

sfr unsigned short volatile IOCAF            absolute 0x393;
    const register unsigned short int IOCAF0 = 0;
    sbit  IOCAF0_bit at IOCAF.B0;
    const register unsigned short int IOCAF1 = 1;
    sbit  IOCAF1_bit at IOCAF.B1;
    const register unsigned short int IOCAF2 = 2;
    sbit  IOCAF2_bit at IOCAF.B2;
    const register unsigned short int IOCAF3 = 3;
    sbit  IOCAF3_bit at IOCAF.B3;
    const register unsigned short int IOCAF4 = 4;
    sbit  IOCAF4_bit at IOCAF.B4;
    const register unsigned short int IOCAF5 = 5;
    sbit  IOCAF5_bit at IOCAF.B5;

sfr unsigned short volatile T4TMR            absolute 0x413;
sfr unsigned short volatile TMR4             absolute 0x413;
sfr unsigned short volatile T4PR             absolute 0x414;
sfr unsigned short volatile PR4              absolute 0x414;
sfr unsigned short volatile T4CON            absolute 0x415;
    const register unsigned short int T4OUTPS0 = 0;
    sbit  T4OUTPS0_bit at T4CON.B0;
    const register unsigned short int T4OUTPS1 = 1;
    sbit  T4OUTPS1_bit at T4CON.B1;
    const register unsigned short int T4OUTPS2 = 2;
    sbit  T4OUTPS2_bit at T4CON.B2;
    const register unsigned short int T4OUTPS3 = 3;
    sbit  T4OUTPS3_bit at T4CON.B3;
    const register unsigned short int T4CKPS0 = 4;
    sbit  T4CKPS0_bit at T4CON.B4;
    const register unsigned short int T4CKPS1 = 5;
    sbit  T4CKPS1_bit at T4CON.B5;
    const register unsigned short int T4CKPS2 = 6;
    sbit  T4CKPS2_bit at T4CON.B6;
    const register unsigned short int T4ON = 7;
    sbit  T4ON_bit at T4CON.B7;
    const register unsigned short int TMR4ON = 7;
    sbit  TMR4ON_bit at T4CON.B7;

sfr unsigned short volatile T4HLT            absolute 0x416;
    const register unsigned short int T4MODE0 = 0;
    sbit  T4MODE0_bit at T4HLT.B0;
    const register unsigned short int T4MODE1 = 1;
    sbit  T4MODE1_bit at T4HLT.B1;
    const register unsigned short int T4MODE2 = 2;
    sbit  T4MODE2_bit at T4HLT.B2;
    const register unsigned short int T4MODE3 = 3;
    sbit  T4MODE3_bit at T4HLT.B3;
    const register unsigned short int T4CKSYNC = 5;
    sbit  T4CKSYNC_bit at T4HLT.B5;
    const register unsigned short int T4CKPOL = 6;
    sbit  T4CKPOL_bit at T4HLT.B6;
    const register unsigned short int T4PSYNC = 7;
    sbit  T4PSYNC_bit at T4HLT.B7;

sfr unsigned short volatile T4CLKCON         absolute 0x417;
    const register unsigned short int T4CS0 = 0;
    sbit  T4CS0_bit at T4CLKCON.B0;
    const register unsigned short int T4CS1 = 1;
    sbit  T4CS1_bit at T4CLKCON.B1;
    const register unsigned short int T4CS2 = 2;
    sbit  T4CS2_bit at T4CLKCON.B2;

sfr unsigned short volatile T4RST            absolute 0x418;
    const register unsigned short int T4RSEL0 = 0;
    sbit  T4RSEL0_bit at T4RST.B0;
    const register unsigned short int T4RSEL1 = 1;
    sbit  T4RSEL1_bit at T4RST.B1;
    const register unsigned short int T4RSEL2 = 2;
    sbit  T4RSEL2_bit at T4RST.B2;
    const register unsigned short int T4RSEL3 = 3;
    sbit  T4RSEL3_bit at T4RST.B3;

sfr unsigned short volatile T6TMR            absolute 0x41A;
sfr unsigned short volatile TMR6             absolute 0x41A;
sfr unsigned short volatile T6PR             absolute 0x41B;
sfr unsigned short volatile PR6              absolute 0x41B;
sfr unsigned short volatile T6CON            absolute 0x41C;
    const register unsigned short int T6OUTPS0 = 0;
    sbit  T6OUTPS0_bit at T6CON.B0;
    const register unsigned short int T6OUTPS1 = 1;
    sbit  T6OUTPS1_bit at T6CON.B1;
    const register unsigned short int T6OUTPS2 = 2;
    sbit  T6OUTPS2_bit at T6CON.B2;
    const register unsigned short int T6OUTPS3 = 3;
    sbit  T6OUTPS3_bit at T6CON.B3;
    const register unsigned short int T6CKPS0 = 4;
    sbit  T6CKPS0_bit at T6CON.B4;
    const register unsigned short int T6CKPS1 = 5;
    sbit  T6CKPS1_bit at T6CON.B5;
    const register unsigned short int T6CKPS2 = 6;
    sbit  T6CKPS2_bit at T6CON.B6;
    const register unsigned short int T6ON = 7;
    sbit  T6ON_bit at T6CON.B7;
    const register unsigned short int TMR6ON = 7;
    sbit  TMR6ON_bit at T6CON.B7;

sfr unsigned short volatile T6HLT            absolute 0x41D;
    const register unsigned short int T6MODE0 = 0;
    sbit  T6MODE0_bit at T6HLT.B0;
    const register unsigned short int T6MODE1 = 1;
    sbit  T6MODE1_bit at T6HLT.B1;
    const register unsigned short int T6MODE2 = 2;
    sbit  T6MODE2_bit at T6HLT.B2;
    const register unsigned short int T6MODE3 = 3;
    sbit  T6MODE3_bit at T6HLT.B3;
    const register unsigned short int T6CKSYNC = 5;
    sbit  T6CKSYNC_bit at T6HLT.B5;
    const register unsigned short int T6CKPOL = 6;
    sbit  T6CKPOL_bit at T6HLT.B6;
    const register unsigned short int T6PSYNC = 7;
    sbit  T6PSYNC_bit at T6HLT.B7;

sfr unsigned short volatile T6CLKCON         absolute 0x41E;
    const register unsigned short int T6CS0 = 0;
    sbit  T6CS0_bit at T6CLKCON.B0;
    const register unsigned short int T6CS1 = 1;
    sbit  T6CS1_bit at T6CLKCON.B1;
    const register unsigned short int T6CS2 = 2;
    sbit  T6CS2_bit at T6CLKCON.B2;

sfr unsigned short volatile T6RST            absolute 0x41F;
    const register unsigned short int T6RSEL0 = 0;
    sbit  T6RSEL0_bit at T6RST.B0;
    const register unsigned short int T6RSEL1 = 1;
    sbit  T6RSEL1_bit at T6RST.B1;
    const register unsigned short int T6RSEL2 = 2;
    sbit  T6RSEL2_bit at T6RST.B2;
    const register unsigned short int T6RSEL3 = 3;
    sbit  T6RSEL3_bit at T6RST.B3;

sfr unsigned short volatile CWG1DBR          absolute 0x691;
    const register unsigned short int CWG1DBR0 = 0;
    sbit  CWG1DBR0_bit at CWG1DBR.B0;
    const register unsigned short int CWG1DBR1 = 1;
    sbit  CWG1DBR1_bit at CWG1DBR.B1;
    const register unsigned short int CWG1DBR2 = 2;
    sbit  CWG1DBR2_bit at CWG1DBR.B2;
    const register unsigned short int CWG1DBR3 = 3;
    sbit  CWG1DBR3_bit at CWG1DBR.B3;
    const register unsigned short int CWG1DBR4 = 4;
    sbit  CWG1DBR4_bit at CWG1DBR.B4;
    const register unsigned short int CWG1DBR5 = 5;
    sbit  CWG1DBR5_bit at CWG1DBR.B5;
    const register unsigned short int DBR0 = 0;
    sbit  DBR0_bit at CWG1DBR.B0;
    const register unsigned short int DBR1 = 1;
    sbit  DBR1_bit at CWG1DBR.B1;
    const register unsigned short int DBR2 = 2;
    sbit  DBR2_bit at CWG1DBR.B2;
    const register unsigned short int DBR3 = 3;
    sbit  DBR3_bit at CWG1DBR.B3;
    const register unsigned short int DBR4 = 4;
    sbit  DBR4_bit at CWG1DBR.B4;
    const register unsigned short int DBR5 = 5;
    sbit  DBR5_bit at CWG1DBR.B5;

sfr unsigned short volatile CWG1DBF          absolute 0x692;
    const register unsigned short int CWG1DBF0 = 0;
    sbit  CWG1DBF0_bit at CWG1DBF.B0;
    const register unsigned short int CWG1DBF1 = 1;
    sbit  CWG1DBF1_bit at CWG1DBF.B1;
    const register unsigned short int CWG1DBF2 = 2;
    sbit  CWG1DBF2_bit at CWG1DBF.B2;
    const register unsigned short int CWG1DBF3 = 3;
    sbit  CWG1DBF3_bit at CWG1DBF.B3;
    const register unsigned short int CWG1DBF4 = 4;
    sbit  CWG1DBF4_bit at CWG1DBF.B4;
    const register unsigned short int CWG1DBF5 = 5;
    sbit  CWG1DBF5_bit at CWG1DBF.B5;
    const register unsigned short int DBF0 = 0;
    sbit  DBF0_bit at CWG1DBF.B0;
    const register unsigned short int DBF1 = 1;
    sbit  DBF1_bit at CWG1DBF.B1;
    const register unsigned short int DBF2 = 2;
    sbit  DBF2_bit at CWG1DBF.B2;
    const register unsigned short int DBF3 = 3;
    sbit  DBF3_bit at CWG1DBF.B3;
    const register unsigned short int DBF4 = 4;
    sbit  DBF4_bit at CWG1DBF.B4;
    const register unsigned short int DBF5 = 5;
    sbit  DBF5_bit at CWG1DBF.B5;

sfr unsigned short volatile CWG1AS0          absolute 0x693;
    const register unsigned short int CWG1LSAC0 = 2;
    sbit  CWG1LSAC0_bit at CWG1AS0.B2;
    const register unsigned short int CWG1LSAC1 = 3;
    sbit  CWG1LSAC1_bit at CWG1AS0.B3;
    const register unsigned short int CWG1LSBD0 = 4;
    sbit  CWG1LSBD0_bit at CWG1AS0.B4;
    const register unsigned short int CWG1LSBD1 = 5;
    sbit  CWG1LSBD1_bit at CWG1AS0.B5;
    const register unsigned short int CWG1REN = 6;
    sbit  CWG1REN_bit at CWG1AS0.B6;
    const register unsigned short int CWG1SHUTDOWN = 7;
    sbit  CWG1SHUTDOWN_bit at CWG1AS0.B7;
    const register unsigned short int LSAC0 = 2;
    sbit  LSAC0_bit at CWG1AS0.B2;
    const register unsigned short int LSAC1 = 3;
    sbit  LSAC1_bit at CWG1AS0.B3;
    const register unsigned short int LSBD0 = 4;
    sbit  LSBD0_bit at CWG1AS0.B4;
    const register unsigned short int LSBD1 = 5;
    sbit  LSBD1_bit at CWG1AS0.B5;
    const register unsigned short int REN = 6;
    sbit  REN_bit at CWG1AS0.B6;
    const register unsigned short int SHUTDOWN = 7;
    sbit  SHUTDOWN_bit at CWG1AS0.B7;

sfr unsigned short volatile CWG1AS1          absolute 0x694;
    const register unsigned short int CWG1INAS = 0;
    sbit  CWG1INAS_bit at CWG1AS1.B0;
    const register unsigned short int C1AS = 1;
    sbit  C1AS_bit at CWG1AS1.B1;
    const register unsigned short int C2AS = 2;
    sbit  C2AS_bit at CWG1AS1.B2;
    const register unsigned short int CWG1TMR2AS = 4;
    sbit  CWG1TMR2AS_bit at CWG1AS1.B4;
    const register unsigned short int CWG1TMR4AS = 5;
    sbit  CWG1TMR4AS_bit at CWG1AS1.B5;
    const register unsigned short int CWG1TMR6AS = 6;
    sbit  CWG1TMR6AS_bit at CWG1AS1.B6;
    const register unsigned short int CWG1C1AS = 1;
    sbit  CWG1C1AS_bit at CWG1AS1.B1;
    const register unsigned short int CWG1C2AS = 2;
    sbit  CWG1C2AS_bit at CWG1AS1.B2;
    const register unsigned short int INAS = 0;
    sbit  INAS_bit at CWG1AS1.B0;
    const register unsigned short int TMR2AS = 4;
    sbit  TMR2AS_bit at CWG1AS1.B4;
    const register unsigned short int TMR4AS = 5;
    sbit  TMR4AS_bit at CWG1AS1.B5;
    const register unsigned short int TMR6AS = 6;
    sbit  TMR6AS_bit at CWG1AS1.B6;

sfr unsigned short volatile CWG1OCON0        absolute 0x695;
    const register unsigned short int CWG1STRA = 0;
    sbit  CWG1STRA_bit at CWG1OCON0.B0;
    const register unsigned short int CWG1STRB = 1;
    sbit  CWG1STRB_bit at CWG1OCON0.B1;
    const register unsigned short int CWG1STRC = 2;
    sbit  CWG1STRC_bit at CWG1OCON0.B2;
    const register unsigned short int CWG1STRD = 3;
    sbit  CWG1STRD_bit at CWG1OCON0.B3;
    const register unsigned short int CWG1OVRA = 4;
    sbit  CWG1OVRA_bit at CWG1OCON0.B4;
    const register unsigned short int CWG1OVRB = 5;
    sbit  CWG1OVRB_bit at CWG1OCON0.B5;
    const register unsigned short int CWG1OVRC = 6;
    sbit  CWG1OVRC_bit at CWG1OCON0.B6;
    const register unsigned short int CWG1OVRD = 7;
    sbit  CWG1OVRD_bit at CWG1OCON0.B7;
    const register unsigned short int OVRA = 4;
    sbit  OVRA_bit at CWG1OCON0.B4;
    const register unsigned short int OVRB = 5;
    sbit  OVRB_bit at CWG1OCON0.B5;
    const register unsigned short int OVRC = 6;
    sbit  OVRC_bit at CWG1OCON0.B6;
    const register unsigned short int OVRD = 7;
    sbit  OVRD_bit at CWG1OCON0.B7;
    const register unsigned short int STRA = 0;
    sbit  STRA_bit at CWG1OCON0.B0;
    const register unsigned short int STRB = 1;
    sbit  STRB_bit at CWG1OCON0.B1;
    const register unsigned short int STRC = 2;
    sbit  STRC_bit at CWG1OCON0.B2;
    const register unsigned short int STRD = 3;
    sbit  STRD_bit at CWG1OCON0.B3;

sfr unsigned short volatile CWG1CON0         absolute 0x696;
    const register unsigned short int CWG1MODE0 = 0;
    sbit  CWG1MODE0_bit at CWG1CON0.B0;
    const register unsigned short int CWG1MODE1 = 1;
    sbit  CWG1MODE1_bit at CWG1CON0.B1;
    const register unsigned short int CWG1MODE2 = 2;
    sbit  CWG1MODE2_bit at CWG1CON0.B2;
    const register unsigned short int CWG1LD = 6;
    sbit  CWG1LD_bit at CWG1CON0.B6;
    const register unsigned short int CWG1EN = 7;
    sbit  CWG1EN_bit at CWG1CON0.B7;
    const register unsigned short int G1EN = 7;
    sbit  G1EN_bit at CWG1CON0.B7;
    const register unsigned short int LD = 6;
    sbit  LD_bit at CWG1CON0.B6;

sfr unsigned short volatile CWG1CON1         absolute 0x697;
    const register unsigned short int CWG1POLA = 0;
    sbit  CWG1POLA_bit at CWG1CON1.B0;
    const register unsigned short int CWG1POLB = 1;
    sbit  CWG1POLB_bit at CWG1CON1.B1;
    const register unsigned short int CWG1POLC = 2;
    sbit  CWG1POLC_bit at CWG1CON1.B2;
    const register unsigned short int CWG1POLD = 3;
    sbit  CWG1POLD_bit at CWG1CON1.B3;
    const register unsigned short int CWG1IN = 5;
    sbit  CWG1IN_bit at CWG1CON1.B5;
    const register unsigned short int IN_ = 5;
    sbit  IN_bit at CWG1CON1.B5;
    const register unsigned short int POLA = 0;
    sbit  POLA_bit at CWG1CON1.B0;
    const register unsigned short int POLB = 1;
    sbit  POLB_bit at CWG1CON1.B1;
    const register unsigned short int POLC = 2;
    sbit  POLC_bit at CWG1CON1.B2;
    const register unsigned short int POLD = 3;
    sbit  POLD_bit at CWG1CON1.B3;

sfr unsigned short volatile CWG1OCON1        absolute 0x698;
    const register unsigned short int CWG1OEA = 0;
    sbit  CWG1OEA_bit at CWG1OCON1.B0;
    const register unsigned short int CWG1OEB = 1;
    sbit  CWG1OEB_bit at CWG1OCON1.B1;
    const register unsigned short int CWG1OEC = 2;
    sbit  CWG1OEC_bit at CWG1OCON1.B2;
    const register unsigned short int CWG1OED = 3;
    sbit  CWG1OED_bit at CWG1OCON1.B3;
    const register unsigned short int OEA = 0;
    sbit  OEA_bit at CWG1OCON1.B0;
    const register unsigned short int OEB = 1;
    sbit  OEB_bit at CWG1OCON1.B1;
    const register unsigned short int OEC = 2;
    sbit  OEC_bit at CWG1OCON1.B2;
    const register unsigned short int OED = 3;
    sbit  OED_bit at CWG1OCON1.B3;

sfr unsigned short volatile CWG1CLKCON       absolute 0x699;
    const register unsigned short int CS = 0;
    sbit  CS_bit at CWG1CLKCON.B0;
    const register unsigned short int CWG1CS = 0;
    sbit  CWG1CS_bit at CWG1CLKCON.B0;

sfr unsigned short volatile CWG1ISM          absolute 0x69A;
    const register unsigned short int CWG1IS0 = 0;
    sbit  CWG1IS0_bit at CWG1ISM.B0;
    const register unsigned short int CWG1IS1 = 1;
    sbit  CWG1IS1_bit at CWG1ISM.B1;
    const register unsigned short int CWG1IS2 = 2;
    sbit  CWG1IS2_bit at CWG1ISM.B2;
    const register unsigned short int IS0 = 0;
    sbit  IS0_bit at CWG1ISM.B0;
    const register unsigned short int IS1 = 1;
    sbit  IS1_bit at CWG1ISM.B1;
    const register unsigned short int IS2 = 2;
    sbit  IS2_bit at CWG1ISM.B2;

sfr unsigned short volatile WDTCON0          absolute 0x711;
    const register unsigned short int SEN = 0;
    sbit  SEN_bit at WDTCON0.B0;
    const register unsigned short int WDTPS0 = 1;
    sbit  WDTPS0_bit at WDTCON0.B1;
    const register unsigned short int WDTPS1 = 2;
    sbit  WDTPS1_bit at WDTCON0.B2;
    const register unsigned short int WDTPS2 = 3;
    sbit  WDTPS2_bit at WDTCON0.B3;
    const register unsigned short int WDTPS3 = 4;
    sbit  WDTPS3_bit at WDTCON0.B4;
    const register unsigned short int WDTPS4 = 5;
    sbit  WDTPS4_bit at WDTCON0.B5;
    const register unsigned short int SWDTEN = 0;
    sbit  SWDTEN_bit at WDTCON0.B0;
    const register unsigned short int WDTSEN = 0;
    sbit  WDTSEN_bit at WDTCON0.B0;

sfr unsigned short volatile WDTCON1          absolute 0x712;
    const register unsigned short int WDTWINDOW0 = 0;
    sbit  WDTWINDOW0_bit at WDTCON1.B0;
    const register unsigned short int WDTWINDOW1 = 1;
    sbit  WDTWINDOW1_bit at WDTCON1.B1;
    const register unsigned short int WDTWINDOW2 = 2;
    sbit  WDTWINDOW2_bit at WDTCON1.B2;
    const register unsigned short int WDTCS0 = 4;
    sbit  WDTCS0_bit at WDTCON1.B4;
    const register unsigned short int WDTCS1 = 5;
    sbit  WDTCS1_bit at WDTCON1.B5;
    const register unsigned short int WDTCS2 = 6;
    sbit  WDTCS2_bit at WDTCON1.B6;
    const register unsigned short int WINDOW0 = 0;
    sbit  WINDOW0_bit at WDTCON1.B0;
    const register unsigned short int WINDOW1 = 1;
    sbit  WINDOW1_bit at WDTCON1.B1;
    const register unsigned short int WINDOW2 = 2;
    sbit  WINDOW2_bit at WDTCON1.B2;

sfr unsigned short volatile WDTPSL           absolute 0x713;
    const register unsigned short int PSCNT0 = 0;
    sbit  PSCNT0_bit at WDTPSL.B0;
    const register unsigned short int PSCNT1 = 1;
    sbit  PSCNT1_bit at WDTPSL.B1;
    const register unsigned short int PSCNT2 = 2;
    sbit  PSCNT2_bit at WDTPSL.B2;
    const register unsigned short int PSCNT3 = 3;
    sbit  PSCNT3_bit at WDTPSL.B3;
    const register unsigned short int PSCNT4 = 4;
    sbit  PSCNT4_bit at WDTPSL.B4;
    const register unsigned short int PSCNT5 = 5;
    sbit  PSCNT5_bit at WDTPSL.B5;
    const register unsigned short int PSCNT6 = 6;
    sbit  PSCNT6_bit at WDTPSL.B6;
    const register unsigned short int PSCNT7 = 7;
    sbit  PSCNT7_bit at WDTPSL.B7;
    const register unsigned short int WDTPSCNT0 = 0;
    sbit  WDTPSCNT0_bit at WDTPSL.B0;
    const register unsigned short int WDTPSCNT1 = 1;
    sbit  WDTPSCNT1_bit at WDTPSL.B1;
    const register unsigned short int WDTPSCNT2 = 2;
    sbit  WDTPSCNT2_bit at WDTPSL.B2;
    const register unsigned short int WDTPSCNT3 = 3;
    sbit  WDTPSCNT3_bit at WDTPSL.B3;
    const register unsigned short int WDTPSCNT4 = 4;
    sbit  WDTPSCNT4_bit at WDTPSL.B4;
    const register unsigned short int WDTPSCNT5 = 5;
    sbit  WDTPSCNT5_bit at WDTPSL.B5;
    const register unsigned short int WDTPSCNT6 = 6;
    sbit  WDTPSCNT6_bit at WDTPSL.B6;
    const register unsigned short int WDTPSCNT7 = 7;
    sbit  WDTPSCNT7_bit at WDTPSL.B7;

sfr unsigned short volatile WDTPSH           absolute 0x714;
    const register unsigned short int PSCNT8 = 0;
    sbit  PSCNT8_bit at WDTPSH.B0;
    const register unsigned short int PSCNT9 = 1;
    sbit  PSCNT9_bit at WDTPSH.B1;
    const register unsigned short int PSCNT10 = 2;
    sbit  PSCNT10_bit at WDTPSH.B2;
    const register unsigned short int PSCNT11 = 3;
    sbit  PSCNT11_bit at WDTPSH.B3;
    const register unsigned short int PSCNT12 = 4;
    sbit  PSCNT12_bit at WDTPSH.B4;
    const register unsigned short int PSCNT13 = 5;
    sbit  PSCNT13_bit at WDTPSH.B5;
    const register unsigned short int PSCNT14 = 6;
    sbit  PSCNT14_bit at WDTPSH.B6;
    const register unsigned short int PSCNT15 = 7;
    sbit  PSCNT15_bit at WDTPSH.B7;
    const register unsigned short int WDTPSCNT10 = 2;
    sbit  WDTPSCNT10_bit at WDTPSH.B2;
    const register unsigned short int WDTPSCNT11 = 3;
    sbit  WDTPSCNT11_bit at WDTPSH.B3;
    const register unsigned short int WDTPSCNT12 = 4;
    sbit  WDTPSCNT12_bit at WDTPSH.B4;
    const register unsigned short int WDTPSCNT13 = 5;
    sbit  WDTPSCNT13_bit at WDTPSH.B5;
    const register unsigned short int WDTPSCNT14 = 6;
    sbit  WDTPSCNT14_bit at WDTPSH.B6;
    const register unsigned short int WDTPSCNT15 = 7;
    sbit  WDTPSCNT15_bit at WDTPSH.B7;
    const register unsigned short int WDTPSCNT8 = 0;
    sbit  WDTPSCNT8_bit at WDTPSH.B0;
    const register unsigned short int WDTPSCNT9 = 1;
    sbit  WDTPSCNT9_bit at WDTPSH.B1;

sfr unsigned short volatile WDTTMR           absolute 0x715;
    const register unsigned short int PSCNT16 = 0;
    sbit  PSCNT16_bit at WDTTMR.B0;
    const register unsigned short int PSCNT17 = 1;
    sbit  PSCNT17_bit at WDTTMR.B1;
    const register unsigned short int STATE = 2;
    sbit  STATE_bit at WDTTMR.B2;
    const register unsigned short int WDTTMR0 = 3;
    sbit  WDTTMR0_bit at WDTTMR.B3;
    const register unsigned short int WDTTMR1 = 4;
    sbit  WDTTMR1_bit at WDTTMR.B4;
    const register unsigned short int WDTTMR2 = 5;
    sbit  WDTTMR2_bit at WDTTMR.B5;
    const register unsigned short int WDTTMR3 = 6;
    sbit  WDTTMR3_bit at WDTTMR.B6;
    const register unsigned short int WDTTMR4 = 7;
    sbit  WDTTMR4_bit at WDTTMR.B7;
    const register unsigned short int WDTPSCNT16 = 0;
    sbit  WDTPSCNT16_bit at WDTTMR.B0;
    const register unsigned short int WDTPSCNT17 = 1;
    sbit  WDTPSCNT17_bit at WDTTMR.B1;
    const register unsigned short int WDTSTATE = 2;
    sbit  WDTSTATE_bit at WDTTMR.B2;

sfr unsigned int   volatile SCANLADR         absolute 0x718;
sfr unsigned short volatile SCANLADRL        absolute 0x718;
    const register unsigned short int LDAR0 = 0;
    sbit  LDAR0_bit at SCANLADRL.B0;
    const register unsigned short int LDAR1 = 1;
    sbit  LDAR1_bit at SCANLADRL.B1;
    const register unsigned short int LADR2 = 2;
    sbit  LADR2_bit at SCANLADRL.B2;
    const register unsigned short int LADR3 = 3;
    sbit  LADR3_bit at SCANLADRL.B3;
    const register unsigned short int LADR4 = 4;
    sbit  LADR4_bit at SCANLADRL.B4;
    const register unsigned short int LADR5 = 5;
    sbit  LADR5_bit at SCANLADRL.B5;
    const register unsigned short int LADR6 = 6;
    sbit  LADR6_bit at SCANLADRL.B6;
    const register unsigned short int LADR7 = 7;
    sbit  LADR7_bit at SCANLADRL.B7;
    const register unsigned short int SCANLADR0 = 0;
    sbit  SCANLADR0_bit at SCANLADRL.B0;
    const register unsigned short int SCANLADR1 = 1;
    sbit  SCANLADR1_bit at SCANLADRL.B1;
    const register unsigned short int SCANLADR2 = 2;
    sbit  SCANLADR2_bit at SCANLADRL.B2;
    const register unsigned short int SCANLADR3 = 3;
    sbit  SCANLADR3_bit at SCANLADRL.B3;
    const register unsigned short int SCANLADR4 = 4;
    sbit  SCANLADR4_bit at SCANLADRL.B4;
    const register unsigned short int SCANLADR5 = 5;
    sbit  SCANLADR5_bit at SCANLADRL.B5;
    const register unsigned short int SCANLADR6 = 6;
    sbit  SCANLADR6_bit at SCANLADRL.B6;
    const register unsigned short int SCANLADR7 = 7;
    sbit  SCANLADR7_bit at SCANLADRL.B7;

sfr unsigned short volatile SCANLADRH        absolute 0x719;
    const register unsigned short int LADR8 = 0;
    sbit  LADR8_bit at SCANLADRH.B0;
    const register unsigned short int LADR9 = 1;
    sbit  LADR9_bit at SCANLADRH.B1;
    const register unsigned short int LADR10 = 2;
    sbit  LADR10_bit at SCANLADRH.B2;
    const register unsigned short int LADR11 = 3;
    sbit  LADR11_bit at SCANLADRH.B3;
    const register unsigned short int LADR12 = 4;
    sbit  LADR12_bit at SCANLADRH.B4;
    const register unsigned short int LADR13 = 5;
    sbit  LADR13_bit at SCANLADRH.B5;
    const register unsigned short int LADR14 = 6;
    sbit  LADR14_bit at SCANLADRH.B6;
    const register unsigned short int LADR15 = 7;
    sbit  LADR15_bit at SCANLADRH.B7;
    const register unsigned short int SCANLADR10 = 2;
    sbit  SCANLADR10_bit at SCANLADRH.B2;
    const register unsigned short int SCANLADR11 = 3;
    sbit  SCANLADR11_bit at SCANLADRH.B3;
    const register unsigned short int SCANLADR12 = 4;
    sbit  SCANLADR12_bit at SCANLADRH.B4;
    const register unsigned short int SCANLADR13 = 5;
    sbit  SCANLADR13_bit at SCANLADRH.B5;
    const register unsigned short int SCANLADR14 = 6;
    sbit  SCANLADR14_bit at SCANLADRH.B6;
    const register unsigned short int SCANLADR15 = 7;
    sbit  SCANLADR15_bit at SCANLADRH.B7;
    const register unsigned short int SCANLADR8 = 0;
    sbit  SCANLADR8_bit at SCANLADRH.B0;
    const register unsigned short int SCANLADR9 = 1;
    sbit  SCANLADR9_bit at SCANLADRH.B1;

sfr unsigned int   volatile SCANHADR         absolute 0x71A;
sfr unsigned short volatile SCANHADRL        absolute 0x71A;
    const register unsigned short int HADR0 = 0;
    sbit  HADR0_bit at SCANHADRL.B0;
    const register unsigned short int HADR1 = 1;
    sbit  HADR1_bit at SCANHADRL.B1;
    const register unsigned short int HARD2 = 2;
    sbit  HARD2_bit at SCANHADRL.B2;
    const register unsigned short int HADR3 = 3;
    sbit  HADR3_bit at SCANHADRL.B3;
    const register unsigned short int HADR4 = 4;
    sbit  HADR4_bit at SCANHADRL.B4;
    const register unsigned short int HADR5 = 5;
    sbit  HADR5_bit at SCANHADRL.B5;
    const register unsigned short int HADR6 = 6;
    sbit  HADR6_bit at SCANHADRL.B6;
    const register unsigned short int HADR7 = 7;
    sbit  HADR7_bit at SCANHADRL.B7;
    const register unsigned short int SCANHADR0 = 0;
    sbit  SCANHADR0_bit at SCANHADRL.B0;
    const register unsigned short int SCANHADR1 = 1;
    sbit  SCANHADR1_bit at SCANHADRL.B1;
    const register unsigned short int SCANHADR2 = 2;
    sbit  SCANHADR2_bit at SCANHADRL.B2;
    const register unsigned short int SCANHADR3 = 3;
    sbit  SCANHADR3_bit at SCANHADRL.B3;
    const register unsigned short int SCANHADR4 = 4;
    sbit  SCANHADR4_bit at SCANHADRL.B4;
    const register unsigned short int SCANHADR5 = 5;
    sbit  SCANHADR5_bit at SCANHADRL.B5;
    const register unsigned short int SCANHADR6 = 6;
    sbit  SCANHADR6_bit at SCANHADRL.B6;
    const register unsigned short int SCANHADR7 = 7;
    sbit  SCANHADR7_bit at SCANHADRL.B7;

sfr unsigned short volatile SCANHADRH        absolute 0x71B;
    const register unsigned short int HADR8 = 0;
    sbit  HADR8_bit at SCANHADRH.B0;
    const register unsigned short int HADR9 = 1;
    sbit  HADR9_bit at SCANHADRH.B1;
    const register unsigned short int HADR10 = 2;
    sbit  HADR10_bit at SCANHADRH.B2;
    const register unsigned short int HADR11 = 3;
    sbit  HADR11_bit at SCANHADRH.B3;
    const register unsigned short int HADR12 = 4;
    sbit  HADR12_bit at SCANHADRH.B4;
    const register unsigned short int HADR13 = 5;
    sbit  HADR13_bit at SCANHADRH.B5;
    const register unsigned short int HADR14 = 6;
    sbit  HADR14_bit at SCANHADRH.B6;
    const register unsigned short int HADR15 = 7;
    sbit  HADR15_bit at SCANHADRH.B7;
    const register unsigned short int SCANHADR10 = 2;
    sbit  SCANHADR10_bit at SCANHADRH.B2;
    const register unsigned short int SCANHADR11 = 3;
    sbit  SCANHADR11_bit at SCANHADRH.B3;
    const register unsigned short int SCANHADR12 = 4;
    sbit  SCANHADR12_bit at SCANHADRH.B4;
    const register unsigned short int SCANHADR13 = 5;
    sbit  SCANHADR13_bit at SCANHADRH.B5;
    const register unsigned short int SCANHADR14 = 6;
    sbit  SCANHADR14_bit at SCANHADRH.B6;
    const register unsigned short int SCANHADR15 = 7;
    sbit  SCANHADR15_bit at SCANHADRH.B7;
    const register unsigned short int SCANHADR8 = 0;
    sbit  SCANHADR8_bit at SCANHADRH.B0;
    const register unsigned short int SCANHADR9 = 1;
    sbit  SCANHADR9_bit at SCANHADRH.B1;

sfr unsigned short volatile SCANCON0         absolute 0x71C;
    const register unsigned short int SCANMODE0 = 0;
    sbit  SCANMODE0_bit at SCANCON0.B0;
    const register unsigned short int SCANMODE1 = 1;
    sbit  SCANMODE1_bit at SCANCON0.B1;
    const register unsigned short int INTM = 3;
    sbit  INTM_bit at SCANCON0.B3;
    const register unsigned short int INVALID = 4;
    sbit  INVALID_bit at SCANCON0.B4;
    const register unsigned short int SCANBUSY = 5;
    sbit  SCANBUSY_bit at SCANCON0.B5;
    const register unsigned short int SCANGO = 6;
    sbit  SCANGO_bit at SCANCON0.B6;
    const register unsigned short int SCANEN = 7;
    sbit  SCANEN_bit at SCANCON0.B7;
    const register unsigned short int SCANINTM = 3;
    sbit  SCANINTM_bit at SCANCON0.B3;
    const register unsigned short int SCANINVALID = 4;
    sbit  SCANINVALID_bit at SCANCON0.B4;

sfr unsigned short volatile SCANTRIG         absolute 0x71D;
    const register unsigned short int SCANTSEL0 = 0;
    sbit  SCANTSEL0_bit at SCANTRIG.B0;
    const register unsigned short int SCANTSEL1 = 1;
    sbit  SCANTSEL1_bit at SCANTRIG.B1;
    const register unsigned short int TSEL0 = 0;
    sbit  TSEL0_bit at SCANTRIG.B0;
    const register unsigned short int TSEL1 = 1;
    sbit  TSEL1_bit at SCANTRIG.B1;

sfr unsigned int   volatile CRCDAT           absolute 0x791;
sfr unsigned short volatile CRCDATL          absolute 0x791;
    const register unsigned short int CRCDAT0 = 0;
    sbit  CRCDAT0_bit at CRCDATL.B0;
    const register unsigned short int CRCDAT1 = 1;
    sbit  CRCDAT1_bit at CRCDATL.B1;
    const register unsigned short int CRCDAT2 = 2;
    sbit  CRCDAT2_bit at CRCDATL.B2;
    const register unsigned short int CRCDAT3 = 3;
    sbit  CRCDAT3_bit at CRCDATL.B3;
    const register unsigned short int CRCDAT4 = 4;
    sbit  CRCDAT4_bit at CRCDATL.B4;
    const register unsigned short int CRCDAT5 = 5;
    sbit  CRCDAT5_bit at CRCDATL.B5;
    const register unsigned short int CRCDAT6 = 6;
    sbit  CRCDAT6_bit at CRCDATL.B6;
    const register unsigned short int CRDCDAT7 = 7;
    sbit  CRDCDAT7_bit at CRCDATL.B7;
    const register unsigned short int DAT0 = 0;
    sbit  DAT0_bit at CRCDATL.B0;
    const register unsigned short int DAT1 = 1;
    sbit  DAT1_bit at CRCDATL.B1;
    const register unsigned short int DAT2 = 2;
    sbit  DAT2_bit at CRCDATL.B2;
    const register unsigned short int DAT3 = 3;
    sbit  DAT3_bit at CRCDATL.B3;
    const register unsigned short int DAT4 = 4;
    sbit  DAT4_bit at CRCDATL.B4;
    const register unsigned short int DAT5 = 5;
    sbit  DAT5_bit at CRCDATL.B5;
    const register unsigned short int DAT6 = 6;
    sbit  DAT6_bit at CRCDATL.B6;
    const register unsigned short int DAT7 = 7;
    sbit  DAT7_bit at CRCDATL.B7;

sfr unsigned short volatile CRCDATH          absolute 0x792;
    const register unsigned short int CRCDAT8 = 0;
    sbit  CRCDAT8_bit at CRCDATH.B0;
    const register unsigned short int CRCDAT9 = 1;
    sbit  CRCDAT9_bit at CRCDATH.B1;
    const register unsigned short int CRCDAT10 = 2;
    sbit  CRCDAT10_bit at CRCDATH.B2;
    const register unsigned short int CRCDAT11 = 3;
    sbit  CRCDAT11_bit at CRCDATH.B3;
    const register unsigned short int CRCDAT12 = 4;
    sbit  CRCDAT12_bit at CRCDATH.B4;
    const register unsigned short int CRCDAT13 = 5;
    sbit  CRCDAT13_bit at CRCDATH.B5;
    const register unsigned short int CRCDAT14 = 6;
    sbit  CRCDAT14_bit at CRCDATH.B6;
    const register unsigned short int CRCDAT15 = 7;
    sbit  CRCDAT15_bit at CRCDATH.B7;
    const register unsigned short int DAT10 = 2;
    sbit  DAT10_bit at CRCDATH.B2;
    const register unsigned short int DAT11 = 3;
    sbit  DAT11_bit at CRCDATH.B3;
    const register unsigned short int DAT12 = 4;
    sbit  DAT12_bit at CRCDATH.B4;
    const register unsigned short int DAT13 = 5;
    sbit  DAT13_bit at CRCDATH.B5;
    const register unsigned short int DAT14 = 6;
    sbit  DAT14_bit at CRCDATH.B6;
    const register unsigned short int DAT15 = 7;
    sbit  DAT15_bit at CRCDATH.B7;
    const register unsigned short int DAT8 = 0;
    sbit  DAT8_bit at CRCDATH.B0;
    const register unsigned short int DAT9 = 1;
    sbit  DAT9_bit at CRCDATH.B1;

sfr unsigned int   volatile CRCACC           absolute 0x793;
sfr unsigned short volatile CRCACCL          absolute 0x793;
    const register unsigned short int ACC0 = 0;
    sbit  ACC0_bit at CRCACCL.B0;
    const register unsigned short int ACC1 = 1;
    sbit  ACC1_bit at CRCACCL.B1;
    const register unsigned short int ACC2 = 2;
    sbit  ACC2_bit at CRCACCL.B2;
    const register unsigned short int ACC3 = 3;
    sbit  ACC3_bit at CRCACCL.B3;
    const register unsigned short int ACC4 = 4;
    sbit  ACC4_bit at CRCACCL.B4;
    const register unsigned short int ACC5 = 5;
    sbit  ACC5_bit at CRCACCL.B5;
    const register unsigned short int ACC6 = 6;
    sbit  ACC6_bit at CRCACCL.B6;
    const register unsigned short int ACC7 = 7;
    sbit  ACC7_bit at CRCACCL.B7;
    const register unsigned short int CRCACC0 = 0;
    sbit  CRCACC0_bit at CRCACCL.B0;
    const register unsigned short int CRCACC1 = 1;
    sbit  CRCACC1_bit at CRCACCL.B1;
    const register unsigned short int CRCACC2 = 2;
    sbit  CRCACC2_bit at CRCACCL.B2;
    const register unsigned short int CRCACC3 = 3;
    sbit  CRCACC3_bit at CRCACCL.B3;
    const register unsigned short int CRCACC4 = 4;
    sbit  CRCACC4_bit at CRCACCL.B4;
    const register unsigned short int CRCACC5 = 5;
    sbit  CRCACC5_bit at CRCACCL.B5;
    const register unsigned short int CRCACC6 = 6;
    sbit  CRCACC6_bit at CRCACCL.B6;
    const register unsigned short int CRCACC7 = 7;
    sbit  CRCACC7_bit at CRCACCL.B7;

sfr unsigned short volatile CRCACCH          absolute 0x794;
    const register unsigned short int ACC8 = 0;
    sbit  ACC8_bit at CRCACCH.B0;
    const register unsigned short int ACC9 = 1;
    sbit  ACC9_bit at CRCACCH.B1;
    const register unsigned short int ACC10 = 2;
    sbit  ACC10_bit at CRCACCH.B2;
    const register unsigned short int ACC11 = 3;
    sbit  ACC11_bit at CRCACCH.B3;
    const register unsigned short int ACC12 = 4;
    sbit  ACC12_bit at CRCACCH.B4;
    const register unsigned short int ACC13 = 5;
    sbit  ACC13_bit at CRCACCH.B5;
    const register unsigned short int ACC14 = 6;
    sbit  ACC14_bit at CRCACCH.B6;
    const register unsigned short int ACC15 = 7;
    sbit  ACC15_bit at CRCACCH.B7;
    const register unsigned short int CRCACC10 = 2;
    sbit  CRCACC10_bit at CRCACCH.B2;
    const register unsigned short int CRCACC11 = 3;
    sbit  CRCACC11_bit at CRCACCH.B3;
    const register unsigned short int CRCACC12 = 4;
    sbit  CRCACC12_bit at CRCACCH.B4;
    const register unsigned short int CRCACC13 = 5;
    sbit  CRCACC13_bit at CRCACCH.B5;
    const register unsigned short int CRCACC14 = 6;
    sbit  CRCACC14_bit at CRCACCH.B6;
    const register unsigned short int CRCACC15 = 7;
    sbit  CRCACC15_bit at CRCACCH.B7;
    const register unsigned short int CRCACC8 = 0;
    sbit  CRCACC8_bit at CRCACCH.B0;
    const register unsigned short int CRCACC9 = 1;
    sbit  CRCACC9_bit at CRCACCH.B1;

sfr unsigned int   volatile CRCSHIFT         absolute 0x795;
sfr unsigned short volatile CRCSHIFTL        absolute 0x795;
    const register unsigned short int CRCSHIFT0 = 0;
    sbit  CRCSHIFT0_bit at CRCSHIFTL.B0;
    const register unsigned short int CRCSHIFT1 = 1;
    sbit  CRCSHIFT1_bit at CRCSHIFTL.B1;
    const register unsigned short int CRCSHIFT2 = 2;
    sbit  CRCSHIFT2_bit at CRCSHIFTL.B2;
    const register unsigned short int CRCSHIFT3 = 3;
    sbit  CRCSHIFT3_bit at CRCSHIFTL.B3;
    const register unsigned short int CRCSHIFT4 = 4;
    sbit  CRCSHIFT4_bit at CRCSHIFTL.B4;
    const register unsigned short int CRCSHIFT5 = 5;
    sbit  CRCSHIFT5_bit at CRCSHIFTL.B5;
    const register unsigned short int CRCSHIFT6 = 6;
    sbit  CRCSHIFT6_bit at CRCSHIFTL.B6;
    const register unsigned short int CRCSHIFT7 = 7;
    sbit  CRCSHIFT7_bit at CRCSHIFTL.B7;
    const register unsigned short int SHIFT0 = 0;
    sbit  SHIFT0_bit at CRCSHIFTL.B0;
    const register unsigned short int SHIFT1 = 1;
    sbit  SHIFT1_bit at CRCSHIFTL.B1;
    const register unsigned short int SHIFT2 = 2;
    sbit  SHIFT2_bit at CRCSHIFTL.B2;
    const register unsigned short int SHIFT3 = 3;
    sbit  SHIFT3_bit at CRCSHIFTL.B3;
    const register unsigned short int SHIFT4 = 4;
    sbit  SHIFT4_bit at CRCSHIFTL.B4;
    const register unsigned short int SHIFT5 = 5;
    sbit  SHIFT5_bit at CRCSHIFTL.B5;
    const register unsigned short int SHIFT6 = 6;
    sbit  SHIFT6_bit at CRCSHIFTL.B6;
    const register unsigned short int SHIFT7 = 7;
    sbit  SHIFT7_bit at CRCSHIFTL.B7;

sfr unsigned short volatile CRCSHIFTH        absolute 0x796;
    const register unsigned short int CRCSHIFT8 = 0;
    sbit  CRCSHIFT8_bit at CRCSHIFTH.B0;
    const register unsigned short int CRCSHIFT9 = 1;
    sbit  CRCSHIFT9_bit at CRCSHIFTH.B1;
    const register unsigned short int CRCSHIFT10 = 2;
    sbit  CRCSHIFT10_bit at CRCSHIFTH.B2;
    const register unsigned short int CRCSHIFT11 = 3;
    sbit  CRCSHIFT11_bit at CRCSHIFTH.B3;
    const register unsigned short int CRCSHIFT12 = 4;
    sbit  CRCSHIFT12_bit at CRCSHIFTH.B4;
    const register unsigned short int CRCSHIFT13 = 5;
    sbit  CRCSHIFT13_bit at CRCSHIFTH.B5;
    const register unsigned short int CRCSHIFT14 = 6;
    sbit  CRCSHIFT14_bit at CRCSHIFTH.B6;
    const register unsigned short int CRCSHIFT15 = 7;
    sbit  CRCSHIFT15_bit at CRCSHIFTH.B7;
    const register unsigned short int SHIFT10 = 2;
    sbit  SHIFT10_bit at CRCSHIFTH.B2;
    const register unsigned short int SHIFT11 = 3;
    sbit  SHIFT11_bit at CRCSHIFTH.B3;
    const register unsigned short int SHIFT12 = 4;
    sbit  SHIFT12_bit at CRCSHIFTH.B4;
    const register unsigned short int SHIFT13 = 5;
    sbit  SHIFT13_bit at CRCSHIFTH.B5;
    const register unsigned short int SHIFT14 = 6;
    sbit  SHIFT14_bit at CRCSHIFTH.B6;
    const register unsigned short int SHIFT15 = 7;
    sbit  SHIFT15_bit at CRCSHIFTH.B7;
    const register unsigned short int SHIFT8 = 0;
    sbit  SHIFT8_bit at CRCSHIFTH.B0;
    const register unsigned short int SHIFT9 = 1;
    sbit  SHIFT9_bit at CRCSHIFTH.B1;

sfr unsigned int   volatile CRCXOR           absolute 0x797;
sfr unsigned short volatile CRCXORL          absolute 0x797;
    const register unsigned short int CRCXOR1 = 1;
    sbit  CRCXOR1_bit at CRCXORL.B1;
    const register unsigned short int CRCXOR2 = 2;
    sbit  CRCXOR2_bit at CRCXORL.B2;
    const register unsigned short int CRCXOR3 = 3;
    sbit  CRCXOR3_bit at CRCXORL.B3;
    const register unsigned short int CRCXOR4 = 4;
    sbit  CRCXOR4_bit at CRCXORL.B4;
    const register unsigned short int CRCXOR5 = 5;
    sbit  CRCXOR5_bit at CRCXORL.B5;
    const register unsigned short int CRCXOR6 = 6;
    sbit  CRCXOR6_bit at CRCXORL.B6;
    const register unsigned short int CRCXOR7 = 7;
    sbit  CRCXOR7_bit at CRCXORL.B7;
    const register unsigned short int XOR1 = 1;
    sbit  XOR1_bit at CRCXORL.B1;
    const register unsigned short int XOR2 = 2;
    sbit  XOR2_bit at CRCXORL.B2;
    const register unsigned short int XOR3 = 3;
    sbit  XOR3_bit at CRCXORL.B3;
    const register unsigned short int XOR4 = 4;
    sbit  XOR4_bit at CRCXORL.B4;
    const register unsigned short int XOR5 = 5;
    sbit  XOR5_bit at CRCXORL.B5;
    const register unsigned short int XOR6 = 6;
    sbit  XOR6_bit at CRCXORL.B6;
    const register unsigned short int XOR7 = 7;
    sbit  XOR7_bit at CRCXORL.B7;

sfr unsigned short volatile CRCXORH          absolute 0x798;
    const register unsigned short int CRCXOR8 = 0;
    sbit  CRCXOR8_bit at CRCXORH.B0;
    const register unsigned short int CRCXOR9 = 1;
    sbit  CRCXOR9_bit at CRCXORH.B1;
    const register unsigned short int CRCXOR10 = 2;
    sbit  CRCXOR10_bit at CRCXORH.B2;
    const register unsigned short int CRCXOR11 = 3;
    sbit  CRCXOR11_bit at CRCXORH.B3;
    const register unsigned short int CRCXOR12 = 4;
    sbit  CRCXOR12_bit at CRCXORH.B4;
    const register unsigned short int CRCXOR13 = 5;
    sbit  CRCXOR13_bit at CRCXORH.B5;
    const register unsigned short int CRCXOR14 = 6;
    sbit  CRCXOR14_bit at CRCXORH.B6;
    const register unsigned short int CRCXOR15 = 7;
    sbit  CRCXOR15_bit at CRCXORH.B7;
    const register unsigned short int XOR10 = 2;
    sbit  XOR10_bit at CRCXORH.B2;
    const register unsigned short int XOR11 = 3;
    sbit  XOR11_bit at CRCXORH.B3;
    const register unsigned short int XOR12 = 4;
    sbit  XOR12_bit at CRCXORH.B4;
    const register unsigned short int XOR13 = 5;
    sbit  XOR13_bit at CRCXORH.B5;
    const register unsigned short int XOR14 = 6;
    sbit  XOR14_bit at CRCXORH.B6;
    const register unsigned short int XOR15 = 7;
    sbit  XOR15_bit at CRCXORH.B7;
    const register unsigned short int XOR8 = 0;
    sbit  XOR8_bit at CRCXORH.B0;
    const register unsigned short int XOR9 = 1;
    sbit  XOR9_bit at CRCXORH.B1;

sfr unsigned short volatile CRCCON0          absolute 0x799;
    const register unsigned short int CRCFULL = 0;
    sbit  CRCFULL_bit at CRCCON0.B0;
    const register unsigned short int CRCSHIFTM = 1;
    sbit  CRCSHIFTM_bit at CRCCON0.B1;
    const register unsigned short int ACCM = 4;
    sbit  ACCM_bit at CRCCON0.B4;
    const register unsigned short int CRCBUSY = 5;
    sbit  CRCBUSY_bit at CRCCON0.B5;
    const register unsigned short int CRCGO = 6;
    sbit  CRCGO_bit at CRCCON0.B6;
    const register unsigned short int CRCEN = 7;
    sbit  CRCEN_bit at CRCCON0.B7;
    const register unsigned short int CRCACCM = 4;
    sbit  CRCACCM_bit at CRCCON0.B4;
    const register unsigned short int FULL = 0;
    sbit  FULL_bit at CRCCON0.B0;
    const register unsigned short int SHIFTM = 1;
    sbit  SHIFTM_bit at CRCCON0.B1;

sfr unsigned short volatile CRCCON1          absolute 0x79A;
    const register unsigned short int CRCPLEN0 = 0;
    sbit  CRCPLEN0_bit at CRCCON1.B0;
    const register unsigned short int CRCPLEN1 = 1;
    sbit  CRCPLEN1_bit at CRCCON1.B1;
    const register unsigned short int CRCPLEN2 = 2;
    sbit  CRCPLEN2_bit at CRCCON1.B2;
    const register unsigned short int CRCPLEN3 = 3;
    sbit  CRCPLEN3_bit at CRCCON1.B3;
    const register unsigned short int CRCDLEN0 = 4;
    sbit  CRCDLEN0_bit at CRCCON1.B4;
    const register unsigned short int CRCDLEN1 = 5;
    sbit  CRCDLEN1_bit at CRCCON1.B5;
    const register unsigned short int CRCDLEN2 = 6;
    sbit  CRCDLEN2_bit at CRCCON1.B6;
    const register unsigned short int CRCDLEN3 = 7;
    sbit  CRCDLEN3_bit at CRCCON1.B7;
    const register unsigned short int DLEN0 = 4;
    sbit  DLEN0_bit at CRCCON1.B4;
    const register unsigned short int DLEN1 = 5;
    sbit  DLEN1_bit at CRCCON1.B5;
    const register unsigned short int DLEN2 = 6;
    sbit  DLEN2_bit at CRCCON1.B6;
    const register unsigned short int DLEN3 = 7;
    sbit  DLEN3_bit at CRCCON1.B7;
    const register unsigned short int PLEN0 = 0;
    sbit  PLEN0_bit at CRCCON1.B0;
    const register unsigned short int PLEN1 = 1;
    sbit  PLEN1_bit at CRCCON1.B1;
    const register unsigned short int PLEN2 = 2;
    sbit  PLEN2_bit at CRCCON1.B2;
    const register unsigned short int PLEN3 = 3;
    sbit  PLEN3_bit at CRCCON1.B3;

sfr unsigned short volatile SMT1TMRL         absolute 0xD8C;
    const register unsigned short int SMT1TMR0 = 0;
    sbit  SMT1TMR0_bit at SMT1TMRL.B0;
    const register unsigned short int SMT1TMR1 = 1;
    sbit  SMT1TMR1_bit at SMT1TMRL.B1;
    const register unsigned short int SMT1TMR2 = 2;
    sbit  SMT1TMR2_bit at SMT1TMRL.B2;
    const register unsigned short int SMT1TMR3 = 3;
    sbit  SMT1TMR3_bit at SMT1TMRL.B3;
    const register unsigned short int SMT1TMR4 = 4;
    sbit  SMT1TMR4_bit at SMT1TMRL.B4;
    const register unsigned short int SMT1TMR5 = 5;
    sbit  SMT1TMR5_bit at SMT1TMRL.B5;
    const register unsigned short int SMT1TMR6 = 6;
    sbit  SMT1TMR6_bit at SMT1TMRL.B6;
    const register unsigned short int SMT1TMR7 = 7;
    sbit  SMT1TMR7_bit at SMT1TMRL.B7;

sfr unsigned short volatile SMT1TMRH         absolute 0xD8D;
    const register unsigned short int SMT1TMR8 = 0;
    sbit  SMT1TMR8_bit at SMT1TMRH.B0;
    const register unsigned short int SMT1TMR9 = 1;
    sbit  SMT1TMR9_bit at SMT1TMRH.B1;
    const register unsigned short int SMT1TMR10 = 2;
    sbit  SMT1TMR10_bit at SMT1TMRH.B2;
    const register unsigned short int SMT1TMR11 = 3;
    sbit  SMT1TMR11_bit at SMT1TMRH.B3;
    const register unsigned short int SMT1TMR12 = 4;
    sbit  SMT1TMR12_bit at SMT1TMRH.B4;
    const register unsigned short int SMT1TMR13 = 5;
    sbit  SMT1TMR13_bit at SMT1TMRH.B5;
    const register unsigned short int SMT1TMR14 = 6;
    sbit  SMT1TMR14_bit at SMT1TMRH.B6;
    const register unsigned short int SMT1TMR15 = 7;
    sbit  SMT1TMR15_bit at SMT1TMRH.B7;

sfr unsigned short volatile SMT1TMRU         absolute 0xD8E;
    const register unsigned short int SMT1TMR16 = 0;
    sbit  SMT1TMR16_bit at SMT1TMRU.B0;
    const register unsigned short int SMT1TMR17 = 1;
    sbit  SMT1TMR17_bit at SMT1TMRU.B1;
    const register unsigned short int SMT1TMR18 = 2;
    sbit  SMT1TMR18_bit at SMT1TMRU.B2;
    const register unsigned short int SMT1TMR19 = 3;
    sbit  SMT1TMR19_bit at SMT1TMRU.B3;
    const register unsigned short int SMT1TMR20 = 4;
    sbit  SMT1TMR20_bit at SMT1TMRU.B4;
    const register unsigned short int SMT1TMR21 = 5;
    sbit  SMT1TMR21_bit at SMT1TMRU.B5;
    const register unsigned short int SMT1TMR22 = 6;
    sbit  SMT1TMR22_bit at SMT1TMRU.B6;
    const register unsigned short int SMT1TMR23 = 7;
    sbit  SMT1TMR23_bit at SMT1TMRU.B7;

sfr unsigned short volatile SMT1CPRL         absolute 0xD8F;
    const register unsigned short int SMT1CPR0 = 0;
    sbit  SMT1CPR0_bit at SMT1CPRL.B0;
    const register unsigned short int SMT1CPR1 = 1;
    sbit  SMT1CPR1_bit at SMT1CPRL.B1;
    const register unsigned short int SMT1CPR2 = 2;
    sbit  SMT1CPR2_bit at SMT1CPRL.B2;
    const register unsigned short int SMT1CPR3 = 3;
    sbit  SMT1CPR3_bit at SMT1CPRL.B3;
    const register unsigned short int SMT1CPR4 = 4;
    sbit  SMT1CPR4_bit at SMT1CPRL.B4;
    const register unsigned short int SMT1CPR5 = 5;
    sbit  SMT1CPR5_bit at SMT1CPRL.B5;
    const register unsigned short int SMT1CPR6 = 6;
    sbit  SMT1CPR6_bit at SMT1CPRL.B6;
    const register unsigned short int SMT1CPR7 = 7;
    sbit  SMT1CPR7_bit at SMT1CPRL.B7;

sfr unsigned short volatile SMT1CPRH         absolute 0xD90;
    const register unsigned short int SMT1CPR8 = 0;
    sbit  SMT1CPR8_bit at SMT1CPRH.B0;
    const register unsigned short int SMT1CPR9 = 1;
    sbit  SMT1CPR9_bit at SMT1CPRH.B1;
    const register unsigned short int SMT1CPR10 = 2;
    sbit  SMT1CPR10_bit at SMT1CPRH.B2;
    const register unsigned short int SMT1CPR11 = 3;
    sbit  SMT1CPR11_bit at SMT1CPRH.B3;
    const register unsigned short int SMT1CPR12 = 4;
    sbit  SMT1CPR12_bit at SMT1CPRH.B4;
    const register unsigned short int SMT1CPR13 = 5;
    sbit  SMT1CPR13_bit at SMT1CPRH.B5;
    const register unsigned short int SMT1CPR14 = 6;
    sbit  SMT1CPR14_bit at SMT1CPRH.B6;
    const register unsigned short int SMT1CPR15 = 7;
    sbit  SMT1CPR15_bit at SMT1CPRH.B7;

sfr unsigned short volatile SMT1CPRU         absolute 0xD91;
    const register unsigned short int SMT1CPR16 = 0;
    sbit  SMT1CPR16_bit at SMT1CPRU.B0;
    const register unsigned short int SMT1CPR17 = 1;
    sbit  SMT1CPR17_bit at SMT1CPRU.B1;
    const register unsigned short int SMT1CPR18 = 2;
    sbit  SMT1CPR18_bit at SMT1CPRU.B2;
    const register unsigned short int SMT1CPR19 = 3;
    sbit  SMT1CPR19_bit at SMT1CPRU.B3;
    const register unsigned short int SMT1CPR20 = 4;
    sbit  SMT1CPR20_bit at SMT1CPRU.B4;
    const register unsigned short int SMT1CPR21 = 5;
    sbit  SMT1CPR21_bit at SMT1CPRU.B5;
    const register unsigned short int SMT1CPR22 = 6;
    sbit  SMT1CPR22_bit at SMT1CPRU.B6;
    const register unsigned short int SMT1CPR23 = 7;
    sbit  SMT1CPR23_bit at SMT1CPRU.B7;

sfr unsigned short volatile SMT1CPWL         absolute 0xD92;
    const register unsigned short int SMT1CPW0 = 0;
    sbit  SMT1CPW0_bit at SMT1CPWL.B0;
    const register unsigned short int SMT1CPW1 = 1;
    sbit  SMT1CPW1_bit at SMT1CPWL.B1;
    const register unsigned short int SMT1CPW2 = 2;
    sbit  SMT1CPW2_bit at SMT1CPWL.B2;
    const register unsigned short int SMT1CPW3 = 3;
    sbit  SMT1CPW3_bit at SMT1CPWL.B3;
    const register unsigned short int SMT1CPW4 = 4;
    sbit  SMT1CPW4_bit at SMT1CPWL.B4;
    const register unsigned short int SMT1CPW5 = 5;
    sbit  SMT1CPW5_bit at SMT1CPWL.B5;
    const register unsigned short int SMT1CPW6 = 6;
    sbit  SMT1CPW6_bit at SMT1CPWL.B6;
    const register unsigned short int SMT1CPW7 = 7;
    sbit  SMT1CPW7_bit at SMT1CPWL.B7;

sfr unsigned short volatile SMT1CPWH         absolute 0xD93;
    const register unsigned short int SMT1CPW8 = 0;
    sbit  SMT1CPW8_bit at SMT1CPWH.B0;
    const register unsigned short int SMT1CPW9 = 1;
    sbit  SMT1CPW9_bit at SMT1CPWH.B1;
    const register unsigned short int SMT1CPW10 = 2;
    sbit  SMT1CPW10_bit at SMT1CPWH.B2;
    const register unsigned short int SMT1CPW11 = 3;
    sbit  SMT1CPW11_bit at SMT1CPWH.B3;
    const register unsigned short int SMT1CPW12 = 4;
    sbit  SMT1CPW12_bit at SMT1CPWH.B4;
    const register unsigned short int SMT1CPW13 = 5;
    sbit  SMT1CPW13_bit at SMT1CPWH.B5;
    const register unsigned short int SMT1CPW14 = 6;
    sbit  SMT1CPW14_bit at SMT1CPWH.B6;
    const register unsigned short int SMT1CPW15 = 7;
    sbit  SMT1CPW15_bit at SMT1CPWH.B7;

sfr unsigned short volatile SMT1CPWU         absolute 0xD94;
    const register unsigned short int SMT1CPW16 = 0;
    sbit  SMT1CPW16_bit at SMT1CPWU.B0;
    const register unsigned short int SMT1CPW17 = 1;
    sbit  SMT1CPW17_bit at SMT1CPWU.B1;
    const register unsigned short int SMT1CPW18 = 2;
    sbit  SMT1CPW18_bit at SMT1CPWU.B2;
    const register unsigned short int SMT1CPW19 = 3;
    sbit  SMT1CPW19_bit at SMT1CPWU.B3;
    const register unsigned short int SMT1CPW20 = 4;
    sbit  SMT1CPW20_bit at SMT1CPWU.B4;
    const register unsigned short int SMT1CPW21 = 5;
    sbit  SMT1CPW21_bit at SMT1CPWU.B5;
    const register unsigned short int SMT1CPW22 = 6;
    sbit  SMT1CPW22_bit at SMT1CPWU.B6;
    const register unsigned short int SMT1CPW23 = 7;
    sbit  SMT1CPW23_bit at SMT1CPWU.B7;

sfr unsigned short volatile SMT1PRL          absolute 0xD95;
    const register unsigned short int SMT1PR0 = 0;
    sbit  SMT1PR0_bit at SMT1PRL.B0;
    const register unsigned short int SMT1PR1 = 1;
    sbit  SMT1PR1_bit at SMT1PRL.B1;
    const register unsigned short int SMT1PR2 = 2;
    sbit  SMT1PR2_bit at SMT1PRL.B2;
    const register unsigned short int SMT1PR3 = 3;
    sbit  SMT1PR3_bit at SMT1PRL.B3;
    const register unsigned short int SMT1PR4 = 4;
    sbit  SMT1PR4_bit at SMT1PRL.B4;
    const register unsigned short int SMT1PR5 = 5;
    sbit  SMT1PR5_bit at SMT1PRL.B5;
    const register unsigned short int SMT1PR6 = 6;
    sbit  SMT1PR6_bit at SMT1PRL.B6;
    const register unsigned short int SMT1PR7 = 7;
    sbit  SMT1PR7_bit at SMT1PRL.B7;

sfr unsigned short volatile SMT1PRH          absolute 0xD96;
    const register unsigned short int SMT1PR8 = 0;
    sbit  SMT1PR8_bit at SMT1PRH.B0;
    const register unsigned short int SMT1PR9 = 1;
    sbit  SMT1PR9_bit at SMT1PRH.B1;
    const register unsigned short int SMT1PR10 = 2;
    sbit  SMT1PR10_bit at SMT1PRH.B2;
    const register unsigned short int SMT1PR11 = 3;
    sbit  SMT1PR11_bit at SMT1PRH.B3;
    const register unsigned short int SMT1PR12 = 4;
    sbit  SMT1PR12_bit at SMT1PRH.B4;
    const register unsigned short int SMT1PR13 = 5;
    sbit  SMT1PR13_bit at SMT1PRH.B5;
    const register unsigned short int SMT1PR14 = 6;
    sbit  SMT1PR14_bit at SMT1PRH.B6;
    const register unsigned short int SMT1PR15 = 7;
    sbit  SMT1PR15_bit at SMT1PRH.B7;

sfr unsigned short volatile SMT1PRU          absolute 0xD97;
    const register unsigned short int SMT1PR16 = 0;
    sbit  SMT1PR16_bit at SMT1PRU.B0;
    const register unsigned short int SMT1PR17 = 1;
    sbit  SMT1PR17_bit at SMT1PRU.B1;
    const register unsigned short int SMT1PR18 = 2;
    sbit  SMT1PR18_bit at SMT1PRU.B2;
    const register unsigned short int SMT1PR19 = 3;
    sbit  SMT1PR19_bit at SMT1PRU.B3;
    const register unsigned short int SMT1PR20 = 4;
    sbit  SMT1PR20_bit at SMT1PRU.B4;
    const register unsigned short int SMT1PR21 = 5;
    sbit  SMT1PR21_bit at SMT1PRU.B5;
    const register unsigned short int SMT1PR22 = 6;
    sbit  SMT1PR22_bit at SMT1PRU.B6;
    const register unsigned short int SMT1PR23 = 7;
    sbit  SMT1PR23_bit at SMT1PRU.B7;

sfr unsigned short volatile SMT1CON0         absolute 0xD98;
    const register unsigned short int SMT1PS0 = 0;
    sbit  SMT1PS0_bit at SMT1CON0.B0;
    const register unsigned short int SMT1PS1 = 1;
    sbit  SMT1PS1_bit at SMT1CON0.B1;

sfr unsigned short volatile SMT1CON1         absolute 0xD99;
    const register unsigned short int SMT1MODE0 = 0;
    sbit  SMT1MODE0_bit at SMT1CON1.B0;
    const register unsigned short int SMT1MODE1 = 1;
    sbit  SMT1MODE1_bit at SMT1CON1.B1;
    const register unsigned short int SMT1MODE2 = 2;
    sbit  SMT1MODE2_bit at SMT1CON1.B2;
    const register unsigned short int SMT1MODE3 = 3;
    sbit  SMT1MODE3_bit at SMT1CON1.B3;
    const register unsigned short int SMT1REPEAT = 6;
    sbit  SMT1REPEAT_bit at SMT1CON1.B6;
    const register unsigned short int SMT1GO = 7;
    sbit  SMT1GO_bit at SMT1CON1.B7;

sfr unsigned short volatile SMT1STAT         absolute 0xD9A;
    const register unsigned short int SMT1AS = 0;
    sbit  SMT1AS_bit at SMT1STAT.B0;
    const register unsigned short int SMT1WS = 1;
    sbit  SMT1WS_bit at SMT1STAT.B1;
    const register unsigned short int SMT1TS = 2;
    sbit  SMT1TS_bit at SMT1STAT.B2;
    const register unsigned short int SMT1RESET = 5;
    sbit  SMT1RESET_bit at SMT1STAT.B5;
    const register unsigned short int SMT1CPWUP = 6;
    sbit  SMT1CPWUP_bit at SMT1STAT.B6;
    const register unsigned short int SMT1CPRUP = 7;
    sbit  SMT1CPRUP_bit at SMT1STAT.B7;

sfr unsigned short volatile SMT1CLK          absolute 0xD9B;
    const register unsigned short int SMT1CSEL0 = 0;
    sbit  SMT1CSEL0_bit at SMT1CLK.B0;
    const register unsigned short int SMT1CSEL1 = 1;
    sbit  SMT1CSEL1_bit at SMT1CLK.B1;
    const register unsigned short int SMT1CSEL2 = 2;
    sbit  SMT1CSEL2_bit at SMT1CLK.B2;

sfr unsigned short volatile SMT1SIG          absolute 0xD9C;
    const register unsigned short int SMT1SSEL0 = 0;
    sbit  SMT1SSEL0_bit at SMT1SIG.B0;
    const register unsigned short int SMT1SSEL1 = 1;
    sbit  SMT1SSEL1_bit at SMT1SIG.B1;
    const register unsigned short int SMT1SSEL2 = 2;
    sbit  SMT1SSEL2_bit at SMT1SIG.B2;

sfr unsigned short volatile SMT1WIN          absolute 0xD9D;
    const register unsigned short int SMT1WSEL0 = 0;
    sbit  SMT1WSEL0_bit at SMT1WIN.B0;
    const register unsigned short int SMT1WSEL1 = 1;
    sbit  SMT1WSEL1_bit at SMT1WIN.B1;
    const register unsigned short int SMT1WSEL2 = 2;
    sbit  SMT1WSEL2_bit at SMT1WIN.B2;
    const register unsigned short int SMT1WSEL3 = 3;
    sbit  SMT1WSEL3_bit at SMT1WIN.B3;

sfr unsigned short volatile SMT2TMRL         absolute 0xD9E;
    const register unsigned short int SMT2TMR0 = 0;
    sbit  SMT2TMR0_bit at SMT2TMRL.B0;
    const register unsigned short int SMT2TMR1 = 1;
    sbit  SMT2TMR1_bit at SMT2TMRL.B1;
    const register unsigned short int SMT2TMR2 = 2;
    sbit  SMT2TMR2_bit at SMT2TMRL.B2;
    const register unsigned short int SMT2TMR3 = 3;
    sbit  SMT2TMR3_bit at SMT2TMRL.B3;
    const register unsigned short int SMT2TMR4 = 4;
    sbit  SMT2TMR4_bit at SMT2TMRL.B4;
    const register unsigned short int SMT2TMR5 = 5;
    sbit  SMT2TMR5_bit at SMT2TMRL.B5;
    const register unsigned short int SMT2TMR6 = 6;
    sbit  SMT2TMR6_bit at SMT2TMRL.B6;
    const register unsigned short int SMT2TMR7 = 7;
    sbit  SMT2TMR7_bit at SMT2TMRL.B7;

sfr unsigned short volatile SMT2TMRH         absolute 0xD9F;
    const register unsigned short int SMT2TMR8 = 0;
    sbit  SMT2TMR8_bit at SMT2TMRH.B0;
    const register unsigned short int SMT2TMR9 = 1;
    sbit  SMT2TMR9_bit at SMT2TMRH.B1;
    const register unsigned short int SMT2TMR10 = 2;
    sbit  SMT2TMR10_bit at SMT2TMRH.B2;
    const register unsigned short int SMT2TMR11 = 3;
    sbit  SMT2TMR11_bit at SMT2TMRH.B3;
    const register unsigned short int SMT2TMR12 = 4;
    sbit  SMT2TMR12_bit at SMT2TMRH.B4;
    const register unsigned short int SMT2TMR13 = 5;
    sbit  SMT2TMR13_bit at SMT2TMRH.B5;
    const register unsigned short int SMT2TMR14 = 6;
    sbit  SMT2TMR14_bit at SMT2TMRH.B6;
    const register unsigned short int SMT2TMR15 = 7;
    sbit  SMT2TMR15_bit at SMT2TMRH.B7;

sfr unsigned short volatile SMT2TMRU         absolute 0xDA0;
    const register unsigned short int SMT2TMR16 = 0;
    sbit  SMT2TMR16_bit at SMT2TMRU.B0;
    const register unsigned short int SMT2TMR17 = 1;
    sbit  SMT2TMR17_bit at SMT2TMRU.B1;
    const register unsigned short int SMT2TMR18 = 2;
    sbit  SMT2TMR18_bit at SMT2TMRU.B2;
    const register unsigned short int SMT2TMR19 = 3;
    sbit  SMT2TMR19_bit at SMT2TMRU.B3;
    const register unsigned short int SMT2TMR20 = 4;
    sbit  SMT2TMR20_bit at SMT2TMRU.B4;
    const register unsigned short int SMT2TMR21 = 5;
    sbit  SMT2TMR21_bit at SMT2TMRU.B5;
    const register unsigned short int SMT2TMR22 = 6;
    sbit  SMT2TMR22_bit at SMT2TMRU.B6;
    const register unsigned short int SMT2TMR23 = 7;
    sbit  SMT2TMR23_bit at SMT2TMRU.B7;

sfr unsigned short volatile SMT2CPRL         absolute 0xDA1;
    const register unsigned short int SMT2CPR0 = 0;
    sbit  SMT2CPR0_bit at SMT2CPRL.B0;
    const register unsigned short int SMT2CPR1 = 1;
    sbit  SMT2CPR1_bit at SMT2CPRL.B1;
    const register unsigned short int SMT2CPR2 = 2;
    sbit  SMT2CPR2_bit at SMT2CPRL.B2;
    const register unsigned short int SMT2CPR3 = 3;
    sbit  SMT2CPR3_bit at SMT2CPRL.B3;
    const register unsigned short int SMT2CPR4 = 4;
    sbit  SMT2CPR4_bit at SMT2CPRL.B4;
    const register unsigned short int SMT2CPR5 = 5;
    sbit  SMT2CPR5_bit at SMT2CPRL.B5;
    const register unsigned short int SMT2CPR6 = 6;
    sbit  SMT2CPR6_bit at SMT2CPRL.B6;
    const register unsigned short int SMT2CPR7 = 7;
    sbit  SMT2CPR7_bit at SMT2CPRL.B7;

sfr unsigned short volatile SMT2CPRH         absolute 0xDA2;
    const register unsigned short int SMT2CPR8 = 0;
    sbit  SMT2CPR8_bit at SMT2CPRH.B0;
    const register unsigned short int SMT2CPR9 = 1;
    sbit  SMT2CPR9_bit at SMT2CPRH.B1;
    const register unsigned short int SMT2CPR10 = 2;
    sbit  SMT2CPR10_bit at SMT2CPRH.B2;
    const register unsigned short int SMT2CPR11 = 3;
    sbit  SMT2CPR11_bit at SMT2CPRH.B3;
    const register unsigned short int SMT2CPR12 = 4;
    sbit  SMT2CPR12_bit at SMT2CPRH.B4;
    const register unsigned short int SMT2CPR13 = 5;
    sbit  SMT2CPR13_bit at SMT2CPRH.B5;
    const register unsigned short int SMT2CPR14 = 6;
    sbit  SMT2CPR14_bit at SMT2CPRH.B6;
    const register unsigned short int SMT2CPR15 = 7;
    sbit  SMT2CPR15_bit at SMT2CPRH.B7;

sfr unsigned short volatile SMT2CPRU         absolute 0xDA3;
    const register unsigned short int SMT2CPR16 = 0;
    sbit  SMT2CPR16_bit at SMT2CPRU.B0;
    const register unsigned short int SMT2CPR17 = 1;
    sbit  SMT2CPR17_bit at SMT2CPRU.B1;
    const register unsigned short int SMT2CPR18 = 2;
    sbit  SMT2CPR18_bit at SMT2CPRU.B2;
    const register unsigned short int SMT2CPR19 = 3;
    sbit  SMT2CPR19_bit at SMT2CPRU.B3;
    const register unsigned short int SMT2CPR20 = 4;
    sbit  SMT2CPR20_bit at SMT2CPRU.B4;
    const register unsigned short int SMT2CPR21 = 5;
    sbit  SMT2CPR21_bit at SMT2CPRU.B5;
    const register unsigned short int SMT2CPR22 = 6;
    sbit  SMT2CPR22_bit at SMT2CPRU.B6;
    const register unsigned short int SMT2CPR23 = 7;
    sbit  SMT2CPR23_bit at SMT2CPRU.B7;

sfr unsigned short volatile SMT2CPWL         absolute 0xDA4;
    const register unsigned short int SMT2CPW0 = 0;
    sbit  SMT2CPW0_bit at SMT2CPWL.B0;
    const register unsigned short int SMT2CPW1 = 1;
    sbit  SMT2CPW1_bit at SMT2CPWL.B1;
    const register unsigned short int SMT2CPW2 = 2;
    sbit  SMT2CPW2_bit at SMT2CPWL.B2;
    const register unsigned short int SMT2CPW3 = 3;
    sbit  SMT2CPW3_bit at SMT2CPWL.B3;
    const register unsigned short int SMT2CPW4 = 4;
    sbit  SMT2CPW4_bit at SMT2CPWL.B4;
    const register unsigned short int SMT2CPW5 = 5;
    sbit  SMT2CPW5_bit at SMT2CPWL.B5;
    const register unsigned short int SMT2CPW6 = 6;
    sbit  SMT2CPW6_bit at SMT2CPWL.B6;
    const register unsigned short int SMT2CPW7 = 7;
    sbit  SMT2CPW7_bit at SMT2CPWL.B7;

sfr unsigned short volatile SMT2CPWH         absolute 0xDA5;
    const register unsigned short int SMT2CPW8 = 0;
    sbit  SMT2CPW8_bit at SMT2CPWH.B0;
    const register unsigned short int SMT2CPW9 = 1;
    sbit  SMT2CPW9_bit at SMT2CPWH.B1;
    const register unsigned short int SMT2CPW10 = 2;
    sbit  SMT2CPW10_bit at SMT2CPWH.B2;
    const register unsigned short int SMT2CPW11 = 3;
    sbit  SMT2CPW11_bit at SMT2CPWH.B3;
    const register unsigned short int SMT2CPW12 = 4;
    sbit  SMT2CPW12_bit at SMT2CPWH.B4;
    const register unsigned short int SMT2CPW13 = 5;
    sbit  SMT2CPW13_bit at SMT2CPWH.B5;
    const register unsigned short int SMT2CPW14 = 6;
    sbit  SMT2CPW14_bit at SMT2CPWH.B6;
    const register unsigned short int SMT2CPW15 = 7;
    sbit  SMT2CPW15_bit at SMT2CPWH.B7;

sfr unsigned short volatile SMT2CPWU         absolute 0xDA6;
    const register unsigned short int SMT2CPW16 = 0;
    sbit  SMT2CPW16_bit at SMT2CPWU.B0;
    const register unsigned short int SMT2CPW17 = 1;
    sbit  SMT2CPW17_bit at SMT2CPWU.B1;
    const register unsigned short int SMT2CPW18 = 2;
    sbit  SMT2CPW18_bit at SMT2CPWU.B2;
    const register unsigned short int SMT2CPW19 = 3;
    sbit  SMT2CPW19_bit at SMT2CPWU.B3;
    const register unsigned short int SMT2CPW20 = 4;
    sbit  SMT2CPW20_bit at SMT2CPWU.B4;
    const register unsigned short int SMT2CPW21 = 5;
    sbit  SMT2CPW21_bit at SMT2CPWU.B5;
    const register unsigned short int SMT2CPW22 = 6;
    sbit  SMT2CPW22_bit at SMT2CPWU.B6;
    const register unsigned short int SMT2CPW23 = 7;
    sbit  SMT2CPW23_bit at SMT2CPWU.B7;

sfr unsigned short volatile SMT2PRL          absolute 0xDA7;
    const register unsigned short int SMT2PR0 = 0;
    sbit  SMT2PR0_bit at SMT2PRL.B0;
    const register unsigned short int SMT2PR1 = 1;
    sbit  SMT2PR1_bit at SMT2PRL.B1;
    const register unsigned short int SMT2PR2 = 2;
    sbit  SMT2PR2_bit at SMT2PRL.B2;
    const register unsigned short int SMT2PR3 = 3;
    sbit  SMT2PR3_bit at SMT2PRL.B3;
    const register unsigned short int SMT2PR4 = 4;
    sbit  SMT2PR4_bit at SMT2PRL.B4;
    const register unsigned short int SMT2PR5 = 5;
    sbit  SMT2PR5_bit at SMT2PRL.B5;
    const register unsigned short int SMT2PR6 = 6;
    sbit  SMT2PR6_bit at SMT2PRL.B6;
    const register unsigned short int SMT2PR7 = 7;
    sbit  SMT2PR7_bit at SMT2PRL.B7;

sfr unsigned short volatile SMT2PRH          absolute 0xDA8;
    const register unsigned short int SMT2PR8 = 0;
    sbit  SMT2PR8_bit at SMT2PRH.B0;
    const register unsigned short int SMT2PR9 = 1;
    sbit  SMT2PR9_bit at SMT2PRH.B1;
    const register unsigned short int SMT2PR10 = 2;
    sbit  SMT2PR10_bit at SMT2PRH.B2;
    const register unsigned short int SMT2PR11 = 3;
    sbit  SMT2PR11_bit at SMT2PRH.B3;
    const register unsigned short int SMT2PR12 = 4;
    sbit  SMT2PR12_bit at SMT2PRH.B4;
    const register unsigned short int SMT2PR13 = 5;
    sbit  SMT2PR13_bit at SMT2PRH.B5;
    const register unsigned short int SMT2PR14 = 6;
    sbit  SMT2PR14_bit at SMT2PRH.B6;
    const register unsigned short int SMT2PR15 = 7;
    sbit  SMT2PR15_bit at SMT2PRH.B7;

sfr unsigned short volatile SMT2PRU          absolute 0xDA9;
    const register unsigned short int SMT2PR16 = 0;
    sbit  SMT2PR16_bit at SMT2PRU.B0;
    const register unsigned short int SMT2PR17 = 1;
    sbit  SMT2PR17_bit at SMT2PRU.B1;
    const register unsigned short int SMT2PR18 = 2;
    sbit  SMT2PR18_bit at SMT2PRU.B2;
    const register unsigned short int SMT2PR19 = 3;
    sbit  SMT2PR19_bit at SMT2PRU.B3;
    const register unsigned short int SMT2PR20 = 4;
    sbit  SMT2PR20_bit at SMT2PRU.B4;
    const register unsigned short int SMT2PR21 = 5;
    sbit  SMT2PR21_bit at SMT2PRU.B5;
    const register unsigned short int SMT2PR22 = 6;
    sbit  SMT2PR22_bit at SMT2PRU.B6;
    const register unsigned short int SMT2PR23 = 7;
    sbit  SMT2PR23_bit at SMT2PRU.B7;

sfr unsigned short volatile SMT2CON0         absolute 0xDAA;
    const register unsigned short int SMT2PS0 = 0;
    sbit  SMT2PS0_bit at SMT2CON0.B0;
    const register unsigned short int SMT2PS1 = 1;
    sbit  SMT2PS1_bit at SMT2CON0.B1;

sfr unsigned short volatile SMT2CON1         absolute 0xDAB;
    const register unsigned short int SMT2MODE0 = 0;
    sbit  SMT2MODE0_bit at SMT2CON1.B0;
    const register unsigned short int SMT2MODE1 = 1;
    sbit  SMT2MODE1_bit at SMT2CON1.B1;
    const register unsigned short int SMT2MODE2 = 2;
    sbit  SMT2MODE2_bit at SMT2CON1.B2;
    const register unsigned short int SMT2MODE3 = 3;
    sbit  SMT2MODE3_bit at SMT2CON1.B3;
    const register unsigned short int SMT2REPEAT = 6;
    sbit  SMT2REPEAT_bit at SMT2CON1.B6;
    const register unsigned short int SMT2GO = 7;
    sbit  SMT2GO_bit at SMT2CON1.B7;

sfr unsigned short volatile SMT2STAT         absolute 0xDAC;
    const register unsigned short int SMT2AS = 0;
    sbit  SMT2AS_bit at SMT2STAT.B0;
    const register unsigned short int SMT2WS = 1;
    sbit  SMT2WS_bit at SMT2STAT.B1;
    const register unsigned short int SMT2TS = 2;
    sbit  SMT2TS_bit at SMT2STAT.B2;
    const register unsigned short int SMT2RESET = 5;
    sbit  SMT2RESET_bit at SMT2STAT.B5;
    const register unsigned short int SMT2CPWUP = 6;
    sbit  SMT2CPWUP_bit at SMT2STAT.B6;
    const register unsigned short int SMT2CPRUP = 7;
    sbit  SMT2CPRUP_bit at SMT2STAT.B7;

sfr unsigned short volatile SMT2CLK          absolute 0xDAD;
    const register unsigned short int SMT2CSEL0 = 0;
    sbit  SMT2CSEL0_bit at SMT2CLK.B0;
    const register unsigned short int SMT2CSEL1 = 1;
    sbit  SMT2CSEL1_bit at SMT2CLK.B1;
    const register unsigned short int SMT2CSEL2 = 2;
    sbit  SMT2CSEL2_bit at SMT2CLK.B2;

sfr unsigned short volatile SMT2SIG          absolute 0xDAE;
    const register unsigned short int SMT2SSEL0 = 0;
    sbit  SMT2SSEL0_bit at SMT2SIG.B0;
    const register unsigned short int SMT2SSEL1 = 1;
    sbit  SMT2SSEL1_bit at SMT2SIG.B1;
    const register unsigned short int SMT2SSEL2 = 2;
    sbit  SMT2SSEL2_bit at SMT2SIG.B2;

sfr unsigned short volatile SMT2WIN          absolute 0xDAF;
    const register unsigned short int SMT2WSEL0 = 0;
    sbit  SMT2WSEL0_bit at SMT2WIN.B0;
    const register unsigned short int SMT2WSEL1 = 1;
    sbit  SMT2WSEL1_bit at SMT2WIN.B1;
    const register unsigned short int SMT2WSEL2 = 2;
    sbit  SMT2WSEL2_bit at SMT2WIN.B2;
    const register unsigned short int SMT2WSEL3 = 3;
    sbit  SMT2WSEL3_bit at SMT2WIN.B3;

sfr unsigned short volatile STATUS_SHAD      absolute 0xFE4;
    const register unsigned short int C_SHAD = 0;
    sbit  C_SHAD_bit at STATUS_SHAD.B0;
    const register unsigned short int DC_SHAD = 1;
    sbit  DC_SHAD_bit at STATUS_SHAD.B1;
    const register unsigned short int Z_SHAD = 2;
    sbit  Z_SHAD_bit at STATUS_SHAD.B2;

sfr unsigned short volatile WREG_SHAD        absolute 0xFE5;
sfr unsigned short volatile BSR_SHAD         absolute 0xFE6;
sfr unsigned short volatile PCLATH_SHAD      absolute 0xFE7;
sfr unsigned short volatile FSR0L_SHAD       absolute 0xFE8;
sfr unsigned short volatile FSR0H_SHAD       absolute 0xFE9;
sfr unsigned short volatile FSR1L_SHAD       absolute 0xFEA;
sfr unsigned short volatile FSR1H_SHAD       absolute 0xFEB;
sfr unsigned short volatile STKPTR           absolute 0xFED;
sfr unsigned short volatile TOSL             absolute 0xFEE;
sfr unsigned short volatile TOSH             absolute 0xFEF;
