// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00000800;

// Working space registers
rx unsigned short R0  absolute 0x0070;
rx unsigned short R1  absolute 0x0071;
rx unsigned short R2  absolute 0x0072;
rx unsigned short R3  absolute 0x0073;
rx unsigned short R4  absolute 0x0074;
rx unsigned short R5  absolute 0x0075;
rx unsigned short R6  absolute 0x0076;
rx unsigned short R7  absolute 0x0077;
rx unsigned short R8  absolute 0x0078;
rx unsigned short R9  absolute 0x0079;
rx unsigned short R10 absolute 0x007A;
rx unsigned short R11 absolute 0x007B;
rx unsigned short R12 absolute 0x007C;
rx unsigned short R13 absolute 0x007D;
rx unsigned short R14 absolute 0x007E;
rx unsigned short R15 absolute 0x007F;

const register unsigned short int W = 0;
const register unsigned short int F = 1;

// Special function registers (SFRs)

const signed int   PORT_TO_TRIS_OFFSET    =     128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

sfr unsigned short volatile INDF0            absolute 0x000;
sfr unsigned short volatile INDF1            absolute 0x001;
sfr unsigned short volatile PCL              absolute 0x002;
sfr unsigned short volatile STATUS           absolute 0x003;
    const register unsigned short int CARRY = 0;
    const register unsigned short int C = 0;
    sbit  CARRY_bit at STATUS.B0;
    sbit  C_bit at STATUS.B0;
    const register unsigned short int DC = 1;
    sbit  DC_bit at STATUS.B1;
    const register unsigned short int ZERO = 2;
    const register unsigned short int Z = 2;
    sbit  ZERO_bit at STATUS.B2;
    sbit  Z_bit at STATUS.B2;
    const register unsigned short int nPD = 3;
    sbit  nPD_bit at STATUS.B3;
    const register unsigned short int nTO = 4;
    sbit  nTO_bit at STATUS.B4;

sfr unsigned int            FSR0             absolute 0x004;
sfr unsigned short          FSR0L            absolute 0x004;
register unsigned short     *FSR0PTR         absolute 0x004;
sfr unsigned short          FSR0H            absolute 0x005;
sfr unsigned int            FSR1             absolute 0x006;
sfr unsigned short          FSR1L            absolute 0x006;
register unsigned short     *FSR1PTR         absolute 0x006;
sfr unsigned short          FSR1H            absolute 0x007;
sfr unsigned short          BSR              absolute 0x008;
    const register unsigned short int BSR0 = 0;
    sbit  BSR0_bit at BSR.B0;
    const register unsigned short int BSR1 = 1;
    sbit  BSR1_bit at BSR.B1;
    const register unsigned short int BSR2 = 2;
    sbit  BSR2_bit at BSR.B2;
    const register unsigned short int BSR3 = 3;
    sbit  BSR3_bit at BSR.B3;
    const register unsigned short int BSR4 = 4;
    sbit  BSR4_bit at BSR.B4;

sfr unsigned short volatile WREG             absolute 0x009;
sfr unsigned short volatile PCLATH           absolute 0x00A;
sfr unsigned short volatile INTCON           absolute 0x00B;
    const register unsigned short int INTEDG = 0;
    sbit  INTEDG_bit at INTCON.B0;
    const register unsigned short int PEIE = 6;
    sbit  PEIE_bit at INTCON.B6;
    const register unsigned short int GIE = 7;
    sbit  GIE_bit at INTCON.B7;

sfr unsigned short volatile PORTA            absolute 0x00C;
    const register unsigned short int RA0 = 0;
    sbit  RA0_bit at PORTA.B0;
    const register unsigned short int RA1 = 1;
    sbit  RA1_bit at PORTA.B1;
    const register unsigned short int RA2 = 2;
    sbit  RA2_bit at PORTA.B2;
    const register unsigned short int RA3 = 3;
    sbit  RA3_bit at PORTA.B3;
    const register unsigned short int RA4 = 4;
    sbit  RA4_bit at PORTA.B4;
    const register unsigned short int RA5 = 5;
    sbit  RA5_bit at PORTA.B5;

sfr unsigned short volatile PIR0             absolute 0x010;
    const register unsigned short int INTF = 0;
    sbit  INTF_bit at PIR0.B0;
    const register unsigned short int IOCIF = 4;
    sbit  IOCIF_bit at PIR0.B4;
    const register unsigned short int TMR0IF = 5;
    sbit  TMR0IF_bit at PIR0.B5;

sfr unsigned short volatile PIR1             absolute 0x011;
    const register unsigned short int TMR1IF = 0;
    sbit  TMR1IF_bit at PIR1.B0;
    const register unsigned short int TMR2IF = 1;
    sbit  TMR2IF_bit at PIR1.B1;
    const register unsigned short int BCL1IF = 2;
    sbit  BCL1IF_bit at PIR1.B2;
    const register unsigned short int SSP1IF = 3;
    sbit  SSP1IF_bit at PIR1.B3;
    const register unsigned short int TXIF = 4;
    sbit  TXIF_bit at PIR1.B4;
    const register unsigned short int RCIF = 5;
    sbit  RCIF_bit at PIR1.B5;
    const register unsigned short int ADIF = 6;
    sbit  ADIF_bit at PIR1.B6;
    const register unsigned short int TMR1GIF = 7;
    sbit  TMR1GIF_bit at PIR1.B7;

sfr unsigned short volatile PIR2             absolute 0x012;
    const register unsigned short int NCO1IF = 0;
    sbit  NCO1IF_bit at PIR2.B0;
    const register unsigned short int NVMIF = 4;
    sbit  NVMIF_bit at PIR2.B4;
    const register unsigned short int C1IF = 5;
    sbit  C1IF_bit at PIR2.B5;

sfr unsigned short volatile PIR3             absolute 0x013;
    const register unsigned short int CLC1IF = 0;
    sbit  CLC1IF_bit at PIR3.B0;
    const register unsigned short int CLC2IF = 1;
    sbit  CLC2IF_bit at PIR3.B1;
    const register unsigned short int CSWIF = 6;
    sbit  CSWIF_bit at PIR3.B6;
    const register unsigned short int OSFIF = 7;
    sbit  OSFIF_bit at PIR3.B7;

sfr unsigned short volatile PIR4             absolute 0x014;
    const register unsigned short int CCP1IF = 0;
    sbit  CCP1IF_bit at PIR4.B0;
    const register unsigned short int CCP2IF = 1;
    sbit  CCP2IF_bit at PIR4.B1;
    const register unsigned short int CWG1IF = 6;
    sbit  CWG1IF_bit at PIR4.B6;

sfr unsigned short volatile TMR0L            absolute 0x015;
    const register unsigned short int TMR00 = 0;
    sbit  TMR00_bit at TMR0L.B0;
    const register unsigned short int TMR01 = 1;
    sbit  TMR01_bit at TMR0L.B1;
    const register unsigned short int TMR02 = 2;
    sbit  TMR02_bit at TMR0L.B2;
    const register unsigned short int TMR03 = 3;
    sbit  TMR03_bit at TMR0L.B3;
    const register unsigned short int TMR04 = 4;
    sbit  TMR04_bit at TMR0L.B4;
    const register unsigned short int TMR05 = 5;
    sbit  TMR05_bit at TMR0L.B5;
    const register unsigned short int TMR06 = 6;
    sbit  TMR06_bit at TMR0L.B6;
    const register unsigned short int TMR07 = 7;
    sbit  TMR07_bit at TMR0L.B7;

sfr unsigned short volatile TMR0             absolute 0x015;
sfr unsigned short volatile TMR0H            absolute 0x016;
    const register unsigned short int PR00 = 0;
    sbit  PR00_bit at TMR0H.B0;
    const register unsigned short int PR01 = 1;
    sbit  PR01_bit at TMR0H.B1;
    const register unsigned short int PR02 = 2;
    sbit  PR02_bit at TMR0H.B2;
    const register unsigned short int PR03 = 3;
    sbit  PR03_bit at TMR0H.B3;
    const register unsigned short int PR04 = 4;
    sbit  PR04_bit at TMR0H.B4;
    const register unsigned short int PR05 = 5;
    sbit  PR05_bit at TMR0H.B5;
    const register unsigned short int PR06 = 6;
    sbit  PR06_bit at TMR0H.B6;
    const register unsigned short int PR07 = 7;
    sbit  PR07_bit at TMR0H.B7;
    const register unsigned short int TMR010 = 2;
    sbit  TMR010_bit at TMR0H.B2;
    const register unsigned short int TMR011 = 3;
    sbit  TMR011_bit at TMR0H.B3;
    const register unsigned short int TMR012 = 4;
    sbit  TMR012_bit at TMR0H.B4;
    const register unsigned short int TMR013 = 5;
    sbit  TMR013_bit at TMR0H.B5;
    const register unsigned short int TMR014 = 6;
    sbit  TMR014_bit at TMR0H.B6;
    const register unsigned short int TMR015 = 7;
    sbit  TMR015_bit at TMR0H.B7;
    const register unsigned short int TMR08 = 0;
    sbit  TMR08_bit at TMR0H.B0;
    const register unsigned short int TMR09 = 1;
    sbit  TMR09_bit at TMR0H.B1;

sfr unsigned short volatile PR0              absolute 0x016;
sfr unsigned short volatile T0CON0           absolute 0x017;
    const register unsigned short int T0OUTPS0 = 0;
    sbit  T0OUTPS0_bit at T0CON0.B0;
    const register unsigned short int T0OUTPS1 = 1;
    sbit  T0OUTPS1_bit at T0CON0.B1;
    const register unsigned short int T0OUTPS2 = 2;
    sbit  T0OUTPS2_bit at T0CON0.B2;
    const register unsigned short int T0OUTPS3 = 3;
    sbit  T0OUTPS3_bit at T0CON0.B3;
    const register unsigned short int T016BIT = 4;
    sbit  T016BIT_bit at T0CON0.B4;
    const register unsigned short int T0OUT = 5;
    sbit  T0OUT_bit at T0CON0.B5;
    const register unsigned short int T0EN = 7;
    sbit  T0EN_bit at T0CON0.B7;

sfr unsigned short volatile T0CON1           absolute 0x018;
    const register unsigned short int T0CKPS0 = 0;
    sbit  T0CKPS0_bit at T0CON1.B0;
    const register unsigned short int T0CKPS1 = 1;
    sbit  T0CKPS1_bit at T0CON1.B1;
    const register unsigned short int T0CKPS2 = 2;
    sbit  T0CKPS2_bit at T0CON1.B2;
    const register unsigned short int T0CKPS3 = 3;
    sbit  T0CKPS3_bit at T0CON1.B3;
    const register unsigned short int T0ASYNC = 4;
    sbit  T0ASYNC_bit at T0CON1.B4;
    const register unsigned short int T0CS0 = 5;
    sbit  T0CS0_bit at T0CON1.B5;
    const register unsigned short int T0CS1 = 6;
    sbit  T0CS1_bit at T0CON1.B6;
    const register unsigned short int T0CS2 = 7;
    sbit  T0CS2_bit at T0CON1.B7;

sfr unsigned int   volatile TMR1             absolute 0x019;
sfr unsigned short volatile TMR1L            absolute 0x019;
sfr unsigned short volatile TMR1H            absolute 0x01A;
sfr unsigned short volatile T1CON            absolute 0x01B;
    const register unsigned short int TMR1ON = 0;
    sbit  TMR1ON_bit at T1CON.B0;
    const register unsigned short int T1SYNC = 2;
    sbit  T1SYNC_bit at T1CON.B2;
    const register unsigned short int T1SOSC = 3;
    sbit  T1SOSC_bit at T1CON.B3;
    const register unsigned short int T1CKPS0 = 4;
    sbit  T1CKPS0_bit at T1CON.B4;
    const register unsigned short int T1CKPS1 = 5;
    sbit  T1CKPS1_bit at T1CON.B5;
    const register unsigned short int TMR1CS0 = 6;
    sbit  TMR1CS0_bit at T1CON.B6;
    const register unsigned short int TMR1CS1 = 7;
    sbit  TMR1CS1_bit at T1CON.B7;

sfr unsigned short volatile T1GCON           absolute 0x01C;
    const register unsigned short int T1GSS0 = 0;
    sbit  T1GSS0_bit at T1GCON.B0;
    const register unsigned short int T1GSS1 = 1;
    sbit  T1GSS1_bit at T1GCON.B1;
    const register unsigned short int T1GVAL = 2;
    sbit  T1GVAL_bit at T1GCON.B2;
    const register unsigned short int T1GGO_nDONE = 3;
    sbit  T1GGO_nDONE_bit at T1GCON.B3;
    const register unsigned short int T1GSPM = 4;
    sbit  T1GSPM_bit at T1GCON.B4;
    const register unsigned short int T1GTM = 5;
    sbit  T1GTM_bit at T1GCON.B5;
    const register unsigned short int T1GPOL = 6;
    sbit  T1GPOL_bit at T1GCON.B6;
    const register unsigned short int TMR1GE = 7;
    sbit  TMR1GE_bit at T1GCON.B7;

sfr unsigned short volatile TMR2             absolute 0x01D;
sfr unsigned short volatile PR2              absolute 0x01E;
sfr unsigned short volatile T2CON            absolute 0x01F;
    const register unsigned short int T2CKPS0 = 0;
    sbit  T2CKPS0_bit at T2CON.B0;
    const register unsigned short int T2CKPS1 = 1;
    sbit  T2CKPS1_bit at T2CON.B1;
    const register unsigned short int TMR2ON = 2;
    sbit  TMR2ON_bit at T2CON.B2;
    const register unsigned short int T2OUTPS0 = 3;
    sbit  T2OUTPS0_bit at T2CON.B3;
    const register unsigned short int T2OUTPS1 = 4;
    sbit  T2OUTPS1_bit at T2CON.B4;
    const register unsigned short int T2OUTPS2 = 5;
    sbit  T2OUTPS2_bit at T2CON.B5;
    const register unsigned short int T2OUTPS3 = 6;
    sbit  T2OUTPS3_bit at T2CON.B6;

sfr unsigned short volatile TRISA            absolute 0x08C;
    const register unsigned short int TRISA0 = 0;
    sbit  TRISA0_bit at TRISA.B0;
    const register unsigned short int TRISA1 = 1;
    sbit  TRISA1_bit at TRISA.B1;
    const register unsigned short int TRISA2 = 2;
    sbit  TRISA2_bit at TRISA.B2;
    const register unsigned short int TRISA4 = 4;
    sbit  TRISA4_bit at TRISA.B4;
    const register unsigned short int TRISA5 = 5;
    sbit  TRISA5_bit at TRISA.B5;

sfr unsigned short volatile PIE0             absolute 0x090;
    const register unsigned short int INTE = 0;
    sbit  INTE_bit at PIE0.B0;
    const register unsigned short int IOCIE = 4;
    sbit  IOCIE_bit at PIE0.B4;
    const register unsigned short int TMR0IE = 5;
    sbit  TMR0IE_bit at PIE0.B5;

sfr unsigned short volatile PIE1             absolute 0x091;
    const register unsigned short int TMR1IE = 0;
    sbit  TMR1IE_bit at PIE1.B0;
    const register unsigned short int TMR2IE = 1;
    sbit  TMR2IE_bit at PIE1.B1;
    const register unsigned short int BCL1IE = 2;
    sbit  BCL1IE_bit at PIE1.B2;
    const register unsigned short int SSP1IE = 3;
    sbit  SSP1IE_bit at PIE1.B3;
    const register unsigned short int TXIE = 4;
    sbit  TXIE_bit at PIE1.B4;
    const register unsigned short int RCIE = 5;
    sbit  RCIE_bit at PIE1.B5;
    const register unsigned short int ADIE = 6;
    sbit  ADIE_bit at PIE1.B6;
    const register unsigned short int TMR1GIE = 7;
    sbit  TMR1GIE_bit at PIE1.B7;

sfr unsigned short volatile PIE2             absolute 0x092;
    const register unsigned short int NCO1IE = 0;
    sbit  NCO1IE_bit at PIE2.B0;
    const register unsigned short int NVMIE = 4;
    sbit  NVMIE_bit at PIE2.B4;
    const register unsigned short int C1IE = 5;
    sbit  C1IE_bit at PIE2.B5;

sfr unsigned short volatile PIE3             absolute 0x093;
    const register unsigned short int CLC1IE = 0;
    sbit  CLC1IE_bit at PIE3.B0;
    const register unsigned short int CLC2IE = 1;
    sbit  CLC2IE_bit at PIE3.B1;
    const register unsigned short int CSWIE = 6;
    sbit  CSWIE_bit at PIE3.B6;
    const register unsigned short int OSFIE = 7;
    sbit  OSFIE_bit at PIE3.B7;

sfr unsigned short volatile PIE4             absolute 0x094;
    const register unsigned short int CCP1IE = 0;
    sbit  CCP1IE_bit at PIE4.B0;
    const register unsigned short int CCP2IE = 1;
    sbit  CCP2IE_bit at PIE4.B1;
    const register unsigned short int CWG1IE = 6;
    sbit  CWG1IE_bit at PIE4.B6;

sfr unsigned short          WDTCON           absolute 0x097;
    const register unsigned short int SWDTEN = 0;
    sbit  SWDTEN_bit at WDTCON.B0;
    const register unsigned short int WDTPS0 = 1;
    sbit  WDTPS0_bit at WDTCON.B1;
    const register unsigned short int WDTPS1 = 2;
    sbit  WDTPS1_bit at WDTCON.B2;
    const register unsigned short int WDTPS2 = 3;
    sbit  WDTPS2_bit at WDTCON.B3;
    const register unsigned short int WDTPS3 = 4;
    sbit  WDTPS3_bit at WDTCON.B4;
    const register unsigned short int WDTPS4 = 5;
    sbit  WDTPS4_bit at WDTCON.B5;

sfr unsigned int   volatile ADRES            absolute 0x09B;
sfr unsigned short volatile ADRESL           absolute 0x09B;
sfr unsigned short volatile ADRESH           absolute 0x09C;
sfr unsigned short volatile ADCON0           absolute 0x09D;
    const register unsigned short int ADON = 0;
    sbit  ADON_bit at ADCON0.B0;
    const register unsigned short int ADGO = 1;
    sbit  ADGO_bit at ADCON0.B1;
    const register unsigned short int CHS0 = 2;
    sbit  CHS0_bit at ADCON0.B2;
    const register unsigned short int CHS1 = 3;
    sbit  CHS1_bit at ADCON0.B3;
    const register unsigned short int CHS2 = 4;
    sbit  CHS2_bit at ADCON0.B4;
    const register unsigned short int CHS3 = 5;
    sbit  CHS3_bit at ADCON0.B5;
    const register unsigned short int CHS4 = 6;
    sbit  CHS4_bit at ADCON0.B6;
    const register unsigned short int CHS5 = 7;
    sbit  CHS5_bit at ADCON0.B7;
    const register unsigned short int GO = 1;
    sbit  GO_bit at ADCON0.B1;
    const register unsigned short int GO_nDONE = 1;
    sbit  GO_nDONE_bit at ADCON0.B1;
    const register unsigned short int GO_NOT_DONE = 1;
    sbit  GO_NOT_DONE_bit at ADCON0.B1;

sfr unsigned short volatile ADCON1           absolute 0x09E;
    const register unsigned short int ADPREF0 = 0;
    sbit  ADPREF0_bit at ADCON1.B0;
    const register unsigned short int ADPREF1 = 1;
    sbit  ADPREF1_bit at ADCON1.B1;
    const register unsigned short int ADNREF = 2;
    sbit  ADNREF_bit at ADCON1.B2;
    const register unsigned short int ADCS0 = 4;
    sbit  ADCS0_bit at ADCON1.B4;
    const register unsigned short int ADCS1 = 5;
    sbit  ADCS1_bit at ADCON1.B5;
    const register unsigned short int ADCS2 = 6;
    sbit  ADCS2_bit at ADCON1.B6;
    const register unsigned short int ADFM = 7;
    sbit  ADFM_bit at ADCON1.B7;

sfr unsigned short volatile ADACT            absolute 0x09F;
    const register unsigned short int ADACT0 = 0;
    sbit  ADACT0_bit at ADACT.B0;
    const register unsigned short int ADACT1 = 1;
    sbit  ADACT1_bit at ADACT.B1;
    const register unsigned short int ADACT2 = 2;
    sbit  ADACT2_bit at ADACT.B2;
    const register unsigned short int ADACT3 = 3;
    sbit  ADACT3_bit at ADACT.B3;

sfr unsigned short volatile LATA             absolute 0x10C;
    const register unsigned short int LATA0 = 0;
    sbit  LATA0_bit at LATA.B0;
    const register unsigned short int LATA1 = 1;
    sbit  LATA1_bit at LATA.B1;
    const register unsigned short int LATA2 = 2;
    sbit  LATA2_bit at LATA.B2;
    const register unsigned short int LATA4 = 4;
    sbit  LATA4_bit at LATA.B4;
    const register unsigned short int LATA5 = 5;
    sbit  LATA5_bit at LATA.B5;

sfr unsigned short volatile CM1CON0          absolute 0x111;
    const register unsigned short int C1SYNC = 0;
    sbit  C1SYNC_bit at CM1CON0.B0;
    const register unsigned short int C1HYS = 1;
    sbit  C1HYS_bit at CM1CON0.B1;
    const register unsigned short int C1SP = 2;
    sbit  C1SP_bit at CM1CON0.B2;
    const register unsigned short int C1POL = 4;
    sbit  C1POL_bit at CM1CON0.B4;
    const register unsigned short int C1OUT = 6;
    sbit  C1OUT_bit at CM1CON0.B6;
    const register unsigned short int C1ON = 7;
    sbit  C1ON_bit at CM1CON0.B7;

sfr unsigned short volatile CM1CON1          absolute 0x112;
    const register unsigned short int C1NCH0 = 0;
    sbit  C1NCH0_bit at CM1CON1.B0;
    const register unsigned short int C1NCH1 = 1;
    sbit  C1NCH1_bit at CM1CON1.B1;
    const register unsigned short int C1NCH2 = 2;
    sbit  C1NCH2_bit at CM1CON1.B2;
    const register unsigned short int C1PCH0 = 3;
    sbit  C1PCH0_bit at CM1CON1.B3;
    const register unsigned short int C1PCH1 = 4;
    sbit  C1PCH1_bit at CM1CON1.B4;
    const register unsigned short int C1PCH2 = 5;
    sbit  C1PCH2_bit at CM1CON1.B5;
    const register unsigned short int C1INTN = 6;
    sbit  C1INTN_bit at CM1CON1.B6;
    const register unsigned short int C1INTP = 7;
    sbit  C1INTP_bit at CM1CON1.B7;

sfr unsigned short volatile CMOUT            absolute 0x115;
    const register unsigned short int MC1OUT = 0;
    sbit  MC1OUT_bit at CMOUT.B0;

sfr unsigned short volatile BORCON           absolute 0x116;
    const register unsigned short int BORRDY = 0;
    sbit  BORRDY_bit at BORCON.B0;
    const register unsigned short int SBOREN = 7;
    sbit  SBOREN_bit at BORCON.B7;

sfr unsigned short volatile FVRCON           absolute 0x117;
    const register unsigned short int ADFVR0 = 0;
    sbit  ADFVR0_bit at FVRCON.B0;
    const register unsigned short int ADFVR1 = 1;
    sbit  ADFVR1_bit at FVRCON.B1;
    const register unsigned short int CDAFVR0 = 2;
    sbit  CDAFVR0_bit at FVRCON.B2;
    const register unsigned short int CDAFVR1 = 3;
    sbit  CDAFVR1_bit at FVRCON.B3;
    const register unsigned short int TSRNG = 4;
    sbit  TSRNG_bit at FVRCON.B4;
    const register unsigned short int TSEN = 5;
    sbit  TSEN_bit at FVRCON.B5;
    const register unsigned short int FVRRDY = 6;
    sbit  FVRRDY_bit at FVRCON.B6;
    const register unsigned short int FVREN = 7;
    sbit  FVREN_bit at FVRCON.B7;

sfr unsigned short volatile DACCON0          absolute 0x118;
    const register unsigned short int DAC1NSS = 0;
    sbit  DAC1NSS_bit at DACCON0.B0;
    const register unsigned short int DAC1PSS0 = 2;
    sbit  DAC1PSS0_bit at DACCON0.B2;
    const register unsigned short int DAC1PSS1 = 3;
    sbit  DAC1PSS1_bit at DACCON0.B3;
    const register unsigned short int DAC1OE = 5;
    sbit  DAC1OE_bit at DACCON0.B5;
    const register unsigned short int DAC1EN = 7;
    sbit  DAC1EN_bit at DACCON0.B7;

sfr unsigned short volatile DACCON1          absolute 0x119;
    const register unsigned short int DAC1R0 = 0;
    sbit  DAC1R0_bit at DACCON1.B0;
    const register unsigned short int DAC1R1 = 1;
    sbit  DAC1R1_bit at DACCON1.B1;
    const register unsigned short int DAC1R2 = 2;
    sbit  DAC1R2_bit at DACCON1.B2;
    const register unsigned short int DAC1R3 = 3;
    sbit  DAC1R3_bit at DACCON1.B3;
    const register unsigned short int DAC1R4 = 4;
    sbit  DAC1R4_bit at DACCON1.B4;

sfr unsigned short volatile ANSELA           absolute 0x18C;
    const register unsigned short int ANSA0 = 0;
    sbit  ANSA0_bit at ANSELA.B0;
    const register unsigned short int ANSA1 = 1;
    sbit  ANSA1_bit at ANSELA.B1;
    const register unsigned short int ANSA2 = 2;
    sbit  ANSA2_bit at ANSELA.B2;
    const register unsigned short int ANSA4 = 4;
    sbit  ANSA4_bit at ANSELA.B4;
    const register unsigned short int ANSA5 = 5;
    sbit  ANSA5_bit at ANSELA.B5;

sfr unsigned short volatile VREGCON          absolute 0x197;
    const register unsigned short int VREGPM = 1;
    sbit  VREGPM_bit at VREGCON.B1;

sfr unsigned short volatile RC1REG           absolute 0x199;
sfr unsigned short volatile RCREG            absolute 0x199;
sfr unsigned short volatile RCREG1           absolute 0x199;
sfr unsigned short volatile TX1REG           absolute 0x19A;
sfr unsigned short volatile TXREG1           absolute 0x19A;
sfr unsigned short volatile TXREG            absolute 0x19A;
sfr unsigned int   volatile SP1BRG           absolute 0x19B;
sfr unsigned short volatile SP1BRGL          absolute 0x19B;
sfr unsigned int            SPBRG            absolute 0x19B;
sfr unsigned int            SPBRG1           absolute 0x19B;
sfr unsigned short volatile SPBRGL           absolute 0x19B;
sfr unsigned short volatile SP1BRGH          absolute 0x19C;
sfr unsigned short          SPBRGH           absolute 0x19C;
sfr unsigned short          SPBRGH1          absolute 0x19C;
sfr unsigned short volatile RC1STA           absolute 0x19D;
    const register unsigned short int RX9D = 0;
    sbit  RX9D_bit at RC1STA.B0;
    const register unsigned short int OERR = 1;
    sbit  OERR_bit at RC1STA.B1;
    const register unsigned short int FERR = 2;
    sbit  FERR_bit at RC1STA.B2;
    const register unsigned short int ADDEN = 3;
    sbit  ADDEN_bit at RC1STA.B3;
    const register unsigned short int CREN = 4;
    sbit  CREN_bit at RC1STA.B4;
    const register unsigned short int SREN = 5;
    sbit  SREN_bit at RC1STA.B5;
    const register unsigned short int RX9 = 6;
    sbit  RX9_bit at RC1STA.B6;
    const register unsigned short int SPEN = 7;
    sbit  SPEN_bit at RC1STA.B7;

sfr unsigned short volatile RCSTA1           absolute 0x19D;
sfr unsigned short volatile RCSTA            absolute 0x19D;
sfr unsigned short volatile TX1STA           absolute 0x19E;
    const register unsigned short int TX9D = 0;
    sbit  TX9D_bit at TX1STA.B0;
    const register unsigned short int TRMT = 1;
    sbit  TRMT_bit at TX1STA.B1;
    const register unsigned short int BRGH = 2;
    sbit  BRGH_bit at TX1STA.B2;
    const register unsigned short int SENDB = 3;
    sbit  SENDB_bit at TX1STA.B3;
    const register unsigned short int SYNC = 4;
    sbit  SYNC_bit at TX1STA.B4;
    const register unsigned short int TXEN = 5;
    sbit  TXEN_bit at TX1STA.B5;
    const register unsigned short int TX9 = 6;
    sbit  TX9_bit at TX1STA.B6;
    const register unsigned short int CSRC = 7;
    sbit  CSRC_bit at TX1STA.B7;

sfr unsigned short volatile TXSTA1           absolute 0x19E;
sfr unsigned short volatile TXSTA            absolute 0x19E;
sfr unsigned short volatile BAUD1CON         absolute 0x19F;
    const register unsigned short int ABDEN = 0;
    sbit  ABDEN_bit at BAUD1CON.B0;
    const register unsigned short int WUE = 1;
    sbit  WUE_bit at BAUD1CON.B1;
    const register unsigned short int BRG16 = 3;
    sbit  BRG16_bit at BAUD1CON.B3;
    const register unsigned short int SCKP = 4;
    sbit  SCKP_bit at BAUD1CON.B4;
    const register unsigned short int RCIDL = 6;
    sbit  RCIDL_bit at BAUD1CON.B6;
    const register unsigned short int ABDOVF = 7;
    sbit  ABDOVF_bit at BAUD1CON.B7;

sfr unsigned short          BAUDCON1         absolute 0x19F;
sfr unsigned short          BAUDCTL1         absolute 0x19F;
sfr unsigned short          BAUDCON          absolute 0x19F;
sfr unsigned short          BAUDCTL          absolute 0x19F;
sfr unsigned short          WPUA             absolute 0x20C;
    const register unsigned short int WPUA0 = 0;
    sbit  WPUA0_bit at WPUA.B0;
    const register unsigned short int WPUA1 = 1;
    sbit  WPUA1_bit at WPUA.B1;
    const register unsigned short int WPUA2 = 2;
    sbit  WPUA2_bit at WPUA.B2;
    const register unsigned short int WPUA3 = 3;
    sbit  WPUA3_bit at WPUA.B3;
    const register unsigned short int WPUA4 = 4;
    sbit  WPUA4_bit at WPUA.B4;
    const register unsigned short int WPUA5 = 5;
    sbit  WPUA5_bit at WPUA.B5;

sfr unsigned short volatile SSP1BUF          absolute 0x211;
    const register unsigned short int BUF0 = 0;
    sbit  BUF0_bit at SSP1BUF.B0;
    const register unsigned short int BUF1 = 1;
    sbit  BUF1_bit at SSP1BUF.B1;
    const register unsigned short int BUF2 = 2;
    sbit  BUF2_bit at SSP1BUF.B2;
    const register unsigned short int BUF3 = 3;
    sbit  BUF3_bit at SSP1BUF.B3;
    const register unsigned short int BUF4 = 4;
    sbit  BUF4_bit at SSP1BUF.B4;
    const register unsigned short int BUF5 = 5;
    sbit  BUF5_bit at SSP1BUF.B5;
    const register unsigned short int BUF6 = 6;
    sbit  BUF6_bit at SSP1BUF.B6;
    const register unsigned short int BUF7 = 7;
    sbit  BUF7_bit at SSP1BUF.B7;
    const register unsigned short int SSP1BUF0 = 0;
    sbit  SSP1BUF0_bit at SSP1BUF.B0;
    const register unsigned short int SSP1BUF1 = 1;
    sbit  SSP1BUF1_bit at SSP1BUF.B1;
    const register unsigned short int SSP1BUF2 = 2;
    sbit  SSP1BUF2_bit at SSP1BUF.B2;
    const register unsigned short int SSP1BUF3 = 3;
    sbit  SSP1BUF3_bit at SSP1BUF.B3;
    const register unsigned short int SSP1BUF4 = 4;
    sbit  SSP1BUF4_bit at SSP1BUF.B4;
    const register unsigned short int SSP1BUF5 = 5;
    sbit  SSP1BUF5_bit at SSP1BUF.B5;
    const register unsigned short int SSP1BUF6 = 6;
    sbit  SSP1BUF6_bit at SSP1BUF.B6;
    const register unsigned short int SSP1BUF7 = 7;
    sbit  SSP1BUF7_bit at SSP1BUF.B7;

sfr unsigned short volatile SSPBUF           absolute 0x211;
sfr unsigned short volatile SSP1ADD          absolute 0x212;
    const register unsigned short int ADD0 = 0;
    sbit  ADD0_bit at SSP1ADD.B0;
    const register unsigned short int ADD1 = 1;
    sbit  ADD1_bit at SSP1ADD.B1;
    const register unsigned short int ADD2 = 2;
    sbit  ADD2_bit at SSP1ADD.B2;
    const register unsigned short int ADD3 = 3;
    sbit  ADD3_bit at SSP1ADD.B3;
    const register unsigned short int ADD4 = 4;
    sbit  ADD4_bit at SSP1ADD.B4;
    const register unsigned short int ADD5 = 5;
    sbit  ADD5_bit at SSP1ADD.B5;
    const register unsigned short int ADD6 = 6;
    sbit  ADD6_bit at SSP1ADD.B6;
    const register unsigned short int ADD7 = 7;
    sbit  ADD7_bit at SSP1ADD.B7;
    const register unsigned short int SSP1ADD0 = 0;
    sbit  SSP1ADD0_bit at SSP1ADD.B0;
    const register unsigned short int SSP1ADD1 = 1;
    sbit  SSP1ADD1_bit at SSP1ADD.B1;
    const register unsigned short int SSP1ADD2 = 2;
    sbit  SSP1ADD2_bit at SSP1ADD.B2;
    const register unsigned short int SSP1ADD3 = 3;
    sbit  SSP1ADD3_bit at SSP1ADD.B3;
    const register unsigned short int SSP1ADD4 = 4;
    sbit  SSP1ADD4_bit at SSP1ADD.B4;
    const register unsigned short int SSP1ADD5 = 5;
    sbit  SSP1ADD5_bit at SSP1ADD.B5;
    const register unsigned short int SSP1ADD6 = 6;
    sbit  SSP1ADD6_bit at SSP1ADD.B6;
    const register unsigned short int SSP1ADD7 = 7;
    sbit  SSP1ADD7_bit at SSP1ADD.B7;

sfr unsigned short volatile SSPADD           absolute 0x212;
sfr unsigned short volatile SSP1MSK          absolute 0x213;
    const register unsigned short int MSK0 = 0;
    sbit  MSK0_bit at SSP1MSK.B0;
    const register unsigned short int MSK1 = 1;
    sbit  MSK1_bit at SSP1MSK.B1;
    const register unsigned short int MSK2 = 2;
    sbit  MSK2_bit at SSP1MSK.B2;
    const register unsigned short int MSK3 = 3;
    sbit  MSK3_bit at SSP1MSK.B3;
    const register unsigned short int MSK4 = 4;
    sbit  MSK4_bit at SSP1MSK.B4;
    const register unsigned short int MSK5 = 5;
    sbit  MSK5_bit at SSP1MSK.B5;
    const register unsigned short int MSK6 = 6;
    sbit  MSK6_bit at SSP1MSK.B6;
    const register unsigned short int MSK7 = 7;
    sbit  MSK7_bit at SSP1MSK.B7;
    const register unsigned short int SSP1MSK0 = 0;
    sbit  SSP1MSK0_bit at SSP1MSK.B0;
    const register unsigned short int SSP1MSK1 = 1;
    sbit  SSP1MSK1_bit at SSP1MSK.B1;
    const register unsigned short int SSP1MSK2 = 2;
    sbit  SSP1MSK2_bit at SSP1MSK.B2;
    const register unsigned short int SSP1MSK3 = 3;
    sbit  SSP1MSK3_bit at SSP1MSK.B3;
    const register unsigned short int SSP1MSK4 = 4;
    sbit  SSP1MSK4_bit at SSP1MSK.B4;
    const register unsigned short int SSP1MSK5 = 5;
    sbit  SSP1MSK5_bit at SSP1MSK.B5;
    const register unsigned short int SSP1MSK6 = 6;
    sbit  SSP1MSK6_bit at SSP1MSK.B6;
    const register unsigned short int SSP1MSK7 = 7;
    sbit  SSP1MSK7_bit at SSP1MSK.B7;

sfr unsigned short volatile SSPMSK           absolute 0x213;
sfr unsigned short volatile SSP1STAT         absolute 0x214;
    const register unsigned short int BF = 0;
    sbit  BF_bit at SSP1STAT.B0;
    const register unsigned short int UA = 1;
    sbit  UA_bit at SSP1STAT.B1;
    const register unsigned short int R_nW = 2;
    sbit  R_nW_bit at SSP1STAT.B2;
    const register unsigned short int D_nA = 5;
    sbit  D_nA_bit at SSP1STAT.B5;
    const register unsigned short int CKE = 6;
    sbit  CKE_bit at SSP1STAT.B6;
    const register unsigned short int SMP = 7;
    sbit  SMP_bit at SSP1STAT.B7;

sfr unsigned short volatile SSPSTAT          absolute 0x214;
sfr unsigned short volatile SSP1CON1         absolute 0x215;
    const register unsigned short int SSPM0 = 0;
    sbit  SSPM0_bit at SSP1CON1.B0;
    const register unsigned short int SSPM1 = 1;
    sbit  SSPM1_bit at SSP1CON1.B1;
    const register unsigned short int SSPM2 = 2;
    sbit  SSPM2_bit at SSP1CON1.B2;
    const register unsigned short int SSPM3 = 3;
    sbit  SSPM3_bit at SSP1CON1.B3;
    const register unsigned short int CKP = 4;
    sbit  CKP_bit at SSP1CON1.B4;
    const register unsigned short int SSPEN = 5;
    sbit  SSPEN_bit at SSP1CON1.B5;
    const register unsigned short int SSPOV = 6;
    sbit  SSPOV_bit at SSP1CON1.B6;
    const register unsigned short int WCOL = 7;
    sbit  WCOL_bit at SSP1CON1.B7;

sfr unsigned short volatile SSPCON           absolute 0x215;
sfr unsigned short volatile SSPCON1          absolute 0x215;
sfr unsigned short volatile SSP1CON          absolute 0x215;
sfr unsigned short volatile SSP1CON2         absolute 0x216;
    const register unsigned short int SEN = 0;
    sbit  SEN_bit at SSP1CON2.B0;
    const register unsigned short int RSEN = 1;
    sbit  RSEN_bit at SSP1CON2.B1;
    const register unsigned short int PEN = 2;
    sbit  PEN_bit at SSP1CON2.B2;
    const register unsigned short int RCEN = 3;
    sbit  RCEN_bit at SSP1CON2.B3;
    const register unsigned short int ACKEN = 4;
    sbit  ACKEN_bit at SSP1CON2.B4;
    const register unsigned short int ACKDT = 5;
    sbit  ACKDT_bit at SSP1CON2.B5;
    const register unsigned short int ACKSTAT = 6;
    sbit  ACKSTAT_bit at SSP1CON2.B6;
    const register unsigned short int GCEN = 7;
    sbit  GCEN_bit at SSP1CON2.B7;

sfr unsigned short volatile SSPCON2          absolute 0x216;
sfr unsigned short volatile SSP1CON3         absolute 0x217;
    const register unsigned short int DHEN = 0;
    sbit  DHEN_bit at SSP1CON3.B0;
    const register unsigned short int AHEN = 1;
    sbit  AHEN_bit at SSP1CON3.B1;
    const register unsigned short int SBCDE = 2;
    sbit  SBCDE_bit at SSP1CON3.B2;
    const register unsigned short int SDAHT = 3;
    sbit  SDAHT_bit at SSP1CON3.B3;
    const register unsigned short int BOEN = 4;
    sbit  BOEN_bit at SSP1CON3.B4;
    const register unsigned short int SCIE = 5;
    sbit  SCIE_bit at SSP1CON3.B5;
    const register unsigned short int PCIE = 6;
    sbit  PCIE_bit at SSP1CON3.B6;
    const register unsigned short int ACKTIM = 7;
    sbit  ACKTIM_bit at SSP1CON3.B7;

sfr unsigned short volatile SSPCON3          absolute 0x217;
sfr unsigned short volatile ODCONA           absolute 0x28C;
    const register unsigned short int ODCA0 = 0;
    sbit  ODCA0_bit at ODCONA.B0;
    const register unsigned short int ODCA1 = 1;
    sbit  ODCA1_bit at ODCONA.B1;
    const register unsigned short int ODCA2 = 2;
    sbit  ODCA2_bit at ODCONA.B2;
    const register unsigned short int ODCA4 = 4;
    sbit  ODCA4_bit at ODCONA.B4;
    const register unsigned short int ODCA5 = 5;
    sbit  ODCA5_bit at ODCONA.B5;

sfr unsigned int   volatile CCPR1            absolute 0x291;
sfr unsigned short volatile CCPR1L           absolute 0x291;
sfr unsigned short volatile CCPR1H           absolute 0x292;
sfr unsigned short volatile CCP1CON          absolute 0x293;
    const register unsigned short int CCP1MODE0 = 0;
    sbit  CCP1MODE0_bit at CCP1CON.B0;
    const register unsigned short int CCP1MODE1 = 1;
    sbit  CCP1MODE1_bit at CCP1CON.B1;
    const register unsigned short int CCP1MODE2 = 2;
    sbit  CCP1MODE2_bit at CCP1CON.B2;
    const register unsigned short int CCP1MODE3 = 3;
    sbit  CCP1MODE3_bit at CCP1CON.B3;
    const register unsigned short int CCP1FMT = 4;
    sbit  CCP1FMT_bit at CCP1CON.B4;
    const register unsigned short int CCP1OUT = 5;
    sbit  CCP1OUT_bit at CCP1CON.B5;
    const register unsigned short int CCP1EN = 7;
    sbit  CCP1EN_bit at CCP1CON.B7;

sfr unsigned short volatile CCP1CAP          absolute 0x294;
    const register unsigned short int CCP1CTS0 = 0;
    sbit  CCP1CTS0_bit at CCP1CAP.B0;
    const register unsigned short int CCP1CTS1 = 1;
    sbit  CCP1CTS1_bit at CCP1CAP.B1;
    const register unsigned short int CCP1CTS2 = 2;
    sbit  CCP1CTS2_bit at CCP1CAP.B2;

sfr unsigned int   volatile CCPR2            absolute 0x295;
sfr unsigned short volatile CCPR2L           absolute 0x295;
sfr unsigned short volatile CCPR2H           absolute 0x296;
sfr unsigned short volatile CCP2CON          absolute 0x297;
    const register unsigned short int CCP2MODE0 = 0;
    sbit  CCP2MODE0_bit at CCP2CON.B0;
    const register unsigned short int CCP2MODE1 = 1;
    sbit  CCP2MODE1_bit at CCP2CON.B1;
    const register unsigned short int CCP2MODE2 = 2;
    sbit  CCP2MODE2_bit at CCP2CON.B2;
    const register unsigned short int CCP2MODE3 = 3;
    sbit  CCP2MODE3_bit at CCP2CON.B3;
    const register unsigned short int CCP2FMT = 4;
    sbit  CCP2FMT_bit at CCP2CON.B4;
    const register unsigned short int CCP2OUT = 5;
    sbit  CCP2OUT_bit at CCP2CON.B5;
    const register unsigned short int CCP2EN = 7;
    sbit  CCP2EN_bit at CCP2CON.B7;

sfr unsigned short volatile CCP2CAP          absolute 0x298;
    const register unsigned short int CCP2CTS0 = 0;
    sbit  CCP2CTS0_bit at CCP2CAP.B0;
    const register unsigned short int CCP2CTS1 = 1;
    sbit  CCP2CTS1_bit at CCP2CAP.B1;
    const register unsigned short int CCP2CTS2 = 2;
    sbit  CCP2CTS2_bit at CCP2CAP.B2;

sfr unsigned short volatile SLRCONA          absolute 0x30C;
    const register unsigned short int SLRA0 = 0;
    sbit  SLRA0_bit at SLRCONA.B0;
    const register unsigned short int SLRA1 = 1;
    sbit  SLRA1_bit at SLRCONA.B1;
    const register unsigned short int SLRA2 = 2;
    sbit  SLRA2_bit at SLRCONA.B2;
    const register unsigned short int SLRA4 = 4;
    sbit  SLRA4_bit at SLRCONA.B4;
    const register unsigned short int SLRA5 = 5;
    sbit  SLRA5_bit at SLRCONA.B5;

sfr unsigned short volatile INLVLA           absolute 0x38C;
    const register unsigned short int INLVLA0 = 0;
    sbit  INLVLA0_bit at INLVLA.B0;
    const register unsigned short int INLVLA1 = 1;
    sbit  INLVLA1_bit at INLVLA.B1;
    const register unsigned short int INLVLA2 = 2;
    sbit  INLVLA2_bit at INLVLA.B2;
    const register unsigned short int INLVLA3 = 3;
    sbit  INLVLA3_bit at INLVLA.B3;
    const register unsigned short int INLVLA4 = 4;
    sbit  INLVLA4_bit at INLVLA.B4;
    const register unsigned short int INLVLA5 = 5;
    sbit  INLVLA5_bit at INLVLA.B5;

sfr unsigned short volatile IOCAP            absolute 0x391;
    const register unsigned short int IOCAP0 = 0;
    sbit  IOCAP0_bit at IOCAP.B0;
    const register unsigned short int IOCAP1 = 1;
    sbit  IOCAP1_bit at IOCAP.B1;
    const register unsigned short int IOCAP2 = 2;
    sbit  IOCAP2_bit at IOCAP.B2;
    const register unsigned short int IOCAP3 = 3;
    sbit  IOCAP3_bit at IOCAP.B3;
    const register unsigned short int IOCAP4 = 4;
    sbit  IOCAP4_bit at IOCAP.B4;
    const register unsigned short int IOCAP5 = 5;
    sbit  IOCAP5_bit at IOCAP.B5;

sfr unsigned short volatile IOCAN            absolute 0x392;
    const register unsigned short int IOCAN0 = 0;
    sbit  IOCAN0_bit at IOCAN.B0;
    const register unsigned short int IOCAN1 = 1;
    sbit  IOCAN1_bit at IOCAN.B1;
    const register unsigned short int IOCAN2 = 2;
    sbit  IOCAN2_bit at IOCAN.B2;
    const register unsigned short int IOCAN3 = 3;
    sbit  IOCAN3_bit at IOCAN.B3;
    const register unsigned short int IOCAN4 = 4;
    sbit  IOCAN4_bit at IOCAN.B4;
    const register unsigned short int IOCAN5 = 5;
    sbit  IOCAN5_bit at IOCAN.B5;

sfr unsigned short volatile IOCAF            absolute 0x393;
    const register unsigned short int IOCAF0 = 0;
    sbit  IOCAF0_bit at IOCAF.B0;
    const register unsigned short int IOCAF1 = 1;
    sbit  IOCAF1_bit at IOCAF.B1;
    const register unsigned short int IOCAF2 = 2;
    sbit  IOCAF2_bit at IOCAF.B2;
    const register unsigned short int IOCAF3 = 3;
    sbit  IOCAF3_bit at IOCAF.B3;
    const register unsigned short int IOCAF4 = 4;
    sbit  IOCAF4_bit at IOCAF.B4;
    const register unsigned short int IOCAF5 = 5;
    sbit  IOCAF5_bit at IOCAF.B5;

sfr unsigned short volatile CLKRCON          absolute 0x39A;
    const register unsigned short int CLKRDIV0 = 0;
    sbit  CLKRDIV0_bit at CLKRCON.B0;
    const register unsigned short int CLKRDIV1 = 1;
    sbit  CLKRDIV1_bit at CLKRCON.B1;
    const register unsigned short int CLKRDIV2 = 2;
    sbit  CLKRDIV2_bit at CLKRCON.B2;
    const register unsigned short int CLKRDC0 = 3;
    sbit  CLKRDC0_bit at CLKRCON.B3;
    const register unsigned short int CLKRDC1 = 4;
    sbit  CLKRDC1_bit at CLKRCON.B4;
    const register unsigned short int CLKREN = 7;
    sbit  CLKREN_bit at CLKRCON.B7;

sfr unsigned short volatile MDCON            absolute 0x39C;
    const register unsigned short int MDBIT = 0;
    sbit  MDBIT_bit at MDCON.B0;
    const register unsigned short int MDOUT = 3;
    sbit  MDOUT_bit at MDCON.B3;
    const register unsigned short int MDOPOL = 4;
    sbit  MDOPOL_bit at MDCON.B4;
    const register unsigned short int MDEN = 7;
    sbit  MDEN_bit at MDCON.B7;

sfr unsigned short volatile MDSRC            absolute 0x39D;
    const register unsigned short int MDMS0 = 0;
    sbit  MDMS0_bit at MDSRC.B0;
    const register unsigned short int MDMS1 = 1;
    sbit  MDMS1_bit at MDSRC.B1;
    const register unsigned short int MDMS2 = 2;
    sbit  MDMS2_bit at MDSRC.B2;
    const register unsigned short int MDMS3 = 3;
    sbit  MDMS3_bit at MDSRC.B3;

sfr unsigned short volatile MDCARH           absolute 0x39E;
    const register unsigned short int MDCH0 = 0;
    sbit  MDCH0_bit at MDCARH.B0;
    const register unsigned short int MDCH1 = 1;
    sbit  MDCH1_bit at MDCARH.B1;
    const register unsigned short int MDCH2 = 2;
    sbit  MDCH2_bit at MDCARH.B2;
    const register unsigned short int MDCH3 = 3;
    sbit  MDCH3_bit at MDCARH.B3;
    const register unsigned short int MDCHSYNC = 5;
    sbit  MDCHSYNC_bit at MDCARH.B5;
    const register unsigned short int MDCHPOL = 6;
    sbit  MDCHPOL_bit at MDCARH.B6;

sfr unsigned short volatile MDCARL           absolute 0x39F;
    const register unsigned short int MDCL0 = 0;
    sbit  MDCL0_bit at MDCARL.B0;
    const register unsigned short int MDCL1 = 1;
    sbit  MDCL1_bit at MDCARL.B1;
    const register unsigned short int MDCL2 = 2;
    sbit  MDCL2_bit at MDCARL.B2;
    const register unsigned short int MDCL3 = 3;
    sbit  MDCL3_bit at MDCARL.B3;
    const register unsigned short int MDCLSYNC = 5;
    sbit  MDCLSYNC_bit at MDCARL.B5;
    const register unsigned short int MDCLPOL = 6;
    sbit  MDCLPOL_bit at MDCARL.B6;

sfr unsigned short volatile NCO1ACCL         absolute 0x498;
sfr unsigned short volatile NCO1ACCH         absolute 0x499;
sfr unsigned short volatile NCO1ACCU         absolute 0x49A;
sfr unsigned short volatile NCO1INCL         absolute 0x49B;
sfr unsigned short volatile NCO1INCH         absolute 0x49C;
sfr unsigned short volatile NCO1INCU         absolute 0x49D;
sfr unsigned short volatile NCO1CON          absolute 0x49E;
    const register unsigned short int N1PFM = 0;
    sbit  N1PFM_bit at NCO1CON.B0;
    const register unsigned short int N1POL = 4;
    sbit  N1POL_bit at NCO1CON.B4;
    const register unsigned short int N1OUT = 5;
    sbit  N1OUT_bit at NCO1CON.B5;
    const register unsigned short int N1EN = 7;
    sbit  N1EN_bit at NCO1CON.B7;

sfr unsigned short volatile NCO1CLK          absolute 0x49F;
sfr unsigned short volatile PWM5DCL          absolute 0x617;
    const register unsigned short int PWM5DCL0 = 6;
    sbit  PWM5DCL0_bit at PWM5DCL.B6;
    const register unsigned short int PWM5DCL1 = 7;
    sbit  PWM5DCL1_bit at PWM5DCL.B7;

sfr unsigned short volatile PWM5DCH          absolute 0x618;
    const register unsigned short int PWM5DCH0 = 0;
    sbit  PWM5DCH0_bit at PWM5DCH.B0;
    const register unsigned short int PWM5DCH1 = 1;
    sbit  PWM5DCH1_bit at PWM5DCH.B1;
    const register unsigned short int PWM5DCH2 = 2;
    sbit  PWM5DCH2_bit at PWM5DCH.B2;
    const register unsigned short int PWM5DCH3 = 3;
    sbit  PWM5DCH3_bit at PWM5DCH.B3;
    const register unsigned short int PWM5DCH4 = 4;
    sbit  PWM5DCH4_bit at PWM5DCH.B4;
    const register unsigned short int PWM5DCH5 = 5;
    sbit  PWM5DCH5_bit at PWM5DCH.B5;
    const register unsigned short int PWM5DCH6 = 6;
    sbit  PWM5DCH6_bit at PWM5DCH.B6;
    const register unsigned short int PWM5DCH7 = 7;
    sbit  PWM5DCH7_bit at PWM5DCH.B7;

sfr unsigned short volatile PWM5CON          absolute 0x619;
    const register unsigned short int PWM5POL = 4;
    sbit  PWM5POL_bit at PWM5CON.B4;
    const register unsigned short int PWM5OUT = 5;
    sbit  PWM5OUT_bit at PWM5CON.B5;
    const register unsigned short int PWM5EN = 7;
    sbit  PWM5EN_bit at PWM5CON.B7;

sfr unsigned short volatile PWM5CON0         absolute 0x619;
sfr unsigned short volatile PWM6DCL          absolute 0x61A;
    const register unsigned short int PWM6DCL0 = 6;
    sbit  PWM6DCL0_bit at PWM6DCL.B6;
    const register unsigned short int PWM6DCL1 = 7;
    sbit  PWM6DCL1_bit at PWM6DCL.B7;

sfr unsigned short volatile PWM6DCH          absolute 0x61B;
    const register unsigned short int PWM6DCH0 = 0;
    sbit  PWM6DCH0_bit at PWM6DCH.B0;
    const register unsigned short int PWM6DCH1 = 1;
    sbit  PWM6DCH1_bit at PWM6DCH.B1;
    const register unsigned short int PWM6DCH2 = 2;
    sbit  PWM6DCH2_bit at PWM6DCH.B2;
    const register unsigned short int PWM6DCH3 = 3;
    sbit  PWM6DCH3_bit at PWM6DCH.B3;
    const register unsigned short int PWM6DCH4 = 4;
    sbit  PWM6DCH4_bit at PWM6DCH.B4;
    const register unsigned short int PWM6DCH5 = 5;
    sbit  PWM6DCH5_bit at PWM6DCH.B5;
    const register unsigned short int PWM6DCH6 = 6;
    sbit  PWM6DCH6_bit at PWM6DCH.B6;
    const register unsigned short int PWM6DCH7 = 7;
    sbit  PWM6DCH7_bit at PWM6DCH.B7;

sfr unsigned short volatile PWM6CON          absolute 0x61C;
    const register unsigned short int PWM6POL = 4;
    sbit  PWM6POL_bit at PWM6CON.B4;
    const register unsigned short int PWM6OUT = 5;
    sbit  PWM6OUT_bit at PWM6CON.B5;
    const register unsigned short int PWM6EN = 7;
    sbit  PWM6EN_bit at PWM6CON.B7;

sfr unsigned short volatile PWM6CON0         absolute 0x61C;
sfr unsigned short volatile CWG1CLKCON       absolute 0x691;
    const register unsigned short int CS = 0;
    sbit  CS_bit at CWG1CLKCON.B0;
    const register unsigned short int CWG1CS = 0;
    sbit  CWG1CS_bit at CWG1CLKCON.B0;

sfr unsigned short volatile CWG1DAT          absolute 0x692;
    const register unsigned short int CWG1DAT0 = 0;
    sbit  CWG1DAT0_bit at CWG1DAT.B0;
    const register unsigned short int CWG1DAT1 = 1;
    sbit  CWG1DAT1_bit at CWG1DAT.B1;
    const register unsigned short int CWG1DAT2 = 2;
    sbit  CWG1DAT2_bit at CWG1DAT.B2;
    const register unsigned short int CWG1DAT3 = 3;
    sbit  CWG1DAT3_bit at CWG1DAT.B3;

sfr unsigned short volatile CWG1DBR          absolute 0x693;
    const register unsigned short int CWG1DBR0 = 0;
    sbit  CWG1DBR0_bit at CWG1DBR.B0;
    const register unsigned short int CWG1DBR1 = 1;
    sbit  CWG1DBR1_bit at CWG1DBR.B1;
    const register unsigned short int CWG1DBR2 = 2;
    sbit  CWG1DBR2_bit at CWG1DBR.B2;
    const register unsigned short int CWG1DBR3 = 3;
    sbit  CWG1DBR3_bit at CWG1DBR.B3;
    const register unsigned short int CWG1DBR4 = 4;
    sbit  CWG1DBR4_bit at CWG1DBR.B4;
    const register unsigned short int CWG1DBR5 = 5;
    sbit  CWG1DBR5_bit at CWG1DBR.B5;
    const register unsigned short int DBR0 = 0;
    sbit  DBR0_bit at CWG1DBR.B0;
    const register unsigned short int DBR1 = 1;
    sbit  DBR1_bit at CWG1DBR.B1;
    const register unsigned short int DBR2 = 2;
    sbit  DBR2_bit at CWG1DBR.B2;
    const register unsigned short int DBR3 = 3;
    sbit  DBR3_bit at CWG1DBR.B3;
    const register unsigned short int DBR4 = 4;
    sbit  DBR4_bit at CWG1DBR.B4;
    const register unsigned short int DBR5 = 5;
    sbit  DBR5_bit at CWG1DBR.B5;

sfr unsigned short volatile CWG1DBF          absolute 0x694;
    const register unsigned short int CWG1DBF0 = 0;
    sbit  CWG1DBF0_bit at CWG1DBF.B0;
    const register unsigned short int CWG1DBF1 = 1;
    sbit  CWG1DBF1_bit at CWG1DBF.B1;
    const register unsigned short int CWG1DBF2 = 2;
    sbit  CWG1DBF2_bit at CWG1DBF.B2;
    const register unsigned short int CWG1DBF3 = 3;
    sbit  CWG1DBF3_bit at CWG1DBF.B3;
    const register unsigned short int CWG1DBF4 = 4;
    sbit  CWG1DBF4_bit at CWG1DBF.B4;
    const register unsigned short int CWG1DBF5 = 5;
    sbit  CWG1DBF5_bit at CWG1DBF.B5;
    const register unsigned short int DBF0 = 0;
    sbit  DBF0_bit at CWG1DBF.B0;
    const register unsigned short int DBF1 = 1;
    sbit  DBF1_bit at CWG1DBF.B1;
    const register unsigned short int DBF2 = 2;
    sbit  DBF2_bit at CWG1DBF.B2;
    const register unsigned short int DBF3 = 3;
    sbit  DBF3_bit at CWG1DBF.B3;
    const register unsigned short int DBF4 = 4;
    sbit  DBF4_bit at CWG1DBF.B4;
    const register unsigned short int DBF5 = 5;
    sbit  DBF5_bit at CWG1DBF.B5;

sfr unsigned short volatile CWG1CON0         absolute 0x695;
    const register unsigned short int CWG1MODE0 = 0;
    sbit  CWG1MODE0_bit at CWG1CON0.B0;
    const register unsigned short int CWG1MODE1 = 1;
    sbit  CWG1MODE1_bit at CWG1CON0.B1;
    const register unsigned short int CWG1MODE2 = 2;
    sbit  CWG1MODE2_bit at CWG1CON0.B2;
    const register unsigned short int CWG1LD = 6;
    sbit  CWG1LD_bit at CWG1CON0.B6;
    const register unsigned short int CWG1EN = 7;
    sbit  CWG1EN_bit at CWG1CON0.B7;
    const register unsigned short int G1EN = 7;
    sbit  G1EN_bit at CWG1CON0.B7;
    const register unsigned short int LD = 6;
    sbit  LD_bit at CWG1CON0.B6;

sfr unsigned short volatile CWG1CON1         absolute 0x696;
    const register unsigned short int CWG1POLA = 0;
    sbit  CWG1POLA_bit at CWG1CON1.B0;
    const register unsigned short int CWG1POLB = 1;
    sbit  CWG1POLB_bit at CWG1CON1.B1;
    const register unsigned short int CWG1POLC = 2;
    sbit  CWG1POLC_bit at CWG1CON1.B2;
    const register unsigned short int CWG1POLD = 3;
    sbit  CWG1POLD_bit at CWG1CON1.B3;
    const register unsigned short int CWG1IN = 5;
    sbit  CWG1IN_bit at CWG1CON1.B5;
    const register unsigned short int IN_ = 5;
    sbit  IN_bit at CWG1CON1.B5;
    const register unsigned short int POLA = 0;
    sbit  POLA_bit at CWG1CON1.B0;
    const register unsigned short int POLB = 1;
    sbit  POLB_bit at CWG1CON1.B1;
    const register unsigned short int POLC = 2;
    sbit  POLC_bit at CWG1CON1.B2;
    const register unsigned short int POLD = 3;
    sbit  POLD_bit at CWG1CON1.B3;

sfr unsigned short volatile CWG1AS0          absolute 0x697;
    const register unsigned short int CWG1LSAC0 = 2;
    sbit  CWG1LSAC0_bit at CWG1AS0.B2;
    const register unsigned short int CWG1LSAC1 = 3;
    sbit  CWG1LSAC1_bit at CWG1AS0.B3;
    const register unsigned short int CWG1LSBD0 = 4;
    sbit  CWG1LSBD0_bit at CWG1AS0.B4;
    const register unsigned short int CWG1LSBD1 = 5;
    sbit  CWG1LSBD1_bit at CWG1AS0.B5;
    const register unsigned short int CWG1REN = 6;
    sbit  CWG1REN_bit at CWG1AS0.B6;
    const register unsigned short int CWG1SHUTDOWN = 7;
    sbit  CWG1SHUTDOWN_bit at CWG1AS0.B7;
    const register unsigned short int LSAC0 = 2;
    sbit  LSAC0_bit at CWG1AS0.B2;
    const register unsigned short int LSAC1 = 3;
    sbit  LSAC1_bit at CWG1AS0.B3;
    const register unsigned short int LSBD0 = 4;
    sbit  LSBD0_bit at CWG1AS0.B4;
    const register unsigned short int LSBD1 = 5;
    sbit  LSBD1_bit at CWG1AS0.B5;
    const register unsigned short int REN = 6;
    sbit  REN_bit at CWG1AS0.B6;
    const register unsigned short int SHUTDOWN = 7;
    sbit  SHUTDOWN_bit at CWG1AS0.B7;

sfr unsigned short volatile CWG1AS1          absolute 0x698;
    const register unsigned short int AS0E = 0;
    sbit  AS0E_bit at CWG1AS1.B0;
    const register unsigned short int AS1E = 1;
    sbit  AS1E_bit at CWG1AS1.B1;
    const register unsigned short int AS3E = 3;
    sbit  AS3E_bit at CWG1AS1.B3;

sfr unsigned short volatile CWG1STR          absolute 0x699;
    const register unsigned short int CWG1STRA = 0;
    sbit  CWG1STRA_bit at CWG1STR.B0;
    const register unsigned short int CWG1STRB = 1;
    sbit  CWG1STRB_bit at CWG1STR.B1;
    const register unsigned short int CWG1STRC = 2;
    sbit  CWG1STRC_bit at CWG1STR.B2;
    const register unsigned short int CWG1STRD = 3;
    sbit  CWG1STRD_bit at CWG1STR.B3;
    const register unsigned short int CWG1OVRA = 4;
    sbit  CWG1OVRA_bit at CWG1STR.B4;
    const register unsigned short int CWG1OVRB = 5;
    sbit  CWG1OVRB_bit at CWG1STR.B5;
    const register unsigned short int CWG1OVRC = 6;
    sbit  CWG1OVRC_bit at CWG1STR.B6;
    const register unsigned short int CWG1OVRD = 7;
    sbit  CWG1OVRD_bit at CWG1STR.B7;
    const register unsigned short int OVRA = 4;
    sbit  OVRA_bit at CWG1STR.B4;
    const register unsigned short int OVRB = 5;
    sbit  OVRB_bit at CWG1STR.B5;
    const register unsigned short int OVRC = 6;
    sbit  OVRC_bit at CWG1STR.B6;
    const register unsigned short int OVRD = 7;
    sbit  OVRD_bit at CWG1STR.B7;
    const register unsigned short int STRA = 0;
    sbit  STRA_bit at CWG1STR.B0;
    const register unsigned short int STRB = 1;
    sbit  STRB_bit at CWG1STR.B1;
    const register unsigned short int STRC = 2;
    sbit  STRC_bit at CWG1STR.B2;
    const register unsigned short int STRD = 3;
    sbit  STRD_bit at CWG1STR.B3;

sfr unsigned int   volatile NVMADR           absolute 0x891;
sfr unsigned int   volatile EEADR            absolute 0x891;
sfr unsigned int   volatile PMADR            absolute 0x891;
sfr unsigned short volatile NVMADRL          absolute 0x891;
    const register unsigned short int EEADR0 = 0;
    sbit  EEADR0_bit at NVMADRL.B0;
    const register unsigned short int EEADR1 = 1;
    sbit  EEADR1_bit at NVMADRL.B1;
    const register unsigned short int EEADR2 = 2;
    sbit  EEADR2_bit at NVMADRL.B2;
    const register unsigned short int EEADR3 = 3;
    sbit  EEADR3_bit at NVMADRL.B3;
    const register unsigned short int EEADR4 = 4;
    sbit  EEADR4_bit at NVMADRL.B4;
    const register unsigned short int EEADR5 = 5;
    sbit  EEADR5_bit at NVMADRL.B5;
    const register unsigned short int EEADR6 = 6;
    sbit  EEADR6_bit at NVMADRL.B6;
    const register unsigned short int EEADR7 = 7;
    sbit  EEADR7_bit at NVMADRL.B7;
    const register unsigned short int NVMADR0 = 0;
    sbit  NVMADR0_bit at NVMADRL.B0;
    const register unsigned short int NVMADR1 = 1;
    sbit  NVMADR1_bit at NVMADRL.B1;
    const register unsigned short int NVMADR2 = 2;
    sbit  NVMADR2_bit at NVMADRL.B2;
    const register unsigned short int NVMADR3 = 3;
    sbit  NVMADR3_bit at NVMADRL.B3;
    const register unsigned short int NVMADR4 = 4;
    sbit  NVMADR4_bit at NVMADRL.B4;
    const register unsigned short int NVMADR5 = 5;
    sbit  NVMADR5_bit at NVMADRL.B5;
    const register unsigned short int NVMADR6 = 6;
    sbit  NVMADR6_bit at NVMADRL.B6;
    const register unsigned short int NVMADR7 = 7;
    sbit  NVMADR7_bit at NVMADRL.B7;

sfr unsigned short volatile EEADRL           absolute 0x891;
sfr unsigned short volatile PMADRL           absolute 0x891;
sfr unsigned short volatile NVMADRH          absolute 0x892;
    const register unsigned short int EEADR8 = 0;
    sbit  EEADR8_bit at NVMADRH.B0;
    const register unsigned short int EEADR9 = 1;
    sbit  EEADR9_bit at NVMADRH.B1;
    const register unsigned short int EEADR10 = 2;
    sbit  EEADR10_bit at NVMADRH.B2;
    const register unsigned short int EEADR11 = 3;
    sbit  EEADR11_bit at NVMADRH.B3;
    const register unsigned short int EEADR12 = 4;
    sbit  EEADR12_bit at NVMADRH.B4;
    const register unsigned short int EEADR13 = 5;
    sbit  EEADR13_bit at NVMADRH.B5;
    const register unsigned short int NVMADR14 = 6;
    sbit  NVMADR14_bit at NVMADRH.B6;
    const register unsigned short int NVMADR10 = 2;
    sbit  NVMADR10_bit at NVMADRH.B2;
    const register unsigned short int NVMADR11 = 3;
    sbit  NVMADR11_bit at NVMADRH.B3;
    const register unsigned short int NVMADR12 = 4;
    sbit  NVMADR12_bit at NVMADRH.B4;
    const register unsigned short int NVMADR13 = 5;
    sbit  NVMADR13_bit at NVMADRH.B5;
    const register unsigned short int NVMADR8 = 0;
    sbit  NVMADR8_bit at NVMADRH.B0;
    const register unsigned short int NVMADR9 = 1;
    sbit  NVMADR9_bit at NVMADRH.B1;

sfr unsigned short volatile EEADRH           absolute 0x892;
sfr unsigned short volatile PMADRH           absolute 0x892;
sfr unsigned int   volatile NVMDAT           absolute 0x893;
sfr unsigned int   volatile EEDAT            absolute 0x893;
sfr unsigned int   volatile PMDAT            absolute 0x893;
sfr unsigned short volatile NVMDATL          absolute 0x893;
    const register unsigned short int EEDAT0 = 0;
    sbit  EEDAT0_bit at NVMDATL.B0;
    const register unsigned short int EEDAT1 = 1;
    sbit  EEDAT1_bit at NVMDATL.B1;
    const register unsigned short int EEDAT2 = 2;
    sbit  EEDAT2_bit at NVMDATL.B2;
    const register unsigned short int EEDAT3 = 3;
    sbit  EEDAT3_bit at NVMDATL.B3;
    const register unsigned short int EEDAT4 = 4;
    sbit  EEDAT4_bit at NVMDATL.B4;
    const register unsigned short int EEDAT5 = 5;
    sbit  EEDAT5_bit at NVMDATL.B5;
    const register unsigned short int EEDAT6 = 6;
    sbit  EEDAT6_bit at NVMDATL.B6;
    const register unsigned short int EEDAT7 = 7;
    sbit  EEDAT7_bit at NVMDATL.B7;
    const register unsigned short int NVMDAT0 = 0;
    sbit  NVMDAT0_bit at NVMDATL.B0;
    const register unsigned short int NVMDAT1 = 1;
    sbit  NVMDAT1_bit at NVMDATL.B1;
    const register unsigned short int NVMDAT2 = 2;
    sbit  NVMDAT2_bit at NVMDATL.B2;
    const register unsigned short int NVMDAT3 = 3;
    sbit  NVMDAT3_bit at NVMDATL.B3;
    const register unsigned short int NVMDAT4 = 4;
    sbit  NVMDAT4_bit at NVMDATL.B4;
    const register unsigned short int NVMDAT5 = 5;
    sbit  NVMDAT5_bit at NVMDATL.B5;
    const register unsigned short int NVMDAT6 = 6;
    sbit  NVMDAT6_bit at NVMDATL.B6;
    const register unsigned short int NVMDAT7 = 7;
    sbit  NVMDAT7_bit at NVMDATL.B7;

sfr unsigned short volatile EEDATL           absolute 0x893;
sfr unsigned short volatile PMDATL           absolute 0x893;
sfr unsigned short volatile NVMDATH          absolute 0x894;
    const register unsigned short int EEDAT8 = 0;
    sbit  EEDAT8_bit at NVMDATH.B0;
    const register unsigned short int EEDAT9 = 1;
    sbit  EEDAT9_bit at NVMDATH.B1;
    const register unsigned short int EEDAT10 = 2;
    sbit  EEDAT10_bit at NVMDATH.B2;
    const register unsigned short int EEDAT11 = 3;
    sbit  EEDAT11_bit at NVMDATH.B3;
    const register unsigned short int EEDAT12 = 4;
    sbit  EEDAT12_bit at NVMDATH.B4;
    const register unsigned short int EEDAT13 = 5;
    sbit  EEDAT13_bit at NVMDATH.B5;
    const register unsigned short int NVMDAT10 = 2;
    sbit  NVMDAT10_bit at NVMDATH.B2;
    const register unsigned short int NVMDAT11 = 3;
    sbit  NVMDAT11_bit at NVMDATH.B3;
    const register unsigned short int NVMDAT12 = 4;
    sbit  NVMDAT12_bit at NVMDATH.B4;
    const register unsigned short int NVMDAT13 = 5;
    sbit  NVMDAT13_bit at NVMDATH.B5;
    const register unsigned short int NVMDAT8 = 0;
    sbit  NVMDAT8_bit at NVMDATH.B0;
    const register unsigned short int NVMDAT9 = 1;
    sbit  NVMDAT9_bit at NVMDATH.B1;

sfr unsigned short volatile EEDATH           absolute 0x894;
sfr unsigned short volatile PMDATH           absolute 0x894;
sfr unsigned short volatile NVMCON1          absolute 0x895;
    const register unsigned short int RD = 0;
    sbit  RD_bit at NVMCON1.B0;
    const register unsigned short int WR = 1;
    sbit  WR_bit at NVMCON1.B1;
    const register unsigned short int WREN = 2;
    sbit  WREN_bit at NVMCON1.B2;
    const register unsigned short int WRERR = 3;
    sbit  WRERR_bit at NVMCON1.B3;
    const register unsigned short int FREE = 4;
    sbit  FREE_bit at NVMCON1.B4;
    const register unsigned short int LWLO = 5;
    sbit  LWLO_bit at NVMCON1.B5;
    const register unsigned short int CFGS = 6;
    sbit  CFGS_bit at NVMCON1.B6;
    const register unsigned short int NVMREGS = 6;
    sbit  NVMREGS_bit at NVMCON1.B6;

sfr unsigned short volatile EECON1           absolute 0x895;
sfr unsigned short volatile PMCON1           absolute 0x895;
sfr unsigned short volatile NVMCON2          absolute 0x896;
sfr unsigned short volatile EECON2           absolute 0x896;
sfr unsigned short volatile PMCON2           absolute 0x896;
sfr unsigned short volatile PCON0            absolute 0x89B;
    const register unsigned short int nBOR = 0;
    sbit  nBOR_bit at PCON0.B0;
    const register unsigned short int nPOR = 1;
    sbit  nPOR_bit at PCON0.B1;
    const register unsigned short int nRI = 2;
    sbit  nRI_bit at PCON0.B2;
    const register unsigned short int nRMCLR = 3;
    sbit  nRMCLR_bit at PCON0.B3;
    const register unsigned short int nRWDT = 4;
    sbit  nRWDT_bit at PCON0.B4;
    const register unsigned short int STKUNF = 6;
    sbit  STKUNF_bit at PCON0.B6;
    const register unsigned short int STKOVF = 7;
    sbit  STKOVF_bit at PCON0.B7;

sfr unsigned short volatile PMD0             absolute 0x911;
    const register unsigned short int IOCMD = 0;
    sbit  IOCMD_bit at PMD0.B0;
    const register unsigned short int CLKRMD = 1;
    sbit  CLKRMD_bit at PMD0.B1;
    const register unsigned short int NVMMD = 2;
    sbit  NVMMD_bit at PMD0.B2;
    const register unsigned short int FVRMD = 6;
    sbit  FVRMD_bit at PMD0.B6;
    const register unsigned short int SYSCMD = 7;
    sbit  SYSCMD_bit at PMD0.B7;

sfr unsigned short volatile PMD1             absolute 0x912;
    const register unsigned short int TMR0MD = 0;
    sbit  TMR0MD_bit at PMD1.B0;
    const register unsigned short int TMR1MD = 1;
    sbit  TMR1MD_bit at PMD1.B1;
    const register unsigned short int TMR2MD = 2;
    sbit  TMR2MD_bit at PMD1.B2;
    const register unsigned short int NCOMD = 7;
    sbit  NCOMD_bit at PMD1.B7;

sfr unsigned short volatile PMD2             absolute 0x913;
    const register unsigned short int CMP1MD = 1;
    sbit  CMP1MD_bit at PMD2.B1;
    const register unsigned short int ADCMD = 5;
    sbit  ADCMD_bit at PMD2.B5;
    const register unsigned short int DACMD = 6;
    sbit  DACMD_bit at PMD2.B6;

sfr unsigned short volatile PMD3             absolute 0x914;
    const register unsigned short int CCP1MD = 0;
    sbit  CCP1MD_bit at PMD3.B0;
    const register unsigned short int CCP2MD = 1;
    sbit  CCP2MD_bit at PMD3.B1;
    const register unsigned short int PWM5MD = 4;
    sbit  PWM5MD_bit at PMD3.B4;
    const register unsigned short int PWM6MD = 5;
    sbit  PWM6MD_bit at PMD3.B5;
    const register unsigned short int CWG1MD = 6;
    sbit  CWG1MD_bit at PMD3.B6;

sfr unsigned short volatile PMD4             absolute 0x915;
    const register unsigned short int MSSP1MD = 1;
    sbit  MSSP1MD_bit at PMD4.B1;
    const register unsigned short int UART1MD = 5;
    sbit  UART1MD_bit at PMD4.B5;

sfr unsigned short volatile PMD5             absolute 0x916;
    const register unsigned short int DSMMD = 0;
    sbit  DSMMD_bit at PMD5.B0;
    const register unsigned short int CLC1MD = 1;
    sbit  CLC1MD_bit at PMD5.B1;
    const register unsigned short int CLC2MD = 2;
    sbit  CLC2MD_bit at PMD5.B2;

sfr unsigned short volatile CPUDOZE          absolute 0x918;
    const register unsigned short int DOZE0 = 0;
    sbit  DOZE0_bit at CPUDOZE.B0;
    const register unsigned short int DOZE1 = 1;
    sbit  DOZE1_bit at CPUDOZE.B1;
    const register unsigned short int DOZE2 = 2;
    sbit  DOZE2_bit at CPUDOZE.B2;
    const register unsigned short int DOE = 4;
    sbit  DOE_bit at CPUDOZE.B4;
    const register unsigned short int ROI = 5;
    sbit  ROI_bit at CPUDOZE.B5;
    const register unsigned short int DOZEN = 6;
    sbit  DOZEN_bit at CPUDOZE.B6;
    const register unsigned short int IDLEN = 7;
    sbit  IDLEN_bit at CPUDOZE.B7;

sfr unsigned short volatile OSCCON1          absolute 0x919;
    const register unsigned short int NDIV0 = 0;
    sbit  NDIV0_bit at OSCCON1.B0;
    const register unsigned short int NDIV1 = 1;
    sbit  NDIV1_bit at OSCCON1.B1;
    const register unsigned short int NDIV2 = 2;
    sbit  NDIV2_bit at OSCCON1.B2;
    const register unsigned short int NDIV3 = 3;
    sbit  NDIV3_bit at OSCCON1.B3;
    const register unsigned short int NOSC0 = 4;
    sbit  NOSC0_bit at OSCCON1.B4;
    const register unsigned short int NOSC1 = 5;
    sbit  NOSC1_bit at OSCCON1.B5;
    const register unsigned short int NOSC2 = 6;
    sbit  NOSC2_bit at OSCCON1.B6;

sfr unsigned short volatile OSCCON2          absolute 0x91A;
    const register unsigned short int CDIV0 = 0;
    sbit  CDIV0_bit at OSCCON2.B0;
    const register unsigned short int CDIV1 = 1;
    sbit  CDIV1_bit at OSCCON2.B1;
    const register unsigned short int CDIV2 = 2;
    sbit  CDIV2_bit at OSCCON2.B2;
    const register unsigned short int CDIV3 = 3;
    sbit  CDIV3_bit at OSCCON2.B3;
    const register unsigned short int COSC0 = 4;
    sbit  COSC0_bit at OSCCON2.B4;
    const register unsigned short int COSC1 = 5;
    sbit  COSC1_bit at OSCCON2.B5;
    const register unsigned short int COSC2 = 6;
    sbit  COSC2_bit at OSCCON2.B6;

sfr unsigned short volatile OSCCON3          absolute 0x91B;
    const register unsigned short int NOSCR = 3;
    sbit  NOSCR_bit at OSCCON3.B3;
    const register unsigned short int ORDY = 4;
    sbit  ORDY_bit at OSCCON3.B4;
    const register unsigned short int SOSCBE = 5;
    sbit  SOSCBE_bit at OSCCON3.B5;
    const register unsigned short int SOSCPWR = 6;
    sbit  SOSCPWR_bit at OSCCON3.B6;
    const register unsigned short int CSWHOLD = 7;
    sbit  CSWHOLD_bit at OSCCON3.B7;

sfr unsigned short volatile OSCSTAT1         absolute 0x91C;
    const register unsigned short int PLLR = 0;
    sbit  PLLR_bit at OSCSTAT1.B0;
    const register unsigned short int ADOR = 2;
    sbit  ADOR_bit at OSCSTAT1.B2;
    const register unsigned short int SOR = 3;
    sbit  SOR_bit at OSCSTAT1.B3;
    const register unsigned short int LFOR = 4;
    sbit  LFOR_bit at OSCSTAT1.B4;
    const register unsigned short int HFOR = 6;
    sbit  HFOR_bit at OSCSTAT1.B6;
    const register unsigned short int EXTOR = 7;
    sbit  EXTOR_bit at OSCSTAT1.B7;

sfr unsigned short volatile OSCEN            absolute 0x91D;
    const register unsigned short int ADOEN = 2;
    sbit  ADOEN_bit at OSCEN.B2;
    const register unsigned short int SOSCEN = 3;
    sbit  SOSCEN_bit at OSCEN.B3;
    const register unsigned short int LFOEN = 4;
    sbit  LFOEN_bit at OSCEN.B4;
    const register unsigned short int HFOEN = 6;
    sbit  HFOEN_bit at OSCEN.B6;
    const register unsigned short int EXTOEN = 7;
    sbit  EXTOEN_bit at OSCEN.B7;

sfr unsigned short volatile OSCTUNE          absolute 0x91E;
    const register unsigned short int HFTUN0 = 0;
    sbit  HFTUN0_bit at OSCTUNE.B0;
    const register unsigned short int HFTUN1 = 1;
    sbit  HFTUN1_bit at OSCTUNE.B1;
    const register unsigned short int HFTUN2 = 2;
    sbit  HFTUN2_bit at OSCTUNE.B2;
    const register unsigned short int HFTUN3 = 3;
    sbit  HFTUN3_bit at OSCTUNE.B3;
    const register unsigned short int HFTUN4 = 4;
    sbit  HFTUN4_bit at OSCTUNE.B4;
    const register unsigned short int HFTUN5 = 5;
    sbit  HFTUN5_bit at OSCTUNE.B5;

sfr unsigned short volatile OSCFRQ           absolute 0x91F;
    const register unsigned short int HFFRQ0 = 0;
    sbit  HFFRQ0_bit at OSCFRQ.B0;
    const register unsigned short int HFFRQ1 = 1;
    sbit  HFFRQ1_bit at OSCFRQ.B1;
    const register unsigned short int HFFRQ2 = 2;
    sbit  HFFRQ2_bit at OSCFRQ.B2;
    const register unsigned short int HFFRQ3 = 3;
    sbit  HFFRQ3_bit at OSCFRQ.B3;

sfr unsigned short volatile PPSLOCK          absolute 0xE0F;
    const register unsigned short int PPSLOCKED = 0;
    sbit  PPSLOCKED_bit at PPSLOCK.B0;

sfr unsigned short volatile INTPPS           absolute 0xE10;
    const register unsigned short int INTPPS0 = 0;
    sbit  INTPPS0_bit at INTPPS.B0;
    const register unsigned short int INTPPS1 = 1;
    sbit  INTPPS1_bit at INTPPS.B1;
    const register unsigned short int INTPPS2 = 2;
    sbit  INTPPS2_bit at INTPPS.B2;
    const register unsigned short int INTPPS3 = 3;
    sbit  INTPPS3_bit at INTPPS.B3;
    const register unsigned short int INTPPS4 = 4;
    sbit  INTPPS4_bit at INTPPS.B4;

sfr unsigned short volatile T0CKIPPS         absolute 0xE11;
    const register unsigned short int T0CKIPPS0 = 0;
    sbit  T0CKIPPS0_bit at T0CKIPPS.B0;
    const register unsigned short int T0CKIPPS1 = 1;
    sbit  T0CKIPPS1_bit at T0CKIPPS.B1;
    const register unsigned short int T0CKIPPS2 = 2;
    sbit  T0CKIPPS2_bit at T0CKIPPS.B2;
    const register unsigned short int T0CKIPPS3 = 3;
    sbit  T0CKIPPS3_bit at T0CKIPPS.B3;
    const register unsigned short int T0CKIPPS4 = 4;
    sbit  T0CKIPPS4_bit at T0CKIPPS.B4;

sfr unsigned short volatile T1CKIPPS         absolute 0xE12;
    const register unsigned short int T1CKIPPS0 = 0;
    sbit  T1CKIPPS0_bit at T1CKIPPS.B0;
    const register unsigned short int T1CKIPPS1 = 1;
    sbit  T1CKIPPS1_bit at T1CKIPPS.B1;
    const register unsigned short int T1CKIPPS2 = 2;
    sbit  T1CKIPPS2_bit at T1CKIPPS.B2;
    const register unsigned short int T1CKIPPS3 = 3;
    sbit  T1CKIPPS3_bit at T1CKIPPS.B3;
    const register unsigned short int T1CKIPPS4 = 4;
    sbit  T1CKIPPS4_bit at T1CKIPPS.B4;

sfr unsigned short volatile T1GPPS           absolute 0xE13;
    const register unsigned short int T1GPPS0 = 0;
    sbit  T1GPPS0_bit at T1GPPS.B0;
    const register unsigned short int T1GPPS1 = 1;
    sbit  T1GPPS1_bit at T1GPPS.B1;
    const register unsigned short int T1GPPS2 = 2;
    sbit  T1GPPS2_bit at T1GPPS.B2;
    const register unsigned short int T1GPPS3 = 3;
    sbit  T1GPPS3_bit at T1GPPS.B3;
    const register unsigned short int T1GPPS4 = 4;
    sbit  T1GPPS4_bit at T1GPPS.B4;

sfr unsigned short volatile CCP1PPS          absolute 0xE14;
    const register unsigned short int CCP1PPS0 = 0;
    sbit  CCP1PPS0_bit at CCP1PPS.B0;
    const register unsigned short int CCP1PPS1 = 1;
    sbit  CCP1PPS1_bit at CCP1PPS.B1;
    const register unsigned short int CCP1PPS2 = 2;
    sbit  CCP1PPS2_bit at CCP1PPS.B2;
    const register unsigned short int CCP1PPS3 = 3;
    sbit  CCP1PPS3_bit at CCP1PPS.B3;
    const register unsigned short int CCP1PPS4 = 4;
    sbit  CCP1PPS4_bit at CCP1PPS.B4;

sfr unsigned short volatile CCP2PPS          absolute 0xE15;
    const register unsigned short int CCP2PPS0 = 0;
    sbit  CCP2PPS0_bit at CCP2PPS.B0;
    const register unsigned short int CCP2PPS1 = 1;
    sbit  CCP2PPS1_bit at CCP2PPS.B1;
    const register unsigned short int CCP2PPS2 = 2;
    sbit  CCP2PPS2_bit at CCP2PPS.B2;
    const register unsigned short int CCP2PPS3 = 3;
    sbit  CCP2PPS3_bit at CCP2PPS.B3;
    const register unsigned short int CCP2PPS4 = 4;
    sbit  CCP2PPS4_bit at CCP2PPS.B4;

sfr unsigned short volatile CWG1PPS          absolute 0xE18;
    const register unsigned short int CWG1PPS0 = 0;
    sbit  CWG1PPS0_bit at CWG1PPS.B0;
    const register unsigned short int CWG1PPS1 = 1;
    sbit  CWG1PPS1_bit at CWG1PPS.B1;
    const register unsigned short int CWG1PPS2 = 2;
    sbit  CWG1PPS2_bit at CWG1PPS.B2;
    const register unsigned short int CWG1PPS3 = 3;
    sbit  CWG1PPS3_bit at CWG1PPS.B3;
    const register unsigned short int CWG1PPS4 = 4;
    sbit  CWG1PPS4_bit at CWG1PPS.B4;

sfr unsigned short volatile MDCIN1PPS        absolute 0xE1A;
    const register unsigned short int MDCIN1PPS0 = 0;
    sbit  MDCIN1PPS0_bit at MDCIN1PPS.B0;
    const register unsigned short int MDCIN1PPS1 = 1;
    sbit  MDCIN1PPS1_bit at MDCIN1PPS.B1;
    const register unsigned short int MDCIN1PPS2 = 2;
    sbit  MDCIN1PPS2_bit at MDCIN1PPS.B2;
    const register unsigned short int MDCIN1PPS3 = 3;
    sbit  MDCIN1PPS3_bit at MDCIN1PPS.B3;
    const register unsigned short int MDCIN1PPS4 = 4;
    sbit  MDCIN1PPS4_bit at MDCIN1PPS.B4;

sfr unsigned short volatile MDCIN2PPS        absolute 0xE1B;
    const register unsigned short int MDCIN2PPS0 = 0;
    sbit  MDCIN2PPS0_bit at MDCIN2PPS.B0;
    const register unsigned short int MDCIN2PPS1 = 1;
    sbit  MDCIN2PPS1_bit at MDCIN2PPS.B1;
    const register unsigned short int MDCIN2PPS2 = 2;
    sbit  MDCIN2PPS2_bit at MDCIN2PPS.B2;
    const register unsigned short int MDCIN2PPS3 = 3;
    sbit  MDCIN2PPS3_bit at MDCIN2PPS.B3;
    const register unsigned short int MDCIN2PPS4 = 4;
    sbit  MDCIN2PPS4_bit at MDCIN2PPS.B4;

sfr unsigned short volatile MDMINPPS         absolute 0xE1C;
    const register unsigned short int MDMINPPS0 = 0;
    sbit  MDMINPPS0_bit at MDMINPPS.B0;
    const register unsigned short int MDMINPPS1 = 1;
    sbit  MDMINPPS1_bit at MDMINPPS.B1;
    const register unsigned short int MDMINPPS2 = 2;
    sbit  MDMINPPS2_bit at MDMINPPS.B2;
    const register unsigned short int MDMINPPS3 = 3;
    sbit  MDMINPPS3_bit at MDMINPPS.B3;
    const register unsigned short int MDMINPPS4 = 4;
    sbit  MDMINPPS4_bit at MDMINPPS.B4;

sfr unsigned short volatile SSP1CLKPPS       absolute 0xE20;
    const register unsigned short int SSP1CLKPPS0 = 0;
    sbit  SSP1CLKPPS0_bit at SSP1CLKPPS.B0;
    const register unsigned short int SSP1CLKPPS1 = 1;
    sbit  SSP1CLKPPS1_bit at SSP1CLKPPS.B1;
    const register unsigned short int SSP1CLKPPS2 = 2;
    sbit  SSP1CLKPPS2_bit at SSP1CLKPPS.B2;
    const register unsigned short int SSP1CLKPPS3 = 3;
    sbit  SSP1CLKPPS3_bit at SSP1CLKPPS.B3;
    const register unsigned short int SSP1CLKPPS4 = 4;
    sbit  SSP1CLKPPS4_bit at SSP1CLKPPS.B4;

sfr unsigned short volatile SSP1DATPPS       absolute 0xE21;
    const register unsigned short int SSP1DATPPS0 = 0;
    sbit  SSP1DATPPS0_bit at SSP1DATPPS.B0;
    const register unsigned short int SSP1DATPPS1 = 1;
    sbit  SSP1DATPPS1_bit at SSP1DATPPS.B1;
    const register unsigned short int SSP1DATPPS2 = 2;
    sbit  SSP1DATPPS2_bit at SSP1DATPPS.B2;
    const register unsigned short int SSP1DATPPS3 = 3;
    sbit  SSP1DATPPS3_bit at SSP1DATPPS.B3;
    const register unsigned short int SSP1DATPPS4 = 4;
    sbit  SSP1DATPPS4_bit at SSP1DATPPS.B4;

sfr unsigned short volatile SSP1SSPPS        absolute 0xE22;
    const register unsigned short int SSP1SSPPS0 = 0;
    sbit  SSP1SSPPS0_bit at SSP1SSPPS.B0;
    const register unsigned short int SSP1SSPPS1 = 1;
    sbit  SSP1SSPPS1_bit at SSP1SSPPS.B1;
    const register unsigned short int SSP1SSPPS2 = 2;
    sbit  SSP1SSPPS2_bit at SSP1SSPPS.B2;
    const register unsigned short int SSP1SSPPS3 = 3;
    sbit  SSP1SSPPS3_bit at SSP1SSPPS.B3;
    const register unsigned short int SSP1SSPPS4 = 4;
    sbit  SSP1SSPPS4_bit at SSP1SSPPS.B4;

sfr unsigned short volatile RXPPS            absolute 0xE24;
    const register unsigned short int RXPPS0 = 0;
    sbit  RXPPS0_bit at RXPPS.B0;
    const register unsigned short int RXPPS1 = 1;
    sbit  RXPPS1_bit at RXPPS.B1;
    const register unsigned short int RXPPS2 = 2;
    sbit  RXPPS2_bit at RXPPS.B2;
    const register unsigned short int RXPPS3 = 3;
    sbit  RXPPS3_bit at RXPPS.B3;
    const register unsigned short int RXPPS4 = 4;
    sbit  RXPPS4_bit at RXPPS.B4;

sfr unsigned short volatile TXPPS            absolute 0xE25;
    const register unsigned short int TXPPS0 = 0;
    sbit  TXPPS0_bit at TXPPS.B0;
    const register unsigned short int TXPPS1 = 1;
    sbit  TXPPS1_bit at TXPPS.B1;
    const register unsigned short int TXPPS2 = 2;
    sbit  TXPPS2_bit at TXPPS.B2;
    const register unsigned short int TXPPS3 = 3;
    sbit  TXPPS3_bit at TXPPS.B3;
    const register unsigned short int TXPPS4 = 4;
    sbit  TXPPS4_bit at TXPPS.B4;

sfr unsigned short volatile CLCIN0PPS        absolute 0xE28;
    const register unsigned short int CLCIN0PPS0 = 0;
    sbit  CLCIN0PPS0_bit at CLCIN0PPS.B0;
    const register unsigned short int CLCIN0PPS1 = 1;
    sbit  CLCIN0PPS1_bit at CLCIN0PPS.B1;
    const register unsigned short int CLCIN0PPS2 = 2;
    sbit  CLCIN0PPS2_bit at CLCIN0PPS.B2;
    const register unsigned short int CLCIN0PPS3 = 3;
    sbit  CLCIN0PPS3_bit at CLCIN0PPS.B3;
    const register unsigned short int CLCIN0PPS4 = 4;
    sbit  CLCIN0PPS4_bit at CLCIN0PPS.B4;

sfr unsigned short volatile CLCIN1PPS        absolute 0xE29;
    const register unsigned short int CLCIN1PPS0 = 0;
    sbit  CLCIN1PPS0_bit at CLCIN1PPS.B0;
    const register unsigned short int CLCIN1PPS1 = 1;
    sbit  CLCIN1PPS1_bit at CLCIN1PPS.B1;
    const register unsigned short int CLCIN1PPS2 = 2;
    sbit  CLCIN1PPS2_bit at CLCIN1PPS.B2;
    const register unsigned short int CLCIN1PPS3 = 3;
    sbit  CLCIN1PPS3_bit at CLCIN1PPS.B3;
    const register unsigned short int CLCIN1PPS4 = 4;
    sbit  CLCIN1PPS4_bit at CLCIN1PPS.B4;

sfr unsigned short volatile CLCIN2PPS        absolute 0xE2A;
    const register unsigned short int CLCIN2PPS0 = 0;
    sbit  CLCIN2PPS0_bit at CLCIN2PPS.B0;
    const register unsigned short int CLCIN2PPS1 = 1;
    sbit  CLCIN2PPS1_bit at CLCIN2PPS.B1;
    const register unsigned short int CLCIN2PPS2 = 2;
    sbit  CLCIN2PPS2_bit at CLCIN2PPS.B2;
    const register unsigned short int CLCIN2PPS3 = 3;
    sbit  CLCIN2PPS3_bit at CLCIN2PPS.B3;
    const register unsigned short int CLCIN2PPS4 = 4;
    sbit  CLCIN2PPS4_bit at CLCIN2PPS.B4;

sfr unsigned short volatile CLCIN3PPS        absolute 0xE2B;
    const register unsigned short int CLCIN3PPS0 = 0;
    sbit  CLCIN3PPS0_bit at CLCIN3PPS.B0;
    const register unsigned short int CLCIN3PPS1 = 1;
    sbit  CLCIN3PPS1_bit at CLCIN3PPS.B1;
    const register unsigned short int CLCIN3PPS2 = 2;
    sbit  CLCIN3PPS2_bit at CLCIN3PPS.B2;
    const register unsigned short int CLCIN3PPS3 = 3;
    sbit  CLCIN3PPS3_bit at CLCIN3PPS.B3;
    const register unsigned short int CLCIN3PPS4 = 4;
    sbit  CLCIN3PPS4_bit at CLCIN3PPS.B4;

sfr unsigned short volatile RA0PPS           absolute 0xE90;
    const register unsigned short int RA0PPS0 = 0;
    sbit  RA0PPS0_bit at RA0PPS.B0;
    const register unsigned short int RA0PPS1 = 1;
    sbit  RA0PPS1_bit at RA0PPS.B1;
    const register unsigned short int RA0PPS2 = 2;
    sbit  RA0PPS2_bit at RA0PPS.B2;
    const register unsigned short int RA0PPS3 = 3;
    sbit  RA0PPS3_bit at RA0PPS.B3;
    const register unsigned short int RA0PPS4 = 4;
    sbit  RA0PPS4_bit at RA0PPS.B4;

sfr unsigned short volatile RA1PPS           absolute 0xE91;
    const register unsigned short int RA1PPS0 = 0;
    sbit  RA1PPS0_bit at RA1PPS.B0;
    const register unsigned short int RA1PPS1 = 1;
    sbit  RA1PPS1_bit at RA1PPS.B1;
    const register unsigned short int RA1PPS2 = 2;
    sbit  RA1PPS2_bit at RA1PPS.B2;
    const register unsigned short int RA1PPS3 = 3;
    sbit  RA1PPS3_bit at RA1PPS.B3;
    const register unsigned short int RA1PPS4 = 4;
    sbit  RA1PPS4_bit at RA1PPS.B4;

sfr unsigned short volatile RA2PPS           absolute 0xE92;
    const register unsigned short int RA2PPS0 = 0;
    sbit  RA2PPS0_bit at RA2PPS.B0;
    const register unsigned short int RA2PPS1 = 1;
    sbit  RA2PPS1_bit at RA2PPS.B1;
    const register unsigned short int RA2PPS2 = 2;
    sbit  RA2PPS2_bit at RA2PPS.B2;
    const register unsigned short int RA2PPS3 = 3;
    sbit  RA2PPS3_bit at RA2PPS.B3;
    const register unsigned short int RA2PPS4 = 4;
    sbit  RA2PPS4_bit at RA2PPS.B4;

sfr unsigned short volatile RA4PPS           absolute 0xE94;
    const register unsigned short int RA4PPS0 = 0;
    sbit  RA4PPS0_bit at RA4PPS.B0;
    const register unsigned short int RA4PPS1 = 1;
    sbit  RA4PPS1_bit at RA4PPS.B1;
    const register unsigned short int RA4PPS2 = 2;
    sbit  RA4PPS2_bit at RA4PPS.B2;
    const register unsigned short int RA4PPS3 = 3;
    sbit  RA4PPS3_bit at RA4PPS.B3;
    const register unsigned short int RA4PPS4 = 4;
    sbit  RA4PPS4_bit at RA4PPS.B4;

sfr unsigned short volatile RA5PPS           absolute 0xE95;
    const register unsigned short int RA5PPS0 = 0;
    sbit  RA5PPS0_bit at RA5PPS.B0;
    const register unsigned short int RA5PPS1 = 1;
    sbit  RA5PPS1_bit at RA5PPS.B1;
    const register unsigned short int RA5PPS2 = 2;
    sbit  RA5PPS2_bit at RA5PPS.B2;
    const register unsigned short int RA5PPS3 = 3;
    sbit  RA5PPS3_bit at RA5PPS.B3;
    const register unsigned short int RA5PPS4 = 4;
    sbit  RA5PPS4_bit at RA5PPS.B4;

sfr unsigned short volatile CLCDATA          absolute 0xF0F;
    const register unsigned short int MLC1OUT = 0;
    sbit  MLC1OUT_bit at CLCDATA.B0;
    const register unsigned short int MLC2OUT = 1;
    sbit  MLC2OUT_bit at CLCDATA.B1;

sfr unsigned short volatile CLC1CON          absolute 0xF10;
    const register unsigned short int LC1MODE0 = 0;
    sbit  LC1MODE0_bit at CLC1CON.B0;
    const register unsigned short int LC1MODE1 = 1;
    sbit  LC1MODE1_bit at CLC1CON.B1;
    const register unsigned short int LC1MODE2 = 2;
    sbit  LC1MODE2_bit at CLC1CON.B2;
    const register unsigned short int LC1INTN = 3;
    sbit  LC1INTN_bit at CLC1CON.B3;
    const register unsigned short int LC1INTP = 4;
    sbit  LC1INTP_bit at CLC1CON.B4;
    const register unsigned short int LC1OUT = 5;
    sbit  LC1OUT_bit at CLC1CON.B5;
    const register unsigned short int LC1EN = 7;
    sbit  LC1EN_bit at CLC1CON.B7;

sfr unsigned short volatile CLC1POL          absolute 0xF11;
    const register unsigned short int LC1G1POL = 0;
    sbit  LC1G1POL_bit at CLC1POL.B0;
    const register unsigned short int LC1G2POL = 1;
    sbit  LC1G2POL_bit at CLC1POL.B1;
    const register unsigned short int LC1G3POL = 2;
    sbit  LC1G3POL_bit at CLC1POL.B2;
    const register unsigned short int LC1G4POL = 3;
    sbit  LC1G4POL_bit at CLC1POL.B3;
    const register unsigned short int LC1POL = 7;
    sbit  LC1POL_bit at CLC1POL.B7;

sfr unsigned short volatile CLC1SEL0         absolute 0xF12;
    const register unsigned short int LC1D1S0 = 0;
    sbit  LC1D1S0_bit at CLC1SEL0.B0;
    const register unsigned short int LC1D1S1 = 1;
    sbit  LC1D1S1_bit at CLC1SEL0.B1;
    const register unsigned short int LC1D1S2 = 2;
    sbit  LC1D1S2_bit at CLC1SEL0.B2;
    const register unsigned short int LC1D1S3 = 3;
    sbit  LC1D1S3_bit at CLC1SEL0.B3;
    const register unsigned short int LC1D1S4 = 4;
    sbit  LC1D1S4_bit at CLC1SEL0.B4;

sfr unsigned short volatile CLC1SEL1         absolute 0xF13;
    const register unsigned short int LC1D2S0 = 0;
    sbit  LC1D2S0_bit at CLC1SEL1.B0;
    const register unsigned short int LC1D2S1 = 1;
    sbit  LC1D2S1_bit at CLC1SEL1.B1;
    const register unsigned short int LC1D2S2 = 2;
    sbit  LC1D2S2_bit at CLC1SEL1.B2;
    const register unsigned short int LC1D2S3 = 3;
    sbit  LC1D2S3_bit at CLC1SEL1.B3;
    const register unsigned short int LC1D2S4 = 4;
    sbit  LC1D2S4_bit at CLC1SEL1.B4;

sfr unsigned short volatile CLC1SEL2         absolute 0xF14;
    const register unsigned short int LC1D3S0 = 0;
    sbit  LC1D3S0_bit at CLC1SEL2.B0;
    const register unsigned short int LC1D3S1 = 1;
    sbit  LC1D3S1_bit at CLC1SEL2.B1;
    const register unsigned short int LC1D3S2 = 2;
    sbit  LC1D3S2_bit at CLC1SEL2.B2;
    const register unsigned short int LC1D3S3 = 3;
    sbit  LC1D3S3_bit at CLC1SEL2.B3;
    const register unsigned short int LC1D3S4 = 4;
    sbit  LC1D3S4_bit at CLC1SEL2.B4;

sfr unsigned short volatile CLC1SEL3         absolute 0xF15;
    const register unsigned short int LC1D4S0 = 0;
    sbit  LC1D4S0_bit at CLC1SEL3.B0;
    const register unsigned short int LC1D4S1 = 1;
    sbit  LC1D4S1_bit at CLC1SEL3.B1;
    const register unsigned short int LC1D4S2 = 2;
    sbit  LC1D4S2_bit at CLC1SEL3.B2;
    const register unsigned short int LC1D4S3 = 3;
    sbit  LC1D4S3_bit at CLC1SEL3.B3;
    const register unsigned short int LC1D4S4 = 4;
    sbit  LC1D4S4_bit at CLC1SEL3.B4;

sfr unsigned short volatile CLC1GLS0         absolute 0xF16;
    const register unsigned short int LC1G1D1N = 0;
    sbit  LC1G1D1N_bit at CLC1GLS0.B0;
    const register unsigned short int LC1G1D1T = 1;
    sbit  LC1G1D1T_bit at CLC1GLS0.B1;
    const register unsigned short int LC1G1D2N = 2;
    sbit  LC1G1D2N_bit at CLC1GLS0.B2;
    const register unsigned short int LC1G1D2T = 3;
    sbit  LC1G1D2T_bit at CLC1GLS0.B3;
    const register unsigned short int LC1G1D3N = 4;
    sbit  LC1G1D3N_bit at CLC1GLS0.B4;
    const register unsigned short int LC1G1D3T = 5;
    sbit  LC1G1D3T_bit at CLC1GLS0.B5;
    const register unsigned short int LC1G1D4N = 6;
    sbit  LC1G1D4N_bit at CLC1GLS0.B6;
    const register unsigned short int LC1G1D4T = 7;
    sbit  LC1G1D4T_bit at CLC1GLS0.B7;

sfr unsigned short volatile CLC1GLS1         absolute 0xF17;
    const register unsigned short int LC1G2D1N = 0;
    sbit  LC1G2D1N_bit at CLC1GLS1.B0;
    const register unsigned short int LC1G2D1T = 1;
    sbit  LC1G2D1T_bit at CLC1GLS1.B1;
    const register unsigned short int LC1G2D2N = 2;
    sbit  LC1G2D2N_bit at CLC1GLS1.B2;
    const register unsigned short int LC1G2D2T = 3;
    sbit  LC1G2D2T_bit at CLC1GLS1.B3;
    const register unsigned short int LC1G2D3N = 4;
    sbit  LC1G2D3N_bit at CLC1GLS1.B4;
    const register unsigned short int LC1G2D3T = 5;
    sbit  LC1G2D3T_bit at CLC1GLS1.B5;
    const register unsigned short int LC1G2D4N = 6;
    sbit  LC1G2D4N_bit at CLC1GLS1.B6;
    const register unsigned short int LC1G2D4T = 7;
    sbit  LC1G2D4T_bit at CLC1GLS1.B7;

sfr unsigned short volatile CLC1GLS2         absolute 0xF18;
    const register unsigned short int LC1G3D1N = 0;
    sbit  LC1G3D1N_bit at CLC1GLS2.B0;
    const register unsigned short int LC1G3D1T = 1;
    sbit  LC1G3D1T_bit at CLC1GLS2.B1;
    const register unsigned short int LC1G3D2N = 2;
    sbit  LC1G3D2N_bit at CLC1GLS2.B2;
    const register unsigned short int LC1G3D2T = 3;
    sbit  LC1G3D2T_bit at CLC1GLS2.B3;
    const register unsigned short int LC1G3D3N = 4;
    sbit  LC1G3D3N_bit at CLC1GLS2.B4;
    const register unsigned short int LC1G3D3T = 5;
    sbit  LC1G3D3T_bit at CLC1GLS2.B5;
    const register unsigned short int LC1G3D4N = 6;
    sbit  LC1G3D4N_bit at CLC1GLS2.B6;
    const register unsigned short int LC1G3D4T = 7;
    sbit  LC1G3D4T_bit at CLC1GLS2.B7;

sfr unsigned short volatile CLC1GLS3         absolute 0xF19;
    const register unsigned short int LC1G4D1N = 0;
    sbit  LC1G4D1N_bit at CLC1GLS3.B0;
    const register unsigned short int LC1G4D1T = 1;
    sbit  LC1G4D1T_bit at CLC1GLS3.B1;
    const register unsigned short int LC1G4D2N = 2;
    sbit  LC1G4D2N_bit at CLC1GLS3.B2;
    const register unsigned short int LC1G4D2T = 3;
    sbit  LC1G4D2T_bit at CLC1GLS3.B3;
    const register unsigned short int LC1G4D3N = 4;
    sbit  LC1G4D3N_bit at CLC1GLS3.B4;
    const register unsigned short int LC1G4D3T = 5;
    sbit  LC1G4D3T_bit at CLC1GLS3.B5;
    const register unsigned short int LC1G4D4N = 6;
    sbit  LC1G4D4N_bit at CLC1GLS3.B6;
    const register unsigned short int LC1G4D4T = 7;
    sbit  LC1G4D4T_bit at CLC1GLS3.B7;

sfr unsigned short volatile CLC2CON          absolute 0xF1A;
    const register unsigned short int LC2MODE0 = 0;
    sbit  LC2MODE0_bit at CLC2CON.B0;
    const register unsigned short int LC2MODE1 = 1;
    sbit  LC2MODE1_bit at CLC2CON.B1;
    const register unsigned short int LC2MODE2 = 2;
    sbit  LC2MODE2_bit at CLC2CON.B2;
    const register unsigned short int LC2INTN = 3;
    sbit  LC2INTN_bit at CLC2CON.B3;
    const register unsigned short int LC2INTP = 4;
    sbit  LC2INTP_bit at CLC2CON.B4;
    const register unsigned short int LC2OUT = 5;
    sbit  LC2OUT_bit at CLC2CON.B5;
    const register unsigned short int LC2EN = 7;
    sbit  LC2EN_bit at CLC2CON.B7;

sfr unsigned short volatile CLC2POL          absolute 0xF1B;
    const register unsigned short int LC2G1POL = 0;
    sbit  LC2G1POL_bit at CLC2POL.B0;
    const register unsigned short int LC2G2POL = 1;
    sbit  LC2G2POL_bit at CLC2POL.B1;
    const register unsigned short int LC2G3POL = 2;
    sbit  LC2G3POL_bit at CLC2POL.B2;
    const register unsigned short int LC2G4POL = 3;
    sbit  LC2G4POL_bit at CLC2POL.B3;
    const register unsigned short int LC2POL = 7;
    sbit  LC2POL_bit at CLC2POL.B7;

sfr unsigned short volatile CLC2SEL0         absolute 0xF1C;
    const register unsigned short int LC2D1S0 = 0;
    sbit  LC2D1S0_bit at CLC2SEL0.B0;
    const register unsigned short int LC2D1S1 = 1;
    sbit  LC2D1S1_bit at CLC2SEL0.B1;
    const register unsigned short int LC2D1S2 = 2;
    sbit  LC2D1S2_bit at CLC2SEL0.B2;
    const register unsigned short int LC2D1S3 = 3;
    sbit  LC2D1S3_bit at CLC2SEL0.B3;
    const register unsigned short int LC2D1S4 = 4;
    sbit  LC2D1S4_bit at CLC2SEL0.B4;

sfr unsigned short volatile CLC2SEL1         absolute 0xF1D;
    const register unsigned short int LC2D2S0 = 0;
    sbit  LC2D2S0_bit at CLC2SEL1.B0;
    const register unsigned short int LC2D2S1 = 1;
    sbit  LC2D2S1_bit at CLC2SEL1.B1;
    const register unsigned short int LC2D2S2 = 2;
    sbit  LC2D2S2_bit at CLC2SEL1.B2;
    const register unsigned short int LC2D2S3 = 3;
    sbit  LC2D2S3_bit at CLC2SEL1.B3;
    const register unsigned short int LC2D2S4 = 4;
    sbit  LC2D2S4_bit at CLC2SEL1.B4;

sfr unsigned short volatile CLC2SEL2         absolute 0xF1E;
    const register unsigned short int LC2D3S0 = 0;
    sbit  LC2D3S0_bit at CLC2SEL2.B0;
    const register unsigned short int LC2D3S1 = 1;
    sbit  LC2D3S1_bit at CLC2SEL2.B1;
    const register unsigned short int LC2D3S2 = 2;
    sbit  LC2D3S2_bit at CLC2SEL2.B2;
    const register unsigned short int LC2D3S3 = 3;
    sbit  LC2D3S3_bit at CLC2SEL2.B3;
    const register unsigned short int LC2D3S4 = 4;
    sbit  LC2D3S4_bit at CLC2SEL2.B4;

sfr unsigned short volatile CLC2SEL3         absolute 0xF1F;
    const register unsigned short int LC2D4S0 = 0;
    sbit  LC2D4S0_bit at CLC2SEL3.B0;
    const register unsigned short int LC2D4S1 = 1;
    sbit  LC2D4S1_bit at CLC2SEL3.B1;
    const register unsigned short int LC2D4S2 = 2;
    sbit  LC2D4S2_bit at CLC2SEL3.B2;
    const register unsigned short int LC2D4S3 = 3;
    sbit  LC2D4S3_bit at CLC2SEL3.B3;
    const register unsigned short int LC2D4S4 = 4;
    sbit  LC2D4S4_bit at CLC2SEL3.B4;

sfr unsigned short volatile CLC2GLS0         absolute 0xF20;
    const register unsigned short int LC2G1D1N = 0;
    sbit  LC2G1D1N_bit at CLC2GLS0.B0;
    const register unsigned short int LC2G1D1T = 1;
    sbit  LC2G1D1T_bit at CLC2GLS0.B1;
    const register unsigned short int LC2G1D2N = 2;
    sbit  LC2G1D2N_bit at CLC2GLS0.B2;
    const register unsigned short int LC2G1D2T = 3;
    sbit  LC2G1D2T_bit at CLC2GLS0.B3;
    const register unsigned short int LC2G1D3N = 4;
    sbit  LC2G1D3N_bit at CLC2GLS0.B4;
    const register unsigned short int LC2G1D3T = 5;
    sbit  LC2G1D3T_bit at CLC2GLS0.B5;
    const register unsigned short int LC2G1D4N = 6;
    sbit  LC2G1D4N_bit at CLC2GLS0.B6;
    const register unsigned short int LC2G1D4T = 7;
    sbit  LC2G1D4T_bit at CLC2GLS0.B7;

sfr unsigned short volatile CLC2GLS1         absolute 0xF21;
    const register unsigned short int LC2G2D1N = 0;
    sbit  LC2G2D1N_bit at CLC2GLS1.B0;
    const register unsigned short int LC2G2D1T = 1;
    sbit  LC2G2D1T_bit at CLC2GLS1.B1;
    const register unsigned short int LC2G2D2N = 2;
    sbit  LC2G2D2N_bit at CLC2GLS1.B2;
    const register unsigned short int LC2G2D2T = 3;
    sbit  LC2G2D2T_bit at CLC2GLS1.B3;
    const register unsigned short int LC2G2D3N = 4;
    sbit  LC2G2D3N_bit at CLC2GLS1.B4;
    const register unsigned short int LC2G2D3T = 5;
    sbit  LC2G2D3T_bit at CLC2GLS1.B5;
    const register unsigned short int LC2G2D4N = 6;
    sbit  LC2G2D4N_bit at CLC2GLS1.B6;
    const register unsigned short int LC2G2D4T = 7;
    sbit  LC2G2D4T_bit at CLC2GLS1.B7;

sfr unsigned short volatile CLC2GLS2         absolute 0xF22;
    const register unsigned short int LC2G3D1N = 0;
    sbit  LC2G3D1N_bit at CLC2GLS2.B0;
    const register unsigned short int LC2G3D1T = 1;
    sbit  LC2G3D1T_bit at CLC2GLS2.B1;
    const register unsigned short int LC2G3D2N = 2;
    sbit  LC2G3D2N_bit at CLC2GLS2.B2;
    const register unsigned short int LC2G3D2T = 3;
    sbit  LC2G3D2T_bit at CLC2GLS2.B3;
    const register unsigned short int LC2G3D3N = 4;
    sbit  LC2G3D3N_bit at CLC2GLS2.B4;
    const register unsigned short int LC2G3D3T = 5;
    sbit  LC2G3D3T_bit at CLC2GLS2.B5;
    const register unsigned short int LC2G3D4N = 6;
    sbit  LC2G3D4N_bit at CLC2GLS2.B6;
    const register unsigned short int LC2G3D4T = 7;
    sbit  LC2G3D4T_bit at CLC2GLS2.B7;

sfr unsigned short volatile CLC2GLS3         absolute 0xF23;
    const register unsigned short int LC2G4D1N = 0;
    sbit  LC2G4D1N_bit at CLC2GLS3.B0;
    const register unsigned short int LC2G4D1T = 1;
    sbit  LC2G4D1T_bit at CLC2GLS3.B1;
    const register unsigned short int LC2G4D2N = 2;
    sbit  LC2G4D2N_bit at CLC2GLS3.B2;
    const register unsigned short int LC2G4D2T = 3;
    sbit  LC2G4D2T_bit at CLC2GLS3.B3;
    const register unsigned short int LC2G4D3N = 4;
    sbit  LC2G4D3N_bit at CLC2GLS3.B4;
    const register unsigned short int LC2G4D3T = 5;
    sbit  LC2G4D3T_bit at CLC2GLS3.B5;
    const register unsigned short int LC2G4D4N = 6;
    sbit  LC2G4D4N_bit at CLC2GLS3.B6;
    const register unsigned short int LC2G4D4T = 7;
    sbit  LC2G4D4T_bit at CLC2GLS3.B7;

sfr unsigned short volatile STATUS_SHAD      absolute 0xFE4;
    const register unsigned short int C_SHAD = 0;
    sbit  C_SHAD_bit at STATUS_SHAD.B0;
    const register unsigned short int DC_SHAD = 1;
    sbit  DC_SHAD_bit at STATUS_SHAD.B1;
    const register unsigned short int Z_SHAD = 2;
    sbit  Z_SHAD_bit at STATUS_SHAD.B2;

sfr unsigned short volatile WREG_SHAD        absolute 0xFE5;
sfr unsigned short volatile BSR_SHAD         absolute 0xFE6;
sfr unsigned short volatile PCLATH_SHAD      absolute 0xFE7;
sfr unsigned short volatile FSR0L_SHAD       absolute 0xFE8;
sfr unsigned short volatile FSR0H_SHAD       absolute 0xFE9;
sfr unsigned short volatile FSR1L_SHAD       absolute 0xFEA;
sfr unsigned short volatile FSR1H_SHAD       absolute 0xFEB;
sfr unsigned short volatile STKPTR           absolute 0xFED;
sfr unsigned short volatile TOSL             absolute 0xFEE;
sfr unsigned short volatile TOSH             absolute 0xFEF;
