// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00002000;

// Working space registers
rx unsigned short R0  absolute 0x0070;
rx unsigned short R1  absolute 0x0071;
rx unsigned short R2  absolute 0x0072;
rx unsigned short R3  absolute 0x0073;
rx unsigned short R4  absolute 0x0074;
rx unsigned short R5  absolute 0x0075;
rx unsigned short R6  absolute 0x0076;
rx unsigned short R7  absolute 0x0077;
rx unsigned short R8  absolute 0x0078;
rx unsigned short R9  absolute 0x0079;
rx unsigned short R10 absolute 0x007A;
rx unsigned short R11 absolute 0x007B;
rx unsigned short R12 absolute 0x007C;
rx unsigned short R13 absolute 0x007D;
rx unsigned short R14 absolute 0x007E;
rx unsigned short R15 absolute 0x007F;

const register unsigned short int W = 0;
const register unsigned short int F = 1;

// Special function registers (SFRs)

const signed int   PORT_TO_TRIS_OFFSET    =     128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

sfr unsigned short volatile INDF0            absolute 0x000;
sfr unsigned short volatile INDF1            absolute 0x001;
sfr unsigned short volatile PCL              absolute 0x002;
sfr unsigned short volatile STATUS           absolute 0x003;
    const register unsigned short int CARRY = 0;
    const register unsigned short int C = 0;
    sbit  CARRY_bit at STATUS.B0;
    sbit  C_bit at STATUS.B0;
    const register unsigned short int DC = 1;
    sbit  DC_bit at STATUS.B1;
    const register unsigned short int ZERO = 2;
    const register unsigned short int Z = 2;
    sbit  ZERO_bit at STATUS.B2;
    sbit  Z_bit at STATUS.B2;
    const register unsigned short int nPD = 3;
    sbit  nPD_bit at STATUS.B3;
    const register unsigned short int nTO = 4;
    sbit  nTO_bit at STATUS.B4;

sfr unsigned int            FSR0             absolute 0x004;
sfr unsigned short          FSR0L            absolute 0x004;
register unsigned short     *FSR0PTR         absolute 0x004;
sfr unsigned short          FSR0H            absolute 0x005;
sfr unsigned int            FSR1             absolute 0x006;
sfr unsigned short          FSR1L            absolute 0x006;
register unsigned short     *FSR1PTR         absolute 0x006;
sfr unsigned short          FSR1H            absolute 0x007;
sfr unsigned short          BSR              absolute 0x008;
    const register unsigned short int BSR0 = 0;
    sbit  BSR0_bit at BSR.B0;
    const register unsigned short int BSR1 = 1;
    sbit  BSR1_bit at BSR.B1;
    const register unsigned short int BSR2 = 2;
    sbit  BSR2_bit at BSR.B2;
    const register unsigned short int BSR3 = 3;
    sbit  BSR3_bit at BSR.B3;
    const register unsigned short int BSR4 = 4;
    sbit  BSR4_bit at BSR.B4;

sfr unsigned short volatile WREG             absolute 0x009;
sfr unsigned short volatile PCLATH           absolute 0x00A;
sfr unsigned short volatile INTCON           absolute 0x00B;
    const register unsigned short int IOCIF = 0;
    sbit  IOCIF_bit at INTCON.B0;
    const register unsigned short int INTF = 1;
    sbit  INTF_bit at INTCON.B1;
    const register unsigned short int T0IF = 2;
    sbit  T0IF_bit at INTCON.B2;
    const register unsigned short int IOCIE = 3;
    sbit  IOCIE_bit at INTCON.B3;
    const register unsigned short int INTE = 4;
    sbit  INTE_bit at INTCON.B4;
    const register unsigned short int T0IE = 5;
    sbit  T0IE_bit at INTCON.B5;
    const register unsigned short int PEIE = 6;
    sbit  PEIE_bit at INTCON.B6;
    const register unsigned short int GIE = 7;
    sbit  GIE_bit at INTCON.B7;
    const register unsigned short int TMR0IE = 5;
    sbit  TMR0IE_bit at INTCON.B5;
    const register unsigned short int TMR0IF = 2;
    sbit  TMR0IF_bit at INTCON.B2;

sfr unsigned short volatile PORTA            absolute 0x00C;
    const register unsigned short int RA0 = 0;
    sbit  RA0_bit at PORTA.B0;
    const register unsigned short int RA1 = 1;
    sbit  RA1_bit at PORTA.B1;
    const register unsigned short int RA2 = 2;
    sbit  RA2_bit at PORTA.B2;
    const register unsigned short int RA3 = 3;
    sbit  RA3_bit at PORTA.B3;
    const register unsigned short int RA4 = 4;
    sbit  RA4_bit at PORTA.B4;
    const register unsigned short int RA5 = 5;
    sbit  RA5_bit at PORTA.B5;
    const register unsigned short int RA6 = 6;
    sbit  RA6_bit at PORTA.B6;
    const register unsigned short int RA7 = 7;
    sbit  RA7_bit at PORTA.B7;

sfr unsigned short volatile PORTB            absolute 0x00D;
    const register unsigned short int RB0 = 0;
    sbit  RB0_bit at PORTB.B0;
    const register unsigned short int RB1 = 1;
    sbit  RB1_bit at PORTB.B1;
    const register unsigned short int RB2 = 2;
    sbit  RB2_bit at PORTB.B2;
    const register unsigned short int RB3 = 3;
    sbit  RB3_bit at PORTB.B3;
    const register unsigned short int RB4 = 4;
    sbit  RB4_bit at PORTB.B4;
    const register unsigned short int RB5 = 5;
    sbit  RB5_bit at PORTB.B5;
    const register unsigned short int RB6 = 6;
    sbit  RB6_bit at PORTB.B6;
    const register unsigned short int RB7 = 7;
    sbit  RB7_bit at PORTB.B7;

sfr unsigned short volatile PORTC            absolute 0x00E;
    const register unsigned short int RC0 = 0;
    sbit  RC0_bit at PORTC.B0;
    const register unsigned short int RC1 = 1;
    sbit  RC1_bit at PORTC.B1;
    const register unsigned short int RC2 = 2;
    sbit  RC2_bit at PORTC.B2;
    const register unsigned short int RC3 = 3;
    sbit  RC3_bit at PORTC.B3;
    const register unsigned short int RC4 = 4;
    sbit  RC4_bit at PORTC.B4;
    const register unsigned short int RC5 = 5;
    sbit  RC5_bit at PORTC.B5;
    const register unsigned short int RC6 = 6;
    sbit  RC6_bit at PORTC.B6;
    const register unsigned short int RC7 = 7;
    sbit  RC7_bit at PORTC.B7;

sfr unsigned short volatile PORTD            absolute 0x00F;
    const register unsigned short int RD0 = 0;
    sbit  RD0_bit at PORTD.B0;
    const register unsigned short int RD1 = 1;
    sbit  RD1_bit at PORTD.B1;
    const register unsigned short int RD2 = 2;
    sbit  RD2_bit at PORTD.B2;
    const register unsigned short int RD3 = 3;
    sbit  RD3_bit at PORTD.B3;
    const register unsigned short int RD4 = 4;
    sbit  RD4_bit at PORTD.B4;
    const register unsigned short int RD5 = 5;
    sbit  RD5_bit at PORTD.B5;
    const register unsigned short int RD6 = 6;
    sbit  RD6_bit at PORTD.B6;
    const register unsigned short int RD7 = 7;
    sbit  RD7_bit at PORTD.B7;

sfr unsigned short volatile PORTE            absolute 0x010;
    const register unsigned short int RE0 = 0;
    sbit  RE0_bit at PORTE.B0;
    const register unsigned short int RE1 = 1;
    sbit  RE1_bit at PORTE.B1;
    const register unsigned short int RE2 = 2;
    sbit  RE2_bit at PORTE.B2;
    const register unsigned short int RE3 = 3;
    sbit  RE3_bit at PORTE.B3;

sfr unsigned short volatile PIR1             absolute 0x011;
    const register unsigned short int TMR1IF = 0;
    sbit  TMR1IF_bit at PIR1.B0;
    const register unsigned short int TMR2IF = 1;
    sbit  TMR2IF_bit at PIR1.B1;
    const register unsigned short int SSP2IF = 2;
    sbit  SSP2IF_bit at PIR1.B2;
    const register unsigned short int SSP1IF = 3;
    sbit  SSP1IF_bit at PIR1.B3;
    const register unsigned short int TXIF = 4;
    sbit  TXIF_bit at PIR1.B4;
    const register unsigned short int RCIF = 5;
    sbit  RCIF_bit at PIR1.B5;
    const register unsigned short int AD1IF = 6;
    sbit  AD1IF_bit at PIR1.B6;
    const register unsigned short int TMR1GIF = 7;
    sbit  TMR1GIF_bit at PIR1.B7;
    const register unsigned short int ADIF = 6;
    sbit  ADIF_bit at PIR1.B6;

sfr unsigned short volatile PIR2             absolute 0x012;
    const register unsigned short int TMR4IF = 1;
    sbit  TMR4IF_bit at PIR2.B1;
    const register unsigned short int BCL2IF = 2;
    sbit  BCL2IF_bit at PIR2.B2;
    const register unsigned short int BCL1IF = 3;
    sbit  BCL1IF_bit at PIR2.B3;
    const register unsigned short int AD2IF = 6;
    sbit  AD2IF_bit at PIR2.B6;

sfr unsigned short volatile TMR0             absolute 0x015;
sfr unsigned int   volatile TMR1             absolute 0x016;
sfr unsigned short volatile TMR1L            absolute 0x016;
sfr unsigned short volatile TMR1H            absolute 0x017;
sfr unsigned short volatile T1CON            absolute 0x018;
    const register unsigned short int TMR1ON = 0;
    sbit  TMR1ON_bit at T1CON.B0;
    const register unsigned short int nT1SYNC = 2;
    sbit  nT1SYNC_bit at T1CON.B2;
    const register unsigned short int T1CKPS0 = 4;
    sbit  T1CKPS0_bit at T1CON.B4;
    const register unsigned short int T1CKPS1 = 5;
    sbit  T1CKPS1_bit at T1CON.B5;
    const register unsigned short int TMR1CS0 = 6;
    sbit  TMR1CS0_bit at T1CON.B6;
    const register unsigned short int TMR1CS1 = 7;
    sbit  TMR1CS1_bit at T1CON.B7;

sfr unsigned short volatile T1GCON           absolute 0x019;
    const register unsigned short int T1GSS = 0;
    sbit  T1GSS_bit at T1GCON.B0;
    const register unsigned short int T1GVAL = 2;
    sbit  T1GVAL_bit at T1GCON.B2;
    const register unsigned short int T1GGO_nDONE = 3;
    sbit  T1GGO_nDONE_bit at T1GCON.B3;
    const register unsigned short int T1GSPM = 4;
    sbit  T1GSPM_bit at T1GCON.B4;
    const register unsigned short int T1GTM = 5;
    sbit  T1GTM_bit at T1GCON.B5;
    const register unsigned short int T1GPOL = 6;
    sbit  T1GPOL_bit at T1GCON.B6;
    const register unsigned short int TMR1GE = 7;
    sbit  TMR1GE_bit at T1GCON.B7;
    const register unsigned short int T1GSS0 = 0;
    sbit  T1GSS0_bit at T1GCON.B0;

sfr unsigned short volatile TMR2             absolute 0x01A;
sfr unsigned short volatile PR2              absolute 0x01B;
sfr unsigned short volatile T2CON            absolute 0x01C;
    const register unsigned short int T2CKPS0 = 0;
    sbit  T2CKPS0_bit at T2CON.B0;
    const register unsigned short int T2CKPS1 = 1;
    sbit  T2CKPS1_bit at T2CON.B1;
    const register unsigned short int TMR2ON = 2;
    sbit  TMR2ON_bit at T2CON.B2;
    const register unsigned short int T2OUTPS0 = 3;
    sbit  T2OUTPS0_bit at T2CON.B3;
    const register unsigned short int T2OUTPS1 = 4;
    sbit  T2OUTPS1_bit at T2CON.B4;
    const register unsigned short int T2OUTPS2 = 5;
    sbit  T2OUTPS2_bit at T2CON.B5;
    const register unsigned short int T2OUTPS3 = 6;
    sbit  T2OUTPS3_bit at T2CON.B6;

sfr unsigned short volatile TRISA            absolute 0x08C;
    const register unsigned short int TRISA0 = 0;
    sbit  TRISA0_bit at TRISA.B0;
    const register unsigned short int TRISA1 = 1;
    sbit  TRISA1_bit at TRISA.B1;
    const register unsigned short int TRISA2 = 2;
    sbit  TRISA2_bit at TRISA.B2;
    const register unsigned short int TRISA3 = 3;
    sbit  TRISA3_bit at TRISA.B3;
    const register unsigned short int TRISA4 = 4;
    sbit  TRISA4_bit at TRISA.B4;
    const register unsigned short int TRISA5 = 5;
    sbit  TRISA5_bit at TRISA.B5;
    const register unsigned short int TRISA6 = 6;
    sbit  TRISA6_bit at TRISA.B6;
    const register unsigned short int TRISA7 = 7;
    sbit  TRISA7_bit at TRISA.B7;

sfr unsigned short volatile TRISB            absolute 0x08D;
    const register unsigned short int TRISB0 = 0;
    sbit  TRISB0_bit at TRISB.B0;
    const register unsigned short int TRISB1 = 1;
    sbit  TRISB1_bit at TRISB.B1;
    const register unsigned short int TRISB2 = 2;
    sbit  TRISB2_bit at TRISB.B2;
    const register unsigned short int TRISB3 = 3;
    sbit  TRISB3_bit at TRISB.B3;
    const register unsigned short int TRISB4 = 4;
    sbit  TRISB4_bit at TRISB.B4;
    const register unsigned short int TRISB5 = 5;
    sbit  TRISB5_bit at TRISB.B5;
    const register unsigned short int TRISB6 = 6;
    sbit  TRISB6_bit at TRISB.B6;
    const register unsigned short int TRISB7 = 7;
    sbit  TRISB7_bit at TRISB.B7;

sfr unsigned short volatile TRISC            absolute 0x08E;
    const register unsigned short int TRISC0 = 0;
    sbit  TRISC0_bit at TRISC.B0;
    const register unsigned short int TRISC1 = 1;
    sbit  TRISC1_bit at TRISC.B1;
    const register unsigned short int TRISC2 = 2;
    sbit  TRISC2_bit at TRISC.B2;
    const register unsigned short int TRISC3 = 3;
    sbit  TRISC3_bit at TRISC.B3;
    const register unsigned short int TRISC4 = 4;
    sbit  TRISC4_bit at TRISC.B4;
    const register unsigned short int TRISC5 = 5;
    sbit  TRISC5_bit at TRISC.B5;
    const register unsigned short int TRISC6 = 6;
    sbit  TRISC6_bit at TRISC.B6;
    const register unsigned short int TRISC7 = 7;
    sbit  TRISC7_bit at TRISC.B7;

sfr unsigned short volatile TRISD            absolute 0x08F;
    const register unsigned short int TRISD0 = 0;
    sbit  TRISD0_bit at TRISD.B0;
    const register unsigned short int TRISD1 = 1;
    sbit  TRISD1_bit at TRISD.B1;
    const register unsigned short int TRISD2 = 2;
    sbit  TRISD2_bit at TRISD.B2;
    const register unsigned short int TRISD3 = 3;
    sbit  TRISD3_bit at TRISD.B3;
    const register unsigned short int TRISD4 = 4;
    sbit  TRISD4_bit at TRISD.B4;
    const register unsigned short int TRISD5 = 5;
    sbit  TRISD5_bit at TRISD.B5;
    const register unsigned short int TRISD6 = 6;
    sbit  TRISD6_bit at TRISD.B6;
    const register unsigned short int TRISD7 = 7;
    sbit  TRISD7_bit at TRISD.B7;

sfr unsigned short volatile TRISE            absolute 0x090;
    const register unsigned short int TRISE0 = 0;
    sbit  TRISE0_bit at TRISE.B0;
    const register unsigned short int TRISE1 = 1;
    sbit  TRISE1_bit at TRISE.B1;
    const register unsigned short int TRISE2 = 2;
    sbit  TRISE2_bit at TRISE.B2;
    const register unsigned short int TRISE3 = 3;
    sbit  TRISE3_bit at TRISE.B3;

sfr unsigned short volatile PIE1             absolute 0x091;
    const register unsigned short int TMR1IE = 0;
    sbit  TMR1IE_bit at PIE1.B0;
    const register unsigned short int TMR2IE = 1;
    sbit  TMR2IE_bit at PIE1.B1;
    const register unsigned short int SSP2IE = 2;
    sbit  SSP2IE_bit at PIE1.B2;
    const register unsigned short int SSP1IE = 3;
    sbit  SSP1IE_bit at PIE1.B3;
    const register unsigned short int TXIE = 4;
    sbit  TXIE_bit at PIE1.B4;
    const register unsigned short int RCIE = 5;
    sbit  RCIE_bit at PIE1.B5;
    const register unsigned short int AD1IE = 6;
    sbit  AD1IE_bit at PIE1.B6;
    const register unsigned short int TMR1GIE = 7;
    sbit  TMR1GIE_bit at PIE1.B7;
    const register unsigned short int ADIE = 6;
    sbit  ADIE_bit at PIE1.B6;
    const register unsigned short int SSPIE = 3;
    sbit  SSPIE_bit at PIE1.B3;

sfr unsigned short volatile PIE2             absolute 0x092;
    const register unsigned short int TMR4IE = 1;
    sbit  TMR4IE_bit at PIE2.B1;
    const register unsigned short int BCL2IE = 2;
    sbit  BCL2IE_bit at PIE2.B2;
    const register unsigned short int BCL1IE = 3;
    sbit  BCL1IE_bit at PIE2.B3;
    const register unsigned short int AD2IE = 6;
    sbit  AD2IE_bit at PIE2.B6;

sfr unsigned short volatile OPTION_REG       absolute 0x095;
    const register unsigned short int PS0 = 0;
    sbit  PS0_bit at OPTION_REG.B0;
    const register unsigned short int PS1 = 1;
    sbit  PS1_bit at OPTION_REG.B1;
    const register unsigned short int PS2 = 2;
    sbit  PS2_bit at OPTION_REG.B2;
    const register unsigned short int PSA = 3;
    sbit  PSA_bit at OPTION_REG.B3;
    const register unsigned short int T0SE = 4;
    sbit  T0SE_bit at OPTION_REG.B4;
    const register unsigned short int T0CS = 5;
    sbit  T0CS_bit at OPTION_REG.B5;
    const register unsigned short int INTEDG = 6;
    sbit  INTEDG_bit at OPTION_REG.B6;
    const register unsigned short int nWPUEN = 7;
    sbit  nWPUEN_bit at OPTION_REG.B7;
    const register unsigned short int TMR0CS = 5;
    sbit  TMR0CS_bit at OPTION_REG.B5;
    const register unsigned short int TMR0SE = 4;
    sbit  TMR0SE_bit at OPTION_REG.B4;

sfr unsigned short volatile PCON             absolute 0x096;
    const register unsigned short int nBOR = 0;
    sbit  nBOR_bit at PCON.B0;
    const register unsigned short int nPOR = 1;
    sbit  nPOR_bit at PCON.B1;
    const register unsigned short int nRI = 2;
    sbit  nRI_bit at PCON.B2;
    const register unsigned short int nRMCLR = 3;
    sbit  nRMCLR_bit at PCON.B3;
    const register unsigned short int nRWDT = 4;
    sbit  nRWDT_bit at PCON.B4;
    const register unsigned short int STKUNF = 6;
    sbit  STKUNF_bit at PCON.B6;
    const register unsigned short int STKOVF = 7;
    sbit  STKOVF_bit at PCON.B7;

sfr unsigned short          WDTCON           absolute 0x097;
    const register unsigned short int SWDTEN = 0;
    sbit  SWDTEN_bit at WDTCON.B0;
    const register unsigned short int WDTPS0 = 1;
    sbit  WDTPS0_bit at WDTCON.B1;
    const register unsigned short int WDTPS1 = 2;
    sbit  WDTPS1_bit at WDTCON.B2;
    const register unsigned short int WDTPS2 = 3;
    sbit  WDTPS2_bit at WDTCON.B3;
    const register unsigned short int WDTPS3 = 4;
    sbit  WDTPS3_bit at WDTCON.B4;
    const register unsigned short int WDTPS4 = 5;
    sbit  WDTPS4_bit at WDTCON.B5;

sfr unsigned short volatile OSCCON           absolute 0x099;
    const register unsigned short int SCS0 = 0;
    sbit  SCS0_bit at OSCCON.B0;
    const register unsigned short int SCS1 = 1;
    sbit  SCS1_bit at OSCCON.B1;
    const register unsigned short int IRCF0 = 3;
    sbit  IRCF0_bit at OSCCON.B3;
    const register unsigned short int IRCF1 = 4;
    sbit  IRCF1_bit at OSCCON.B4;
    const register unsigned short int IRCF2 = 5;
    sbit  IRCF2_bit at OSCCON.B5;
    const register unsigned short int IRCF3 = 6;
    sbit  IRCF3_bit at OSCCON.B6;
    const register unsigned short int SPLLEN = 7;
    sbit  SPLLEN_bit at OSCCON.B7;

sfr unsigned short volatile OSCSTAT          absolute 0x09A;
    const register unsigned short int HFIOFS = 0;
    sbit  HFIOFS_bit at OSCSTAT.B0;
    const register unsigned short int LFIOFR = 1;
    sbit  LFIOFR_bit at OSCSTAT.B1;
    const register unsigned short int HFIOFR = 4;
    sbit  HFIOFR_bit at OSCSTAT.B4;
    const register unsigned short int PLLSR = 6;
    sbit  PLLSR_bit at OSCSTAT.B6;

sfr unsigned int   volatile ADRES            absolute 0x09B;
sfr unsigned short volatile ADRESL           absolute 0x09B;
sfr unsigned short volatile ADRESH           absolute 0x09C;
sfr unsigned short volatile ADCON0           absolute 0x09D;
    const register unsigned short int ADGO = 1;
    sbit  ADGO_bit at ADCON0.B1;
    const register unsigned short int GO_NOT_DONE = 1;
    sbit  GO_NOT_DONE_bit at ADCON0.B1;

sfr unsigned short volatile ADCON1           absolute 0x09E;
sfr unsigned short volatile ADCON2           absolute 0x09F;
sfr unsigned short volatile LATA             absolute 0x10C;
    const register unsigned short int LATA0 = 0;
    sbit  LATA0_bit at LATA.B0;
    const register unsigned short int LATA1 = 1;
    sbit  LATA1_bit at LATA.B1;
    const register unsigned short int LATA2 = 2;
    sbit  LATA2_bit at LATA.B2;
    const register unsigned short int LATA3 = 3;
    sbit  LATA3_bit at LATA.B3;
    const register unsigned short int LATA4 = 4;
    sbit  LATA4_bit at LATA.B4;
    const register unsigned short int LATA5 = 5;
    sbit  LATA5_bit at LATA.B5;
    const register unsigned short int LATA6 = 6;
    sbit  LATA6_bit at LATA.B6;
    const register unsigned short int LATA7 = 7;
    sbit  LATA7_bit at LATA.B7;

sfr unsigned short volatile LATB             absolute 0x10D;
    const register unsigned short int LATB0 = 0;
    sbit  LATB0_bit at LATB.B0;
    const register unsigned short int LATB1 = 1;
    sbit  LATB1_bit at LATB.B1;
    const register unsigned short int LATB2 = 2;
    sbit  LATB2_bit at LATB.B2;
    const register unsigned short int LATB3 = 3;
    sbit  LATB3_bit at LATB.B3;
    const register unsigned short int LATB4 = 4;
    sbit  LATB4_bit at LATB.B4;
    const register unsigned short int LATB5 = 5;
    sbit  LATB5_bit at LATB.B5;
    const register unsigned short int LATB6 = 6;
    sbit  LATB6_bit at LATB.B6;
    const register unsigned short int LATB7 = 7;
    sbit  LATB7_bit at LATB.B7;

sfr unsigned short volatile LATC             absolute 0x10E;
    const register unsigned short int LATC0 = 0;
    sbit  LATC0_bit at LATC.B0;
    const register unsigned short int LATC1 = 1;
    sbit  LATC1_bit at LATC.B1;
    const register unsigned short int LATC2 = 2;
    sbit  LATC2_bit at LATC.B2;
    const register unsigned short int LATC3 = 3;
    sbit  LATC3_bit at LATC.B3;
    const register unsigned short int LATC4 = 4;
    sbit  LATC4_bit at LATC.B4;
    const register unsigned short int LATC5 = 5;
    sbit  LATC5_bit at LATC.B5;
    const register unsigned short int LATC6 = 6;
    sbit  LATC6_bit at LATC.B6;
    const register unsigned short int LATC7 = 7;
    sbit  LATC7_bit at LATC.B7;

sfr unsigned short volatile LATD             absolute 0x10F;
    const register unsigned short int LATD0 = 0;
    sbit  LATD0_bit at LATD.B0;
    const register unsigned short int LATD1 = 1;
    sbit  LATD1_bit at LATD.B1;
    const register unsigned short int LATD2 = 2;
    sbit  LATD2_bit at LATD.B2;
    const register unsigned short int LATD3 = 3;
    sbit  LATD3_bit at LATD.B3;
    const register unsigned short int LATD4 = 4;
    sbit  LATD4_bit at LATD.B4;
    const register unsigned short int LATD5 = 5;
    sbit  LATD5_bit at LATD.B5;
    const register unsigned short int LATD6 = 6;
    sbit  LATD6_bit at LATD.B6;
    const register unsigned short int LATD7 = 7;
    sbit  LATD7_bit at LATD.B7;

sfr unsigned short volatile LATE             absolute 0x110;
    const register unsigned short int LATE0 = 0;
    sbit  LATE0_bit at LATE.B0;
    const register unsigned short int LATE1 = 1;
    sbit  LATE1_bit at LATE.B1;
    const register unsigned short int LATE2 = 2;
    sbit  LATE2_bit at LATE.B2;

sfr unsigned short volatile BORCON           absolute 0x116;
    const register unsigned short int BORRDY = 0;
    sbit  BORRDY_bit at BORCON.B0;
    const register unsigned short int BORFS = 6;
    sbit  BORFS_bit at BORCON.B6;
    const register unsigned short int SBOREN = 7;
    sbit  SBOREN_bit at BORCON.B7;

sfr unsigned short volatile FVRCON           absolute 0x117;
    const register unsigned short int ADFVR0 = 0;
    sbit  ADFVR0_bit at FVRCON.B0;
    const register unsigned short int ADFVR1 = 1;
    sbit  ADFVR1_bit at FVRCON.B1;
    const register unsigned short int TSRNG = 4;
    sbit  TSRNG_bit at FVRCON.B4;
    const register unsigned short int TSEN = 5;
    sbit  TSEN_bit at FVRCON.B5;
    const register unsigned short int FVRRDY = 6;
    sbit  FVRRDY_bit at FVRCON.B6;
    const register unsigned short int FVREN = 7;
    sbit  FVREN_bit at FVRCON.B7;

sfr unsigned short          APFCON           absolute 0x11D;
    const register unsigned short int GRDASEL = 0;
    sbit  GRDASEL_bit at APFCON.B0;
    const register unsigned short int GRDBSEL = 1;
    sbit  GRDBSEL_bit at APFCON.B1;
    const register unsigned short int SSSEL = 5;
    sbit  SSSEL_bit at APFCON.B5;

sfr unsigned short volatile ANSELA           absolute 0x18C;
    const register unsigned short int ANSA0 = 0;
    sbit  ANSA0_bit at ANSELA.B0;
    const register unsigned short int ANSA1 = 1;
    sbit  ANSA1_bit at ANSELA.B1;
    const register unsigned short int ANSA2 = 2;
    sbit  ANSA2_bit at ANSELA.B2;
    const register unsigned short int ANSA3 = 3;
    sbit  ANSA3_bit at ANSELA.B3;
    const register unsigned short int ANSA4 = 4;
    sbit  ANSA4_bit at ANSELA.B4;
    const register unsigned short int ANSA5 = 5;
    sbit  ANSA5_bit at ANSELA.B5;
    const register unsigned short int ANSA6 = 6;
    sbit  ANSA6_bit at ANSELA.B6;
    const register unsigned short int ANSA7 = 7;
    sbit  ANSA7_bit at ANSELA.B7;

sfr unsigned short volatile ANSELB           absolute 0x18D;
    const register unsigned short int ANSB0 = 0;
    sbit  ANSB0_bit at ANSELB.B0;
    const register unsigned short int ANSB1 = 1;
    sbit  ANSB1_bit at ANSELB.B1;
    const register unsigned short int ANSB2 = 2;
    sbit  ANSB2_bit at ANSELB.B2;
    const register unsigned short int ANSB3 = 3;
    sbit  ANSB3_bit at ANSELB.B3;
    const register unsigned short int ANSB4 = 4;
    sbit  ANSB4_bit at ANSELB.B4;
    const register unsigned short int ANSB5 = 5;
    sbit  ANSB5_bit at ANSELB.B5;
    const register unsigned short int ANSB6 = 6;
    sbit  ANSB6_bit at ANSELB.B6;
    const register unsigned short int ANSB7 = 7;
    sbit  ANSB7_bit at ANSELB.B7;

sfr unsigned short volatile ANSELC           absolute 0x18E;
    const register unsigned short int ANSC0 = 0;
    sbit  ANSC0_bit at ANSELC.B0;
    const register unsigned short int ANSC1 = 1;
    sbit  ANSC1_bit at ANSELC.B1;
    const register unsigned short int ANSC2 = 2;
    sbit  ANSC2_bit at ANSELC.B2;
    const register unsigned short int ANSC3 = 3;
    sbit  ANSC3_bit at ANSELC.B3;
    const register unsigned short int ANSC4 = 4;
    sbit  ANSC4_bit at ANSELC.B4;
    const register unsigned short int ANSC5 = 5;
    sbit  ANSC5_bit at ANSELC.B5;
    const register unsigned short int ANSC6 = 6;
    sbit  ANSC6_bit at ANSELC.B6;
    const register unsigned short int ANSC7 = 7;
    sbit  ANSC7_bit at ANSELC.B7;

sfr unsigned short volatile ANSELD           absolute 0x18F;
    const register unsigned short int ANSD0 = 0;
    sbit  ANSD0_bit at ANSELD.B0;
    const register unsigned short int ANSD1 = 1;
    sbit  ANSD1_bit at ANSELD.B1;
    const register unsigned short int ANSD2 = 2;
    sbit  ANSD2_bit at ANSELD.B2;
    const register unsigned short int ANSD3 = 3;
    sbit  ANSD3_bit at ANSELD.B3;
    const register unsigned short int ANSD4 = 4;
    sbit  ANSD4_bit at ANSELD.B4;
    const register unsigned short int ANSD5 = 5;
    sbit  ANSD5_bit at ANSELD.B5;
    const register unsigned short int ANSD6 = 6;
    sbit  ANSD6_bit at ANSELD.B6;
    const register unsigned short int ANSD7 = 7;
    sbit  ANSD7_bit at ANSELD.B7;

sfr unsigned short volatile ANSELE           absolute 0x190;
    const register unsigned short int ANSE0 = 0;
    sbit  ANSE0_bit at ANSELE.B0;
    const register unsigned short int ANSE1 = 1;
    sbit  ANSE1_bit at ANSELE.B1;
    const register unsigned short int ANSE2 = 2;
    sbit  ANSE2_bit at ANSELE.B2;

sfr unsigned int   volatile PMADR            absolute 0x191;
sfr unsigned short volatile PMADRL           absolute 0x191;
sfr unsigned short volatile PMADRH           absolute 0x192;
sfr unsigned int   volatile PMDAT            absolute 0x193;
sfr unsigned short volatile PMDATL           absolute 0x193;
sfr unsigned short volatile PMDATH           absolute 0x194;
sfr unsigned short volatile PMCON1           absolute 0x195;
    const register unsigned short int RD = 0;
    sbit  RD_bit at PMCON1.B0;
    const register unsigned short int WR = 1;
    sbit  WR_bit at PMCON1.B1;
    const register unsigned short int WREN = 2;
    sbit  WREN_bit at PMCON1.B2;
    const register unsigned short int WRERR = 3;
    sbit  WRERR_bit at PMCON1.B3;
    const register unsigned short int FREE = 4;
    sbit  FREE_bit at PMCON1.B4;
    const register unsigned short int LWLO = 5;
    sbit  LWLO_bit at PMCON1.B5;
    const register unsigned short int CFGS = 6;
    sbit  CFGS_bit at PMCON1.B6;

sfr unsigned short volatile PMCON2           absolute 0x196;
sfr unsigned short volatile RC1REG           absolute 0x199;
sfr unsigned short volatile RCREG            absolute 0x199;
sfr unsigned short volatile TX1REG           absolute 0x19A;
sfr unsigned short volatile TXREG            absolute 0x19A;
sfr unsigned int            SPBRG            absolute 0x19B;
sfr unsigned short volatile SPBRGL           absolute 0x19B;
sfr unsigned short          SPBRGH           absolute 0x19C;
sfr unsigned short volatile RCSTA            absolute 0x19D;
    const register unsigned short int RX9D = 0;
    sbit  RX9D_bit at RCSTA.B0;
    const register unsigned short int OERR = 1;
    sbit  OERR_bit at RCSTA.B1;
    const register unsigned short int FERR = 2;
    sbit  FERR_bit at RCSTA.B2;
    const register unsigned short int ADDEN = 3;
    sbit  ADDEN_bit at RCSTA.B3;
    const register unsigned short int CREN = 4;
    sbit  CREN_bit at RCSTA.B4;
    const register unsigned short int SREN = 5;
    sbit  SREN_bit at RCSTA.B5;
    const register unsigned short int RX9 = 6;
    sbit  RX9_bit at RCSTA.B6;
    const register unsigned short int SPEN = 7;
    sbit  SPEN_bit at RCSTA.B7;

sfr unsigned short volatile RC1STA           absolute 0x19D;
sfr unsigned short volatile TXSTA            absolute 0x19E;
    const register unsigned short int TX9D = 0;
    sbit  TX9D_bit at TXSTA.B0;
    const register unsigned short int TRMT = 1;
    sbit  TRMT_bit at TXSTA.B1;
    const register unsigned short int BRGH = 2;
    sbit  BRGH_bit at TXSTA.B2;
    const register unsigned short int SENDB = 3;
    sbit  SENDB_bit at TXSTA.B3;
    const register unsigned short int SYNC = 4;
    sbit  SYNC_bit at TXSTA.B4;
    const register unsigned short int TXEN = 5;
    sbit  TXEN_bit at TXSTA.B5;
    const register unsigned short int TX9 = 6;
    sbit  TX9_bit at TXSTA.B6;
    const register unsigned short int CSRC = 7;
    sbit  CSRC_bit at TXSTA.B7;

sfr unsigned short volatile TX1STA           absolute 0x19E;
sfr unsigned short          BAUDCON          absolute 0x19F;
    const register unsigned short int ABDEN = 0;
    sbit  ABDEN_bit at BAUDCON.B0;
    const register unsigned short int WUE = 1;
    sbit  WUE_bit at BAUDCON.B1;
    const register unsigned short int BRG16 = 3;
    sbit  BRG16_bit at BAUDCON.B3;
    const register unsigned short int SCKP = 4;
    sbit  SCKP_bit at BAUDCON.B4;
    const register unsigned short int RCIDL = 6;
    sbit  RCIDL_bit at BAUDCON.B6;
    const register unsigned short int ABDOVF = 7;
    sbit  ABDOVF_bit at BAUDCON.B7;

sfr unsigned short          WPUB             absolute 0x20D;
    const register unsigned short int WPUB0 = 0;
    sbit  WPUB0_bit at WPUB.B0;
    const register unsigned short int WPUB1 = 1;
    sbit  WPUB1_bit at WPUB.B1;
    const register unsigned short int WPUB2 = 2;
    sbit  WPUB2_bit at WPUB.B2;
    const register unsigned short int WPUB3 = 3;
    sbit  WPUB3_bit at WPUB.B3;
    const register unsigned short int WPUB4 = 4;
    sbit  WPUB4_bit at WPUB.B4;
    const register unsigned short int WPUB5 = 5;
    sbit  WPUB5_bit at WPUB.B5;
    const register unsigned short int WPUB6 = 6;
    sbit  WPUB6_bit at WPUB.B6;
    const register unsigned short int WPUB7 = 7;
    sbit  WPUB7_bit at WPUB.B7;

sfr unsigned short volatile WPUE             absolute 0x210;
    const register unsigned short int WPUE3 = 3;
    sbit  WPUE3_bit at WPUE.B3;

sfr unsigned short volatile SSP1BUF          absolute 0x211;
    const register unsigned short int SSP1BUF0 = 0;
    sbit  SSP1BUF0_bit at SSP1BUF.B0;
    const register unsigned short int SSP1BUF1 = 1;
    sbit  SSP1BUF1_bit at SSP1BUF.B1;
    const register unsigned short int SSP1BUF2 = 2;
    sbit  SSP1BUF2_bit at SSP1BUF.B2;
    const register unsigned short int SSP1BUF3 = 3;
    sbit  SSP1BUF3_bit at SSP1BUF.B3;
    const register unsigned short int SSP1BUF4 = 4;
    sbit  SSP1BUF4_bit at SSP1BUF.B4;
    const register unsigned short int SSP1BUF5 = 5;
    sbit  SSP1BUF5_bit at SSP1BUF.B5;
    const register unsigned short int SSP1BUF6 = 6;
    sbit  SSP1BUF6_bit at SSP1BUF.B6;
    const register unsigned short int SSP1BUF7 = 7;
    sbit  SSP1BUF7_bit at SSP1BUF.B7;

sfr unsigned short volatile SSPBUF           absolute 0x211;
sfr unsigned short volatile SSP1ADD          absolute 0x212;
    const register unsigned short int SSP1ADD0 = 0;
    sbit  SSP1ADD0_bit at SSP1ADD.B0;
    const register unsigned short int SSP1ADD1 = 1;
    sbit  SSP1ADD1_bit at SSP1ADD.B1;
    const register unsigned short int SSP1ADD2 = 2;
    sbit  SSP1ADD2_bit at SSP1ADD.B2;
    const register unsigned short int SSP1ADD3 = 3;
    sbit  SSP1ADD3_bit at SSP1ADD.B3;
    const register unsigned short int SSP1ADD4 = 4;
    sbit  SSP1ADD4_bit at SSP1ADD.B4;
    const register unsigned short int SSP1ADD5 = 5;
    sbit  SSP1ADD5_bit at SSP1ADD.B5;
    const register unsigned short int SSP1ADD6 = 6;
    sbit  SSP1ADD6_bit at SSP1ADD.B6;
    const register unsigned short int SSP1ADD7 = 7;
    sbit  SSP1ADD7_bit at SSP1ADD.B7;

sfr unsigned short volatile SSPADD           absolute 0x212;
sfr unsigned short volatile SSP1MSK          absolute 0x213;
    const register unsigned short int SSP1MSK0 = 0;
    sbit  SSP1MSK0_bit at SSP1MSK.B0;
    const register unsigned short int SSP1MSK1 = 1;
    sbit  SSP1MSK1_bit at SSP1MSK.B1;
    const register unsigned short int SSP1MSK2 = 2;
    sbit  SSP1MSK2_bit at SSP1MSK.B2;
    const register unsigned short int SSP1MSK3 = 3;
    sbit  SSP1MSK3_bit at SSP1MSK.B3;
    const register unsigned short int SSP1MSK4 = 4;
    sbit  SSP1MSK4_bit at SSP1MSK.B4;
    const register unsigned short int SSP1MSK5 = 5;
    sbit  SSP1MSK5_bit at SSP1MSK.B5;
    const register unsigned short int SSP1MSK6 = 6;
    sbit  SSP1MSK6_bit at SSP1MSK.B6;
    const register unsigned short int SSP1MSK7 = 7;
    sbit  SSP1MSK7_bit at SSP1MSK.B7;

sfr unsigned short volatile SSPMSK           absolute 0x213;
sfr unsigned short volatile SSP1STAT         absolute 0x214;
sfr unsigned short volatile SSPSTAT          absolute 0x214;
sfr unsigned short volatile SSP1CON1         absolute 0x215;
sfr unsigned short volatile SSPCON           absolute 0x215;
sfr unsigned short volatile SSPCON1          absolute 0x215;
sfr unsigned short volatile SSP1CON          absolute 0x215;
sfr unsigned short volatile SSP1CON2         absolute 0x216;
sfr unsigned short volatile SSPCON2          absolute 0x216;
sfr unsigned short volatile SSP1CON3         absolute 0x217;
sfr unsigned short volatile SSPCON3          absolute 0x217;
sfr unsigned short volatile SSPLVL           absolute 0x218;
    const register unsigned short int S1ILS = 0;
    sbit  S1ILS_bit at SSPLVL.B0;
    const register unsigned short int S2ILS = 4;
    sbit  S2ILS_bit at SSPLVL.B4;

sfr unsigned short volatile SSP2BUF          absolute 0x219;
    const register unsigned short int SSP2BUF0 = 0;
    sbit  SSP2BUF0_bit at SSP2BUF.B0;
    const register unsigned short int SSP2BUF1 = 1;
    sbit  SSP2BUF1_bit at SSP2BUF.B1;
    const register unsigned short int SSP2BUF2 = 2;
    sbit  SSP2BUF2_bit at SSP2BUF.B2;
    const register unsigned short int SSP2BUF3 = 3;
    sbit  SSP2BUF3_bit at SSP2BUF.B3;
    const register unsigned short int SSP2BUF4 = 4;
    sbit  SSP2BUF4_bit at SSP2BUF.B4;
    const register unsigned short int SSP2BUF5 = 5;
    sbit  SSP2BUF5_bit at SSP2BUF.B5;
    const register unsigned short int SSP2BUF6 = 6;
    sbit  SSP2BUF6_bit at SSP2BUF.B6;
    const register unsigned short int SSP2BUF7 = 7;
    sbit  SSP2BUF7_bit at SSP2BUF.B7;

sfr unsigned short volatile SSP2ADD          absolute 0x21A;
    const register unsigned short int SSP2ADD0 = 0;
    sbit  SSP2ADD0_bit at SSP2ADD.B0;
    const register unsigned short int SSP2ADD1 = 1;
    sbit  SSP2ADD1_bit at SSP2ADD.B1;
    const register unsigned short int SSP2ADD2 = 2;
    sbit  SSP2ADD2_bit at SSP2ADD.B2;
    const register unsigned short int SSP2ADD3 = 3;
    sbit  SSP2ADD3_bit at SSP2ADD.B3;
    const register unsigned short int SSP2ADD4 = 4;
    sbit  SSP2ADD4_bit at SSP2ADD.B4;
    const register unsigned short int SSP2ADD5 = 5;
    sbit  SSP2ADD5_bit at SSP2ADD.B5;
    const register unsigned short int SSP2ADD6 = 6;
    sbit  SSP2ADD6_bit at SSP2ADD.B6;
    const register unsigned short int SSP2ADD7 = 7;
    sbit  SSP2ADD7_bit at SSP2ADD.B7;

sfr unsigned short volatile SSP2MSK          absolute 0x21B;
    const register unsigned short int SSP2MSK0 = 0;
    sbit  SSP2MSK0_bit at SSP2MSK.B0;
    const register unsigned short int SSP2MSK1 = 1;
    sbit  SSP2MSK1_bit at SSP2MSK.B1;
    const register unsigned short int SSP2MSK2 = 2;
    sbit  SSP2MSK2_bit at SSP2MSK.B2;
    const register unsigned short int SSP2MSK3 = 3;
    sbit  SSP2MSK3_bit at SSP2MSK.B3;
    const register unsigned short int SSP2MSK4 = 4;
    sbit  SSP2MSK4_bit at SSP2MSK.B4;
    const register unsigned short int SSP2MSK5 = 5;
    sbit  SSP2MSK5_bit at SSP2MSK.B5;
    const register unsigned short int SSP2MSK6 = 6;
    sbit  SSP2MSK6_bit at SSP2MSK.B6;
    const register unsigned short int SSP2MSK7 = 7;
    sbit  SSP2MSK7_bit at SSP2MSK.B7;

sfr unsigned short volatile SSP2STAT         absolute 0x21C;
sfr unsigned short volatile SSP2CON1         absolute 0x21D;
sfr unsigned short volatile SSP2CON          absolute 0x21D;
sfr unsigned short volatile SSP2CON2         absolute 0x21E;
sfr unsigned short volatile SSP2CON3         absolute 0x21F;
sfr unsigned short volatile IOCBP            absolute 0x394;
    const register unsigned short int IOCBP0 = 0;
    sbit  IOCBP0_bit at IOCBP.B0;
    const register unsigned short int IOCBP1 = 1;
    sbit  IOCBP1_bit at IOCBP.B1;
    const register unsigned short int IOCBP2 = 2;
    sbit  IOCBP2_bit at IOCBP.B2;
    const register unsigned short int IOCBP3 = 3;
    sbit  IOCBP3_bit at IOCBP.B3;
    const register unsigned short int IOCBP4 = 4;
    sbit  IOCBP4_bit at IOCBP.B4;
    const register unsigned short int IOCBP5 = 5;
    sbit  IOCBP5_bit at IOCBP.B5;
    const register unsigned short int IOCBP6 = 6;
    sbit  IOCBP6_bit at IOCBP.B6;
    const register unsigned short int IOCBP7 = 7;
    sbit  IOCBP7_bit at IOCBP.B7;

sfr unsigned short volatile IOCBN            absolute 0x395;
    const register unsigned short int IOCBN0 = 0;
    sbit  IOCBN0_bit at IOCBN.B0;
    const register unsigned short int IOCBN1 = 1;
    sbit  IOCBN1_bit at IOCBN.B1;
    const register unsigned short int IOCBN2 = 2;
    sbit  IOCBN2_bit at IOCBN.B2;
    const register unsigned short int IOCBN3 = 3;
    sbit  IOCBN3_bit at IOCBN.B3;
    const register unsigned short int IOCBN4 = 4;
    sbit  IOCBN4_bit at IOCBN.B4;
    const register unsigned short int IOCBN5 = 5;
    sbit  IOCBN5_bit at IOCBN.B5;
    const register unsigned short int IOCBN6 = 6;
    sbit  IOCBN6_bit at IOCBN.B6;
    const register unsigned short int IOCBN7 = 7;
    sbit  IOCBN7_bit at IOCBN.B7;

sfr unsigned short volatile IOCBF            absolute 0x396;
    const register unsigned short int IOCBF0 = 0;
    sbit  IOCBF0_bit at IOCBF.B0;
    const register unsigned short int IOCBF1 = 1;
    sbit  IOCBF1_bit at IOCBF.B1;
    const register unsigned short int IOCBF2 = 2;
    sbit  IOCBF2_bit at IOCBF.B2;
    const register unsigned short int IOCBF3 = 3;
    sbit  IOCBF3_bit at IOCBF.B3;
    const register unsigned short int IOCBF4 = 4;
    sbit  IOCBF4_bit at IOCBF.B4;
    const register unsigned short int IOCBF5 = 5;
    sbit  IOCBF5_bit at IOCBF.B5;
    const register unsigned short int IOCBF6 = 6;
    sbit  IOCBF6_bit at IOCBF.B6;
    const register unsigned short int IOCBF7 = 7;
    sbit  IOCBF7_bit at IOCBF.B7;

sfr unsigned short volatile TMR4             absolute 0x415;
sfr unsigned short volatile PR4              absolute 0x416;
sfr unsigned short volatile T4CON            absolute 0x417;
    const register unsigned short int T4CKPS0 = 0;
    sbit  T4CKPS0_bit at T4CON.B0;
    const register unsigned short int T4CKPS1 = 1;
    sbit  T4CKPS1_bit at T4CON.B1;
    const register unsigned short int TMR4ON = 2;
    sbit  TMR4ON_bit at T4CON.B2;
    const register unsigned short int T4OUTPS0 = 3;
    sbit  T4OUTPS0_bit at T4CON.B3;
    const register unsigned short int T4OUTPS1 = 4;
    sbit  T4OUTPS1_bit at T4CON.B4;
    const register unsigned short int T4OUTPS2 = 5;
    sbit  T4OUTPS2_bit at T4CON.B5;
    const register unsigned short int T4OUTPS3 = 6;
    sbit  T4OUTPS3_bit at T4CON.B6;

sfr unsigned short volatile PWM1DCL          absolute 0x611;
    const register unsigned short int PWM1DCL0 = 6;
    sbit  PWM1DCL0_bit at PWM1DCL.B6;
    const register unsigned short int PWM1DCL1 = 7;
    sbit  PWM1DCL1_bit at PWM1DCL.B7;

sfr unsigned short volatile PWM1DCH          absolute 0x612;
    const register unsigned short int PWM1DCH0 = 0;
    sbit  PWM1DCH0_bit at PWM1DCH.B0;
    const register unsigned short int PWM1DCH1 = 1;
    sbit  PWM1DCH1_bit at PWM1DCH.B1;
    const register unsigned short int PWM1DCH2 = 2;
    sbit  PWM1DCH2_bit at PWM1DCH.B2;
    const register unsigned short int PWM1DCH3 = 3;
    sbit  PWM1DCH3_bit at PWM1DCH.B3;
    const register unsigned short int PWM1DCH4 = 4;
    sbit  PWM1DCH4_bit at PWM1DCH.B4;
    const register unsigned short int PWM1DCH5 = 5;
    sbit  PWM1DCH5_bit at PWM1DCH.B5;
    const register unsigned short int PWM1DCH6 = 6;
    sbit  PWM1DCH6_bit at PWM1DCH.B6;
    const register unsigned short int PWM1DCH7 = 7;
    sbit  PWM1DCH7_bit at PWM1DCH.B7;

sfr unsigned short          PWM1CON          absolute 0x613;
    const register unsigned short int PWM1POL = 4;
    sbit  PWM1POL_bit at PWM1CON.B4;
    const register unsigned short int PWM1OUT = 5;
    sbit  PWM1OUT_bit at PWM1CON.B5;
    const register unsigned short int PWM1OE = 6;
    sbit  PWM1OE_bit at PWM1CON.B6;
    const register unsigned short int PWM1EN = 7;
    sbit  PWM1EN_bit at PWM1CON.B7;

sfr unsigned short volatile PWM1CON0         absolute 0x613;
sfr unsigned short volatile PWM2DCL          absolute 0x614;
    const register unsigned short int PWM2DCL0 = 6;
    sbit  PWM2DCL0_bit at PWM2DCL.B6;
    const register unsigned short int PWM2DCL1 = 7;
    sbit  PWM2DCL1_bit at PWM2DCL.B7;

sfr unsigned short volatile PWM2DCH          absolute 0x615;
    const register unsigned short int PWM2DCH0 = 0;
    sbit  PWM2DCH0_bit at PWM2DCH.B0;
    const register unsigned short int PWM2DCH1 = 1;
    sbit  PWM2DCH1_bit at PWM2DCH.B1;
    const register unsigned short int PWM2DCH2 = 2;
    sbit  PWM2DCH2_bit at PWM2DCH.B2;
    const register unsigned short int PWM2DCH3 = 3;
    sbit  PWM2DCH3_bit at PWM2DCH.B3;
    const register unsigned short int PWM2DCH4 = 4;
    sbit  PWM2DCH4_bit at PWM2DCH.B4;
    const register unsigned short int PWM2DCH5 = 5;
    sbit  PWM2DCH5_bit at PWM2DCH.B5;
    const register unsigned short int PWM2DCH6 = 6;
    sbit  PWM2DCH6_bit at PWM2DCH.B6;
    const register unsigned short int PWM2DCH7 = 7;
    sbit  PWM2DCH7_bit at PWM2DCH.B7;

sfr unsigned short          PWM2CON          absolute 0x616;
    const register unsigned short int PWM2POL = 4;
    sbit  PWM2POL_bit at PWM2CON.B4;
    const register unsigned short int PWM2OUT = 5;
    sbit  PWM2OUT_bit at PWM2CON.B5;
    const register unsigned short int PWM2OE = 6;
    sbit  PWM2OE_bit at PWM2CON.B6;
    const register unsigned short int PWM2EN = 7;
    sbit  PWM2EN_bit at PWM2CON.B7;

sfr unsigned short volatile PWM2CON0         absolute 0x616;
sfr unsigned short volatile PWMTMRS          absolute 0x61D;
    const register unsigned short int P1TSEL = 0;
    sbit  P1TSEL_bit at PWMTMRS.B0;
    const register unsigned short int P2TSEL = 2;
    sbit  P2TSEL_bit at PWMTMRS.B2;

sfr unsigned short volatile PWM1AOE          absolute 0x61E;
    const register unsigned short int PWM1OE0 = 0;
    sbit  PWM1OE0_bit at PWM1AOE.B0;
    const register unsigned short int PWM1OE1 = 1;
    sbit  PWM1OE1_bit at PWM1AOE.B1;
    const register unsigned short int PWM1OE2 = 2;
    sbit  PWM1OE2_bit at PWM1AOE.B2;
    const register unsigned short int PWM1OE3 = 3;
    sbit  PWM1OE3_bit at PWM1AOE.B3;

sfr unsigned short volatile PWM2AOE          absolute 0x61F;
    const register unsigned short int PWM2OE0 = 0;
    sbit  PWM2OE0_bit at PWM2AOE.B0;
    const register unsigned short int PWM2OE1 = 1;
    sbit  PWM2OE1_bit at PWM2AOE.B1;
    const register unsigned short int PWM2OE2 = 2;
    sbit  PWM2OE2_bit at PWM2AOE.B2;
    const register unsigned short int PWM2OE3 = 3;
    sbit  PWM2OE3_bit at PWM2AOE.B3;

sfr unsigned short volatile ADCTX            absolute 0x691;
    const register unsigned short int A1TX0 = 0;
    sbit  A1TX0_bit at ADCTX.B0;
    const register unsigned short int A1TX1 = 1;
    sbit  A1TX1_bit at ADCTX.B1;
    const register unsigned short int A1TX2 = 2;
    sbit  A1TX2_bit at ADCTX.B2;
    const register unsigned short int A2TX0 = 4;
    sbit  A2TX0_bit at ADCTX.B4;
    const register unsigned short int A2TX1 = 5;
    sbit  A2TX1_bit at ADCTX.B5;
    const register unsigned short int A2TX2 = 6;
    sbit  A2TX2_bit at ADCTX.B6;

sfr unsigned short volatile AD1TX            absolute 0x692;
sfr unsigned short volatile AAD1TX           absolute 0x692;
sfr unsigned short volatile AD1TX0           absolute 0x692;
    const register unsigned short int TX10 = 0;
    sbit  TX10_bit at AD1TX0.B0;
    const register unsigned short int TX11 = 1;
    sbit  TX11_bit at AD1TX0.B1;
    const register unsigned short int TX12 = 2;
    sbit  TX12_bit at AD1TX0.B2;
    const register unsigned short int TX13 = 3;
    sbit  TX13_bit at AD1TX0.B3;
    const register unsigned short int TX14 = 4;
    sbit  TX14_bit at AD1TX0.B4;
    const register unsigned short int TX15 = 5;
    sbit  TX15_bit at AD1TX0.B5;
    const register unsigned short int TX16 = 6;
    sbit  TX16_bit at AD1TX0.B6;
    const register unsigned short int TX17 = 7;
    sbit  TX17_bit at AD1TX0.B7;

sfr unsigned short volatile AAD1TX0          absolute 0x692;
sfr unsigned short volatile AD1TX1           absolute 0x693;
    const register unsigned short int TX18 = 0;
    sbit  TX18_bit at AD1TX1.B0;
    const register unsigned short int TX19 = 1;
    sbit  TX19_bit at AD1TX1.B1;
    const register unsigned short int TX30 = 2;
    sbit  TX30_bit at AD1TX1.B2;
    const register unsigned short int TX31 = 3;
    sbit  TX31_bit at AD1TX1.B3;
    const register unsigned short int TX32 = 4;
    sbit  TX32_bit at AD1TX1.B4;
    const register unsigned short int TX33 = 5;
    sbit  TX33_bit at AD1TX1.B5;
    const register unsigned short int TX34 = 6;
    sbit  TX34_bit at AD1TX1.B6;
    const register unsigned short int TX35 = 7;
    sbit  TX35_bit at AD1TX1.B7;

sfr unsigned short volatile AAD1TX1          absolute 0x693;
sfr unsigned short volatile AD2TX            absolute 0x694;
sfr unsigned short volatile AAD2TX           absolute 0x694;
sfr unsigned short volatile AD2TX0           absolute 0x694;
    const register unsigned short int TX20 = 0;
    sbit  TX20_bit at AD2TX0.B0;
    const register unsigned short int TX21 = 1;
    sbit  TX21_bit at AD2TX0.B1;
    const register unsigned short int TX22 = 2;
    sbit  TX22_bit at AD2TX0.B2;
    const register unsigned short int TX23 = 3;
    sbit  TX23_bit at AD2TX0.B3;
    const register unsigned short int TX24 = 4;
    sbit  TX24_bit at AD2TX0.B4;
    const register unsigned short int TX25 = 5;
    sbit  TX25_bit at AD2TX0.B5;
    const register unsigned short int TX26 = 6;
    sbit  TX26_bit at AD2TX0.B6;
    const register unsigned short int TX27 = 7;
    sbit  TX27_bit at AD2TX0.B7;

sfr unsigned short volatile AAD2TX0          absolute 0x694;
sfr unsigned short volatile AD2TX1           absolute 0x695;
    const register unsigned short int TX28 = 0;
    sbit  TX28_bit at AD2TX1.B0;
    const register unsigned short int TX29 = 1;
    sbit  TX29_bit at AD2TX1.B1;
    const register unsigned short int TX40 = 2;
    sbit  TX40_bit at AD2TX1.B2;
    const register unsigned short int TX41 = 3;
    sbit  TX41_bit at AD2TX1.B3;
    const register unsigned short int TX42 = 4;
    sbit  TX42_bit at AD2TX1.B4;
    const register unsigned short int TX43 = 5;
    sbit  TX43_bit at AD2TX1.B5;
    const register unsigned short int TX44 = 6;
    sbit  TX44_bit at AD2TX1.B6;
    const register unsigned short int TX45 = 7;
    sbit  TX45_bit at AD2TX1.B7;

sfr unsigned short volatile AAD2TX1          absolute 0x695;
sfr unsigned short volatile AD1CON0          absolute 0x711;
    const register unsigned short int GO_nDONE1 = 1;
    sbit  GO_nDONE1_bit at AD1CON0.B1;

sfr unsigned short volatile AADCON0          absolute 0x711;
sfr unsigned short volatile AAD1CON0         absolute 0x711;
sfr unsigned short volatile ADCOMCON         absolute 0x712;
    const register unsigned short int ADCS0 = 4;
    sbit  ADCS0_bit at ADCOMCON.B4;
    const register unsigned short int ADCS1 = 5;
    sbit  ADCS1_bit at ADCOMCON.B5;
    const register unsigned short int ADCS2 = 6;
    sbit  ADCS2_bit at ADCOMCON.B6;

sfr unsigned short volatile AADCON1          absolute 0x712;
sfr unsigned short volatile AD1CON2          absolute 0x713;
sfr unsigned short volatile AADCON2          absolute 0x713;
sfr unsigned short volatile AAD1CON2         absolute 0x713;
sfr unsigned short volatile AD1CON3          absolute 0x714;
    const register unsigned short int AD1DSEN = 0;
    sbit  AD1DSEN_bit at AD1CON3.B0;
    const register unsigned short int AD1IPEN = 1;
    sbit  AD1IPEN_bit at AD1CON3.B1;
    const register unsigned short int AD1IPPOL = 6;
    sbit  AD1IPPOL_bit at AD1CON3.B6;
    const register unsigned short int AD1EPPOL = 7;
    sbit  AD1EPPOL_bit at AD1CON3.B7;

sfr unsigned short volatile AADCON3          absolute 0x714;
sfr unsigned short volatile AAD1CON3         absolute 0x714;
sfr unsigned short volatile ADSTAT           absolute 0x715;
    const register unsigned short int AD1STG0 = 0;
    sbit  AD1STG0_bit at ADSTAT.B0;
    const register unsigned short int AD1STG1 = 1;
    sbit  AD1STG1_bit at ADSTAT.B1;
    const register unsigned short int AD1CONV = 2;
    sbit  AD1CONV_bit at ADSTAT.B2;
    const register unsigned short int AD2STG0 = 4;
    sbit  AD2STG0_bit at ADSTAT.B4;
    const register unsigned short int AD2STG1 = 5;
    sbit  AD2STG1_bit at ADSTAT.B5;
    const register unsigned short int AD2CONV = 6;
    sbit  AD2CONV_bit at ADSTAT.B6;
    const register unsigned short int ADCONV = 2;
    sbit  ADCONV_bit at ADSTAT.B2;

sfr unsigned short volatile AADSTAT          absolute 0x715;
sfr unsigned short volatile AD1PRECON        absolute 0x716;
sfr unsigned short volatile AADPRE           absolute 0x716;
sfr unsigned short volatile AD1PRE           absolute 0x716;
sfr unsigned short volatile AAD1PRE          absolute 0x716;
sfr unsigned short volatile AD1ACQCON        absolute 0x717;
sfr unsigned short volatile AADACQ           absolute 0x717;
sfr unsigned short volatile AD1ACQ           absolute 0x717;
sfr unsigned short volatile AAD1ACQ          absolute 0x717;
sfr unsigned short volatile AD1GRD           absolute 0x718;
    const register unsigned short int TX1POL = 0;
    sbit  TX1POL_bit at AD1GRD.B0;
    const register unsigned short int GRD1POL = 5;
    sbit  GRD1POL_bit at AD1GRD.B5;
    const register unsigned short int GRD1AOE = 6;
    sbit  GRD1AOE_bit at AD1GRD.B6;
    const register unsigned short int GRD1BOE = 7;
    sbit  GRD1BOE_bit at AD1GRD.B7;

sfr unsigned short volatile AADGRD           absolute 0x718;
sfr unsigned short volatile AAD1GRD          absolute 0x718;
sfr unsigned short volatile AD1CAPCON        absolute 0x719;
sfr unsigned short volatile AADCAP           absolute 0x719;
sfr unsigned short volatile AAD1CAP          absolute 0x719;
sfr unsigned short volatile AAD1CAPCON       absolute 0x719;
sfr unsigned int   volatile AAD1RES0         absolute 0x71A;
sfr unsigned int   volatile AD1RES0          absolute 0x71A;
sfr unsigned int   volatile ADRES0           absolute 0x71A;
sfr unsigned short volatile AAD1RES0L        absolute 0x71A;
sfr unsigned short volatile AD1RES0L         absolute 0x71A;
sfr unsigned short volatile AAD1RES0H        absolute 0x71B;
sfr unsigned short volatile AD1RES0H         absolute 0x71B;
sfr unsigned int   volatile AAD1RES1         absolute 0x71C;
sfr unsigned int   volatile AD1RES1          absolute 0x71C;
sfr unsigned int   volatile ADRES1           absolute 0x71C;
sfr unsigned short volatile AAD1RES1L        absolute 0x71C;
sfr unsigned short volatile AD1RES1L         absolute 0x71C;
sfr unsigned short volatile AAD1RES1H        absolute 0x71D;
sfr unsigned short volatile AD1RES1H         absolute 0x71D;
sfr unsigned int   volatile AD1CH            absolute 0x71E;
sfr unsigned int   volatile AAD1CH           absolute 0x71E;
sfr unsigned short volatile AD1CH0           absolute 0x71E;
    const register unsigned short int CH10 = 0;
    sbit  CH10_bit at AD1CH0.B0;
    const register unsigned short int CH11 = 1;
    sbit  CH11_bit at AD1CH0.B1;
    const register unsigned short int CH12 = 2;
    sbit  CH12_bit at AD1CH0.B2;
    const register unsigned short int CH13 = 3;
    sbit  CH13_bit at AD1CH0.B3;
    const register unsigned short int CH14 = 4;
    sbit  CH14_bit at AD1CH0.B4;
    const register unsigned short int CH15 = 5;
    sbit  CH15_bit at AD1CH0.B5;
    const register unsigned short int CH16 = 6;
    sbit  CH16_bit at AD1CH0.B6;
    const register unsigned short int CH17 = 7;
    sbit  CH17_bit at AD1CH0.B7;
    const register unsigned short int CHS17 = 7;
    sbit  CHS17_bit at AD1CH0.B7;

sfr unsigned short volatile AAD1CH0          absolute 0x71E;
sfr unsigned short volatile AD1CH1           absolute 0x71F;
    const register unsigned short int CH18 = 0;
    sbit  CH18_bit at AD1CH1.B0;
    const register unsigned short int CH19 = 1;
    sbit  CH19_bit at AD1CH1.B1;
    const register unsigned short int CH30 = 2;
    sbit  CH30_bit at AD1CH1.B2;
    const register unsigned short int CH31 = 3;
    sbit  CH31_bit at AD1CH1.B3;
    const register unsigned short int CH32 = 4;
    sbit  CH32_bit at AD1CH1.B4;
    const register unsigned short int CH33 = 5;
    sbit  CH33_bit at AD1CH1.B5;
    const register unsigned short int CH34 = 6;
    sbit  CH34_bit at AD1CH1.B6;
    const register unsigned short int CH35 = 7;
    sbit  CH35_bit at AD1CH1.B7;

sfr unsigned short volatile AAD1CH1          absolute 0x71F;
sfr unsigned short volatile AD2CON0          absolute 0x791;
    const register unsigned short int AD2ON = 0;
    sbit  AD2ON_bit at AD2CON0.B0;
    const register unsigned short int GO_nDONE2 = 1;
    sbit  GO_nDONE2_bit at AD2CON0.B1;

sfr unsigned short volatile AAD2CON0         absolute 0x791;
sfr unsigned short volatile AD2CON2          absolute 0x793;
sfr unsigned short volatile AAD2CON2         absolute 0x793;
sfr unsigned short volatile AD2CON3          absolute 0x794;
    const register unsigned short int AD2DSEN = 0;
    sbit  AD2DSEN_bit at AD2CON3.B0;
    const register unsigned short int AD2IPEN = 1;
    sbit  AD2IPEN_bit at AD2CON3.B1;
    const register unsigned short int AD2IPPOL = 6;
    sbit  AD2IPPOL_bit at AD2CON3.B6;
    const register unsigned short int AD2EPPOL = 7;
    sbit  AD2EPPOL_bit at AD2CON3.B7;

sfr unsigned short volatile AAD2CON3         absolute 0x794;
sfr unsigned short volatile AD2PRECON        absolute 0x796;
sfr unsigned short volatile AD2PRE           absolute 0x796;
sfr unsigned short volatile AAD2PRE          absolute 0x796;
sfr unsigned short volatile AD2ACQCON        absolute 0x797;
sfr unsigned short volatile AD2ACQ           absolute 0x797;
sfr unsigned short volatile AAD2ACQ          absolute 0x797;
sfr unsigned short volatile AD2GRD           absolute 0x798;
    const register unsigned short int TX2POL = 0;
    sbit  TX2POL_bit at AD2GRD.B0;
    const register unsigned short int GRD2POL = 5;
    sbit  GRD2POL_bit at AD2GRD.B5;
    const register unsigned short int GRD2AOE = 6;
    sbit  GRD2AOE_bit at AD2GRD.B6;
    const register unsigned short int GRD2BOE = 7;
    sbit  GRD2BOE_bit at AD2GRD.B7;

sfr unsigned short volatile AAD2GRD          absolute 0x798;
sfr unsigned short volatile AD2CAPCON        absolute 0x799;
sfr unsigned short volatile AAD2CAP          absolute 0x799;
sfr unsigned short volatile AAD2CAPCON       absolute 0x799;
sfr unsigned int   volatile AAD2RES0         absolute 0x79A;
sfr unsigned int   volatile AD2RES0          absolute 0x79A;
sfr unsigned short volatile AAD2RES0L        absolute 0x79A;
sfr unsigned short volatile AAD2RES0H        absolute 0x79B;
sfr unsigned int   volatile AAD2RES1         absolute 0x79C;
sfr unsigned int   volatile AD2RES1          absolute 0x79C;
sfr unsigned short volatile AAD2RES1L        absolute 0x79C;
sfr unsigned short volatile AAD2RES1H        absolute 0x79D;
sfr unsigned short volatile AD2CH            absolute 0x79E;
sfr unsigned short volatile AAD2CH           absolute 0x79E;
sfr unsigned short volatile AD2CH0           absolute 0x79E;
    const register unsigned short int CH20 = 0;
    sbit  CH20_bit at AD2CH0.B0;
    const register unsigned short int CH21 = 1;
    sbit  CH21_bit at AD2CH0.B1;
    const register unsigned short int CH22 = 2;
    sbit  CH22_bit at AD2CH0.B2;
    const register unsigned short int CH23 = 3;
    sbit  CH23_bit at AD2CH0.B3;
    const register unsigned short int CH24 = 4;
    sbit  CH24_bit at AD2CH0.B4;
    const register unsigned short int CH25 = 5;
    sbit  CH25_bit at AD2CH0.B5;
    const register unsigned short int CH26 = 6;
    sbit  CH26_bit at AD2CH0.B6;
    const register unsigned short int CH27 = 7;
    sbit  CH27_bit at AD2CH0.B7;

sfr unsigned short volatile AAD2CH0          absolute 0x79E;
sfr unsigned short volatile AD2CH1           absolute 0x79F;
    const register unsigned short int CH28 = 0;
    sbit  CH28_bit at AD2CH1.B0;
    const register unsigned short int CH29 = 1;
    sbit  CH29_bit at AD2CH1.B1;
    const register unsigned short int CH40 = 2;
    sbit  CH40_bit at AD2CH1.B2;
    const register unsigned short int CH41 = 3;
    sbit  CH41_bit at AD2CH1.B3;
    const register unsigned short int CH42 = 4;
    sbit  CH42_bit at AD2CH1.B4;
    const register unsigned short int CH43 = 5;
    sbit  CH43_bit at AD2CH1.B5;
    const register unsigned short int CH44 = 6;
    sbit  CH44_bit at AD2CH1.B6;
    const register unsigned short int CH45 = 7;
    sbit  CH45_bit at AD2CH1.B7;

sfr unsigned short volatile AAD2CH1          absolute 0x79F;
sfr unsigned short volatile ICDIO            absolute 0xF8C;
    const register unsigned short int TRIS_ICDCLK = 2;
    sbit  TRIS_ICDCLK_bit at ICDIO.B2;
    const register unsigned short int TRIS_ICDDAT = 3;
    sbit  TRIS_ICDDAT_bit at ICDIO.B3;
    const register unsigned short int LAT_ICDCLK = 4;
    sbit  LAT_ICDCLK_bit at ICDIO.B4;
    const register unsigned short int LAT_ICDDAT = 5;
    sbit  LAT_ICDDAT_bit at ICDIO.B5;
    const register unsigned short int PORT_ICDCLK = 6;
    sbit  PORT_ICDCLK_bit at ICDIO.B6;
    const register unsigned short int PORT_ICDDAT = 7;
    sbit  PORT_ICDDAT_bit at ICDIO.B7;

sfr unsigned short volatile ICDCON0          absolute 0xF8D;
    const register unsigned short int RSTVEC = 0;
    sbit  RSTVEC_bit at ICDCON0.B0;
    const register unsigned short int DBGINEX = 3;
    sbit  DBGINEX_bit at ICDCON0.B3;
    const register unsigned short int SSTEP = 5;
    sbit  SSTEP_bit at ICDCON0.B5;
    const register unsigned short int FREEZ = 6;
    sbit  FREEZ_bit at ICDCON0.B6;
    const register unsigned short int INBUG = 7;
    sbit  INBUG_bit at ICDCON0.B7;

sfr unsigned short volatile ICDSTAT          absolute 0xF91;
    const register unsigned short int USRHLTF = 1;
    sbit  USRHLTF_bit at ICDSTAT.B1;
    const register unsigned short int TRP0HLTF = 6;
    sbit  TRP0HLTF_bit at ICDSTAT.B6;
    const register unsigned short int TRP1HLTF = 7;
    sbit  TRP1HLTF_bit at ICDSTAT.B7;

sfr unsigned short volatile ICDINSTL         absolute 0xF96;
    const register unsigned short int DBGIN0 = 0;
    sbit  DBGIN0_bit at ICDINSTL.B0;
    const register unsigned short int DBGIN1 = 1;
    sbit  DBGIN1_bit at ICDINSTL.B1;
    const register unsigned short int DBGIN2 = 2;
    sbit  DBGIN2_bit at ICDINSTL.B2;
    const register unsigned short int DBGIN3 = 3;
    sbit  DBGIN3_bit at ICDINSTL.B3;
    const register unsigned short int DBGIN4 = 4;
    sbit  DBGIN4_bit at ICDINSTL.B4;
    const register unsigned short int DBGIN5 = 5;
    sbit  DBGIN5_bit at ICDINSTL.B5;
    const register unsigned short int DBGIN6 = 6;
    sbit  DBGIN6_bit at ICDINSTL.B6;
    const register unsigned short int DBGIN7 = 7;
    sbit  DBGIN7_bit at ICDINSTL.B7;

sfr unsigned short volatile ICDINSTH         absolute 0xF97;
    const register unsigned short int DBGIN8 = 0;
    sbit  DBGIN8_bit at ICDINSTH.B0;
    const register unsigned short int DBGIN9 = 1;
    sbit  DBGIN9_bit at ICDINSTH.B1;
    const register unsigned short int DBGIN10 = 2;
    sbit  DBGIN10_bit at ICDINSTH.B2;
    const register unsigned short int DBGIN11 = 3;
    sbit  DBGIN11_bit at ICDINSTH.B3;
    const register unsigned short int DBGIN12 = 4;
    sbit  DBGIN12_bit at ICDINSTH.B4;
    const register unsigned short int DBGIN13 = 5;
    sbit  DBGIN13_bit at ICDINSTH.B5;

sfr unsigned short volatile ICDBK0CON        absolute 0xF9C;
    const register unsigned short int BKHLT = 0;
    sbit  BKHLT_bit at ICDBK0CON.B0;
    const register unsigned short int BKEN = 7;
    sbit  BKEN_bit at ICDBK0CON.B7;

sfr unsigned short volatile ICDBK0L          absolute 0xF9D;
    const register unsigned short int BKA0 = 0;
    sbit  BKA0_bit at ICDBK0L.B0;
    const register unsigned short int BKA1 = 1;
    sbit  BKA1_bit at ICDBK0L.B1;
    const register unsigned short int BKA2 = 2;
    sbit  BKA2_bit at ICDBK0L.B2;
    const register unsigned short int BKA3 = 3;
    sbit  BKA3_bit at ICDBK0L.B3;
    const register unsigned short int BKA4 = 4;
    sbit  BKA4_bit at ICDBK0L.B4;
    const register unsigned short int BKA5 = 5;
    sbit  BKA5_bit at ICDBK0L.B5;
    const register unsigned short int BKA6 = 6;
    sbit  BKA6_bit at ICDBK0L.B6;
    const register unsigned short int BKA7 = 7;
    sbit  BKA7_bit at ICDBK0L.B7;

sfr unsigned short volatile ICDBK0H          absolute 0xF9E;
    const register unsigned short int BKA8 = 0;
    sbit  BKA8_bit at ICDBK0H.B0;
    const register unsigned short int BKA9 = 1;
    sbit  BKA9_bit at ICDBK0H.B1;
    const register unsigned short int BKA10 = 2;
    sbit  BKA10_bit at ICDBK0H.B2;
    const register unsigned short int BKA11 = 3;
    sbit  BKA11_bit at ICDBK0H.B3;
    const register unsigned short int BKA12 = 4;
    sbit  BKA12_bit at ICDBK0H.B4;
    const register unsigned short int BKA13 = 5;
    sbit  BKA13_bit at ICDBK0H.B5;
    const register unsigned short int BKA14 = 6;
    sbit  BKA14_bit at ICDBK0H.B6;

sfr unsigned short volatile BSRICDSHAD       absolute 0xFE3;
sfr unsigned short volatile STATUS_SHAD      absolute 0xFE4;
    const register unsigned short int C_SHAD = 0;
    sbit  C_SHAD_bit at STATUS_SHAD.B0;
    const register unsigned short int DC_SHAD = 1;
    sbit  DC_SHAD_bit at STATUS_SHAD.B1;
    const register unsigned short int Z_SHAD = 2;
    sbit  Z_SHAD_bit at STATUS_SHAD.B2;

sfr unsigned short volatile WREG_SHAD        absolute 0xFE5;
sfr unsigned short volatile BSR_SHAD         absolute 0xFE6;
sfr unsigned short volatile PCLATH_SHAD      absolute 0xFE7;
sfr unsigned short volatile FSR0L_SHAD       absolute 0xFE8;
sfr unsigned short volatile FSR0H_SHAD       absolute 0xFE9;
sfr unsigned short volatile FSR1L_SHAD       absolute 0xFEA;
sfr unsigned short volatile FSR1H_SHAD       absolute 0xFEB;
sfr unsigned short volatile STKPTR           absolute 0xFED;
sfr unsigned short volatile TOSL             absolute 0xFEE;
sfr unsigned short volatile TOSH             absolute 0xFEF;
