// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00002000;

// Working space registers
rx unsigned short R0 ;
rx unsigned short R1 ;
rx unsigned short R2 ;
rx unsigned short R3 ;
rx unsigned short R4 ;
rx unsigned short R5 ;
rx unsigned short R6 ;
rx unsigned short R7 ;
rx unsigned short R8 ;
rx unsigned short R9 ;
rx unsigned short R10;
rx unsigned short R11;
rx unsigned short R12;
rx unsigned short R13;
rx unsigned short R14;
rx unsigned short R15;

const register unsigned short int W = 0;
const register unsigned short int F = 1;

// Special function registers (SFRs)

const signed int   PORT_TO_TRIS_OFFSET    =     128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

sfr unsigned short volatile INDF             absolute 0x0000;
sfr unsigned short volatile TMR0             absolute 0x0001;
sfr unsigned short volatile PCL              absolute 0x0002;
sfr unsigned short volatile STATUS           absolute 0x0003;
sfr unsigned short          FSR              absolute 0x0004;
register unsigned short     *FSRPTR          absolute 0x0004;
sfr unsigned short volatile PCLATH           absolute 0x000A;
sfr unsigned short volatile INTCON           absolute 0x000B;
sfr unsigned short volatile PIR1             absolute 0x000C;
sfr unsigned short volatile PIR2             absolute 0x000D;
sfr unsigned short volatile TMR1L            absolute 0x000E;
sfr unsigned short volatile TMR1H            absolute 0x000F;
sfr unsigned short volatile T1CON            absolute 0x0010;
sfr unsigned short volatile TMR2             absolute 0x0011;
sfr unsigned short volatile T2CON            absolute 0x0012;
sfr unsigned short volatile SSPBUF           absolute 0x0013;
sfr unsigned short volatile SSPCON           absolute 0x0014;
sfr unsigned int   volatile CCPR1            absolute 0x0015;
sfr unsigned short volatile CCPR1L           absolute 0x0015;
sfr unsigned short volatile CCPR1H           absolute 0x0016;
sfr unsigned short volatile CCP1CON          absolute 0x0017;
sfr unsigned short volatile RCSTA            absolute 0x0018;
sfr unsigned short volatile TXREG            absolute 0x0019;
sfr unsigned short volatile RCREG            absolute 0x001A;
sfr unsigned short volatile CCP2CON          absolute 0x001D;
sfr unsigned short volatile ADRESH           absolute 0x001E;
sfr unsigned short volatile ADCON0           absolute 0x001F;
sfr unsigned short volatile OPTION_REG       absolute 0x0081;
sfr unsigned short volatile PIE1             absolute 0x008C;
sfr unsigned short volatile PIE2             absolute 0x008D;
sfr unsigned short volatile PCON             absolute 0x008E;
sfr unsigned short volatile OSCCON           absolute 0x008F;
sfr unsigned short volatile OSCTUNE          absolute 0x0090;
sfr unsigned short          ANSEL            absolute 0x0091;
sfr unsigned short volatile PR2              absolute 0x0092;
sfr unsigned short volatile SSPADD           absolute 0x0093;
sfr unsigned short volatile SSPSTAT          absolute 0x0094;
sfr unsigned short          WPU              absolute 0x0095;
sfr unsigned short          WPUB             absolute 0x0095;
sfr unsigned short volatile IOC              absolute 0x0096;
sfr unsigned short volatile IOCB             absolute 0x0096;
sfr unsigned short volatile CMCON1           absolute 0x0097;
sfr unsigned short volatile TXSTA            absolute 0x0098;
sfr unsigned short          SPBRG            absolute 0x0099;
sfr unsigned short volatile CMCON0           absolute 0x009C;
sfr unsigned short volatile VRCON            absolute 0x009D;
sfr unsigned short volatile ADRESL           absolute 0x009E;
sfr unsigned short volatile ADCON1           absolute 0x009F;
sfr unsigned short          WDTCON           absolute 0x0105;
sfr unsigned short volatile LCDCON           absolute 0x0107;
sfr unsigned short volatile LCDPS            absolute 0x0108;
sfr unsigned short volatile LVDCON           absolute 0x0109;
sfr unsigned short volatile EEDATA           absolute 0x010C;
sfr unsigned short volatile EEDATL           absolute 0x010C;
sfr unsigned short volatile EEADR            absolute 0x010D;
sfr unsigned short volatile EEADRL           absolute 0x010D;
sfr unsigned short volatile EEDATH           absolute 0x010E;
sfr unsigned short volatile EEADRH           absolute 0x010F;
sfr unsigned short volatile LCDDATA0         absolute 0x0110;
sfr unsigned short volatile LCDDATA1         absolute 0x0111;
sfr unsigned short volatile LCDDATA2         absolute 0x0112;
sfr unsigned short volatile LCDDATA3         absolute 0x0113;
sfr unsigned short volatile LCDDATA4         absolute 0x0114;
sfr unsigned short volatile LCDDATA5         absolute 0x0115;
sfr unsigned short volatile LCDDATA6         absolute 0x0116;
sfr unsigned short volatile LCDDATA7         absolute 0x0117;
sfr unsigned short volatile LCDDATA8         absolute 0x0118;
sfr unsigned short volatile LCDDATA9         absolute 0x0119;
sfr unsigned short volatile LCDDATA10        absolute 0x011A;
sfr unsigned short volatile LCDDATA11        absolute 0x011B;
sfr unsigned short volatile LCDSE0           absolute 0x011C;
sfr unsigned short volatile LCDSE1           absolute 0x011D;
sfr unsigned short volatile LCDSE2           absolute 0x011E;
sfr unsigned short volatile EECON1           absolute 0x018C;
sfr unsigned short volatile EECON2           absolute 0x018D;
sfr unsigned short volatile PORTA            absolute 0x0005;
sfr unsigned short volatile PORTB            absolute 0x0006;
sfr unsigned short volatile PORTC            absolute 0x0007;
sfr unsigned short volatile PORTD            absolute 0x0008;
sfr unsigned short volatile PORTE            absolute 0x0009;
sfr unsigned short volatile CCPR2L           absolute 0x001B;
sfr unsigned short volatile CCPR2H           absolute 0x001C;
sfr unsigned short volatile TRISA            absolute 0x0085;
sfr unsigned short volatile TRISB            absolute 0x0086;
sfr unsigned short volatile TRISC            absolute 0x0087;
sfr unsigned short volatile TRISD            absolute 0x0088;
sfr unsigned short volatile TRISE            absolute 0x0089;

    // STATUS bits
    const register unsigned short int C = 0;
    sbit  C_bit at STATUS.B0;
    const register unsigned short int DC = 1;
    sbit  DC_bit at STATUS.B1;
    const register unsigned short int Z = 2;
    sbit  Z_bit at STATUS.B2;
    const register unsigned short int NOT_PD = 3;
    sbit  NOT_PD_bit at STATUS.B3;
    const register unsigned short int NOT_TO = 4;
    sbit  NOT_TO_bit at STATUS.B4;
    const register unsigned short int IRP = 7;
    sbit  IRP_bit at STATUS.B7;
    const register unsigned short int RP0 = 5;
    sbit  RP0_bit at STATUS.B5;
    const register unsigned short int RP1 = 6;
    sbit  RP1_bit at STATUS.B6;

    // INTCON bits
    const register unsigned short int RBIF = 0;
    sbit  RBIF_bit at INTCON.B0;
    const register unsigned short int INTF = 1;
    sbit  INTF_bit at INTCON.B1;
    const register unsigned short int TMR0IF = 2;
    sbit  TMR0IF_bit at INTCON.B2;
    const register unsigned short int RBIE = 3;
    sbit  RBIE_bit at INTCON.B3;
    const register unsigned short int INTE = 4;
    sbit  INTE_bit at INTCON.B4;
    const register unsigned short int TMR0IE = 5;
    sbit  TMR0IE_bit at INTCON.B5;
    const register unsigned short int PEIE = 6;
    sbit  PEIE_bit at INTCON.B6;
    const register unsigned short int GIE = 7;
    sbit  GIE_bit at INTCON.B7;
    const register unsigned short int T0IF = 2;
    sbit  T0IF_bit at INTCON.B2;
    const register unsigned short int T0IE = 5;
    sbit  T0IE_bit at INTCON.B5;

    // PIR1 bits
    const register unsigned short int TMR1IF = 0;
    sbit  TMR1IF_bit at PIR1.B0;
    const register unsigned short int TMR2IF = 1;
    sbit  TMR2IF_bit at PIR1.B1;
    const register unsigned short int CCP1IF = 2;
    sbit  CCP1IF_bit at PIR1.B2;
    const register unsigned short int SSPIF = 3;
    sbit  SSPIF_bit at PIR1.B3;
    const register unsigned short int TXIF = 4;
    sbit  TXIF_bit at PIR1.B4;
    const register unsigned short int RCIF = 5;
    sbit  RCIF_bit at PIR1.B5;
    const register unsigned short int ADIF = 6;
    sbit  ADIF_bit at PIR1.B6;
    const register unsigned short int EEIF = 7;
    sbit  EEIF_bit at PIR1.B7;

    // PIR2 bits
    const register unsigned short int CCP2IF = 0;
    sbit  CCP2IF_bit at PIR2.B0;
    const register unsigned short int LVDIF = 2;
    sbit  LVDIF_bit at PIR2.B2;
    const register unsigned short int LCDIF = 4;
    sbit  LCDIF_bit at PIR2.B4;
    const register unsigned short int C1IF = 5;
    sbit  C1IF_bit at PIR2.B5;
    const register unsigned short int C2IF = 6;
    sbit  C2IF_bit at PIR2.B6;
    const register unsigned short int OSFIF = 7;
    sbit  OSFIF_bit at PIR2.B7;

    // T1CON bits
    const register unsigned short int TMR1ON = 0;
    sbit  TMR1ON_bit at T1CON.B0;
    const register unsigned short int TMR1CS = 1;
    sbit  TMR1CS_bit at T1CON.B1;
    const register unsigned short int NOT_T1SYNC = 2;
    sbit  NOT_T1SYNC_bit at T1CON.B2;
    const register unsigned short int T1OSCEN = 3;
    sbit  T1OSCEN_bit at T1CON.B3;
    const register unsigned short int TMR1GE = 6;
    sbit  TMR1GE_bit at T1CON.B6;
    const register unsigned short int T1GINV = 7;
    sbit  T1GINV_bit at T1CON.B7;
    const register unsigned short int T1SYNC = 2;
    sbit  T1SYNC_bit at T1CON.B2;
    const register unsigned short int T1CKPS0 = 4;
    sbit  T1CKPS0_bit at T1CON.B4;
    const register unsigned short int T1CKPS1 = 5;
    sbit  T1CKPS1_bit at T1CON.B5;
    const register unsigned short int T1GE = 6;
    sbit  T1GE_bit at T1CON.B6;
    const register unsigned short int T1INSYNC = 2;
    sbit  T1INSYNC_bit at T1CON.B2;

    // T2CON bits
    const register unsigned short int TMR2ON = 2;
    sbit  TMR2ON_bit at T2CON.B2;
    const register unsigned short int T2CKPS0 = 0;
    sbit  T2CKPS0_bit at T2CON.B0;
    const register unsigned short int T2CKPS1 = 1;
    sbit  T2CKPS1_bit at T2CON.B1;
    const register unsigned short int TOUTPS0 = 3;
    sbit  TOUTPS0_bit at T2CON.B3;
    const register unsigned short int TOUTPS1 = 4;
    sbit  TOUTPS1_bit at T2CON.B4;
    const register unsigned short int TOUTPS2 = 5;
    sbit  TOUTPS2_bit at T2CON.B5;
    const register unsigned short int TOUTPS3 = 6;
    sbit  TOUTPS3_bit at T2CON.B6;

    // SSPCON bits
    const register unsigned short int CKP = 4;
    sbit  CKP_bit at SSPCON.B4;
    const register unsigned short int SSPEN = 5;
    sbit  SSPEN_bit at SSPCON.B5;
    const register unsigned short int SSPOV = 6;
    sbit  SSPOV_bit at SSPCON.B6;
    const register unsigned short int WCOL = 7;
    sbit  WCOL_bit at SSPCON.B7;
    const register unsigned short int SSPM0 = 0;
    sbit  SSPM0_bit at SSPCON.B0;
    const register unsigned short int SSPM1 = 1;
    sbit  SSPM1_bit at SSPCON.B1;
    const register unsigned short int SSPM2 = 2;
    sbit  SSPM2_bit at SSPCON.B2;
    const register unsigned short int SSPM3 = 3;
    sbit  SSPM3_bit at SSPCON.B3;

    // CCP1CON bits
    const register unsigned short int CCP1Y = 4;
    sbit  CCP1Y_bit at CCP1CON.B4;
    const register unsigned short int CCP1X = 5;
    sbit  CCP1X_bit at CCP1CON.B5;
    const register unsigned short int CCP1M0 = 0;
    sbit  CCP1M0_bit at CCP1CON.B0;
    const register unsigned short int CCP1M1 = 1;
    sbit  CCP1M1_bit at CCP1CON.B1;
    const register unsigned short int CCP1M2 = 2;
    sbit  CCP1M2_bit at CCP1CON.B2;
    const register unsigned short int CCP1M3 = 3;
    sbit  CCP1M3_bit at CCP1CON.B3;

    // RCSTA bits
    const register unsigned short int RX9D = 0;
    sbit  RX9D_bit at RCSTA.B0;
    const register unsigned short int OERR = 1;
    sbit  OERR_bit at RCSTA.B1;
    const register unsigned short int FERR = 2;
    sbit  FERR_bit at RCSTA.B2;
    const register unsigned short int ADDEN = 3;
    sbit  ADDEN_bit at RCSTA.B3;
    const register unsigned short int CREN = 4;
    sbit  CREN_bit at RCSTA.B4;
    const register unsigned short int SREN = 5;
    sbit  SREN_bit at RCSTA.B5;
    const register unsigned short int RX9 = 6;
    sbit  RX9_bit at RCSTA.B6;
    const register unsigned short int SPEN = 7;
    sbit  SPEN_bit at RCSTA.B7;
    const register unsigned short int RCD8 = 0;
    sbit  RCD8_bit at RCSTA.B0;
    const register unsigned short int RC9 = 6;
    sbit  RC9_bit at RCSTA.B6;
    const register unsigned short int NOT_RC8 = 6;
    sbit  NOT_RC8_bit at RCSTA.B6;
    const register unsigned short int RC8_9 = 6;
    sbit  RC8_9_bit at RCSTA.B6;

    // CCP2CON bits
    const register unsigned short int CCP2Y = 4;
    sbit  CCP2Y_bit at CCP2CON.B4;
    const register unsigned short int CCP2X = 5;
    sbit  CCP2X_bit at CCP2CON.B5;
    const register unsigned short int CCP2M0 = 0;
    sbit  CCP2M0_bit at CCP2CON.B0;
    const register unsigned short int CCP2M1 = 1;
    sbit  CCP2M1_bit at CCP2CON.B1;
    const register unsigned short int CCP2M2 = 2;
    sbit  CCP2M2_bit at CCP2CON.B2;
    const register unsigned short int CCP2M3 = 3;
    sbit  CCP2M3_bit at CCP2CON.B3;

    // ADCON0 bits
    const register unsigned short int ADON = 0;
    sbit  ADON_bit at ADCON0.B0;
    const register unsigned short int GO_NOT_DONE = 1;
    sbit  GO_NOT_DONE_bit at ADCON0.B1;
    const register unsigned short int ADFM = 7;
    sbit  ADFM_bit at ADCON0.B7;
    const register unsigned short int NOT_DONE = 1;
    sbit  NOT_DONE_bit at ADCON0.B1;
    const register unsigned short int CHS0 = 2;
    sbit  CHS0_bit at ADCON0.B2;
    const register unsigned short int CHS1 = 3;
    sbit  CHS1_bit at ADCON0.B3;
    const register unsigned short int CHS2 = 4;
    sbit  CHS2_bit at ADCON0.B4;
    const register unsigned short int VCFG0 = 5;
    sbit  VCFG0_bit at ADCON0.B5;
    const register unsigned short int VCFG1 = 6;
    sbit  VCFG1_bit at ADCON0.B6;
    const register unsigned short int GO_DONE = 1;
    sbit  GO_DONE_bit at ADCON0.B1;
    const register unsigned short int GO = 1;
    sbit  GO_bit at ADCON0.B1;

    // OPTION_REG bits
    const register unsigned short int PSA = 3;
    sbit  PSA_bit at OPTION_REG.B3;
    const register unsigned short int T0SE = 4;
    sbit  T0SE_bit at OPTION_REG.B4;
    const register unsigned short int T0CS = 5;
    sbit  T0CS_bit at OPTION_REG.B5;
    const register unsigned short int INTEDG = 6;
    sbit  INTEDG_bit at OPTION_REG.B6;
    const register unsigned short int NOT_RBPU = 7;
    sbit  NOT_RBPU_bit at OPTION_REG.B7;
    const register unsigned short int PS0 = 0;
    sbit  PS0_bit at OPTION_REG.B0;
    const register unsigned short int PS1 = 1;
    sbit  PS1_bit at OPTION_REG.B1;
    const register unsigned short int PS2 = 2;
    sbit  PS2_bit at OPTION_REG.B2;

    // PIE1 bits
    const register unsigned short int TMR1IE = 0;
    sbit  TMR1IE_bit at PIE1.B0;
    const register unsigned short int TMR2IE = 1;
    sbit  TMR2IE_bit at PIE1.B1;
    const register unsigned short int CCP1IE = 2;
    sbit  CCP1IE_bit at PIE1.B2;
    const register unsigned short int SSPIE = 3;
    sbit  SSPIE_bit at PIE1.B3;
    const register unsigned short int TXIE = 4;
    sbit  TXIE_bit at PIE1.B4;
    const register unsigned short int RCIE = 5;
    sbit  RCIE_bit at PIE1.B5;
    const register unsigned short int ADIE = 6;
    sbit  ADIE_bit at PIE1.B6;
    const register unsigned short int EEIE = 7;
    sbit  EEIE_bit at PIE1.B7;

    // PIE2 bits
    const register unsigned short int CCP2IE = 0;
    sbit  CCP2IE_bit at PIE2.B0;
    const register unsigned short int LVDIE = 2;
    sbit  LVDIE_bit at PIE2.B2;
    const register unsigned short int LCDIE = 4;
    sbit  LCDIE_bit at PIE2.B4;
    const register unsigned short int C1IE = 5;
    sbit  C1IE_bit at PIE2.B5;
    const register unsigned short int C2IE = 6;
    sbit  C2IE_bit at PIE2.B6;
    const register unsigned short int OSFIE = 7;
    sbit  OSFIE_bit at PIE2.B7;

    // PCON bits
    const register unsigned short int NOT_BOR = 0;
    sbit  NOT_BOR_bit at PCON.B0;
    const register unsigned short int NOT_POR = 1;
    sbit  NOT_POR_bit at PCON.B1;
    const register unsigned short int SBOREN = 4;
    sbit  SBOREN_bit at PCON.B4;
    const register unsigned short int NOT_BO = 0;
    sbit  NOT_BO_bit at PCON.B0;

    // OSCCON bits
    const register unsigned short int SCS = 0;
    sbit  SCS_bit at OSCCON.B0;
    const register unsigned short int LTS = 1;
    sbit  LTS_bit at OSCCON.B1;
    const register unsigned short int HTS = 2;
    sbit  HTS_bit at OSCCON.B2;
    const register unsigned short int OSTS = 3;
    sbit  OSTS_bit at OSCCON.B3;
    const register unsigned short int IRCF0 = 4;
    sbit  IRCF0_bit at OSCCON.B4;
    const register unsigned short int IRCF1 = 5;
    sbit  IRCF1_bit at OSCCON.B5;
    const register unsigned short int IRCF2 = 6;
    sbit  IRCF2_bit at OSCCON.B6;

    // OSCTUNE bits
    const register unsigned short int TUN0 = 0;
    sbit  TUN0_bit at OSCTUNE.B0;
    const register unsigned short int TUN1 = 1;
    sbit  TUN1_bit at OSCTUNE.B1;
    const register unsigned short int TUN2 = 2;
    sbit  TUN2_bit at OSCTUNE.B2;
    const register unsigned short int TUN3 = 3;
    sbit  TUN3_bit at OSCTUNE.B3;
    const register unsigned short int TUN4 = 4;
    sbit  TUN4_bit at OSCTUNE.B4;

    // ANSEL bits
    const register unsigned short int ANS0 = 0;
    sbit  ANS0_bit at ANSEL.B0;
    const register unsigned short int ANS1 = 1;
    sbit  ANS1_bit at ANSEL.B1;
    const register unsigned short int ANS2 = 2;
    sbit  ANS2_bit at ANSEL.B2;
    const register unsigned short int ANS3 = 3;
    sbit  ANS3_bit at ANSEL.B3;
    const register unsigned short int ANS4 = 4;
    sbit  ANS4_bit at ANSEL.B4;
    const register unsigned short int ANS5 = 5;
    sbit  ANS5_bit at ANSEL.B5;
    const register unsigned short int ANS6 = 6;
    sbit  ANS6_bit at ANSEL.B6;
    const register unsigned short int ANS7 = 7;
    sbit  ANS7_bit at ANSEL.B7;
    const register unsigned short int AN0 = 0;
    sbit  AN0_bit at ANSEL.B0;
    const register unsigned short int AN1 = 1;
    sbit  AN1_bit at ANSEL.B1;
    const register unsigned short int AN2 = 2;
    sbit  AN2_bit at ANSEL.B2;
    const register unsigned short int AN3 = 3;
    sbit  AN3_bit at ANSEL.B3;
    const register unsigned short int AN4 = 4;
    sbit  AN4_bit at ANSEL.B4;
    const register unsigned short int AN5 = 5;
    sbit  AN5_bit at ANSEL.B5;
    const register unsigned short int AN6 = 6;
    sbit  AN6_bit at ANSEL.B6;
    const register unsigned short int AN7 = 7;
    sbit  AN7_bit at ANSEL.B7;

    // SSPSTAT bits
    const register unsigned short int BF = 0;
    sbit  BF_bit at SSPSTAT.B0;
    const register unsigned short int UA = 1;
    sbit  UA_bit at SSPSTAT.B1;
    const register unsigned short int R_NOT_W = 2;
    sbit  R_NOT_W_bit at SSPSTAT.B2;
    const register unsigned short int S = 3;
    sbit  S_bit at SSPSTAT.B3;
    const register unsigned short int P = 4;
    sbit  P_bit at SSPSTAT.B4;
    const register unsigned short int D_NOT_A = 5;
    sbit  D_NOT_A_bit at SSPSTAT.B5;
    const register unsigned short int CKE = 6;
    sbit  CKE_bit at SSPSTAT.B6;
    const register unsigned short int SMP = 7;
    sbit  SMP_bit at SSPSTAT.B7;
    const register unsigned short int R = 2;
    sbit  R_bit at SSPSTAT.B2;
    const register unsigned short int D = 5;
    sbit  D_bit at SSPSTAT.B5;
    const register unsigned short int NOT_W = 2;
    sbit  NOT_W_bit at SSPSTAT.B2;
    const register unsigned short int NOT_A = 5;
    sbit  NOT_A_bit at SSPSTAT.B5;
    const register unsigned short int NOT_WRITE = 2;
    sbit  NOT_WRITE_bit at SSPSTAT.B2;
    const register unsigned short int NOT_ADDRESS = 5;
    sbit  NOT_ADDRESS_bit at SSPSTAT.B5;
    const register unsigned short int R_W = 2;
    sbit  R_W_bit at SSPSTAT.B2;
    const register unsigned short int D_A = 5;
    sbit  D_A_bit at SSPSTAT.B5;
    const register unsigned short int READ_WRITE = 2;
    sbit  READ_WRITE_bit at SSPSTAT.B2;
    const register unsigned short int DATA_ADDRESS = 5;
    sbit  DATA_ADDRESS_bit at SSPSTAT.B5;

    // WPU, WPUB bits
    const register unsigned short int WPUB0 = 0;
    sbit  WPUB0_bit at WPU.B0;
    const register unsigned short int WPUB1 = 1;
    sbit  WPUB1_bit at WPU.B1;
    const register unsigned short int WPUB2 = 2;
    sbit  WPUB2_bit at WPU.B2;
    const register unsigned short int WPUB3 = 3;
    sbit  WPUB3_bit at WPU.B3;
    const register unsigned short int WPUB4 = 4;
    sbit  WPUB4_bit at WPU.B4;
    const register unsigned short int WPUB5 = 5;
    sbit  WPUB5_bit at WPU.B5;
    const register unsigned short int WPUB6 = 6;
    sbit  WPUB6_bit at WPU.B6;
    const register unsigned short int WPUB7 = 7;
    sbit  WPUB7_bit at WPU.B7;
    const register unsigned short int WPU0 = 0;
    sbit  WPU0_bit at WPU.B0;
    const register unsigned short int WPU1 = 1;
    sbit  WPU1_bit at WPU.B1;
    const register unsigned short int WPU2 = 2;
    sbit  WPU2_bit at WPU.B2;
    const register unsigned short int WPU3 = 3;
    sbit  WPU3_bit at WPU.B3;
    const register unsigned short int WPU4 = 4;
    sbit  WPU4_bit at WPU.B4;
    const register unsigned short int WPU5 = 5;
    sbit  WPU5_bit at WPU.B5;
    const register unsigned short int WPU6 = 6;
    sbit  WPU6_bit at WPU.B6;
    const register unsigned short int WPU7 = 7;
    sbit  WPU7_bit at WPU.B7;

    // IOC, IOCB bits
    const register unsigned short int IOCB4 = 4;
    sbit  IOCB4_bit at IOC.B4;
    const register unsigned short int IOCB5 = 5;
    sbit  IOCB5_bit at IOC.B5;
    const register unsigned short int IOCB6 = 6;
    sbit  IOCB6_bit at IOC.B6;
    const register unsigned short int IOCB7 = 7;
    sbit  IOCB7_bit at IOC.B7;
    const register unsigned short int IOC4 = 4;
    sbit  IOC4_bit at IOC.B4;
    const register unsigned short int IOC5 = 5;
    sbit  IOC5_bit at IOC.B5;
    const register unsigned short int IOC6 = 6;
    sbit  IOC6_bit at IOC.B6;
    const register unsigned short int IOC7 = 7;
    sbit  IOC7_bit at IOC.B7;

    // CMCON1 bits
    const register unsigned short int C2SYNC = 0;
    sbit  C2SYNC_bit at CMCON1.B0;
    const register unsigned short int T1GSS = 1;
    sbit  T1GSS_bit at CMCON1.B1;

    // TXSTA bits
    const register unsigned short int TX9D = 0;
    sbit  TX9D_bit at TXSTA.B0;
    const register unsigned short int TRMT = 1;
    sbit  TRMT_bit at TXSTA.B1;
    const register unsigned short int BRGH = 2;
    sbit  BRGH_bit at TXSTA.B2;
    const register unsigned short int SYNC = 4;
    sbit  SYNC_bit at TXSTA.B4;
    const register unsigned short int TXEN = 5;
    sbit  TXEN_bit at TXSTA.B5;
    const register unsigned short int TX9 = 6;
    sbit  TX9_bit at TXSTA.B6;
    const register unsigned short int CSRC = 7;
    sbit  CSRC_bit at TXSTA.B7;
    const register unsigned short int TXD8 = 0;
    sbit  TXD8_bit at TXSTA.B0;
    const register unsigned short int NOT_TX8 = 6;
    sbit  NOT_TX8_bit at TXSTA.B6;
    const register unsigned short int TX8_9 = 6;
    sbit  TX8_9_bit at TXSTA.B6;

    // CMCON0 bits
    const register unsigned short int CIS = 3;
    sbit  CIS_bit at CMCON0.B3;
    const register unsigned short int C1INV = 4;
    sbit  C1INV_bit at CMCON0.B4;
    const register unsigned short int C2INV = 5;
    sbit  C2INV_bit at CMCON0.B5;
    const register unsigned short int C1OUT = 6;
    sbit  C1OUT_bit at CMCON0.B6;
    const register unsigned short int C2OUT = 7;
    sbit  C2OUT_bit at CMCON0.B7;
    const register unsigned short int CM0 = 0;
    sbit  CM0_bit at CMCON0.B0;
    const register unsigned short int CM1 = 1;
    sbit  CM1_bit at CMCON0.B1;
    const register unsigned short int CM2 = 2;
    sbit  CM2_bit at CMCON0.B2;

    // VRCON bits
    const register unsigned short int VRR = 5;
    sbit  VRR_bit at VRCON.B5;
    const register unsigned short int VREN = 7;
    sbit  VREN_bit at VRCON.B7;
    const register unsigned short int VR0 = 0;
    sbit  VR0_bit at VRCON.B0;
    const register unsigned short int VR1 = 1;
    sbit  VR1_bit at VRCON.B1;
    const register unsigned short int VR2 = 2;
    sbit  VR2_bit at VRCON.B2;
    const register unsigned short int VR3 = 3;
    sbit  VR3_bit at VRCON.B3;

    // ADCON1 bits
    const register unsigned short int ADCS0 = 4;
    sbit  ADCS0_bit at ADCON1.B4;
    const register unsigned short int ADCS1 = 5;
    sbit  ADCS1_bit at ADCON1.B5;
    const register unsigned short int ADCS2 = 6;
    sbit  ADCS2_bit at ADCON1.B6;

    // WDTCON bits
    const register unsigned short int SWDTEN = 0;
    sbit  SWDTEN_bit at WDTCON.B0;
    const register unsigned short int SWDTE = 0;
    sbit  SWDTE_bit at WDTCON.B0;
    const register unsigned short int WDTPS0 = 1;
    sbit  WDTPS0_bit at WDTCON.B1;
    const register unsigned short int WDTPS1 = 2;
    sbit  WDTPS1_bit at WDTCON.B2;
    const register unsigned short int WDTPS2 = 3;
    sbit  WDTPS2_bit at WDTCON.B3;
    const register unsigned short int WDTPS3 = 4;
    sbit  WDTPS3_bit at WDTCON.B4;

    // LCDCON bits
    const register unsigned short int VLCDEN = 4;
    sbit  VLCDEN_bit at LCDCON.B4;
    const register unsigned short int WERR = 5;
    sbit  WERR_bit at LCDCON.B5;
    const register unsigned short int SLPEN = 6;
    sbit  SLPEN_bit at LCDCON.B6;
    const register unsigned short int LCDEN = 7;
    sbit  LCDEN_bit at LCDCON.B7;
    const register unsigned short int LMUX0 = 0;
    sbit  LMUX0_bit at LCDCON.B0;
    const register unsigned short int LMUX1 = 1;
    sbit  LMUX1_bit at LCDCON.B1;
    const register unsigned short int CS0 = 2;
    sbit  CS0_bit at LCDCON.B2;
    const register unsigned short int CS1 = 3;
    sbit  CS1_bit at LCDCON.B3;

    // LCDPS bits
    const register unsigned short int WA = 4;
    sbit  WA_bit at LCDPS.B4;
    const register unsigned short int LCDA = 5;
    sbit  LCDA_bit at LCDPS.B5;
    const register unsigned short int BIASMD = 6;
    sbit  BIASMD_bit at LCDPS.B6;
    const register unsigned short int WFT = 7;
    sbit  WFT_bit at LCDPS.B7;
    const register unsigned short int LP0 = 0;
    sbit  LP0_bit at LCDPS.B0;
    const register unsigned short int LP1 = 1;
    sbit  LP1_bit at LCDPS.B1;
    const register unsigned short int LP2 = 2;
    sbit  LP2_bit at LCDPS.B2;
    const register unsigned short int LP3 = 3;
    sbit  LP3_bit at LCDPS.B3;

    // LVDCON bits
    const register unsigned short int LVDEN = 4;
    sbit  LVDEN_bit at LVDCON.B4;
    const register unsigned short int IRVST = 5;
    sbit  IRVST_bit at LVDCON.B5;
    const register unsigned short int LVDL0 = 0;
    sbit  LVDL0_bit at LVDCON.B0;
    const register unsigned short int LVDL1 = 1;
    sbit  LVDL1_bit at LVDCON.B1;
    const register unsigned short int LVDL2 = 2;
    sbit  LVDL2_bit at LVDCON.B2;

    // EEDATA, EEDATL bits
    const register unsigned short int EEDATL0 = 0;
    sbit  EEDATL0_bit at EEDATA.B0;
    const register unsigned short int EEDATL1 = 1;
    sbit  EEDATL1_bit at EEDATA.B1;
    const register unsigned short int EEDATL2 = 2;
    sbit  EEDATL2_bit at EEDATA.B2;
    const register unsigned short int EEDATL3 = 3;
    sbit  EEDATL3_bit at EEDATA.B3;
    const register unsigned short int EEDATL4 = 4;
    sbit  EEDATL4_bit at EEDATA.B4;
    const register unsigned short int EEDATL5 = 5;
    sbit  EEDATL5_bit at EEDATA.B5;
    const register unsigned short int EEDATL6 = 6;
    sbit  EEDATL6_bit at EEDATA.B6;
    const register unsigned short int EEDATL7 = 7;
    sbit  EEDATL7_bit at EEDATA.B7;

    // EEADR, EEADRL bits
    const register unsigned short int EEADRL0 = 0;
    sbit  EEADRL0_bit at EEADR.B0;
    const register unsigned short int EEADRL1 = 1;
    sbit  EEADRL1_bit at EEADR.B1;
    const register unsigned short int EEADRL2 = 2;
    sbit  EEADRL2_bit at EEADR.B2;
    const register unsigned short int EEADRL3 = 3;
    sbit  EEADRL3_bit at EEADR.B3;
    const register unsigned short int EEADRL4 = 4;
    sbit  EEADRL4_bit at EEADR.B4;
    const register unsigned short int EEADRL5 = 5;
    sbit  EEADRL5_bit at EEADR.B5;
    const register unsigned short int EEADRL6 = 6;
    sbit  EEADRL6_bit at EEADR.B6;
    const register unsigned short int EEADRL7 = 7;
    sbit  EEADRL7_bit at EEADR.B7;

    // EEDATH bits
    const register unsigned short int EEDATH0 = 0;
    sbit  EEDATH0_bit at EEDATH.B0;
    const register unsigned short int EEDATH1 = 1;
    sbit  EEDATH1_bit at EEDATH.B1;
    const register unsigned short int EEDATH2 = 2;
    sbit  EEDATH2_bit at EEDATH.B2;
    const register unsigned short int EEDATH3 = 3;
    sbit  EEDATH3_bit at EEDATH.B3;
    const register unsigned short int EEDATH4 = 4;
    sbit  EEDATH4_bit at EEDATH.B4;
    const register unsigned short int EEDATH5 = 5;
    sbit  EEDATH5_bit at EEDATH.B5;

    // EEADRH bits
    const register unsigned short int EEADRH0 = 0;
    sbit  EEADRH0_bit at EEADRH.B0;
    const register unsigned short int EEADRH1 = 1;
    sbit  EEADRH1_bit at EEADRH.B1;
    const register unsigned short int EEADRH2 = 2;
    sbit  EEADRH2_bit at EEADRH.B2;
    const register unsigned short int EEADRH3 = 3;
    sbit  EEADRH3_bit at EEADRH.B3;
    const register unsigned short int EEADRH4 = 4;
    sbit  EEADRH4_bit at EEADRH.B4;

    // LCDDATA0 bits
    const register unsigned short int SEG0 = 0;
    sbit  SEG0_bit at LCDDATA0.B0;
    const register unsigned short int SEG1 = 1;
    sbit  SEG1_bit at LCDDATA0.B1;
    const register unsigned short int SEG2 = 2;
    sbit  SEG2_bit at LCDDATA0.B2;
    const register unsigned short int SEG3 = 3;
    sbit  SEG3_bit at LCDDATA0.B3;
    const register unsigned short int SEG4 = 4;
    sbit  SEG4_bit at LCDDATA0.B4;
    const register unsigned short int SEG5 = 5;
    sbit  SEG5_bit at LCDDATA0.B5;
    const register unsigned short int SEG6 = 6;
    sbit  SEG6_bit at LCDDATA0.B6;
    const register unsigned short int SEG7 = 7;
    sbit  SEG7_bit at LCDDATA0.B7;
    const register unsigned short int SEG0COM0 = 0;
    sbit  SEG0COM0_bit at LCDDATA0.B0;
    const register unsigned short int SEG1COM0 = 1;
    sbit  SEG1COM0_bit at LCDDATA0.B1;
    const register unsigned short int SEG2COM0 = 2;
    sbit  SEG2COM0_bit at LCDDATA0.B2;
    const register unsigned short int SEG3COM0 = 3;
    sbit  SEG3COM0_bit at LCDDATA0.B3;
    const register unsigned short int SEG4COM0 = 4;
    sbit  SEG4COM0_bit at LCDDATA0.B4;
    const register unsigned short int SEG5COM0 = 5;
    sbit  SEG5COM0_bit at LCDDATA0.B5;
    const register unsigned short int SEG6COM0 = 6;
    sbit  SEG6COM0_bit at LCDDATA0.B6;
    const register unsigned short int SEG7COM0 = 7;
    sbit  SEG7COM0_bit at LCDDATA0.B7;
    const register unsigned short int S0C0 = 0;
    sbit  S0C0_bit at LCDDATA0.B0;
    const register unsigned short int S1C0 = 1;
    sbit  S1C0_bit at LCDDATA0.B1;
    const register unsigned short int S2C0 = 2;
    sbit  S2C0_bit at LCDDATA0.B2;
    const register unsigned short int S3C0 = 3;
    sbit  S3C0_bit at LCDDATA0.B3;
    const register unsigned short int S4C0 = 4;
    sbit  S4C0_bit at LCDDATA0.B4;
    const register unsigned short int S5C0 = 5;
    sbit  S5C0_bit at LCDDATA0.B5;
    const register unsigned short int S6C0 = 6;
    sbit  S6C0_bit at LCDDATA0.B6;
    const register unsigned short int S7C0 = 7;
    sbit  S7C0_bit at LCDDATA0.B7;

    // LCDDATA1 bits
    const register unsigned short int SEG8 = 0;
    sbit  SEG8_bit at LCDDATA1.B0;
    const register unsigned short int SEG9 = 1;
    sbit  SEG9_bit at LCDDATA1.B1;
    const register unsigned short int SEG10 = 2;
    sbit  SEG10_bit at LCDDATA1.B2;
    const register unsigned short int SEG11 = 3;
    sbit  SEG11_bit at LCDDATA1.B3;
    const register unsigned short int SEG12 = 4;
    sbit  SEG12_bit at LCDDATA1.B4;
    const register unsigned short int SEG13 = 5;
    sbit  SEG13_bit at LCDDATA1.B5;
    const register unsigned short int SEG14 = 6;
    sbit  SEG14_bit at LCDDATA1.B6;
    const register unsigned short int SEG15 = 7;
    sbit  SEG15_bit at LCDDATA1.B7;
    const register unsigned short int SEG8COM0 = 0;
    sbit  SEG8COM0_bit at LCDDATA1.B0;
    const register unsigned short int SEG9COM0 = 1;
    sbit  SEG9COM0_bit at LCDDATA1.B1;
    const register unsigned short int SEG10COM0 = 2;
    sbit  SEG10COM0_bit at LCDDATA1.B2;
    const register unsigned short int SEG11COM0 = 3;
    sbit  SEG11COM0_bit at LCDDATA1.B3;
    const register unsigned short int SEG12COM0 = 4;
    sbit  SEG12COM0_bit at LCDDATA1.B4;
    const register unsigned short int SEG13COM0 = 5;
    sbit  SEG13COM0_bit at LCDDATA1.B5;
    const register unsigned short int SEG14COM0 = 6;
    sbit  SEG14COM0_bit at LCDDATA1.B6;
    const register unsigned short int SEG15COM0 = 7;
    sbit  SEG15COM0_bit at LCDDATA1.B7;
    const register unsigned short int S8C0 = 0;
    sbit  S8C0_bit at LCDDATA1.B0;
    const register unsigned short int S9C0 = 1;
    sbit  S9C0_bit at LCDDATA1.B1;
    const register unsigned short int S10C0 = 2;
    sbit  S10C0_bit at LCDDATA1.B2;
    const register unsigned short int S11C0 = 3;
    sbit  S11C0_bit at LCDDATA1.B3;
    const register unsigned short int S12C0 = 4;
    sbit  S12C0_bit at LCDDATA1.B4;
    const register unsigned short int S13C0 = 5;
    sbit  S13C0_bit at LCDDATA1.B5;
    const register unsigned short int S14C0 = 6;
    sbit  S14C0_bit at LCDDATA1.B6;
    const register unsigned short int S15C0 = 7;
    sbit  S15C0_bit at LCDDATA1.B7;

    // LCDDATA2 bits
    const register unsigned short int SEG16 = 0;
    sbit  SEG16_bit at LCDDATA2.B0;
    const register unsigned short int SEG17 = 1;
    sbit  SEG17_bit at LCDDATA2.B1;
    const register unsigned short int SEG18 = 2;
    sbit  SEG18_bit at LCDDATA2.B2;
    const register unsigned short int SEG19 = 3;
    sbit  SEG19_bit at LCDDATA2.B3;
    const register unsigned short int SEG20 = 4;
    sbit  SEG20_bit at LCDDATA2.B4;
    const register unsigned short int SEG21 = 5;
    sbit  SEG21_bit at LCDDATA2.B5;
    const register unsigned short int SEG22 = 6;
    sbit  SEG22_bit at LCDDATA2.B6;
    const register unsigned short int SEG23 = 7;
    sbit  SEG23_bit at LCDDATA2.B7;
    const register unsigned short int SEG16COM0 = 0;
    sbit  SEG16COM0_bit at LCDDATA2.B0;
    const register unsigned short int SEG17COM0 = 1;
    sbit  SEG17COM0_bit at LCDDATA2.B1;
    const register unsigned short int SEG18COM0 = 2;
    sbit  SEG18COM0_bit at LCDDATA2.B2;
    const register unsigned short int SEG19COM0 = 3;
    sbit  SEG19COM0_bit at LCDDATA2.B3;
    const register unsigned short int SEG20COM0 = 4;
    sbit  SEG20COM0_bit at LCDDATA2.B4;
    const register unsigned short int SEG21COM0 = 5;
    sbit  SEG21COM0_bit at LCDDATA2.B5;
    const register unsigned short int SEG22COM0 = 6;
    sbit  SEG22COM0_bit at LCDDATA2.B6;
    const register unsigned short int SEG23COM0 = 7;
    sbit  SEG23COM0_bit at LCDDATA2.B7;
    const register unsigned short int S16C0 = 0;
    sbit  S16C0_bit at LCDDATA2.B0;
    const register unsigned short int S17C0 = 1;
    sbit  S17C0_bit at LCDDATA2.B1;
    const register unsigned short int S18C0 = 2;
    sbit  S18C0_bit at LCDDATA2.B2;
    const register unsigned short int S19C0 = 3;
    sbit  S19C0_bit at LCDDATA2.B3;
    const register unsigned short int S20C0 = 4;
    sbit  S20C0_bit at LCDDATA2.B4;
    const register unsigned short int S21C0 = 5;
    sbit  S21C0_bit at LCDDATA2.B5;
    const register unsigned short int S22C0 = 6;
    sbit  S22C0_bit at LCDDATA2.B6;
    const register unsigned short int S23C0 = 7;
    sbit  S23C0_bit at LCDDATA2.B7;

    // LCDDATA3 bits
    sbit  SEG0_LCDDATA3_bit at LCDDATA3.B0;
    sbit  SEG1_LCDDATA3_bit at LCDDATA3.B1;
    sbit  SEG2_LCDDATA3_bit at LCDDATA3.B2;
    sbit  SEG3_LCDDATA3_bit at LCDDATA3.B3;
    sbit  SEG4_LCDDATA3_bit at LCDDATA3.B4;
    sbit  SEG5_LCDDATA3_bit at LCDDATA3.B5;
    sbit  SEG6_LCDDATA3_bit at LCDDATA3.B6;
    sbit  SEG7_LCDDATA3_bit at LCDDATA3.B7;
    const register unsigned short int SEG0COM1 = 0;
    sbit  SEG0COM1_bit at LCDDATA3.B0;
    const register unsigned short int SEG1COM1 = 1;
    sbit  SEG1COM1_bit at LCDDATA3.B1;
    const register unsigned short int SEG2COM1 = 2;
    sbit  SEG2COM1_bit at LCDDATA3.B2;
    const register unsigned short int SEG3COM1 = 3;
    sbit  SEG3COM1_bit at LCDDATA3.B3;
    const register unsigned short int SEG4COM1 = 4;
    sbit  SEG4COM1_bit at LCDDATA3.B4;
    const register unsigned short int SEG5COM1 = 5;
    sbit  SEG5COM1_bit at LCDDATA3.B5;
    const register unsigned short int SEG6COM1 = 6;
    sbit  SEG6COM1_bit at LCDDATA3.B6;
    const register unsigned short int SEG7COM1 = 7;
    sbit  SEG7COM1_bit at LCDDATA3.B7;
    const register unsigned short int S0C1 = 0;
    sbit  S0C1_bit at LCDDATA3.B0;
    const register unsigned short int S1C1 = 1;
    sbit  S1C1_bit at LCDDATA3.B1;
    const register unsigned short int S2C1 = 2;
    sbit  S2C1_bit at LCDDATA3.B2;
    const register unsigned short int S3C1 = 3;
    sbit  S3C1_bit at LCDDATA3.B3;
    const register unsigned short int S4C1 = 4;
    sbit  S4C1_bit at LCDDATA3.B4;
    const register unsigned short int S5C1 = 5;
    sbit  S5C1_bit at LCDDATA3.B5;
    const register unsigned short int S6C1 = 6;
    sbit  S6C1_bit at LCDDATA3.B6;
    const register unsigned short int S7C1 = 7;
    sbit  S7C1_bit at LCDDATA3.B7;

    // LCDDATA4 bits
    sbit  SEG8_LCDDATA4_bit at LCDDATA4.B0;
    sbit  SEG9_LCDDATA4_bit at LCDDATA4.B1;
    sbit  SEG10_LCDDATA4_bit at LCDDATA4.B2;
    sbit  SEG11_LCDDATA4_bit at LCDDATA4.B3;
    sbit  SEG12_LCDDATA4_bit at LCDDATA4.B4;
    sbit  SEG13_LCDDATA4_bit at LCDDATA4.B5;
    sbit  SEG14_LCDDATA4_bit at LCDDATA4.B6;
    sbit  SEG15_LCDDATA4_bit at LCDDATA4.B7;
    const register unsigned short int SEG8COM1 = 0;
    sbit  SEG8COM1_bit at LCDDATA4.B0;
    const register unsigned short int SEG9COM1 = 1;
    sbit  SEG9COM1_bit at LCDDATA4.B1;
    const register unsigned short int SEG10COM1 = 2;
    sbit  SEG10COM1_bit at LCDDATA4.B2;
    const register unsigned short int SEG11COM1 = 3;
    sbit  SEG11COM1_bit at LCDDATA4.B3;
    const register unsigned short int SEG12COM1 = 4;
    sbit  SEG12COM1_bit at LCDDATA4.B4;
    const register unsigned short int SEG13COM1 = 5;
    sbit  SEG13COM1_bit at LCDDATA4.B5;
    const register unsigned short int SEG14COM1 = 6;
    sbit  SEG14COM1_bit at LCDDATA4.B6;
    const register unsigned short int SEG15COM1 = 7;
    sbit  SEG15COM1_bit at LCDDATA4.B7;
    const register unsigned short int S8C1 = 0;
    sbit  S8C1_bit at LCDDATA4.B0;
    const register unsigned short int S9C1 = 1;
    sbit  S9C1_bit at LCDDATA4.B1;
    const register unsigned short int S10C1 = 2;
    sbit  S10C1_bit at LCDDATA4.B2;
    const register unsigned short int S11C1 = 3;
    sbit  S11C1_bit at LCDDATA4.B3;
    const register unsigned short int S12C1 = 4;
    sbit  S12C1_bit at LCDDATA4.B4;
    const register unsigned short int S13C1 = 5;
    sbit  S13C1_bit at LCDDATA4.B5;
    const register unsigned short int S14C1 = 6;
    sbit  S14C1_bit at LCDDATA4.B6;
    const register unsigned short int S15C1 = 7;
    sbit  S15C1_bit at LCDDATA4.B7;

    // LCDDATA5 bits
    sbit  SEG16_LCDDATA5_bit at LCDDATA5.B0;
    sbit  SEG17_LCDDATA5_bit at LCDDATA5.B1;
    sbit  SEG18_LCDDATA5_bit at LCDDATA5.B2;
    sbit  SEG19_LCDDATA5_bit at LCDDATA5.B3;
    sbit  SEG20_LCDDATA5_bit at LCDDATA5.B4;
    sbit  SEG21_LCDDATA5_bit at LCDDATA5.B5;
    sbit  SEG22_LCDDATA5_bit at LCDDATA5.B6;
    sbit  SEG23_LCDDATA5_bit at LCDDATA5.B7;
    const register unsigned short int SEG16COM1 = 0;
    sbit  SEG16COM1_bit at LCDDATA5.B0;
    const register unsigned short int SEG17COM1 = 1;
    sbit  SEG17COM1_bit at LCDDATA5.B1;
    const register unsigned short int SEG18COM1 = 2;
    sbit  SEG18COM1_bit at LCDDATA5.B2;
    const register unsigned short int SEG19COM1 = 3;
    sbit  SEG19COM1_bit at LCDDATA5.B3;
    const register unsigned short int SEG20COM1 = 4;
    sbit  SEG20COM1_bit at LCDDATA5.B4;
    const register unsigned short int SEG21COM1 = 5;
    sbit  SEG21COM1_bit at LCDDATA5.B5;
    const register unsigned short int SEG22COM1 = 6;
    sbit  SEG22COM1_bit at LCDDATA5.B6;
    const register unsigned short int SEG23COM1 = 7;
    sbit  SEG23COM1_bit at LCDDATA5.B7;
    const register unsigned short int S16C1 = 0;
    sbit  S16C1_bit at LCDDATA5.B0;
    const register unsigned short int S17C1 = 1;
    sbit  S17C1_bit at LCDDATA5.B1;
    const register unsigned short int S18C1 = 2;
    sbit  S18C1_bit at LCDDATA5.B2;
    const register unsigned short int S19C1 = 3;
    sbit  S19C1_bit at LCDDATA5.B3;
    const register unsigned short int S20C1 = 4;
    sbit  S20C1_bit at LCDDATA5.B4;
    const register unsigned short int S21C1 = 5;
    sbit  S21C1_bit at LCDDATA5.B5;
    const register unsigned short int S22C1 = 6;
    sbit  S22C1_bit at LCDDATA5.B6;
    const register unsigned short int S23C1 = 7;
    sbit  S23C1_bit at LCDDATA5.B7;

    // LCDDATA6 bits
    sbit  SEG0_LCDDATA6_bit at LCDDATA6.B0;
    sbit  SEG1_LCDDATA6_bit at LCDDATA6.B1;
    sbit  SEG2_LCDDATA6_bit at LCDDATA6.B2;
    sbit  SEG3_LCDDATA6_bit at LCDDATA6.B3;
    sbit  SEG4_LCDDATA6_bit at LCDDATA6.B4;
    sbit  SEG5_LCDDATA6_bit at LCDDATA6.B5;
    sbit  SEG6_LCDDATA6_bit at LCDDATA6.B6;
    sbit  SEG7_LCDDATA6_bit at LCDDATA6.B7;
    const register unsigned short int SEG0COM2 = 0;
    sbit  SEG0COM2_bit at LCDDATA6.B0;
    const register unsigned short int SEG1COM2 = 1;
    sbit  SEG1COM2_bit at LCDDATA6.B1;
    const register unsigned short int SEG2COM2 = 2;
    sbit  SEG2COM2_bit at LCDDATA6.B2;
    const register unsigned short int SEG3COM2 = 3;
    sbit  SEG3COM2_bit at LCDDATA6.B3;
    const register unsigned short int SEG4COM2 = 4;
    sbit  SEG4COM2_bit at LCDDATA6.B4;
    const register unsigned short int SEG5COM2 = 5;
    sbit  SEG5COM2_bit at LCDDATA6.B5;
    const register unsigned short int SEG6COM2 = 6;
    sbit  SEG6COM2_bit at LCDDATA6.B6;
    const register unsigned short int SEG7COM2 = 7;
    sbit  SEG7COM2_bit at LCDDATA6.B7;
    const register unsigned short int S0C2 = 0;
    sbit  S0C2_bit at LCDDATA6.B0;
    const register unsigned short int S1C2 = 1;
    sbit  S1C2_bit at LCDDATA6.B1;
    const register unsigned short int S2C2 = 2;
    sbit  S2C2_bit at LCDDATA6.B2;
    const register unsigned short int S3C2 = 3;
    sbit  S3C2_bit at LCDDATA6.B3;
    const register unsigned short int S4C2 = 4;
    sbit  S4C2_bit at LCDDATA6.B4;
    const register unsigned short int S5C2 = 5;
    sbit  S5C2_bit at LCDDATA6.B5;
    const register unsigned short int S6C2 = 6;
    sbit  S6C2_bit at LCDDATA6.B6;
    const register unsigned short int S7C2 = 7;
    sbit  S7C2_bit at LCDDATA6.B7;

    // LCDDATA7 bits
    sbit  SEG8_LCDDATA7_bit at LCDDATA7.B0;
    sbit  SEG9_LCDDATA7_bit at LCDDATA7.B1;
    sbit  SEG10_LCDDATA7_bit at LCDDATA7.B2;
    sbit  SEG11_LCDDATA7_bit at LCDDATA7.B3;
    sbit  SEG12_LCDDATA7_bit at LCDDATA7.B4;
    sbit  SEG13_LCDDATA7_bit at LCDDATA7.B5;
    sbit  SEG14_LCDDATA7_bit at LCDDATA7.B6;
    sbit  SEG15_LCDDATA7_bit at LCDDATA7.B7;
    const register unsigned short int SEG8COM2 = 0;
    sbit  SEG8COM2_bit at LCDDATA7.B0;
    const register unsigned short int SEG9COM2 = 1;
    sbit  SEG9COM2_bit at LCDDATA7.B1;
    const register unsigned short int SEG10COM2 = 2;
    sbit  SEG10COM2_bit at LCDDATA7.B2;
    const register unsigned short int SEG11COM2 = 3;
    sbit  SEG11COM2_bit at LCDDATA7.B3;
    const register unsigned short int SEG12COM2 = 4;
    sbit  SEG12COM2_bit at LCDDATA7.B4;
    const register unsigned short int SEG13COM2 = 5;
    sbit  SEG13COM2_bit at LCDDATA7.B5;
    const register unsigned short int SEG14COM2 = 6;
    sbit  SEG14COM2_bit at LCDDATA7.B6;
    const register unsigned short int SEG15COM2 = 7;
    sbit  SEG15COM2_bit at LCDDATA7.B7;
    const register unsigned short int S8C2 = 0;
    sbit  S8C2_bit at LCDDATA7.B0;
    const register unsigned short int S9C2 = 1;
    sbit  S9C2_bit at LCDDATA7.B1;
    const register unsigned short int S10C2 = 2;
    sbit  S10C2_bit at LCDDATA7.B2;
    const register unsigned short int S11C2 = 3;
    sbit  S11C2_bit at LCDDATA7.B3;
    const register unsigned short int S12C2 = 4;
    sbit  S12C2_bit at LCDDATA7.B4;
    const register unsigned short int S13C2 = 5;
    sbit  S13C2_bit at LCDDATA7.B5;
    const register unsigned short int S14C2 = 6;
    sbit  S14C2_bit at LCDDATA7.B6;
    const register unsigned short int S15C2 = 7;
    sbit  S15C2_bit at LCDDATA7.B7;

    // LCDDATA8 bits
    sbit  SEG16_LCDDATA8_bit at LCDDATA8.B0;
    sbit  SEG17_LCDDATA8_bit at LCDDATA8.B1;
    sbit  SEG18_LCDDATA8_bit at LCDDATA8.B2;
    sbit  SEG19_LCDDATA8_bit at LCDDATA8.B3;
    sbit  SEG20_LCDDATA8_bit at LCDDATA8.B4;
    sbit  SEG21_LCDDATA8_bit at LCDDATA8.B5;
    sbit  SEG22_LCDDATA8_bit at LCDDATA8.B6;
    sbit  SEG23_LCDDATA8_bit at LCDDATA8.B7;
    const register unsigned short int SEG16COM2 = 0;
    sbit  SEG16COM2_bit at LCDDATA8.B0;
    const register unsigned short int SEG17COM2 = 1;
    sbit  SEG17COM2_bit at LCDDATA8.B1;
    const register unsigned short int SEG18COM2 = 2;
    sbit  SEG18COM2_bit at LCDDATA8.B2;
    const register unsigned short int SEG19COM2 = 3;
    sbit  SEG19COM2_bit at LCDDATA8.B3;
    const register unsigned short int SEG20COM2 = 4;
    sbit  SEG20COM2_bit at LCDDATA8.B4;
    const register unsigned short int SEG21COM2 = 5;
    sbit  SEG21COM2_bit at LCDDATA8.B5;
    const register unsigned short int SEG22COM2 = 6;
    sbit  SEG22COM2_bit at LCDDATA8.B6;
    const register unsigned short int SEG23COM2 = 7;
    sbit  SEG23COM2_bit at LCDDATA8.B7;
    const register unsigned short int S16C2 = 0;
    sbit  S16C2_bit at LCDDATA8.B0;
    const register unsigned short int S17C2 = 1;
    sbit  S17C2_bit at LCDDATA8.B1;
    const register unsigned short int S18C2 = 2;
    sbit  S18C2_bit at LCDDATA8.B2;
    const register unsigned short int S19C2 = 3;
    sbit  S19C2_bit at LCDDATA8.B3;
    const register unsigned short int S20C2 = 4;
    sbit  S20C2_bit at LCDDATA8.B4;
    const register unsigned short int S21C2 = 5;
    sbit  S21C2_bit at LCDDATA8.B5;
    const register unsigned short int S22C2 = 6;
    sbit  S22C2_bit at LCDDATA8.B6;
    const register unsigned short int S23C2 = 7;
    sbit  S23C2_bit at LCDDATA8.B7;

    // LCDDATA9 bits
    sbit  SEG0_LCDDATA9_bit at LCDDATA9.B0;
    sbit  SEG1_LCDDATA9_bit at LCDDATA9.B1;
    sbit  SEG2_LCDDATA9_bit at LCDDATA9.B2;
    sbit  SEG3_LCDDATA9_bit at LCDDATA9.B3;
    sbit  SEG4_LCDDATA9_bit at LCDDATA9.B4;
    sbit  SEG5_LCDDATA9_bit at LCDDATA9.B5;
    sbit  SEG6_LCDDATA9_bit at LCDDATA9.B6;
    sbit  SEG7_LCDDATA9_bit at LCDDATA9.B7;
    const register unsigned short int SEG0COM3 = 0;
    sbit  SEG0COM3_bit at LCDDATA9.B0;
    const register unsigned short int SEG1COM3 = 1;
    sbit  SEG1COM3_bit at LCDDATA9.B1;
    const register unsigned short int SEG2COM3 = 2;
    sbit  SEG2COM3_bit at LCDDATA9.B2;
    const register unsigned short int SEG3COM3 = 3;
    sbit  SEG3COM3_bit at LCDDATA9.B3;
    const register unsigned short int SEG4COM3 = 4;
    sbit  SEG4COM3_bit at LCDDATA9.B4;
    const register unsigned short int SEG5COM3 = 5;
    sbit  SEG5COM3_bit at LCDDATA9.B5;
    const register unsigned short int SEG6COM3 = 6;
    sbit  SEG6COM3_bit at LCDDATA9.B6;
    const register unsigned short int SEG7COM3 = 7;
    sbit  SEG7COM3_bit at LCDDATA9.B7;
    const register unsigned short int S0C3 = 0;
    sbit  S0C3_bit at LCDDATA9.B0;
    const register unsigned short int S1C3 = 1;
    sbit  S1C3_bit at LCDDATA9.B1;
    const register unsigned short int S2C3 = 2;
    sbit  S2C3_bit at LCDDATA9.B2;
    const register unsigned short int S3C3 = 3;
    sbit  S3C3_bit at LCDDATA9.B3;
    const register unsigned short int S4C3 = 4;
    sbit  S4C3_bit at LCDDATA9.B4;
    const register unsigned short int S5C3 = 5;
    sbit  S5C3_bit at LCDDATA9.B5;
    const register unsigned short int S6C3 = 6;
    sbit  S6C3_bit at LCDDATA9.B6;
    const register unsigned short int S7C3 = 7;
    sbit  S7C3_bit at LCDDATA9.B7;

    // LCDDATA10 bits
    sbit  SEG8_LCDDATA10_bit at LCDDATA10.B0;
    sbit  SEG9_LCDDATA10_bit at LCDDATA10.B1;
    sbit  SEG10_LCDDATA10_bit at LCDDATA10.B2;
    sbit  SEG11_LCDDATA10_bit at LCDDATA10.B3;
    sbit  SEG12_LCDDATA10_bit at LCDDATA10.B4;
    sbit  SEG13_LCDDATA10_bit at LCDDATA10.B5;
    sbit  SEG14_LCDDATA10_bit at LCDDATA10.B6;
    sbit  SEG15_LCDDATA10_bit at LCDDATA10.B7;
    const register unsigned short int SEG8COM3 = 0;
    sbit  SEG8COM3_bit at LCDDATA10.B0;
    const register unsigned short int SEG9COM3 = 1;
    sbit  SEG9COM3_bit at LCDDATA10.B1;
    const register unsigned short int SEG10COM3 = 2;
    sbit  SEG10COM3_bit at LCDDATA10.B2;
    const register unsigned short int SEG11COM3 = 3;
    sbit  SEG11COM3_bit at LCDDATA10.B3;
    const register unsigned short int SEG12COM3 = 4;
    sbit  SEG12COM3_bit at LCDDATA10.B4;
    const register unsigned short int SEG13COM3 = 5;
    sbit  SEG13COM3_bit at LCDDATA10.B5;
    const register unsigned short int SEG14COM3 = 6;
    sbit  SEG14COM3_bit at LCDDATA10.B6;
    const register unsigned short int SEG15COM3 = 7;
    sbit  SEG15COM3_bit at LCDDATA10.B7;
    const register unsigned short int S8C3 = 0;
    sbit  S8C3_bit at LCDDATA10.B0;
    const register unsigned short int S9C3 = 1;
    sbit  S9C3_bit at LCDDATA10.B1;
    const register unsigned short int S10C3 = 2;
    sbit  S10C3_bit at LCDDATA10.B2;
    const register unsigned short int S11C3 = 3;
    sbit  S11C3_bit at LCDDATA10.B3;
    const register unsigned short int S12C3 = 4;
    sbit  S12C3_bit at LCDDATA10.B4;
    const register unsigned short int S13C3 = 5;
    sbit  S13C3_bit at LCDDATA10.B5;
    const register unsigned short int S14C3 = 6;
    sbit  S14C3_bit at LCDDATA10.B6;
    const register unsigned short int S15C3 = 7;
    sbit  S15C3_bit at LCDDATA10.B7;

    // LCDDATA11 bits
    sbit  SEG16_LCDDATA11_bit at LCDDATA11.B0;
    sbit  SEG17_LCDDATA11_bit at LCDDATA11.B1;
    sbit  SEG18_LCDDATA11_bit at LCDDATA11.B2;
    sbit  SEG19_LCDDATA11_bit at LCDDATA11.B3;
    sbit  SEG20_LCDDATA11_bit at LCDDATA11.B4;
    sbit  SEG21_LCDDATA11_bit at LCDDATA11.B5;
    sbit  SEG22_LCDDATA11_bit at LCDDATA11.B6;
    sbit  SEG23_LCDDATA11_bit at LCDDATA11.B7;
    const register unsigned short int SEG16COM3 = 0;
    sbit  SEG16COM3_bit at LCDDATA11.B0;
    const register unsigned short int SEG17COM3 = 1;
    sbit  SEG17COM3_bit at LCDDATA11.B1;
    const register unsigned short int SEG18COM3 = 2;
    sbit  SEG18COM3_bit at LCDDATA11.B2;
    const register unsigned short int SEG19COM3 = 3;
    sbit  SEG19COM3_bit at LCDDATA11.B3;
    const register unsigned short int SEG20COM3 = 4;
    sbit  SEG20COM3_bit at LCDDATA11.B4;
    const register unsigned short int SEG21COM3 = 5;
    sbit  SEG21COM3_bit at LCDDATA11.B5;
    const register unsigned short int SEG22COM3 = 6;
    sbit  SEG22COM3_bit at LCDDATA11.B6;
    const register unsigned short int SEG23COM3 = 7;
    sbit  SEG23COM3_bit at LCDDATA11.B7;
    const register unsigned short int S16C3 = 0;
    sbit  S16C3_bit at LCDDATA11.B0;
    const register unsigned short int S17C3 = 1;
    sbit  S17C3_bit at LCDDATA11.B1;
    const register unsigned short int S18C3 = 2;
    sbit  S18C3_bit at LCDDATA11.B2;
    const register unsigned short int S19C3 = 3;
    sbit  S19C3_bit at LCDDATA11.B3;
    const register unsigned short int S20C3 = 4;
    sbit  S20C3_bit at LCDDATA11.B4;
    const register unsigned short int S21C3 = 5;
    sbit  S21C3_bit at LCDDATA11.B5;
    const register unsigned short int S22C3 = 6;
    sbit  S22C3_bit at LCDDATA11.B6;
    const register unsigned short int S23C3 = 7;
    sbit  S23C3_bit at LCDDATA11.B7;

    // LCDSE0 bits
    sbit  SEG0_LCDSE0_bit at LCDSE0.B0;
    sbit  SEG1_LCDSE0_bit at LCDSE0.B1;
    sbit  SEG2_LCDSE0_bit at LCDSE0.B2;
    sbit  SEG3_LCDSE0_bit at LCDSE0.B3;
    sbit  SEG4_LCDSE0_bit at LCDSE0.B4;
    sbit  SEG5_LCDSE0_bit at LCDSE0.B5;
    sbit  SEG6_LCDSE0_bit at LCDSE0.B6;
    sbit  SEG7_LCDSE0_bit at LCDSE0.B7;
    const register unsigned short int SE0 = 0;
    sbit  SE0_bit at LCDSE0.B0;
    const register unsigned short int SE1 = 1;
    sbit  SE1_bit at LCDSE0.B1;
    const register unsigned short int SE2 = 2;
    sbit  SE2_bit at LCDSE0.B2;
    const register unsigned short int SE3 = 3;
    sbit  SE3_bit at LCDSE0.B3;
    const register unsigned short int SE4 = 4;
    sbit  SE4_bit at LCDSE0.B4;
    const register unsigned short int SE5 = 5;
    sbit  SE5_bit at LCDSE0.B5;
    const register unsigned short int SE6 = 6;
    sbit  SE6_bit at LCDSE0.B6;
    const register unsigned short int SE7 = 7;
    sbit  SE7_bit at LCDSE0.B7;
    const register unsigned short int SEGEN0 = 0;
    sbit  SEGEN0_bit at LCDSE0.B0;
    const register unsigned short int SEGEN1 = 1;
    sbit  SEGEN1_bit at LCDSE0.B1;
    const register unsigned short int SEGEN2 = 2;
    sbit  SEGEN2_bit at LCDSE0.B2;
    const register unsigned short int SEGEN3 = 3;
    sbit  SEGEN3_bit at LCDSE0.B3;
    const register unsigned short int SEGEN4 = 4;
    sbit  SEGEN4_bit at LCDSE0.B4;
    const register unsigned short int SEGEN5 = 5;
    sbit  SEGEN5_bit at LCDSE0.B5;
    const register unsigned short int SEGEN6 = 6;
    sbit  SEGEN6_bit at LCDSE0.B6;
    const register unsigned short int SEGEN7 = 7;
    sbit  SEGEN7_bit at LCDSE0.B7;

    // LCDSE1 bits
    sbit  SEG8_LCDSE1_bit at LCDSE1.B0;
    sbit  SEG9_LCDSE1_bit at LCDSE1.B1;
    sbit  SEG10_LCDSE1_bit at LCDSE1.B2;
    sbit  SEG11_LCDSE1_bit at LCDSE1.B3;
    sbit  SEG12_LCDSE1_bit at LCDSE1.B4;
    sbit  SEG13_LCDSE1_bit at LCDSE1.B5;
    sbit  SEG14_LCDSE1_bit at LCDSE1.B6;
    sbit  SEG15_LCDSE1_bit at LCDSE1.B7;
    const register unsigned short int SE8 = 0;
    sbit  SE8_bit at LCDSE1.B0;
    const register unsigned short int SE9 = 1;
    sbit  SE9_bit at LCDSE1.B1;
    const register unsigned short int SE10 = 2;
    sbit  SE10_bit at LCDSE1.B2;
    const register unsigned short int SE11 = 3;
    sbit  SE11_bit at LCDSE1.B3;
    const register unsigned short int SE12 = 4;
    sbit  SE12_bit at LCDSE1.B4;
    const register unsigned short int SE13 = 5;
    sbit  SE13_bit at LCDSE1.B5;
    const register unsigned short int SE14 = 6;
    sbit  SE14_bit at LCDSE1.B6;
    const register unsigned short int SE15 = 7;
    sbit  SE15_bit at LCDSE1.B7;
    const register unsigned short int SEGEN8 = 0;
    sbit  SEGEN8_bit at LCDSE1.B0;
    const register unsigned short int SEGEN9 = 1;
    sbit  SEGEN9_bit at LCDSE1.B1;
    const register unsigned short int SEGEN10 = 2;
    sbit  SEGEN10_bit at LCDSE1.B2;
    const register unsigned short int SEGEN11 = 3;
    sbit  SEGEN11_bit at LCDSE1.B3;
    const register unsigned short int SEGEN12 = 4;
    sbit  SEGEN12_bit at LCDSE1.B4;
    const register unsigned short int SEGEN13 = 5;
    sbit  SEGEN13_bit at LCDSE1.B5;
    const register unsigned short int SEGEN14 = 6;
    sbit  SEGEN14_bit at LCDSE1.B6;
    const register unsigned short int SEGEN15 = 7;
    sbit  SEGEN15_bit at LCDSE1.B7;

    // LCDSE2 bits
    sbit  SEG16_LCDSE2_bit at LCDSE2.B0;
    sbit  SEG17_LCDSE2_bit at LCDSE2.B1;
    sbit  SEG18_LCDSE2_bit at LCDSE2.B2;
    sbit  SEG19_LCDSE2_bit at LCDSE2.B3;
    sbit  SEG20_LCDSE2_bit at LCDSE2.B4;
    sbit  SEG21_LCDSE2_bit at LCDSE2.B5;
    sbit  SEG22_LCDSE2_bit at LCDSE2.B6;
    sbit  SEG23_LCDSE2_bit at LCDSE2.B7;
    const register unsigned short int SE16 = 0;
    sbit  SE16_bit at LCDSE2.B0;
    const register unsigned short int SE17 = 1;
    sbit  SE17_bit at LCDSE2.B1;
    const register unsigned short int SE18 = 2;
    sbit  SE18_bit at LCDSE2.B2;
    const register unsigned short int SE19 = 3;
    sbit  SE19_bit at LCDSE2.B3;
    const register unsigned short int SE20 = 4;
    sbit  SE20_bit at LCDSE2.B4;
    const register unsigned short int SE21 = 5;
    sbit  SE21_bit at LCDSE2.B5;
    const register unsigned short int SE22 = 6;
    sbit  SE22_bit at LCDSE2.B6;
    const register unsigned short int SE23 = 7;
    sbit  SE23_bit at LCDSE2.B7;
    const register unsigned short int SEGEN16 = 0;
    sbit  SEGEN16_bit at LCDSE2.B0;
    const register unsigned short int SEGEN17 = 1;
    sbit  SEGEN17_bit at LCDSE2.B1;
    const register unsigned short int SEGEN18 = 2;
    sbit  SEGEN18_bit at LCDSE2.B2;
    const register unsigned short int SEGEN19 = 3;
    sbit  SEGEN19_bit at LCDSE2.B3;
    const register unsigned short int SEGEN20 = 4;
    sbit  SEGEN20_bit at LCDSE2.B4;
    const register unsigned short int SEGEN21 = 5;
    sbit  SEGEN21_bit at LCDSE2.B5;
    const register unsigned short int SEGEN22 = 6;
    sbit  SEGEN22_bit at LCDSE2.B6;
    const register unsigned short int SEGEN23 = 7;
    sbit  SEGEN23_bit at LCDSE2.B7;

    // EECON1 bits
    const register unsigned short int RD = 0;
    sbit  RD_bit at EECON1.B0;
    const register unsigned short int WR = 1;
    sbit  WR_bit at EECON1.B1;
    const register unsigned short int WREN = 2;
    sbit  WREN_bit at EECON1.B2;
    const register unsigned short int WRERR = 3;
    sbit  WRERR_bit at EECON1.B3;
    const register unsigned short int EEPGD = 7;
    sbit  EEPGD_bit at EECON1.B7;
    const register unsigned short int EERD = 0;
    sbit  EERD_bit at EECON1.B0;
    const register unsigned short int EEWR = 1;
    sbit  EEWR_bit at EECON1.B1;

    // PORTA bits
    const register unsigned short int RA7 = 7;
    sbit  RA7_bit at PORTA.B7;
    const register unsigned short int RA6 = 6;
    sbit  RA6_bit at PORTA.B6;
    const register unsigned short int RA5 = 5;
    sbit  RA5_bit at PORTA.B5;
    const register unsigned short int RA4 = 4;
    sbit  RA4_bit at PORTA.B4;
    const register unsigned short int RA3 = 3;
    sbit  RA3_bit at PORTA.B3;
    const register unsigned short int RA2 = 2;
    sbit  RA2_bit at PORTA.B2;
    const register unsigned short int RA1 = 1;
    sbit  RA1_bit at PORTA.B1;
    const register unsigned short int RA0 = 0;
    sbit  RA0_bit at PORTA.B0;

    // PORTB bits
    const register unsigned short int RB7 = 7;
    sbit  RB7_bit at PORTB.B7;
    const register unsigned short int RB6 = 6;
    sbit  RB6_bit at PORTB.B6;
    const register unsigned short int RB5 = 5;
    sbit  RB5_bit at PORTB.B5;
    const register unsigned short int RB4 = 4;
    sbit  RB4_bit at PORTB.B4;
    const register unsigned short int RB3 = 3;
    sbit  RB3_bit at PORTB.B3;
    const register unsigned short int RB2 = 2;
    sbit  RB2_bit at PORTB.B2;
    const register unsigned short int RB1 = 1;
    sbit  RB1_bit at PORTB.B1;
    const register unsigned short int RB0 = 0;
    sbit  RB0_bit at PORTB.B0;

    // PORTC bits
    const register unsigned short int RC7 = 7;
    sbit  RC7_bit at PORTC.B7;
    const register unsigned short int RC6 = 6;
    sbit  RC6_bit at PORTC.B6;
    const register unsigned short int RC5 = 5;
    sbit  RC5_bit at PORTC.B5;
    const register unsigned short int RC4 = 4;
    sbit  RC4_bit at PORTC.B4;
    const register unsigned short int RC3 = 3;
    sbit  RC3_bit at PORTC.B3;
    const register unsigned short int RC2 = 2;
    sbit  RC2_bit at PORTC.B2;
    const register unsigned short int RC1 = 1;
    sbit  RC1_bit at PORTC.B1;
    const register unsigned short int RC0 = 0;
    sbit  RC0_bit at PORTC.B0;

    // PORTD bits
    const register unsigned short int RD7 = 7;
    sbit  RD7_bit at PORTD.B7;
    const register unsigned short int RD6 = 6;
    sbit  RD6_bit at PORTD.B6;
    const register unsigned short int RD5 = 5;
    sbit  RD5_bit at PORTD.B5;
    const register unsigned short int RD4 = 4;
    sbit  RD4_bit at PORTD.B4;
    const register unsigned short int RD3 = 3;
    sbit  RD3_bit at PORTD.B3;
    const register unsigned short int RD2 = 2;
    sbit  RD2_bit at PORTD.B2;
    const register unsigned short int RD1 = 1;
    sbit  RD1_bit at PORTD.B1;
    const register unsigned short int RD0 = 0;
    sbit  RD0_bit at PORTD.B0;

    // PORTE bits
    const register unsigned short int RE3 = 3;
    sbit  RE3_bit at PORTE.B3;
    const register unsigned short int RE2 = 2;
    sbit  RE2_bit at PORTE.B2;
    const register unsigned short int RE1 = 1;
    sbit  RE1_bit at PORTE.B1;
    const register unsigned short int RE0 = 0;
    sbit  RE0_bit at PORTE.B0;

    // TRISA bits
    const register unsigned short int TRISA7 = 7;
    sbit  TRISA7_bit at TRISA.B7;
    const register unsigned short int TRISA6 = 6;
    sbit  TRISA6_bit at TRISA.B6;
    const register unsigned short int TRISA5 = 5;
    sbit  TRISA5_bit at TRISA.B5;
    const register unsigned short int TRISA4 = 4;
    sbit  TRISA4_bit at TRISA.B4;
    const register unsigned short int TRISA3 = 3;
    sbit  TRISA3_bit at TRISA.B3;
    const register unsigned short int TRISA2 = 2;
    sbit  TRISA2_bit at TRISA.B2;
    const register unsigned short int TRISA1 = 1;
    sbit  TRISA1_bit at TRISA.B1;
    const register unsigned short int TRISA0 = 0;
    sbit  TRISA0_bit at TRISA.B0;

    // TRISB bits
    const register unsigned short int TRISB7 = 7;
    sbit  TRISB7_bit at TRISB.B7;
    const register unsigned short int TRISB6 = 6;
    sbit  TRISB6_bit at TRISB.B6;
    const register unsigned short int TRISB5 = 5;
    sbit  TRISB5_bit at TRISB.B5;
    const register unsigned short int TRISB4 = 4;
    sbit  TRISB4_bit at TRISB.B4;
    const register unsigned short int TRISB3 = 3;
    sbit  TRISB3_bit at TRISB.B3;
    const register unsigned short int TRISB2 = 2;
    sbit  TRISB2_bit at TRISB.B2;
    const register unsigned short int TRISB1 = 1;
    sbit  TRISB1_bit at TRISB.B1;
    const register unsigned short int TRISB0 = 0;
    sbit  TRISB0_bit at TRISB.B0;

    // TRISC bits
    const register unsigned short int TRISC7 = 7;
    sbit  TRISC7_bit at TRISC.B7;
    const register unsigned short int TRISC6 = 6;
    sbit  TRISC6_bit at TRISC.B6;
    const register unsigned short int TRISC5 = 5;
    sbit  TRISC5_bit at TRISC.B5;
    const register unsigned short int TRISC4 = 4;
    sbit  TRISC4_bit at TRISC.B4;
    const register unsigned short int TRISC3 = 3;
    sbit  TRISC3_bit at TRISC.B3;
    const register unsigned short int TRISC2 = 2;
    sbit  TRISC2_bit at TRISC.B2;
    const register unsigned short int TRISC1 = 1;
    sbit  TRISC1_bit at TRISC.B1;
    const register unsigned short int TRISC0 = 0;
    sbit  TRISC0_bit at TRISC.B0;

    // TRISD bits
    const register unsigned short int TRISD7 = 7;
    sbit  TRISD7_bit at TRISD.B7;
    const register unsigned short int TRISD6 = 6;
    sbit  TRISD6_bit at TRISD.B6;
    const register unsigned short int TRISD5 = 5;
    sbit  TRISD5_bit at TRISD.B5;
    const register unsigned short int TRISD4 = 4;
    sbit  TRISD4_bit at TRISD.B4;
    const register unsigned short int TRISD3 = 3;
    sbit  TRISD3_bit at TRISD.B3;
    const register unsigned short int TRISD2 = 2;
    sbit  TRISD2_bit at TRISD.B2;
    const register unsigned short int TRISD1 = 1;
    sbit  TRISD1_bit at TRISD.B1;
    const register unsigned short int TRISD0 = 0;
    sbit  TRISD0_bit at TRISD.B0;

    // TRISE bits
    const register unsigned short int TRISE3 = 3;
    sbit  TRISE3_bit at TRISE.B3;
    const register unsigned short int TRISE2 = 2;
    sbit  TRISE2_bit at TRISE.B2;
    const register unsigned short int TRISE1 = 1;
    sbit  TRISE1_bit at TRISE.B1;
    const register unsigned short int TRISE0 = 0;
    sbit  TRISE0_bit at TRISE.B0;
