// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00001000;

// Working space registers
rx unsigned short R0  absolute 0x0070;
rx unsigned short R1  absolute 0x0071;
rx unsigned short R2  absolute 0x0072;
rx unsigned short R3  absolute 0x0073;
rx unsigned short R4  absolute 0x0074;
rx unsigned short R5  absolute 0x0075;
rx unsigned short R6  absolute 0x0076;
rx unsigned short R7  absolute 0x0077;
rx unsigned short R8  absolute 0x0078;
rx unsigned short R9  absolute 0x0079;
rx unsigned short R10 absolute 0x007A;
rx unsigned short R11 absolute 0x007B;
rx unsigned short R12 absolute 0x007C;
rx unsigned short R13 absolute 0x007D;
rx unsigned short R14 absolute 0x007E;
rx unsigned short R15 absolute 0x007F;

const register unsigned short int W = 0;
const register unsigned short int F = 1;

// Special function registers (SFRs)

const signed int   PORT_TO_TRIS_OFFSET    =     128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

sfr unsigned short volatile INDF0            absolute 0x000;
sfr unsigned short volatile INDF1            absolute 0x001;
sfr unsigned short volatile PCL              absolute 0x002;
sfr unsigned short volatile STATUS           absolute 0x003;
    const register unsigned short int CARRY = 0;
    const register unsigned short int C = 0;
    sbit  CARRY_bit at STATUS.B0;
    sbit  C_bit at STATUS.B0;
    const register unsigned short int DC = 1;
    sbit  DC_bit at STATUS.B1;
    const register unsigned short int ZERO = 2;
    const register unsigned short int Z = 2;
    sbit  ZERO_bit at STATUS.B2;
    sbit  Z_bit at STATUS.B2;
    const register unsigned short int nPD = 3;
    sbit  nPD_bit at STATUS.B3;
    const register unsigned short int nTO = 4;
    sbit  nTO_bit at STATUS.B4;

sfr unsigned int            FSR0             absolute 0x004;
sfr unsigned short          FSR0L            absolute 0x004;
register unsigned short     *FSR0PTR         absolute 0x004;
sfr unsigned short          FSR0H            absolute 0x005;
sfr unsigned int            FSR1             absolute 0x006;
sfr unsigned short          FSR1L            absolute 0x006;
register unsigned short     *FSR1PTR         absolute 0x006;
sfr unsigned short          FSR1H            absolute 0x007;
sfr unsigned short          BSR              absolute 0x008;
    const register unsigned short int BSR0 = 0;
    sbit  BSR0_bit at BSR.B0;
    const register unsigned short int BSR1 = 1;
    sbit  BSR1_bit at BSR.B1;
    const register unsigned short int BSR2 = 2;
    sbit  BSR2_bit at BSR.B2;
    const register unsigned short int BSR3 = 3;
    sbit  BSR3_bit at BSR.B3;
    const register unsigned short int BSR4 = 4;
    sbit  BSR4_bit at BSR.B4;

sfr unsigned short volatile WREG             absolute 0x009;
sfr unsigned short volatile PCLATH           absolute 0x00A;
sfr unsigned short volatile INTCON           absolute 0x00B;
    const register unsigned short int IOCIF = 0;
    sbit  IOCIF_bit at INTCON.B0;
    const register unsigned short int INTF = 1;
    sbit  INTF_bit at INTCON.B1;
    const register unsigned short int T0IF = 2;
    sbit  T0IF_bit at INTCON.B2;
    const register unsigned short int IOCIE = 3;
    sbit  IOCIE_bit at INTCON.B3;
    const register unsigned short int INTE = 4;
    sbit  INTE_bit at INTCON.B4;
    const register unsigned short int T0IE = 5;
    sbit  T0IE_bit at INTCON.B5;
    const register unsigned short int PEIE = 6;
    sbit  PEIE_bit at INTCON.B6;
    const register unsigned short int GIE = 7;
    sbit  GIE_bit at INTCON.B7;
    const register unsigned short int TMR0IE = 5;
    sbit  TMR0IE_bit at INTCON.B5;
    const register unsigned short int TMR0IF = 2;
    sbit  TMR0IF_bit at INTCON.B2;

sfr unsigned short volatile PORTA            absolute 0x00C;
    const register unsigned short int RA0 = 0;
    sbit  RA0_bit at PORTA.B0;
    const register unsigned short int RA1 = 1;
    sbit  RA1_bit at PORTA.B1;
    const register unsigned short int RA2 = 2;
    sbit  RA2_bit at PORTA.B2;
    const register unsigned short int RA3 = 3;
    sbit  RA3_bit at PORTA.B3;
    const register unsigned short int RA4 = 4;
    sbit  RA4_bit at PORTA.B4;
    const register unsigned short int RA5 = 5;
    sbit  RA5_bit at PORTA.B5;

sfr unsigned short volatile PORTC            absolute 0x00E;
    const register unsigned short int RC0 = 0;
    sbit  RC0_bit at PORTC.B0;
    const register unsigned short int RC1 = 1;
    sbit  RC1_bit at PORTC.B1;
    const register unsigned short int RC2 = 2;
    sbit  RC2_bit at PORTC.B2;
    const register unsigned short int RC3 = 3;
    sbit  RC3_bit at PORTC.B3;
    const register unsigned short int RC4 = 4;
    sbit  RC4_bit at PORTC.B4;
    const register unsigned short int RC5 = 5;
    sbit  RC5_bit at PORTC.B5;

sfr unsigned short volatile PIR1             absolute 0x011;
    const register unsigned short int TMR1IF = 0;
    sbit  TMR1IF_bit at PIR1.B0;
    const register unsigned short int TMR2IF = 1;
    sbit  TMR2IF_bit at PIR1.B1;
    const register unsigned short int SSP1IF = 3;
    sbit  SSP1IF_bit at PIR1.B3;
    const register unsigned short int TXIF = 4;
    sbit  TXIF_bit at PIR1.B4;
    const register unsigned short int RCIF = 5;
    sbit  RCIF_bit at PIR1.B5;
    const register unsigned short int AD1IF = 6;
    sbit  AD1IF_bit at PIR1.B6;
    const register unsigned short int TMR1GIF = 7;
    sbit  TMR1GIF_bit at PIR1.B7;
    const register unsigned short int ADIF = 6;
    sbit  ADIF_bit at PIR1.B6;

sfr unsigned short volatile PIR2             absolute 0x012;
    const register unsigned short int BCL1IF = 3;
    sbit  BCL1IF_bit at PIR2.B3;
    const register unsigned short int AD2IF = 6;
    sbit  AD2IF_bit at PIR2.B6;

sfr unsigned short volatile TMR0             absolute 0x015;
sfr unsigned int   volatile TMR1             absolute 0x016;
sfr unsigned short volatile TMR1L            absolute 0x016;
sfr unsigned short volatile TMR1H            absolute 0x017;
sfr unsigned short volatile T1CON            absolute 0x018;
    const register unsigned short int TMR1ON = 0;
    sbit  TMR1ON_bit at T1CON.B0;
    const register unsigned short int nT1SYNC = 2;
    sbit  nT1SYNC_bit at T1CON.B2;
    const register unsigned short int T1CKPS0 = 4;
    sbit  T1CKPS0_bit at T1CON.B4;
    const register unsigned short int T1CKPS1 = 5;
    sbit  T1CKPS1_bit at T1CON.B5;
    const register unsigned short int TMR1CS0 = 6;
    sbit  TMR1CS0_bit at T1CON.B6;
    const register unsigned short int TMR1CS1 = 7;
    sbit  TMR1CS1_bit at T1CON.B7;

sfr unsigned short volatile T1GCON           absolute 0x019;
    const register unsigned short int T1GSS0 = 0;
    sbit  T1GSS0_bit at T1GCON.B0;
    const register unsigned short int T1GSS1 = 1;
    sbit  T1GSS1_bit at T1GCON.B1;
    const register unsigned short int T1GVAL = 2;
    sbit  T1GVAL_bit at T1GCON.B2;
    const register unsigned short int T1GGO_nDONE = 3;
    sbit  T1GGO_nDONE_bit at T1GCON.B3;
    const register unsigned short int T1GSPM = 4;
    sbit  T1GSPM_bit at T1GCON.B4;
    const register unsigned short int T1GTM = 5;
    sbit  T1GTM_bit at T1GCON.B5;
    const register unsigned short int T1GPOL = 6;
    sbit  T1GPOL_bit at T1GCON.B6;
    const register unsigned short int TMR1GE = 7;
    sbit  TMR1GE_bit at T1GCON.B7;

sfr unsigned short volatile TMR2             absolute 0x01A;
sfr unsigned short volatile PR2              absolute 0x01B;
sfr unsigned short volatile T2CON            absolute 0x01C;
    const register unsigned short int T2CKPS0 = 0;
    sbit  T2CKPS0_bit at T2CON.B0;
    const register unsigned short int T2CKPS1 = 1;
    sbit  T2CKPS1_bit at T2CON.B1;
    const register unsigned short int TMR2ON = 2;
    sbit  TMR2ON_bit at T2CON.B2;
    const register unsigned short int T2OUTPS0 = 3;
    sbit  T2OUTPS0_bit at T2CON.B3;
    const register unsigned short int T2OUTPS1 = 4;
    sbit  T2OUTPS1_bit at T2CON.B4;
    const register unsigned short int T2OUTPS2 = 5;
    sbit  T2OUTPS2_bit at T2CON.B5;
    const register unsigned short int T2OUTPS3 = 6;
    sbit  T2OUTPS3_bit at T2CON.B6;

sfr unsigned short volatile TRISA            absolute 0x08C;
    const register unsigned short int TRISA0 = 0;
    sbit  TRISA0_bit at TRISA.B0;
    const register unsigned short int TRISA1 = 1;
    sbit  TRISA1_bit at TRISA.B1;
    const register unsigned short int TRISA2 = 2;
    sbit  TRISA2_bit at TRISA.B2;
    const register unsigned short int TRISA3 = 3;
    sbit  TRISA3_bit at TRISA.B3;
    const register unsigned short int TRISA4 = 4;
    sbit  TRISA4_bit at TRISA.B4;
    const register unsigned short int TRISA5 = 5;
    sbit  TRISA5_bit at TRISA.B5;

sfr unsigned short volatile TRISC            absolute 0x08E;
    const register unsigned short int TRISC0 = 0;
    sbit  TRISC0_bit at TRISC.B0;
    const register unsigned short int TRISC1 = 1;
    sbit  TRISC1_bit at TRISC.B1;
    const register unsigned short int TRISC2 = 2;
    sbit  TRISC2_bit at TRISC.B2;
    const register unsigned short int TRISC3 = 3;
    sbit  TRISC3_bit at TRISC.B3;
    const register unsigned short int TRISC4 = 4;
    sbit  TRISC4_bit at TRISC.B4;
    const register unsigned short int TRISC5 = 5;
    sbit  TRISC5_bit at TRISC.B5;

sfr unsigned short volatile PIE1             absolute 0x091;
    const register unsigned short int TMR1IE = 0;
    sbit  TMR1IE_bit at PIE1.B0;
    const register unsigned short int TMR2IE = 1;
    sbit  TMR2IE_bit at PIE1.B1;
    const register unsigned short int SSP1IE = 3;
    sbit  SSP1IE_bit at PIE1.B3;
    const register unsigned short int TXIE = 4;
    sbit  TXIE_bit at PIE1.B4;
    const register unsigned short int RCIE = 5;
    sbit  RCIE_bit at PIE1.B5;
    const register unsigned short int AD1IE = 6;
    sbit  AD1IE_bit at PIE1.B6;
    const register unsigned short int TMR1GIE = 7;
    sbit  TMR1GIE_bit at PIE1.B7;
    const register unsigned short int ADIE = 6;
    sbit  ADIE_bit at PIE1.B6;

sfr unsigned short volatile PIE2             absolute 0x092;
    const register unsigned short int BCL1IE = 3;
    sbit  BCL1IE_bit at PIE2.B3;
    const register unsigned short int AD2IE = 6;
    sbit  AD2IE_bit at PIE2.B6;

sfr unsigned short volatile OPTION_REG       absolute 0x095;
    const register unsigned short int PS0 = 0;
    sbit  PS0_bit at OPTION_REG.B0;
    const register unsigned short int PS1 = 1;
    sbit  PS1_bit at OPTION_REG.B1;
    const register unsigned short int PS2 = 2;
    sbit  PS2_bit at OPTION_REG.B2;
    const register unsigned short int PSA = 3;
    sbit  PSA_bit at OPTION_REG.B3;
    const register unsigned short int T0SE = 4;
    sbit  T0SE_bit at OPTION_REG.B4;
    const register unsigned short int T0CS = 5;
    sbit  T0CS_bit at OPTION_REG.B5;
    const register unsigned short int INTEDG = 6;
    sbit  INTEDG_bit at OPTION_REG.B6;
    const register unsigned short int nWPUEN = 7;
    sbit  nWPUEN_bit at OPTION_REG.B7;
    const register unsigned short int TMR0CS = 5;
    sbit  TMR0CS_bit at OPTION_REG.B5;
    const register unsigned short int TMR0SE = 4;
    sbit  TMR0SE_bit at OPTION_REG.B4;

sfr unsigned short volatile PCON             absolute 0x096;
    const register unsigned short int nBOR = 0;
    sbit  nBOR_bit at PCON.B0;
    const register unsigned short int nPOR = 1;
    sbit  nPOR_bit at PCON.B1;
    const register unsigned short int nRI = 2;
    sbit  nRI_bit at PCON.B2;
    const register unsigned short int nRMCLR = 3;
    sbit  nRMCLR_bit at PCON.B3;
    const register unsigned short int nRWDT = 4;
    sbit  nRWDT_bit at PCON.B4;
    const register unsigned short int STKUNF = 6;
    sbit  STKUNF_bit at PCON.B6;
    const register unsigned short int STKOVF = 7;
    sbit  STKOVF_bit at PCON.B7;

sfr unsigned short          WDTCON           absolute 0x097;
    const register unsigned short int SWDTEN = 0;
    sbit  SWDTEN_bit at WDTCON.B0;
    const register unsigned short int WDTPS0 = 1;
    sbit  WDTPS0_bit at WDTCON.B1;
    const register unsigned short int WDTPS1 = 2;
    sbit  WDTPS1_bit at WDTCON.B2;
    const register unsigned short int WDTPS2 = 3;
    sbit  WDTPS2_bit at WDTCON.B3;
    const register unsigned short int WDTPS3 = 4;
    sbit  WDTPS3_bit at WDTCON.B4;
    const register unsigned short int WDTPS4 = 5;
    sbit  WDTPS4_bit at WDTCON.B5;

sfr unsigned short volatile OSCCON           absolute 0x099;
    const register unsigned short int SCS0 = 0;
    sbit  SCS0_bit at OSCCON.B0;
    const register unsigned short int SCS1 = 1;
    sbit  SCS1_bit at OSCCON.B1;
    const register unsigned short int IRCF0 = 3;
    sbit  IRCF0_bit at OSCCON.B3;
    const register unsigned short int IRCF1 = 4;
    sbit  IRCF1_bit at OSCCON.B4;
    const register unsigned short int IRCF2 = 5;
    sbit  IRCF2_bit at OSCCON.B5;
    const register unsigned short int IRCF3 = 6;
    sbit  IRCF3_bit at OSCCON.B6;
    const register unsigned short int SPLLEN = 7;
    sbit  SPLLEN_bit at OSCCON.B7;

sfr unsigned short volatile OSCSTAT          absolute 0x09A;
    const register unsigned short int HFIOFS = 0;
    sbit  HFIOFS_bit at OSCSTAT.B0;
    const register unsigned short int LFIOFR = 1;
    sbit  LFIOFR_bit at OSCSTAT.B1;
    const register unsigned short int HFIOFR = 4;
    sbit  HFIOFR_bit at OSCSTAT.B4;
    const register unsigned short int PLLSR = 6;
    sbit  PLLSR_bit at OSCSTAT.B6;

sfr unsigned int   volatile ADRES            absolute 0x09B;
sfr unsigned short volatile ADRESL           absolute 0x09B;
sfr unsigned short volatile ADRESH           absolute 0x09C;
sfr unsigned short volatile ADCON0           absolute 0x09D;
    const register unsigned short int AD1ON = 0;
    sbit  AD1ON_bit at ADCON0.B0;
    const register unsigned short int ADGO = 1;
    sbit  ADGO_bit at ADCON0.B1;
    const register unsigned short int GO_NOT_DONE = 1;
    sbit  GO_NOT_DONE_bit at ADCON0.B1;

sfr unsigned short volatile ADCON1           absolute 0x09E;
sfr unsigned short volatile ADCON2           absolute 0x09F;
sfr unsigned short volatile LATA             absolute 0x10C;
    const register unsigned short int LATA0 = 0;
    sbit  LATA0_bit at LATA.B0;
    const register unsigned short int LATA1 = 1;
    sbit  LATA1_bit at LATA.B1;
    const register unsigned short int LATA2 = 2;
    sbit  LATA2_bit at LATA.B2;
    const register unsigned short int LATA4 = 4;
    sbit  LATA4_bit at LATA.B4;
    const register unsigned short int LATA5 = 5;
    sbit  LATA5_bit at LATA.B5;

sfr unsigned short volatile LATC             absolute 0x10E;
    const register unsigned short int LATC0 = 0;
    sbit  LATC0_bit at LATC.B0;
    const register unsigned short int LATC1 = 1;
    sbit  LATC1_bit at LATC.B1;
    const register unsigned short int LATC2 = 2;
    sbit  LATC2_bit at LATC.B2;
    const register unsigned short int LATC3 = 3;
    sbit  LATC3_bit at LATC.B3;
    const register unsigned short int LATC4 = 4;
    sbit  LATC4_bit at LATC.B4;
    const register unsigned short int LATC5 = 5;
    sbit  LATC5_bit at LATC.B5;

sfr unsigned short volatile BORCON           absolute 0x116;
    const register unsigned short int BORRDY = 0;
    sbit  BORRDY_bit at BORCON.B0;
    const register unsigned short int BORFS = 6;
    sbit  BORFS_bit at BORCON.B6;
    const register unsigned short int SBOREN = 7;
    sbit  SBOREN_bit at BORCON.B7;

sfr unsigned short volatile FVRCON           absolute 0x117;
    const register unsigned short int ADFVR0 = 0;
    sbit  ADFVR0_bit at FVRCON.B0;
    const register unsigned short int ADFVR1 = 1;
    sbit  ADFVR1_bit at FVRCON.B1;
    const register unsigned short int CDAFVR0 = 2;
    sbit  CDAFVR0_bit at FVRCON.B2;
    const register unsigned short int CDAFVR1 = 3;
    sbit  CDAFVR1_bit at FVRCON.B3;
    const register unsigned short int TSRNG = 4;
    sbit  TSRNG_bit at FVRCON.B4;
    const register unsigned short int TSEN = 5;
    sbit  TSEN_bit at FVRCON.B5;
    const register unsigned short int FVRRDY = 6;
    sbit  FVRRDY_bit at FVRCON.B6;
    const register unsigned short int FVREN = 7;
    sbit  FVREN_bit at FVRCON.B7;

sfr unsigned short          APFCON           absolute 0x11D;
    const register unsigned short int GRDASEL = 0;
    sbit  GRDASEL_bit at APFCON.B0;
    const register unsigned short int GRDBSEL = 1;
    sbit  GRDBSEL_bit at APFCON.B1;
    const register unsigned short int TXCKSEL = 2;
    sbit  TXCKSEL_bit at APFCON.B2;
    const register unsigned short int SDSEL = 4;
    sbit  SDSEL_bit at APFCON.B4;
    const register unsigned short int SSSEL = 5;
    sbit  SSSEL_bit at APFCON.B5;
    const register unsigned short int SDOSEL = 6;
    sbit  SDOSEL_bit at APFCON.B6;
    const register unsigned short int RXDTSEL = 7;
    sbit  RXDTSEL_bit at APFCON.B7;

sfr unsigned short volatile ANSELA           absolute 0x18C;
    const register unsigned short int ANSA0 = 0;
    sbit  ANSA0_bit at ANSELA.B0;
    const register unsigned short int ANSA1 = 1;
    sbit  ANSA1_bit at ANSELA.B1;
    const register unsigned short int ANSA2 = 2;
    sbit  ANSA2_bit at ANSELA.B2;
    const register unsigned short int ANSA4 = 4;
    sbit  ANSA4_bit at ANSELA.B4;
    const register unsigned short int ANSA5 = 5;
    sbit  ANSA5_bit at ANSELA.B5;

sfr unsigned short volatile ANSELC           absolute 0x18E;
    const register unsigned short int ANSC0 = 0;
    sbit  ANSC0_bit at ANSELC.B0;
    const register unsigned short int ANSC1 = 1;
    sbit  ANSC1_bit at ANSELC.B1;
    const register unsigned short int ANSC2 = 2;
    sbit  ANSC2_bit at ANSELC.B2;
    const register unsigned short int ANSC3 = 3;
    sbit  ANSC3_bit at ANSELC.B3;
    const register unsigned short int ANSC4 = 4;
    sbit  ANSC4_bit at ANSELC.B4;
    const register unsigned short int ANSC5 = 5;
    sbit  ANSC5_bit at ANSELC.B5;

sfr unsigned int   volatile PMADR            absolute 0x191;
sfr unsigned short volatile PMADRL           absolute 0x191;
sfr unsigned short volatile PMADRH           absolute 0x192;
sfr unsigned int   volatile PMDAT            absolute 0x193;
sfr unsigned short volatile PMDATL           absolute 0x193;
sfr unsigned short volatile PMDATH           absolute 0x194;
sfr unsigned short volatile PMCON1           absolute 0x195;
    const register unsigned short int RD = 0;
    sbit  RD_bit at PMCON1.B0;
    const register unsigned short int WR = 1;
    sbit  WR_bit at PMCON1.B1;
    const register unsigned short int WREN = 2;
    sbit  WREN_bit at PMCON1.B2;
    const register unsigned short int WRERR = 3;
    sbit  WRERR_bit at PMCON1.B3;
    const register unsigned short int FREE = 4;
    sbit  FREE_bit at PMCON1.B4;
    const register unsigned short int LWLO = 5;
    sbit  LWLO_bit at PMCON1.B5;
    const register unsigned short int CFGS = 6;
    sbit  CFGS_bit at PMCON1.B6;

sfr unsigned short volatile PMCON2           absolute 0x196;
sfr unsigned short volatile RC1REG           absolute 0x199;
sfr unsigned short volatile RCREG            absolute 0x199;
sfr unsigned short volatile TX1REG           absolute 0x19A;
sfr unsigned short volatile TXREG            absolute 0x19A;
sfr unsigned int            SPBRG            absolute 0x19B;
sfr unsigned short volatile SPBRGL           absolute 0x19B;
sfr unsigned short          SPBRGH           absolute 0x19C;
sfr unsigned short volatile RCSTA            absolute 0x19D;
    const register unsigned short int RX9D = 0;
    sbit  RX9D_bit at RCSTA.B0;
    const register unsigned short int OERR = 1;
    sbit  OERR_bit at RCSTA.B1;
    const register unsigned short int FERR = 2;
    sbit  FERR_bit at RCSTA.B2;
    const register unsigned short int ADDEN = 3;
    sbit  ADDEN_bit at RCSTA.B3;
    const register unsigned short int CREN = 4;
    sbit  CREN_bit at RCSTA.B4;
    const register unsigned short int SREN = 5;
    sbit  SREN_bit at RCSTA.B5;
    const register unsigned short int RX9 = 6;
    sbit  RX9_bit at RCSTA.B6;
    const register unsigned short int SPEN = 7;
    sbit  SPEN_bit at RCSTA.B7;

sfr unsigned short volatile RC1STA           absolute 0x19D;
sfr unsigned short volatile TXSTA            absolute 0x19E;
    const register unsigned short int TX9D = 0;
    sbit  TX9D_bit at TXSTA.B0;
    const register unsigned short int TRMT = 1;
    sbit  TRMT_bit at TXSTA.B1;
    const register unsigned short int BRGH = 2;
    sbit  BRGH_bit at TXSTA.B2;
    const register unsigned short int SENDB = 3;
    sbit  SENDB_bit at TXSTA.B3;
    const register unsigned short int SYNC = 4;
    sbit  SYNC_bit at TXSTA.B4;
    const register unsigned short int TXEN = 5;
    sbit  TXEN_bit at TXSTA.B5;
    const register unsigned short int TX9 = 6;
    sbit  TX9_bit at TXSTA.B6;
    const register unsigned short int CSRC = 7;
    sbit  CSRC_bit at TXSTA.B7;

sfr unsigned short volatile TX1STA           absolute 0x19E;
sfr unsigned short          BAUDCON          absolute 0x19F;
    const register unsigned short int ABDEN = 0;
    sbit  ABDEN_bit at BAUDCON.B0;
    const register unsigned short int WUE = 1;
    sbit  WUE_bit at BAUDCON.B1;
    const register unsigned short int BRG16 = 3;
    sbit  BRG16_bit at BAUDCON.B3;
    const register unsigned short int SCKP = 4;
    sbit  SCKP_bit at BAUDCON.B4;
    const register unsigned short int RCIDL = 6;
    sbit  RCIDL_bit at BAUDCON.B6;
    const register unsigned short int ABDOVF = 7;
    sbit  ABDOVF_bit at BAUDCON.B7;

sfr unsigned short          WPUA             absolute 0x20C;
    const register unsigned short int WPUA0 = 0;
    sbit  WPUA0_bit at WPUA.B0;
    const register unsigned short int WPUA1 = 1;
    sbit  WPUA1_bit at WPUA.B1;
    const register unsigned short int WPUA2 = 2;
    sbit  WPUA2_bit at WPUA.B2;
    const register unsigned short int WPUA3 = 3;
    sbit  WPUA3_bit at WPUA.B3;
    const register unsigned short int WPUA4 = 4;
    sbit  WPUA4_bit at WPUA.B4;
    const register unsigned short int WPUA5 = 5;
    sbit  WPUA5_bit at WPUA.B5;

sfr unsigned short volatile SSP1BUF          absolute 0x211;
sfr unsigned short volatile SSPBUF           absolute 0x211;
sfr unsigned short volatile SSP1ADD          absolute 0x212;
sfr unsigned short volatile SSPADD           absolute 0x212;
sfr unsigned short volatile SSP1MSK          absolute 0x213;
sfr unsigned short volatile SSPMSK           absolute 0x213;
sfr unsigned short volatile SSP1STAT         absolute 0x214;
    const register unsigned short int BF = 0;
    sbit  BF_bit at SSP1STAT.B0;
    const register unsigned short int UA = 1;
    sbit  UA_bit at SSP1STAT.B1;
    const register unsigned short int R_nW = 2;
    sbit  R_nW_bit at SSP1STAT.B2;
    const register unsigned short int D_nA = 5;
    sbit  D_nA_bit at SSP1STAT.B5;
    const register unsigned short int CKE = 6;
    sbit  CKE_bit at SSP1STAT.B6;
    const register unsigned short int SMP = 7;
    sbit  SMP_bit at SSP1STAT.B7;

sfr unsigned short volatile SSPSTAT          absolute 0x214;
sfr unsigned short volatile SSP1CON1         absolute 0x215;
    const register unsigned short int SSPM0 = 0;
    sbit  SSPM0_bit at SSP1CON1.B0;
    const register unsigned short int SSPM1 = 1;
    sbit  SSPM1_bit at SSP1CON1.B1;
    const register unsigned short int SSPM2 = 2;
    sbit  SSPM2_bit at SSP1CON1.B2;
    const register unsigned short int SSPM3 = 3;
    sbit  SSPM3_bit at SSP1CON1.B3;
    const register unsigned short int CKP = 4;
    sbit  CKP_bit at SSP1CON1.B4;
    const register unsigned short int SSPEN = 5;
    sbit  SSPEN_bit at SSP1CON1.B5;
    const register unsigned short int SSPOV = 6;
    sbit  SSPOV_bit at SSP1CON1.B6;
    const register unsigned short int WCOL = 7;
    sbit  WCOL_bit at SSP1CON1.B7;

sfr unsigned short volatile SSPCON           absolute 0x215;
sfr unsigned short volatile SSPCON1          absolute 0x215;
sfr unsigned short volatile SSP1CON2         absolute 0x216;
    const register unsigned short int SEN = 0;
    sbit  SEN_bit at SSP1CON2.B0;
    const register unsigned short int RSEN = 1;
    sbit  RSEN_bit at SSP1CON2.B1;
    const register unsigned short int PEN = 2;
    sbit  PEN_bit at SSP1CON2.B2;
    const register unsigned short int RCEN = 3;
    sbit  RCEN_bit at SSP1CON2.B3;
    const register unsigned short int ACKEN = 4;
    sbit  ACKEN_bit at SSP1CON2.B4;
    const register unsigned short int ACKDT = 5;
    sbit  ACKDT_bit at SSP1CON2.B5;
    const register unsigned short int ACKSTAT = 6;
    sbit  ACKSTAT_bit at SSP1CON2.B6;
    const register unsigned short int GCEN = 7;
    sbit  GCEN_bit at SSP1CON2.B7;

sfr unsigned short volatile SSPCON2          absolute 0x216;
sfr unsigned short volatile SSP1CON3         absolute 0x217;
    const register unsigned short int DHEN = 0;
    sbit  DHEN_bit at SSP1CON3.B0;
    const register unsigned short int AHEN = 1;
    sbit  AHEN_bit at SSP1CON3.B1;
    const register unsigned short int SBCDE = 2;
    sbit  SBCDE_bit at SSP1CON3.B2;
    const register unsigned short int SDAHT = 3;
    sbit  SDAHT_bit at SSP1CON3.B3;
    const register unsigned short int BOEN = 4;
    sbit  BOEN_bit at SSP1CON3.B4;
    const register unsigned short int SCIE = 5;
    sbit  SCIE_bit at SSP1CON3.B5;
    const register unsigned short int PCIE = 6;
    sbit  PCIE_bit at SSP1CON3.B6;
    const register unsigned short int ACKTIM = 7;
    sbit  ACKTIM_bit at SSP1CON3.B7;

sfr unsigned short volatile SSPCON3          absolute 0x217;
sfr unsigned short volatile IOCAP            absolute 0x391;
    const register unsigned short int IOCAP0 = 0;
    sbit  IOCAP0_bit at IOCAP.B0;
    const register unsigned short int IOCAP1 = 1;
    sbit  IOCAP1_bit at IOCAP.B1;
    const register unsigned short int IOCAP2 = 2;
    sbit  IOCAP2_bit at IOCAP.B2;
    const register unsigned short int IOCAP3 = 3;
    sbit  IOCAP3_bit at IOCAP.B3;
    const register unsigned short int IOCAP4 = 4;
    sbit  IOCAP4_bit at IOCAP.B4;
    const register unsigned short int IOCAP5 = 5;
    sbit  IOCAP5_bit at IOCAP.B5;

sfr unsigned short volatile IOCAN            absolute 0x392;
    const register unsigned short int IOCAN0 = 0;
    sbit  IOCAN0_bit at IOCAN.B0;
    const register unsigned short int IOCAN1 = 1;
    sbit  IOCAN1_bit at IOCAN.B1;
    const register unsigned short int IOCAN2 = 2;
    sbit  IOCAN2_bit at IOCAN.B2;
    const register unsigned short int IOCAN3 = 3;
    sbit  IOCAN3_bit at IOCAN.B3;
    const register unsigned short int IOCAN4 = 4;
    sbit  IOCAN4_bit at IOCAN.B4;
    const register unsigned short int IOCAN5 = 5;
    sbit  IOCAN5_bit at IOCAN.B5;

sfr unsigned short volatile IOCAF            absolute 0x393;
    const register unsigned short int IOCAF0 = 0;
    sbit  IOCAF0_bit at IOCAF.B0;
    const register unsigned short int IOCAF1 = 1;
    sbit  IOCAF1_bit at IOCAF.B1;
    const register unsigned short int IOCAF2 = 2;
    sbit  IOCAF2_bit at IOCAF.B2;
    const register unsigned short int IOCAF3 = 3;
    sbit  IOCAF3_bit at IOCAF.B3;
    const register unsigned short int IOCAF4 = 4;
    sbit  IOCAF4_bit at IOCAF.B4;
    const register unsigned short int IOCAF5 = 5;
    sbit  IOCAF5_bit at IOCAF.B5;

sfr unsigned short volatile PWM1DCL          absolute 0x611;
    const register unsigned short int PWM1DCL0 = 6;
    sbit  PWM1DCL0_bit at PWM1DCL.B6;
    const register unsigned short int PWM1DCL1 = 7;
    sbit  PWM1DCL1_bit at PWM1DCL.B7;

sfr unsigned short volatile PWM1DCH          absolute 0x612;
    const register unsigned short int PWM1DCH0 = 0;
    sbit  PWM1DCH0_bit at PWM1DCH.B0;
    const register unsigned short int PWM1DCH1 = 1;
    sbit  PWM1DCH1_bit at PWM1DCH.B1;
    const register unsigned short int PWM1DCH2 = 2;
    sbit  PWM1DCH2_bit at PWM1DCH.B2;
    const register unsigned short int PWM1DCH3 = 3;
    sbit  PWM1DCH3_bit at PWM1DCH.B3;
    const register unsigned short int PWM1DCH4 = 4;
    sbit  PWM1DCH4_bit at PWM1DCH.B4;
    const register unsigned short int PWM1DCH5 = 5;
    sbit  PWM1DCH5_bit at PWM1DCH.B5;
    const register unsigned short int PWM1DCH6 = 6;
    sbit  PWM1DCH6_bit at PWM1DCH.B6;
    const register unsigned short int PWM1DCH7 = 7;
    sbit  PWM1DCH7_bit at PWM1DCH.B7;

sfr unsigned short          PWM1CON          absolute 0x613;
    const register unsigned short int PWM1POL = 4;
    sbit  PWM1POL_bit at PWM1CON.B4;
    const register unsigned short int PWM1OUT = 5;
    sbit  PWM1OUT_bit at PWM1CON.B5;
    const register unsigned short int PWM1OE = 6;
    sbit  PWM1OE_bit at PWM1CON.B6;
    const register unsigned short int PWM1EN = 7;
    sbit  PWM1EN_bit at PWM1CON.B7;

sfr unsigned short volatile PWM1CON0         absolute 0x613;
sfr unsigned short volatile PWM2DCL          absolute 0x614;
    const register unsigned short int PWM2DCL0 = 6;
    sbit  PWM2DCL0_bit at PWM2DCL.B6;
    const register unsigned short int PWM2DCL1 = 7;
    sbit  PWM2DCL1_bit at PWM2DCL.B7;

sfr unsigned short volatile PWM2DCH          absolute 0x615;
    const register unsigned short int PWM2DCH0 = 0;
    sbit  PWM2DCH0_bit at PWM2DCH.B0;
    const register unsigned short int PWM2DCH1 = 1;
    sbit  PWM2DCH1_bit at PWM2DCH.B1;
    const register unsigned short int PWM2DCH2 = 2;
    sbit  PWM2DCH2_bit at PWM2DCH.B2;
    const register unsigned short int PWM2DCH3 = 3;
    sbit  PWM2DCH3_bit at PWM2DCH.B3;
    const register unsigned short int PWM2DCH4 = 4;
    sbit  PWM2DCH4_bit at PWM2DCH.B4;
    const register unsigned short int PWM2DCH5 = 5;
    sbit  PWM2DCH5_bit at PWM2DCH.B5;
    const register unsigned short int PWM2DCH6 = 6;
    sbit  PWM2DCH6_bit at PWM2DCH.B6;
    const register unsigned short int PWM2DCH7 = 7;
    sbit  PWM2DCH7_bit at PWM2DCH.B7;

sfr unsigned short          PWM2CON          absolute 0x616;
    const register unsigned short int PWM2POL = 4;
    sbit  PWM2POL_bit at PWM2CON.B4;
    const register unsigned short int PWM2OUT = 5;
    sbit  PWM2OUT_bit at PWM2CON.B5;
    const register unsigned short int PWM2OE = 6;
    sbit  PWM2OE_bit at PWM2CON.B6;
    const register unsigned short int PWM2EN = 7;
    sbit  PWM2EN_bit at PWM2CON.B7;

sfr unsigned short volatile PWM2CON0         absolute 0x616;
sfr unsigned short volatile AD1CON0          absolute 0x711;
    const register unsigned short int GO_nDONE1 = 1;
    sbit  GO_nDONE1_bit at AD1CON0.B1;

sfr unsigned short volatile AADCON0          absolute 0x711;
sfr unsigned short volatile AAD1CON0         absolute 0x711;
sfr unsigned short volatile ADCOMCON         absolute 0x712;
    const register unsigned short int ADCS0 = 4;
    sbit  ADCS0_bit at ADCOMCON.B4;
    const register unsigned short int ADCS1 = 5;
    sbit  ADCS1_bit at ADCOMCON.B5;
    const register unsigned short int ADCS2 = 6;
    sbit  ADCS2_bit at ADCOMCON.B6;

sfr unsigned short volatile AADCON1          absolute 0x712;
sfr unsigned short volatile AD1CON2          absolute 0x713;
sfr unsigned short volatile AADCON2          absolute 0x713;
sfr unsigned short volatile AAD1CON2         absolute 0x713;
sfr unsigned short volatile AD1CON3          absolute 0x714;
    const register unsigned short int AD1DSEN = 0;
    sbit  AD1DSEN_bit at AD1CON3.B0;
    const register unsigned short int AD1IPEN = 1;
    sbit  AD1IPEN_bit at AD1CON3.B1;
    const register unsigned short int AD1IPPOL = 6;
    sbit  AD1IPPOL_bit at AD1CON3.B6;
    const register unsigned short int AD1EPPOL = 7;
    sbit  AD1EPPOL_bit at AD1CON3.B7;

sfr unsigned short volatile AADCON3          absolute 0x714;
sfr unsigned short volatile AAD1CON3         absolute 0x714;
sfr unsigned short volatile ADSTAT           absolute 0x715;
    const register unsigned short int AD1STG0 = 0;
    sbit  AD1STG0_bit at ADSTAT.B0;
    const register unsigned short int AD1STG1 = 1;
    sbit  AD1STG1_bit at ADSTAT.B1;
    const register unsigned short int AD1CONV = 2;
    sbit  AD1CONV_bit at ADSTAT.B2;
    const register unsigned short int AD2STG0 = 4;
    sbit  AD2STG0_bit at ADSTAT.B4;
    const register unsigned short int AD2STG1 = 5;
    sbit  AD2STG1_bit at ADSTAT.B5;
    const register unsigned short int AD2CONV = 6;
    sbit  AD2CONV_bit at ADSTAT.B6;
    const register unsigned short int ADCONV = 2;
    sbit  ADCONV_bit at ADSTAT.B2;

sfr unsigned short volatile AADSTAT          absolute 0x715;
sfr unsigned short volatile AD1PRECON        absolute 0x716;
sfr unsigned short volatile AADPRE           absolute 0x716;
sfr unsigned short volatile AD1PRE           absolute 0x716;
sfr unsigned short volatile AAD1PRE          absolute 0x716;
sfr unsigned short volatile AD1ACQCON        absolute 0x717;
sfr unsigned short volatile AADACQ           absolute 0x717;
sfr unsigned short volatile AD1ACQ           absolute 0x717;
sfr unsigned short volatile AAD1ACQ          absolute 0x717;
sfr unsigned short volatile AD1GRD           absolute 0x718;
    const register unsigned short int GRD1POL = 5;
    sbit  GRD1POL_bit at AD1GRD.B5;
    const register unsigned short int GRD1AOE = 6;
    sbit  GRD1AOE_bit at AD1GRD.B6;
    const register unsigned short int GRD1BOE = 7;
    sbit  GRD1BOE_bit at AD1GRD.B7;

sfr unsigned short volatile AADGRD           absolute 0x718;
sfr unsigned short volatile AAD1GRD          absolute 0x718;
sfr unsigned short volatile AD1CAPCON        absolute 0x719;
sfr unsigned short volatile AADCAP           absolute 0x719;
sfr unsigned short volatile AAD1CAP          absolute 0x719;
sfr unsigned short volatile AAD1CAPCON       absolute 0x719;
sfr unsigned int   volatile AAD1RES0         absolute 0x71A;
sfr unsigned int   volatile AD1RES0          absolute 0x71A;
sfr unsigned int   volatile ADRES0           absolute 0x71A;
sfr unsigned short volatile AAD1RES0L        absolute 0x71A;
sfr unsigned short volatile AD1RES0L         absolute 0x71A;
sfr unsigned short volatile AAD1RES0H        absolute 0x71B;
sfr unsigned short volatile AD1RES0H         absolute 0x71B;
sfr unsigned int   volatile AAD1RES1         absolute 0x71C;
sfr unsigned int   volatile AD1RES1          absolute 0x71C;
sfr unsigned int   volatile ADRES1           absolute 0x71C;
sfr unsigned short volatile AAD1RES1L        absolute 0x71C;
sfr unsigned short volatile AD1RES1L         absolute 0x71C;
sfr unsigned short volatile AAD1RES1H        absolute 0x71D;
sfr unsigned short volatile AD1RES1H         absolute 0x71D;
sfr unsigned short volatile AD1CH            absolute 0x71E;
    const register unsigned short int CH10 = 0;
    sbit  CH10_bit at AD1CH.B0;
    const register unsigned short int CH11 = 1;
    sbit  CH11_bit at AD1CH.B1;
    const register unsigned short int CH12 = 2;
    sbit  CH12_bit at AD1CH.B2;
    const register unsigned short int CH13 = 3;
    sbit  CH13_bit at AD1CH.B3;

sfr unsigned short volatile AAD1CH           absolute 0x71E;
sfr unsigned short volatile AD2CON0          absolute 0x791;
    const register unsigned short int GO_nDONE2 = 1;
    sbit  GO_nDONE2_bit at AD2CON0.B1;

sfr unsigned short volatile AAD2CON0         absolute 0x791;
sfr unsigned short volatile AD2CON2          absolute 0x793;
sfr unsigned short volatile AAD2CON2         absolute 0x793;
sfr unsigned short volatile AD2CON3          absolute 0x794;
    const register unsigned short int AD2DSEN = 0;
    sbit  AD2DSEN_bit at AD2CON3.B0;
    const register unsigned short int AD2IPEN = 1;
    sbit  AD2IPEN_bit at AD2CON3.B1;
    const register unsigned short int AD2IPPOL = 6;
    sbit  AD2IPPOL_bit at AD2CON3.B6;
    const register unsigned short int AD2EPPOL = 7;
    sbit  AD2EPPOL_bit at AD2CON3.B7;

sfr unsigned short volatile AAD2CON3         absolute 0x794;
sfr unsigned short volatile AD2PRECON        absolute 0x796;
sfr unsigned short volatile AD2PRE           absolute 0x796;
sfr unsigned short volatile AAD2PRE          absolute 0x796;
sfr unsigned short volatile AD2ACQCON        absolute 0x797;
sfr unsigned short volatile AD2ACQ           absolute 0x797;
sfr unsigned short volatile AAD2ACQ          absolute 0x797;
sfr unsigned short volatile AD2GRD           absolute 0x798;
    const register unsigned short int GRD2POL = 5;
    sbit  GRD2POL_bit at AD2GRD.B5;
    const register unsigned short int GRD2AOE = 6;
    sbit  GRD2AOE_bit at AD2GRD.B6;
    const register unsigned short int GRD2BOE = 7;
    sbit  GRD2BOE_bit at AD2GRD.B7;

sfr unsigned short volatile AAD2GRD          absolute 0x798;
sfr unsigned short volatile AD2CAPCON        absolute 0x799;
sfr unsigned short volatile AAD2CAP          absolute 0x799;
sfr unsigned short volatile AAD2CAPCON       absolute 0x799;
sfr unsigned int   volatile AAD2RES0         absolute 0x79A;
sfr unsigned int   volatile AD2RES0          absolute 0x79A;
sfr unsigned short volatile AAD2RES0L        absolute 0x79A;
sfr unsigned short volatile AD2RES0L         absolute 0x79A;
sfr unsigned short volatile AAD2RES0H        absolute 0x79B;
sfr unsigned short volatile AD2RES0H         absolute 0x79B;
sfr unsigned int   volatile AAD2RES1         absolute 0x79C;
sfr unsigned int   volatile AD2RES1          absolute 0x79C;
sfr unsigned short volatile AAD2RES1L        absolute 0x79C;
sfr unsigned short volatile AD2RES1L         absolute 0x79C;
sfr unsigned short volatile AAD2RES1H        absolute 0x79D;
sfr unsigned short volatile AD2RES1H         absolute 0x79D;
sfr unsigned short volatile AD2CH            absolute 0x79E;
    const register unsigned short int CH20 = 0;
    sbit  CH20_bit at AD2CH.B0;
    const register unsigned short int CH21 = 1;
    sbit  CH21_bit at AD2CH.B1;
    const register unsigned short int CH22 = 2;
    sbit  CH22_bit at AD2CH.B2;
    const register unsigned short int CH23 = 3;
    sbit  CH23_bit at AD2CH.B3;

sfr unsigned short volatile AAD2CH           absolute 0x79E;
sfr unsigned short volatile ICDIO            absolute 0xF8C;
    const register unsigned short int TRIS_ICDCLK = 2;
    sbit  TRIS_ICDCLK_bit at ICDIO.B2;
    const register unsigned short int TRIS_ICDDAT = 3;
    sbit  TRIS_ICDDAT_bit at ICDIO.B3;
    const register unsigned short int LAT_ICDCLK = 4;
    sbit  LAT_ICDCLK_bit at ICDIO.B4;
    const register unsigned short int LAT_ICDDAT = 5;
    sbit  LAT_ICDDAT_bit at ICDIO.B5;
    const register unsigned short int PORT_ICDCLK = 6;
    sbit  PORT_ICDCLK_bit at ICDIO.B6;
    const register unsigned short int PORT_ICDDAT = 7;
    sbit  PORT_ICDDAT_bit at ICDIO.B7;

sfr unsigned short volatile ICDCON0          absolute 0xF8D;
    const register unsigned short int RSTVEC = 0;
    sbit  RSTVEC_bit at ICDCON0.B0;
    const register unsigned short int DBGINEX = 3;
    sbit  DBGINEX_bit at ICDCON0.B3;
    const register unsigned short int SSTEP = 5;
    sbit  SSTEP_bit at ICDCON0.B5;
    const register unsigned short int FREEZ = 6;
    sbit  FREEZ_bit at ICDCON0.B6;
    const register unsigned short int INBUG = 7;
    sbit  INBUG_bit at ICDCON0.B7;

sfr unsigned short volatile ICDSTAT          absolute 0xF91;
    const register unsigned short int USRHLTF = 1;
    sbit  USRHLTF_bit at ICDSTAT.B1;
    const register unsigned short int TRP0HLTF = 6;
    sbit  TRP0HLTF_bit at ICDSTAT.B6;
    const register unsigned short int TRP1HLTF = 7;
    sbit  TRP1HLTF_bit at ICDSTAT.B7;

sfr unsigned short volatile ICDINSTL         absolute 0xF96;
    const register unsigned short int DBGIN0 = 0;
    sbit  DBGIN0_bit at ICDINSTL.B0;
    const register unsigned short int DBGIN1 = 1;
    sbit  DBGIN1_bit at ICDINSTL.B1;
    const register unsigned short int DBGIN2 = 2;
    sbit  DBGIN2_bit at ICDINSTL.B2;
    const register unsigned short int DBGIN3 = 3;
    sbit  DBGIN3_bit at ICDINSTL.B3;
    const register unsigned short int DBGIN4 = 4;
    sbit  DBGIN4_bit at ICDINSTL.B4;
    const register unsigned short int DBGIN5 = 5;
    sbit  DBGIN5_bit at ICDINSTL.B5;
    const register unsigned short int DBGIN6 = 6;
    sbit  DBGIN6_bit at ICDINSTL.B6;
    const register unsigned short int DBGIN7 = 7;
    sbit  DBGIN7_bit at ICDINSTL.B7;

sfr unsigned short volatile ICDINSTH         absolute 0xF97;
    const register unsigned short int DBGIN8 = 0;
    sbit  DBGIN8_bit at ICDINSTH.B0;
    const register unsigned short int DBGIN9 = 1;
    sbit  DBGIN9_bit at ICDINSTH.B1;
    const register unsigned short int DBGIN10 = 2;
    sbit  DBGIN10_bit at ICDINSTH.B2;
    const register unsigned short int DBGIN11 = 3;
    sbit  DBGIN11_bit at ICDINSTH.B3;
    const register unsigned short int DBGIN12 = 4;
    sbit  DBGIN12_bit at ICDINSTH.B4;
    const register unsigned short int DBGIN13 = 5;
    sbit  DBGIN13_bit at ICDINSTH.B5;

sfr unsigned short volatile ICDBK0CON        absolute 0xF9C;
    const register unsigned short int BKHLT = 0;
    sbit  BKHLT_bit at ICDBK0CON.B0;
    const register unsigned short int BKEN = 7;
    sbit  BKEN_bit at ICDBK0CON.B7;

sfr unsigned short volatile ICDBK0L          absolute 0xF9D;
    const register unsigned short int BKA0 = 0;
    sbit  BKA0_bit at ICDBK0L.B0;
    const register unsigned short int BKA1 = 1;
    sbit  BKA1_bit at ICDBK0L.B1;
    const register unsigned short int BKA2 = 2;
    sbit  BKA2_bit at ICDBK0L.B2;
    const register unsigned short int BKA3 = 3;
    sbit  BKA3_bit at ICDBK0L.B3;
    const register unsigned short int BKA4 = 4;
    sbit  BKA4_bit at ICDBK0L.B4;
    const register unsigned short int BKA5 = 5;
    sbit  BKA5_bit at ICDBK0L.B5;
    const register unsigned short int BKA6 = 6;
    sbit  BKA6_bit at ICDBK0L.B6;
    const register unsigned short int BKA7 = 7;
    sbit  BKA7_bit at ICDBK0L.B7;

sfr unsigned short volatile ICDBK0H          absolute 0xF9E;
    const register unsigned short int BKA8 = 0;
    sbit  BKA8_bit at ICDBK0H.B0;
    const register unsigned short int BKA9 = 1;
    sbit  BKA9_bit at ICDBK0H.B1;
    const register unsigned short int BKA10 = 2;
    sbit  BKA10_bit at ICDBK0H.B2;
    const register unsigned short int BKA11 = 3;
    sbit  BKA11_bit at ICDBK0H.B3;
    const register unsigned short int BKA12 = 4;
    sbit  BKA12_bit at ICDBK0H.B4;
    const register unsigned short int BKA13 = 5;
    sbit  BKA13_bit at ICDBK0H.B5;
    const register unsigned short int BKA14 = 6;
    sbit  BKA14_bit at ICDBK0H.B6;

sfr unsigned short volatile BSRICDSHAD       absolute 0xFE3;
sfr unsigned short volatile STATUS_SHAD      absolute 0xFE4;
    const register unsigned short int C_SHAD = 0;
    sbit  C_SHAD_bit at STATUS_SHAD.B0;
    const register unsigned short int DC_SHAD = 1;
    sbit  DC_SHAD_bit at STATUS_SHAD.B1;
    const register unsigned short int Z_SHAD = 2;
    sbit  Z_SHAD_bit at STATUS_SHAD.B2;

sfr unsigned short volatile WREG_SHAD        absolute 0xFE5;
sfr unsigned short volatile BSR_SHAD         absolute 0xFE6;
sfr unsigned short volatile PCLATH_SHAD      absolute 0xFE7;
sfr unsigned short volatile FSR0L_SHAD       absolute 0xFE8;
sfr unsigned short volatile FSR0H_SHAD       absolute 0xFE9;
sfr unsigned short volatile FSR1L_SHAD       absolute 0xFEA;
sfr unsigned short volatile FSR1H_SHAD       absolute 0xFEB;
sfr unsigned short volatile STKPTR           absolute 0xFED;
sfr unsigned short volatile TOSL             absolute 0xFEE;
sfr unsigned short volatile TOSH             absolute 0xFEF;
