// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00000400;

// Working space registers
rx unsigned short R0  absolute 0x0070;
rx unsigned short R1  absolute 0x0071;
rx unsigned short R2  absolute 0x0072;
rx unsigned short R3  absolute 0x0073;
rx unsigned short R4  absolute 0x0074;
rx unsigned short R5  absolute 0x0075;
rx unsigned short R6  absolute 0x0076;
rx unsigned short R7  absolute 0x0077;
rx unsigned short R8  absolute 0x0078;
rx unsigned short R9  absolute 0x0079;
rx unsigned short R10 absolute 0x007A;
rx unsigned short R11 absolute 0x007B;
rx unsigned short R12 absolute 0x007C;
rx unsigned short R13 absolute 0x007D;
rx unsigned short R14 absolute 0x007E;
rx unsigned short R15 absolute 0x007F;

const register unsigned short int W = 0;
const register unsigned short int F = 1;

// Special function registers (SFRs)

const signed int   PORT_TO_TRIS_OFFSET    =     128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

sfr unsigned short volatile INDF0            absolute 0x000;
sfr unsigned short volatile INDF1            absolute 0x001;
sfr unsigned short volatile PCL              absolute 0x002;
sfr unsigned short volatile STATUS           absolute 0x003;
    const register unsigned short int CARRY = 0;
    const register unsigned short int C = 0;
    sbit  CARRY_bit at STATUS.B0;
    sbit  C_bit at STATUS.B0;
    const register unsigned short int DC = 1;
    sbit  DC_bit at STATUS.B1;
    const register unsigned short int ZERO = 2;
    const register unsigned short int Z = 2;
    sbit  ZERO_bit at STATUS.B2;
    sbit  Z_bit at STATUS.B2;
    const register unsigned short int nPD = 3;
    sbit  nPD_bit at STATUS.B3;
    const register unsigned short int nTO = 4;
    sbit  nTO_bit at STATUS.B4;

sfr unsigned int            FSR0             absolute 0x004;
sfr unsigned short          FSR0L            absolute 0x004;
register unsigned short     *FSR0PTR         absolute 0x004;
sfr unsigned short          FSR0H            absolute 0x005;
sfr unsigned int            FSR1             absolute 0x006;
sfr unsigned short          FSR1L            absolute 0x006;
register unsigned short     *FSR1PTR         absolute 0x006;
sfr unsigned short          FSR1H            absolute 0x007;
sfr unsigned short          BSR              absolute 0x008;
    const register unsigned short int BSR0 = 0;
    sbit  BSR0_bit at BSR.B0;
    const register unsigned short int BSR1 = 1;
    sbit  BSR1_bit at BSR.B1;
    const register unsigned short int BSR2 = 2;
    sbit  BSR2_bit at BSR.B2;
    const register unsigned short int BSR3 = 3;
    sbit  BSR3_bit at BSR.B3;
    const register unsigned short int BSR4 = 4;
    sbit  BSR4_bit at BSR.B4;

sfr unsigned short volatile WREG             absolute 0x009;
sfr unsigned short volatile PCLATH           absolute 0x00A;
sfr unsigned short volatile INTCON           absolute 0x00B;
    const register unsigned short int IOCIF = 0;
    sbit  IOCIF_bit at INTCON.B0;
    const register unsigned short int INTF = 1;
    sbit  INTF_bit at INTCON.B1;
    const register unsigned short int T0IF = 2;
    sbit  T0IF_bit at INTCON.B2;
    const register unsigned short int IOCIE = 3;
    sbit  IOCIE_bit at INTCON.B3;
    const register unsigned short int INTE = 4;
    sbit  INTE_bit at INTCON.B4;
    const register unsigned short int T0IE = 5;
    sbit  T0IE_bit at INTCON.B5;
    const register unsigned short int PEIE = 6;
    sbit  PEIE_bit at INTCON.B6;
    const register unsigned short int GIE = 7;
    sbit  GIE_bit at INTCON.B7;
    const register unsigned short int TMR0IE = 5;
    sbit  TMR0IE_bit at INTCON.B5;
    const register unsigned short int TMR0IF = 2;
    sbit  TMR0IF_bit at INTCON.B2;

sfr unsigned short volatile PORTA            absolute 0x00C;
    const register unsigned short int RA0 = 0;
    sbit  RA0_bit at PORTA.B0;
    const register unsigned short int RA1 = 1;
    sbit  RA1_bit at PORTA.B1;
    const register unsigned short int RA2 = 2;
    sbit  RA2_bit at PORTA.B2;
    const register unsigned short int RA3 = 3;
    sbit  RA3_bit at PORTA.B3;
    const register unsigned short int RA4 = 4;
    sbit  RA4_bit at PORTA.B4;
    const register unsigned short int RA5 = 5;
    sbit  RA5_bit at PORTA.B5;

sfr unsigned short volatile PIR1             absolute 0x011;
    const register unsigned short int TMR1IF = 0;
    sbit  TMR1IF_bit at PIR1.B0;
    const register unsigned short int TMR2IF = 1;
    sbit  TMR2IF_bit at PIR1.B1;
    const register unsigned short int ADIF = 6;
    sbit  ADIF_bit at PIR1.B6;
    const register unsigned short int TMR1GIF = 7;
    sbit  TMR1GIF_bit at PIR1.B7;

sfr unsigned short volatile PIR2             absolute 0x012;
    const register unsigned short int C1IF = 5;
    sbit  C1IF_bit at PIR2.B5;

sfr unsigned short volatile PIR3             absolute 0x013;
    const register unsigned short int PWM1IF = 4;
    sbit  PWM1IF_bit at PIR3.B4;
    const register unsigned short int PWM2IF = 5;
    sbit  PWM2IF_bit at PIR3.B5;
    const register unsigned short int PWM3IF = 6;
    sbit  PWM3IF_bit at PIR3.B6;

sfr unsigned short volatile TMR0             absolute 0x015;
sfr unsigned int   volatile TMR1             absolute 0x016;
sfr unsigned short volatile TMR1L            absolute 0x016;
sfr unsigned short volatile TMR1H            absolute 0x017;
sfr unsigned short volatile T1CON            absolute 0x018;
    const register unsigned short int TMR1ON = 0;
    sbit  TMR1ON_bit at T1CON.B0;
    const register unsigned short int nT1SYNC = 2;
    sbit  nT1SYNC_bit at T1CON.B2;
    const register unsigned short int T1CKPS0 = 4;
    sbit  T1CKPS0_bit at T1CON.B4;
    const register unsigned short int T1CKPS1 = 5;
    sbit  T1CKPS1_bit at T1CON.B5;
    const register unsigned short int TMR1CS0 = 6;
    sbit  TMR1CS0_bit at T1CON.B6;
    const register unsigned short int TMR1CS1 = 7;
    sbit  TMR1CS1_bit at T1CON.B7;

sfr unsigned short volatile T1GCON           absolute 0x019;
    const register unsigned short int T1GSS0 = 0;
    sbit  T1GSS0_bit at T1GCON.B0;
    const register unsigned short int T1GSS1 = 1;
    sbit  T1GSS1_bit at T1GCON.B1;
    const register unsigned short int T1GVAL = 2;
    sbit  T1GVAL_bit at T1GCON.B2;
    const register unsigned short int T1GGO = 3;
    sbit  T1GGO_bit at T1GCON.B3;
    const register unsigned short int T1GSPM = 4;
    sbit  T1GSPM_bit at T1GCON.B4;
    const register unsigned short int T1GTM = 5;
    sbit  T1GTM_bit at T1GCON.B5;
    const register unsigned short int T1GPOL = 6;
    sbit  T1GPOL_bit at T1GCON.B6;
    const register unsigned short int TMR1GE = 7;
    sbit  TMR1GE_bit at T1GCON.B7;
    const register unsigned short int T1GGO_nDONE = 3;
    sbit  T1GGO_nDONE_bit at T1GCON.B3;

sfr unsigned short volatile TMR2             absolute 0x01A;
sfr unsigned short volatile PR2              absolute 0x01B;
sfr unsigned short volatile T2CON            absolute 0x01C;
    const register unsigned short int T2CKPS0 = 0;
    sbit  T2CKPS0_bit at T2CON.B0;
    const register unsigned short int T2CKPS1 = 1;
    sbit  T2CKPS1_bit at T2CON.B1;
    const register unsigned short int TMR2ON = 2;
    sbit  TMR2ON_bit at T2CON.B2;
    const register unsigned short int T2OUTPS0 = 3;
    sbit  T2OUTPS0_bit at T2CON.B3;
    const register unsigned short int T2OUTPS1 = 4;
    sbit  T2OUTPS1_bit at T2CON.B4;
    const register unsigned short int T2OUTPS2 = 5;
    sbit  T2OUTPS2_bit at T2CON.B5;
    const register unsigned short int T2OUTPS3 = 6;
    sbit  T2OUTPS3_bit at T2CON.B6;

sfr unsigned short volatile TRISA            absolute 0x08C;
    const register unsigned short int TRISA0 = 0;
    sbit  TRISA0_bit at TRISA.B0;
    const register unsigned short int TRISA1 = 1;
    sbit  TRISA1_bit at TRISA.B1;
    const register unsigned short int TRISA2 = 2;
    sbit  TRISA2_bit at TRISA.B2;
    const register unsigned short int TRISA3 = 3;
    sbit  TRISA3_bit at TRISA.B3;
    const register unsigned short int TRISA4 = 4;
    sbit  TRISA4_bit at TRISA.B4;
    const register unsigned short int TRISA5 = 5;
    sbit  TRISA5_bit at TRISA.B5;

sfr unsigned short volatile PIE1             absolute 0x091;
    const register unsigned short int TMR1IE = 0;
    sbit  TMR1IE_bit at PIE1.B0;
    const register unsigned short int TMR2IE = 1;
    sbit  TMR2IE_bit at PIE1.B1;
    const register unsigned short int ADIE = 6;
    sbit  ADIE_bit at PIE1.B6;
    const register unsigned short int TMR1GIE = 7;
    sbit  TMR1GIE_bit at PIE1.B7;

sfr unsigned short volatile PIE2             absolute 0x092;
    const register unsigned short int C1IE = 5;
    sbit  C1IE_bit at PIE2.B5;

sfr unsigned short volatile PIE3             absolute 0x093;
    const register unsigned short int PWM1IE = 4;
    sbit  PWM1IE_bit at PIE3.B4;
    const register unsigned short int PWM2IE = 5;
    sbit  PWM2IE_bit at PIE3.B5;
    const register unsigned short int PWM3IE = 6;
    sbit  PWM3IE_bit at PIE3.B6;

sfr unsigned short volatile OPTION_REG       absolute 0x095;
    const register unsigned short int PSA = 3;
    sbit  PSA_bit at OPTION_REG.B3;
    const register unsigned short int T0SE = 4;
    sbit  T0SE_bit at OPTION_REG.B4;
    const register unsigned short int T0CS = 5;
    sbit  T0CS_bit at OPTION_REG.B5;
    const register unsigned short int INTEDG = 6;
    sbit  INTEDG_bit at OPTION_REG.B6;
    const register unsigned short int nWPUEN = 7;
    sbit  nWPUEN_bit at OPTION_REG.B7;
    const register unsigned short int TMR0CS = 5;
    sbit  TMR0CS_bit at OPTION_REG.B5;
    const register unsigned short int TMR0SE = 4;
    sbit  TMR0SE_bit at OPTION_REG.B4;

sfr unsigned short volatile PCON             absolute 0x096;
    const register unsigned short int nBOR = 0;
    sbit  nBOR_bit at PCON.B0;
    const register unsigned short int nPOR = 1;
    sbit  nPOR_bit at PCON.B1;
    const register unsigned short int nRI = 2;
    sbit  nRI_bit at PCON.B2;
    const register unsigned short int nRMCLR = 3;
    sbit  nRMCLR_bit at PCON.B3;
    const register unsigned short int nRWDT = 4;
    sbit  nRWDT_bit at PCON.B4;
    const register unsigned short int STKUNF = 6;
    sbit  STKUNF_bit at PCON.B6;
    const register unsigned short int STKOVF = 7;
    sbit  STKOVF_bit at PCON.B7;

sfr unsigned short          WDTCON           absolute 0x097;
    const register unsigned short int SWDTEN = 0;
    sbit  SWDTEN_bit at WDTCON.B0;
    const register unsigned short int WDTPS0 = 1;
    sbit  WDTPS0_bit at WDTCON.B1;
    const register unsigned short int WDTPS1 = 2;
    sbit  WDTPS1_bit at WDTCON.B2;
    const register unsigned short int WDTPS2 = 3;
    sbit  WDTPS2_bit at WDTCON.B3;
    const register unsigned short int WDTPS3 = 4;
    sbit  WDTPS3_bit at WDTCON.B4;
    const register unsigned short int WDTPS4 = 5;
    sbit  WDTPS4_bit at WDTCON.B5;

sfr unsigned short volatile OSCTUNE          absolute 0x098;
    const register unsigned short int TUN0 = 0;
    sbit  TUN0_bit at OSCTUNE.B0;
    const register unsigned short int TUN1 = 1;
    sbit  TUN1_bit at OSCTUNE.B1;
    const register unsigned short int TUN2 = 2;
    sbit  TUN2_bit at OSCTUNE.B2;
    const register unsigned short int TUN3 = 3;
    sbit  TUN3_bit at OSCTUNE.B3;
    const register unsigned short int TUN4 = 4;
    sbit  TUN4_bit at OSCTUNE.B4;
    const register unsigned short int TUN5 = 5;
    sbit  TUN5_bit at OSCTUNE.B5;

sfr unsigned short volatile OSCCON           absolute 0x099;
    const register unsigned short int SCS0 = 0;
    sbit  SCS0_bit at OSCCON.B0;
    const register unsigned short int SCS1 = 1;
    sbit  SCS1_bit at OSCCON.B1;
    const register unsigned short int IRCF0 = 3;
    sbit  IRCF0_bit at OSCCON.B3;
    const register unsigned short int IRCF1 = 4;
    sbit  IRCF1_bit at OSCCON.B4;
    const register unsigned short int IRCF2 = 5;
    sbit  IRCF2_bit at OSCCON.B5;
    const register unsigned short int IRCF3 = 6;
    sbit  IRCF3_bit at OSCCON.B6;
    const register unsigned short int SPLLEN = 7;
    sbit  SPLLEN_bit at OSCCON.B7;

sfr unsigned short volatile OSCSTAT          absolute 0x09A;
    const register unsigned short int HFIOFS = 0;
    sbit  HFIOFS_bit at OSCSTAT.B0;
    const register unsigned short int LFIOFR = 1;
    sbit  LFIOFR_bit at OSCSTAT.B1;
    const register unsigned short int MFIOFR = 2;
    sbit  MFIOFR_bit at OSCSTAT.B2;
    const register unsigned short int HFIOFL = 3;
    sbit  HFIOFL_bit at OSCSTAT.B3;
    const register unsigned short int HFIOFR = 4;
    sbit  HFIOFR_bit at OSCSTAT.B4;
    const register unsigned short int OSTS = 5;
    sbit  OSTS_bit at OSCSTAT.B5;
    const register unsigned short int PLLR = 6;
    sbit  PLLR_bit at OSCSTAT.B6;

sfr unsigned int   volatile ADRES            absolute 0x09B;
sfr unsigned short volatile ADRESL           absolute 0x09B;
sfr unsigned short volatile ADRESH           absolute 0x09C;
sfr unsigned short volatile ADCON0           absolute 0x09D;
    const register unsigned short int ADON = 0;
    sbit  ADON_bit at ADCON0.B0;
    const register unsigned short int ADGO = 1;
    sbit  ADGO_bit at ADCON0.B1;
    const register unsigned short int CHS0 = 2;
    sbit  CHS0_bit at ADCON0.B2;
    const register unsigned short int CHS1 = 3;
    sbit  CHS1_bit at ADCON0.B3;
    const register unsigned short int CHS2 = 4;
    sbit  CHS2_bit at ADCON0.B4;
    const register unsigned short int CHS3 = 5;
    sbit  CHS3_bit at ADCON0.B5;
    const register unsigned short int CHS4 = 6;
    sbit  CHS4_bit at ADCON0.B6;
    const register unsigned short int GO = 1;
    sbit  GO_bit at ADCON0.B1;
    const register unsigned short int GO_nDONE = 1;
    sbit  GO_nDONE_bit at ADCON0.B1;
    const register unsigned short int nDONE = 1;
    sbit  nDONE_bit at ADCON0.B1;
    const register unsigned short int GO_NOT_DONE = 1;
    sbit  GO_NOT_DONE_bit at ADCON0.B1;

sfr unsigned short volatile ADCON1           absolute 0x09E;
    const register unsigned short int ADPREF0 = 0;
    sbit  ADPREF0_bit at ADCON1.B0;
    const register unsigned short int ADPREF1 = 1;
    sbit  ADPREF1_bit at ADCON1.B1;
    const register unsigned short int ADCS0 = 4;
    sbit  ADCS0_bit at ADCON1.B4;
    const register unsigned short int ADCS1 = 5;
    sbit  ADCS1_bit at ADCON1.B5;
    const register unsigned short int ADCS2 = 6;
    sbit  ADCS2_bit at ADCON1.B6;
    const register unsigned short int ADFM = 7;
    sbit  ADFM_bit at ADCON1.B7;

sfr unsigned short volatile ADCON2           absolute 0x09F;
    const register unsigned short int TRIGSEL0 = 4;
    sbit  TRIGSEL0_bit at ADCON2.B4;
    const register unsigned short int TRIGSEL1 = 5;
    sbit  TRIGSEL1_bit at ADCON2.B5;
    const register unsigned short int TRIGSEL2 = 6;
    sbit  TRIGSEL2_bit at ADCON2.B6;
    const register unsigned short int TRIGSEL3 = 7;
    sbit  TRIGSEL3_bit at ADCON2.B7;

sfr unsigned short volatile LATA             absolute 0x10C;
    const register unsigned short int LATA0 = 0;
    sbit  LATA0_bit at LATA.B0;
    const register unsigned short int LATA1 = 1;
    sbit  LATA1_bit at LATA.B1;
    const register unsigned short int LATA2 = 2;
    sbit  LATA2_bit at LATA.B2;
    const register unsigned short int LATA4 = 4;
    sbit  LATA4_bit at LATA.B4;
    const register unsigned short int LATA5 = 5;
    sbit  LATA5_bit at LATA.B5;

sfr unsigned short volatile CM1CON0          absolute 0x111;
    const register unsigned short int C1SYNC = 0;
    sbit  C1SYNC_bit at CM1CON0.B0;
    const register unsigned short int C1HYS = 1;
    sbit  C1HYS_bit at CM1CON0.B1;
    const register unsigned short int C1SP = 2;
    sbit  C1SP_bit at CM1CON0.B2;
    const register unsigned short int C1POL = 4;
    sbit  C1POL_bit at CM1CON0.B4;
    const register unsigned short int C1OE = 5;
    sbit  C1OE_bit at CM1CON0.B5;
    const register unsigned short int C1OUT = 6;
    sbit  C1OUT_bit at CM1CON0.B6;
    const register unsigned short int C1ON = 7;
    sbit  C1ON_bit at CM1CON0.B7;

sfr unsigned short volatile CM1CON1          absolute 0x112;
    const register unsigned short int C1NCH0 = 0;
    sbit  C1NCH0_bit at CM1CON1.B0;
    const register unsigned short int C1NCH1 = 1;
    sbit  C1NCH1_bit at CM1CON1.B1;
    const register unsigned short int C1NCH2 = 2;
    sbit  C1NCH2_bit at CM1CON1.B2;
    const register unsigned short int C1PCH0 = 4;
    sbit  C1PCH0_bit at CM1CON1.B4;
    const register unsigned short int C1PCH1 = 5;
    sbit  C1PCH1_bit at CM1CON1.B5;
    const register unsigned short int C1INTN = 6;
    sbit  C1INTN_bit at CM1CON1.B6;
    const register unsigned short int C1INTP = 7;
    sbit  C1INTP_bit at CM1CON1.B7;

sfr unsigned short volatile CMOUT            absolute 0x115;
    const register unsigned short int MC1OUT = 0;
    sbit  MC1OUT_bit at CMOUT.B0;

sfr unsigned short volatile BORCON           absolute 0x116;
    const register unsigned short int BORRDY = 0;
    sbit  BORRDY_bit at BORCON.B0;
    const register unsigned short int BORFS = 6;
    sbit  BORFS_bit at BORCON.B6;
    const register unsigned short int SBOREN = 7;
    sbit  SBOREN_bit at BORCON.B7;

sfr unsigned short volatile FVRCON           absolute 0x117;
    const register unsigned short int ADFVR0 = 0;
    sbit  ADFVR0_bit at FVRCON.B0;
    const register unsigned short int ADFVR1 = 1;
    sbit  ADFVR1_bit at FVRCON.B1;
    const register unsigned short int CDAFVR0 = 2;
    sbit  CDAFVR0_bit at FVRCON.B2;
    const register unsigned short int CDAFVR1 = 3;
    sbit  CDAFVR1_bit at FVRCON.B3;
    const register unsigned short int TSRNG = 4;
    sbit  TSRNG_bit at FVRCON.B4;
    const register unsigned short int TSEN = 5;
    sbit  TSEN_bit at FVRCON.B5;
    const register unsigned short int FVRRDY = 6;
    sbit  FVRRDY_bit at FVRCON.B6;
    const register unsigned short int FVREN = 7;
    sbit  FVREN_bit at FVRCON.B7;

sfr unsigned short volatile DACCON0          absolute 0x118;
    const register unsigned short int DACPSS0 = 2;
    sbit  DACPSS0_bit at DACCON0.B2;
    const register unsigned short int DACPSS1 = 3;
    sbit  DACPSS1_bit at DACCON0.B3;
    const register unsigned short int DACOE = 5;
    sbit  DACOE_bit at DACCON0.B5;
    const register unsigned short int DACLPS = 6;
    sbit  DACLPS_bit at DACCON0.B6;
    const register unsigned short int DACEN = 7;
    sbit  DACEN_bit at DACCON0.B7;

sfr unsigned short volatile DACCON1          absolute 0x119;
    const register unsigned short int DACR0 = 0;
    sbit  DACR0_bit at DACCON1.B0;
    const register unsigned short int DACR1 = 1;
    sbit  DACR1_bit at DACCON1.B1;
    const register unsigned short int DACR2 = 2;
    sbit  DACR2_bit at DACCON1.B2;
    const register unsigned short int DACR3 = 3;
    sbit  DACR3_bit at DACCON1.B3;
    const register unsigned short int DACR4 = 4;
    sbit  DACR4_bit at DACCON1.B4;

sfr unsigned short          APFCON           absolute 0x11D;
    const register unsigned short int P1SEL = 0;
    sbit  P1SEL_bit at APFCON.B0;
    const register unsigned short int P2SEL = 1;
    sbit  P2SEL_bit at APFCON.B1;
    const register unsigned short int T1GSEL = 3;
    sbit  T1GSEL_bit at APFCON.B3;
    const register unsigned short int CWGBSEL = 5;
    sbit  CWGBSEL_bit at APFCON.B5;
    const register unsigned short int CWGASEL = 6;
    sbit  CWGASEL_bit at APFCON.B6;

sfr unsigned short volatile APFCON0          absolute 0x11D;
sfr unsigned short volatile ANSELA           absolute 0x18C;
    const register unsigned short int ANSA0 = 0;
    sbit  ANSA0_bit at ANSELA.B0;
    const register unsigned short int ANSA1 = 1;
    sbit  ANSA1_bit at ANSELA.B1;
    const register unsigned short int ANSA2 = 2;
    sbit  ANSA2_bit at ANSELA.B2;
    const register unsigned short int ANSA4 = 4;
    sbit  ANSA4_bit at ANSELA.B4;

sfr unsigned int   volatile PMADR            absolute 0x191;
sfr unsigned short volatile PMADRL           absolute 0x191;
sfr unsigned short volatile PMADRH           absolute 0x192;
sfr unsigned int   volatile PMDAT            absolute 0x193;
sfr unsigned short volatile PMDATL           absolute 0x193;
sfr unsigned short volatile PMDATH           absolute 0x194;
sfr unsigned short volatile PMCON1           absolute 0x195;
    const register unsigned short int RD = 0;
    sbit  RD_bit at PMCON1.B0;
    const register unsigned short int WR = 1;
    sbit  WR_bit at PMCON1.B1;
    const register unsigned short int WREN = 2;
    sbit  WREN_bit at PMCON1.B2;
    const register unsigned short int WRERR = 3;
    sbit  WRERR_bit at PMCON1.B3;
    const register unsigned short int FREE = 4;
    sbit  FREE_bit at PMCON1.B4;
    const register unsigned short int LWLO = 5;
    sbit  LWLO_bit at PMCON1.B5;
    const register unsigned short int CFGS = 6;
    sbit  CFGS_bit at PMCON1.B6;

sfr unsigned short volatile PMCON2           absolute 0x196;
sfr unsigned short          WPUA             absolute 0x20C;
    const register unsigned short int WPUA0 = 0;
    sbit  WPUA0_bit at WPUA.B0;
    const register unsigned short int WPUA1 = 1;
    sbit  WPUA1_bit at WPUA.B1;
    const register unsigned short int WPUA2 = 2;
    sbit  WPUA2_bit at WPUA.B2;
    const register unsigned short int WPUA3 = 3;
    sbit  WPUA3_bit at WPUA.B3;
    const register unsigned short int WPUA4 = 4;
    sbit  WPUA4_bit at WPUA.B4;
    const register unsigned short int WPUA5 = 5;
    sbit  WPUA5_bit at WPUA.B5;

sfr unsigned short volatile ODCONA           absolute 0x28C;
    const register unsigned short int ODA0 = 0;
    sbit  ODA0_bit at ODCONA.B0;
    const register unsigned short int ODA1 = 1;
    sbit  ODA1_bit at ODCONA.B1;
    const register unsigned short int ODA2 = 2;
    sbit  ODA2_bit at ODCONA.B2;
    const register unsigned short int ODA4 = 4;
    sbit  ODA4_bit at ODCONA.B4;
    const register unsigned short int ODA5 = 5;
    sbit  ODA5_bit at ODCONA.B5;

sfr unsigned short volatile SLRCONA          absolute 0x30C;
    const register unsigned short int SLRA0 = 0;
    sbit  SLRA0_bit at SLRCONA.B0;
    const register unsigned short int SLRA1 = 1;
    sbit  SLRA1_bit at SLRCONA.B1;
    const register unsigned short int SLRA2 = 2;
    sbit  SLRA2_bit at SLRCONA.B2;
    const register unsigned short int SLRA4 = 4;
    sbit  SLRA4_bit at SLRCONA.B4;
    const register unsigned short int SLRA5 = 5;
    sbit  SLRA5_bit at SLRCONA.B5;

sfr unsigned short volatile INLVLA           absolute 0x38C;
    const register unsigned short int INLVLA0 = 0;
    sbit  INLVLA0_bit at INLVLA.B0;
    const register unsigned short int INLVLA1 = 1;
    sbit  INLVLA1_bit at INLVLA.B1;
    const register unsigned short int INLVLA2 = 2;
    sbit  INLVLA2_bit at INLVLA.B2;
    const register unsigned short int INLVLA3 = 3;
    sbit  INLVLA3_bit at INLVLA.B3;
    const register unsigned short int INLVLA4 = 4;
    sbit  INLVLA4_bit at INLVLA.B4;
    const register unsigned short int INLVLA5 = 5;
    sbit  INLVLA5_bit at INLVLA.B5;

sfr unsigned short volatile IOCAP            absolute 0x391;
    const register unsigned short int IOCAP0 = 0;
    sbit  IOCAP0_bit at IOCAP.B0;
    const register unsigned short int IOCAP1 = 1;
    sbit  IOCAP1_bit at IOCAP.B1;
    const register unsigned short int IOCAP2 = 2;
    sbit  IOCAP2_bit at IOCAP.B2;
    const register unsigned short int IOCAP3 = 3;
    sbit  IOCAP3_bit at IOCAP.B3;
    const register unsigned short int IOCAP4 = 4;
    sbit  IOCAP4_bit at IOCAP.B4;
    const register unsigned short int IOCAP5 = 5;
    sbit  IOCAP5_bit at IOCAP.B5;

sfr unsigned short volatile IOCAN            absolute 0x392;
    const register unsigned short int IOCAN0 = 0;
    sbit  IOCAN0_bit at IOCAN.B0;
    const register unsigned short int IOCAN1 = 1;
    sbit  IOCAN1_bit at IOCAN.B1;
    const register unsigned short int IOCAN2 = 2;
    sbit  IOCAN2_bit at IOCAN.B2;
    const register unsigned short int IOCAN3 = 3;
    sbit  IOCAN3_bit at IOCAN.B3;
    const register unsigned short int IOCAN4 = 4;
    sbit  IOCAN4_bit at IOCAN.B4;
    const register unsigned short int IOCAN5 = 5;
    sbit  IOCAN5_bit at IOCAN.B5;

sfr unsigned short volatile IOCAF            absolute 0x393;
    const register unsigned short int IOCAF0 = 0;
    sbit  IOCAF0_bit at IOCAF.B0;
    const register unsigned short int IOCAF1 = 1;
    sbit  IOCAF1_bit at IOCAF.B1;
    const register unsigned short int IOCAF2 = 2;
    sbit  IOCAF2_bit at IOCAF.B2;
    const register unsigned short int IOCAF3 = 3;
    sbit  IOCAF3_bit at IOCAF.B3;
    const register unsigned short int IOCAF4 = 4;
    sbit  IOCAF4_bit at IOCAF.B4;
    const register unsigned short int IOCAF5 = 5;
    sbit  IOCAF5_bit at IOCAF.B5;

sfr unsigned short volatile CWG1DBR          absolute 0x691;
    const register unsigned short int CWG1DBR0 = 0;
    sbit  CWG1DBR0_bit at CWG1DBR.B0;
    const register unsigned short int CWG1DBR1 = 1;
    sbit  CWG1DBR1_bit at CWG1DBR.B1;
    const register unsigned short int CWG1DBR2 = 2;
    sbit  CWG1DBR2_bit at CWG1DBR.B2;
    const register unsigned short int CWG1DBR3 = 3;
    sbit  CWG1DBR3_bit at CWG1DBR.B3;
    const register unsigned short int CWG1DBR4 = 4;
    sbit  CWG1DBR4_bit at CWG1DBR.B4;
    const register unsigned short int CWG1DBR5 = 5;
    sbit  CWG1DBR5_bit at CWG1DBR.B5;

sfr unsigned short volatile CWG1DBF          absolute 0x692;
    const register unsigned short int CWG1DBF0 = 0;
    sbit  CWG1DBF0_bit at CWG1DBF.B0;
    const register unsigned short int CWG1DBF1 = 1;
    sbit  CWG1DBF1_bit at CWG1DBF.B1;
    const register unsigned short int CWG1DBF2 = 2;
    sbit  CWG1DBF2_bit at CWG1DBF.B2;
    const register unsigned short int CWG1DBF3 = 3;
    sbit  CWG1DBF3_bit at CWG1DBF.B3;
    const register unsigned short int CWG1DBF4 = 4;
    sbit  CWG1DBF4_bit at CWG1DBF.B4;
    const register unsigned short int CWG1DBF5 = 5;
    sbit  CWG1DBF5_bit at CWG1DBF.B5;

sfr unsigned short volatile CWG1CON0         absolute 0x693;
    const register unsigned short int G1CS0 = 0;
    sbit  G1CS0_bit at CWG1CON0.B0;
    const register unsigned short int G1POLA = 3;
    sbit  G1POLA_bit at CWG1CON0.B3;
    const register unsigned short int G1POLB = 4;
    sbit  G1POLB_bit at CWG1CON0.B4;
    const register unsigned short int G1OEA = 5;
    sbit  G1OEA_bit at CWG1CON0.B5;
    const register unsigned short int G1OEB = 6;
    sbit  G1OEB_bit at CWG1CON0.B6;
    const register unsigned short int G1EN = 7;
    sbit  G1EN_bit at CWG1CON0.B7;

sfr unsigned short volatile CWG1CON1         absolute 0x694;
    const register unsigned short int G1IS0 = 0;
    sbit  G1IS0_bit at CWG1CON1.B0;
    const register unsigned short int G1IS1 = 1;
    sbit  G1IS1_bit at CWG1CON1.B1;
    const register unsigned short int G1IS2 = 2;
    sbit  G1IS2_bit at CWG1CON1.B2;
    const register unsigned short int G1ASDLA0 = 4;
    sbit  G1ASDLA0_bit at CWG1CON1.B4;
    const register unsigned short int G1ASDLA1 = 5;
    sbit  G1ASDLA1_bit at CWG1CON1.B5;
    const register unsigned short int G1ASDLB0 = 6;
    sbit  G1ASDLB0_bit at CWG1CON1.B6;
    const register unsigned short int G1ASDLB1 = 7;
    sbit  G1ASDLB1_bit at CWG1CON1.B7;

sfr unsigned short volatile CWG1CON2         absolute 0x695;
    const register unsigned short int G1ASDSFLT = 1;
    sbit  G1ASDSFLT_bit at CWG1CON2.B1;
    const register unsigned short int G1ASDSC1 = 2;
    sbit  G1ASDSC1_bit at CWG1CON2.B2;
    const register unsigned short int G1ARSEN = 6;
    sbit  G1ARSEN_bit at CWG1CON2.B6;
    const register unsigned short int G1ASE = 7;
    sbit  G1ASE_bit at CWG1CON2.B7;

sfr unsigned short volatile PWMEN            absolute 0xD8E;
    const register unsigned short int MPWM1EN = 0;
    sbit  MPWM1EN_bit at PWMEN.B0;
    const register unsigned short int MPWM2EN = 1;
    sbit  MPWM2EN_bit at PWMEN.B1;
    const register unsigned short int MPWM3EN = 2;
    sbit  MPWM3EN_bit at PWMEN.B2;
    const register unsigned short int PWM1EN_A = 0;
    sbit  PWM1EN_A_bit at PWMEN.B0;
    const register unsigned short int PWM2EN_A = 1;
    sbit  PWM2EN_A_bit at PWMEN.B1;
    const register unsigned short int PWM3EN_A = 2;
    sbit  PWM3EN_A_bit at PWMEN.B2;

sfr unsigned short volatile PWMLD            absolute 0xD8F;
    const register unsigned short int MPWM1LD = 0;
    sbit  MPWM1LD_bit at PWMLD.B0;
    const register unsigned short int MPWM2LD = 1;
    sbit  MPWM2LD_bit at PWMLD.B1;
    const register unsigned short int MPWM3LD = 2;
    sbit  MPWM3LD_bit at PWMLD.B2;
    const register unsigned short int PWM1LDA_A = 0;
    sbit  PWM1LDA_A_bit at PWMLD.B0;
    const register unsigned short int PWM2LDA_A = 1;
    sbit  PWM2LDA_A_bit at PWMLD.B1;
    const register unsigned short int PWM3LDA_A = 2;
    sbit  PWM3LDA_A_bit at PWMLD.B2;

sfr unsigned short volatile PWMOUT           absolute 0xD90;
    const register unsigned short int MPWM1OUT = 0;
    sbit  MPWM1OUT_bit at PWMOUT.B0;
    const register unsigned short int MPWM2OUT = 1;
    sbit  MPWM2OUT_bit at PWMOUT.B1;
    const register unsigned short int MPWM3OUT = 2;
    sbit  MPWM3OUT_bit at PWMOUT.B2;
    const register unsigned short int PWM1OUT_A = 0;
    sbit  PWM1OUT_A_bit at PWMOUT.B0;
    const register unsigned short int PWM2OUT_A = 1;
    sbit  PWM2OUT_A_bit at PWMOUT.B1;
    const register unsigned short int PWM3OUT_A = 2;
    sbit  PWM3OUT_A_bit at PWMOUT.B2;

sfr unsigned int   volatile PWM1PH           absolute 0xD91;
sfr unsigned short volatile PWM1PHL          absolute 0xD91;
    const register unsigned short int PWM1PHL0 = 0;
    sbit  PWM1PHL0_bit at PWM1PHL.B0;
    const register unsigned short int PWM1PHL1 = 1;
    sbit  PWM1PHL1_bit at PWM1PHL.B1;
    const register unsigned short int PWM1PHL2 = 2;
    sbit  PWM1PHL2_bit at PWM1PHL.B2;
    const register unsigned short int PWM1PHL3 = 3;
    sbit  PWM1PHL3_bit at PWM1PHL.B3;
    const register unsigned short int PWM1PHL4 = 4;
    sbit  PWM1PHL4_bit at PWM1PHL.B4;
    const register unsigned short int PWM1PHL5 = 5;
    sbit  PWM1PHL5_bit at PWM1PHL.B5;
    const register unsigned short int PWM1PHL6 = 6;
    sbit  PWM1PHL6_bit at PWM1PHL.B6;
    const register unsigned short int PWM1PHL7 = 7;
    sbit  PWM1PHL7_bit at PWM1PHL.B7;

sfr unsigned short volatile PWM1PHH          absolute 0xD92;
    const register unsigned short int PWM1PHH0 = 0;
    sbit  PWM1PHH0_bit at PWM1PHH.B0;
    const register unsigned short int PWM1PHH1 = 1;
    sbit  PWM1PHH1_bit at PWM1PHH.B1;
    const register unsigned short int PWM1PHH2 = 2;
    sbit  PWM1PHH2_bit at PWM1PHH.B2;
    const register unsigned short int PWM1PHH3 = 3;
    sbit  PWM1PHH3_bit at PWM1PHH.B3;
    const register unsigned short int PWM1PHH4 = 4;
    sbit  PWM1PHH4_bit at PWM1PHH.B4;
    const register unsigned short int PWM1PHH5 = 5;
    sbit  PWM1PHH5_bit at PWM1PHH.B5;
    const register unsigned short int PWM1PHH6 = 6;
    sbit  PWM1PHH6_bit at PWM1PHH.B6;
    const register unsigned short int PWM1PHH7 = 7;
    sbit  PWM1PHH7_bit at PWM1PHH.B7;

sfr unsigned int   volatile PWM1DC           absolute 0xD93;
sfr unsigned short volatile PWM1DCL          absolute 0xD93;
    const register unsigned short int PWM1DCL0 = 0;
    sbit  PWM1DCL0_bit at PWM1DCL.B0;
    const register unsigned short int PWM1DCL1 = 1;
    sbit  PWM1DCL1_bit at PWM1DCL.B1;
    const register unsigned short int PWM1DCL2 = 2;
    sbit  PWM1DCL2_bit at PWM1DCL.B2;
    const register unsigned short int PWM1DCL3 = 3;
    sbit  PWM1DCL3_bit at PWM1DCL.B3;
    const register unsigned short int PWM1DCL4 = 4;
    sbit  PWM1DCL4_bit at PWM1DCL.B4;
    const register unsigned short int PWM1DCL5 = 5;
    sbit  PWM1DCL5_bit at PWM1DCL.B5;
    const register unsigned short int PWM1DCL6 = 6;
    sbit  PWM1DCL6_bit at PWM1DCL.B6;
    const register unsigned short int PWM1DCL7 = 7;
    sbit  PWM1DCL7_bit at PWM1DCL.B7;

sfr unsigned short volatile PWM1DCH          absolute 0xD94;
    const register unsigned short int PWM1DCH0 = 0;
    sbit  PWM1DCH0_bit at PWM1DCH.B0;
    const register unsigned short int PWM1DCH1 = 1;
    sbit  PWM1DCH1_bit at PWM1DCH.B1;
    const register unsigned short int PWM1DCH2 = 2;
    sbit  PWM1DCH2_bit at PWM1DCH.B2;
    const register unsigned short int PWM1DCH3 = 3;
    sbit  PWM1DCH3_bit at PWM1DCH.B3;
    const register unsigned short int PWM1DCH4 = 4;
    sbit  PWM1DCH4_bit at PWM1DCH.B4;
    const register unsigned short int PWM1DCH5 = 5;
    sbit  PWM1DCH5_bit at PWM1DCH.B5;
    const register unsigned short int PWM1DCH6 = 6;
    sbit  PWM1DCH6_bit at PWM1DCH.B6;
    const register unsigned short int PWM1DCH7 = 7;
    sbit  PWM1DCH7_bit at PWM1DCH.B7;

sfr unsigned int   volatile PWM1PR           absolute 0xD95;
sfr unsigned short volatile PWM1PRL          absolute 0xD95;
    const register unsigned short int PWM1PRL0 = 0;
    sbit  PWM1PRL0_bit at PWM1PRL.B0;
    const register unsigned short int PWM1PRL1 = 1;
    sbit  PWM1PRL1_bit at PWM1PRL.B1;
    const register unsigned short int PWM1PRL2 = 2;
    sbit  PWM1PRL2_bit at PWM1PRL.B2;
    const register unsigned short int PWM1PRL3 = 3;
    sbit  PWM1PRL3_bit at PWM1PRL.B3;
    const register unsigned short int PWM1PRL4 = 4;
    sbit  PWM1PRL4_bit at PWM1PRL.B4;
    const register unsigned short int PWM1PRL5 = 5;
    sbit  PWM1PRL5_bit at PWM1PRL.B5;
    const register unsigned short int PWM1PRL6 = 6;
    sbit  PWM1PRL6_bit at PWM1PRL.B6;
    const register unsigned short int PWM1PRL7 = 7;
    sbit  PWM1PRL7_bit at PWM1PRL.B7;

sfr unsigned short volatile PWM1PRH          absolute 0xD96;
    const register unsigned short int PWM1PRH0 = 0;
    sbit  PWM1PRH0_bit at PWM1PRH.B0;
    const register unsigned short int PWM1PRH1 = 1;
    sbit  PWM1PRH1_bit at PWM1PRH.B1;
    const register unsigned short int PWM1PRH2 = 2;
    sbit  PWM1PRH2_bit at PWM1PRH.B2;
    const register unsigned short int PWM1PRH3 = 3;
    sbit  PWM1PRH3_bit at PWM1PRH.B3;
    const register unsigned short int PWM1PRH4 = 4;
    sbit  PWM1PRH4_bit at PWM1PRH.B4;
    const register unsigned short int PWM1PRH5 = 5;
    sbit  PWM1PRH5_bit at PWM1PRH.B5;
    const register unsigned short int PWM1PRH6 = 6;
    sbit  PWM1PRH6_bit at PWM1PRH.B6;
    const register unsigned short int PWM1PRH7 = 7;
    sbit  PWM1PRH7_bit at PWM1PRH.B7;

sfr unsigned int   volatile PWM1OF           absolute 0xD97;
sfr unsigned short volatile PWM1OFL          absolute 0xD97;
    const register unsigned short int PWM1OFL0 = 0;
    sbit  PWM1OFL0_bit at PWM1OFL.B0;
    const register unsigned short int PWM1OFL1 = 1;
    sbit  PWM1OFL1_bit at PWM1OFL.B1;
    const register unsigned short int PWM1OFL2 = 2;
    sbit  PWM1OFL2_bit at PWM1OFL.B2;
    const register unsigned short int PWM1OFL3 = 3;
    sbit  PWM1OFL3_bit at PWM1OFL.B3;
    const register unsigned short int PWM1OFL4 = 4;
    sbit  PWM1OFL4_bit at PWM1OFL.B4;
    const register unsigned short int PWM1OFL5 = 5;
    sbit  PWM1OFL5_bit at PWM1OFL.B5;
    const register unsigned short int PWM1OFL6 = 6;
    sbit  PWM1OFL6_bit at PWM1OFL.B6;
    const register unsigned short int PWM1OFL7 = 7;
    sbit  PWM1OFL7_bit at PWM1OFL.B7;

sfr unsigned short volatile PWM1OFH          absolute 0xD98;
    const register unsigned short int PWM1OFH0 = 0;
    sbit  PWM1OFH0_bit at PWM1OFH.B0;
    const register unsigned short int PWM1OFH1 = 1;
    sbit  PWM1OFH1_bit at PWM1OFH.B1;
    const register unsigned short int PWM1OFH2 = 2;
    sbit  PWM1OFH2_bit at PWM1OFH.B2;
    const register unsigned short int PWM1OFH3 = 3;
    sbit  PWM1OFH3_bit at PWM1OFH.B3;
    const register unsigned short int PWM1OFH4 = 4;
    sbit  PWM1OFH4_bit at PWM1OFH.B4;
    const register unsigned short int PWM1OFH5 = 5;
    sbit  PWM1OFH5_bit at PWM1OFH.B5;
    const register unsigned short int PWM1OFH6 = 6;
    sbit  PWM1OFH6_bit at PWM1OFH.B6;
    const register unsigned short int PWM1OFH7 = 7;
    sbit  PWM1OFH7_bit at PWM1OFH.B7;

sfr unsigned int   volatile PWM1TMR          absolute 0xD99;
sfr unsigned short volatile PWM1TMRL         absolute 0xD99;
    const register unsigned short int PWM1TMRL0 = 0;
    sbit  PWM1TMRL0_bit at PWM1TMRL.B0;
    const register unsigned short int PWM1TMRL1 = 1;
    sbit  PWM1TMRL1_bit at PWM1TMRL.B1;
    const register unsigned short int PWM1TMRL2 = 2;
    sbit  PWM1TMRL2_bit at PWM1TMRL.B2;
    const register unsigned short int PWM1TMRL3 = 3;
    sbit  PWM1TMRL3_bit at PWM1TMRL.B3;
    const register unsigned short int PWM1TMRL4 = 4;
    sbit  PWM1TMRL4_bit at PWM1TMRL.B4;
    const register unsigned short int PWM1TMRL5 = 5;
    sbit  PWM1TMRL5_bit at PWM1TMRL.B5;
    const register unsigned short int PWM1TMRL6 = 6;
    sbit  PWM1TMRL6_bit at PWM1TMRL.B6;
    const register unsigned short int PWM1TMRL7 = 7;
    sbit  PWM1TMRL7_bit at PWM1TMRL.B7;

sfr unsigned short volatile PWM1TMRH         absolute 0xD9A;
    const register unsigned short int PWM1TMRH0 = 0;
    sbit  PWM1TMRH0_bit at PWM1TMRH.B0;
    const register unsigned short int PWM1TMRH1 = 1;
    sbit  PWM1TMRH1_bit at PWM1TMRH.B1;
    const register unsigned short int PWM1TMRH2 = 2;
    sbit  PWM1TMRH2_bit at PWM1TMRH.B2;
    const register unsigned short int PWM1TMRH3 = 3;
    sbit  PWM1TMRH3_bit at PWM1TMRH.B3;
    const register unsigned short int PWM1TMRH4 = 4;
    sbit  PWM1TMRH4_bit at PWM1TMRH.B4;
    const register unsigned short int PWM1TMRH5 = 5;
    sbit  PWM1TMRH5_bit at PWM1TMRH.B5;
    const register unsigned short int PWM1TMRH6 = 6;
    sbit  PWM1TMRH6_bit at PWM1TMRH.B6;
    const register unsigned short int PWM1TMRH7 = 7;
    sbit  PWM1TMRH7_bit at PWM1TMRH.B7;

sfr unsigned short          PWM1CON          absolute 0xD9B;
    const register unsigned short int PWM1MODE0 = 2;
    sbit  PWM1MODE0_bit at PWM1CON.B2;
    const register unsigned short int PWM1MODE1 = 3;
    sbit  PWM1MODE1_bit at PWM1CON.B3;
    const register unsigned short int PWM1POL = 4;
    sbit  PWM1POL_bit at PWM1CON.B4;
    const register unsigned short int PWM1OUT = 5;
    sbit  PWM1OUT_bit at PWM1CON.B5;
    const register unsigned short int PWM1OE = 6;
    sbit  PWM1OE_bit at PWM1CON.B6;
    const register unsigned short int PWM1EN = 7;
    sbit  PWM1EN_bit at PWM1CON.B7;

sfr unsigned short volatile PWM1INTE         absolute 0xD9C;
    const register unsigned short int PWM1PRIE = 0;
    sbit  PWM1PRIE_bit at PWM1INTE.B0;
    const register unsigned short int PWM1DCIE = 1;
    sbit  PWM1DCIE_bit at PWM1INTE.B1;
    const register unsigned short int PWM1PHIE = 2;
    sbit  PWM1PHIE_bit at PWM1INTE.B2;
    const register unsigned short int PWM1OFIE = 3;
    sbit  PWM1OFIE_bit at PWM1INTE.B3;

sfr unsigned short volatile PWM1INTCON       absolute 0xD9C;
sfr unsigned short volatile PWM1INTF         absolute 0xD9D;
    const register unsigned short int PWM1PRIF = 0;
    sbit  PWM1PRIF_bit at PWM1INTF.B0;
    const register unsigned short int PWM1DCIF = 1;
    sbit  PWM1DCIF_bit at PWM1INTF.B1;
    const register unsigned short int PWM1PHIF = 2;
    sbit  PWM1PHIF_bit at PWM1INTF.B2;
    const register unsigned short int PWM1OFIF = 3;
    sbit  PWM1OFIF_bit at PWM1INTF.B3;

sfr unsigned short volatile PWM1INTFLG       absolute 0xD9D;
sfr unsigned short volatile PWM1CLKCON       absolute 0xD9E;
    const register unsigned short int PWM1CS0 = 0;
    sbit  PWM1CS0_bit at PWM1CLKCON.B0;
    const register unsigned short int PWM1CS1 = 1;
    sbit  PWM1CS1_bit at PWM1CLKCON.B1;
    const register unsigned short int PWM1PS0 = 4;
    sbit  PWM1PS0_bit at PWM1CLKCON.B4;
    const register unsigned short int PWM1PS1 = 5;
    sbit  PWM1PS1_bit at PWM1CLKCON.B5;
    const register unsigned short int PWM1PS2 = 6;
    sbit  PWM1PS2_bit at PWM1CLKCON.B6;

sfr unsigned short volatile PWM1LDCON        absolute 0xD9F;
    const register unsigned short int PWM1LDS0 = 0;
    sbit  PWM1LDS0_bit at PWM1LDCON.B0;
    const register unsigned short int PWM1LDS1 = 1;
    sbit  PWM1LDS1_bit at PWM1LDCON.B1;
    const register unsigned short int PWM1LDM = 6;
    sbit  PWM1LDM_bit at PWM1LDCON.B6;
    const register unsigned short int PWM1LD = 7;
    sbit  PWM1LD_bit at PWM1LDCON.B7;

sfr unsigned short volatile PWM1OFCON        absolute 0xDA0;
    const register unsigned short int PWM1OFS0 = 0;
    sbit  PWM1OFS0_bit at PWM1OFCON.B0;
    const register unsigned short int PWM1OFS1 = 1;
    sbit  PWM1OFS1_bit at PWM1OFCON.B1;
    const register unsigned short int PWM1OFMC = 4;
    sbit  PWM1OFMC_bit at PWM1OFCON.B4;
    const register unsigned short int PWM1OFM0 = 5;
    sbit  PWM1OFM0_bit at PWM1OFCON.B5;
    const register unsigned short int PWM1OFM1 = 6;
    sbit  PWM1OFM1_bit at PWM1OFCON.B6;

sfr unsigned int   volatile PWM2PH           absolute 0xDA1;
sfr unsigned short volatile PWM2PHL          absolute 0xDA1;
    const register unsigned short int PWM2PHL0 = 0;
    sbit  PWM2PHL0_bit at PWM2PHL.B0;
    const register unsigned short int PWM2PHL1 = 1;
    sbit  PWM2PHL1_bit at PWM2PHL.B1;
    const register unsigned short int PWM2PHL2 = 2;
    sbit  PWM2PHL2_bit at PWM2PHL.B2;
    const register unsigned short int PWM2PHL3 = 3;
    sbit  PWM2PHL3_bit at PWM2PHL.B3;
    const register unsigned short int PWM2PHL4 = 4;
    sbit  PWM2PHL4_bit at PWM2PHL.B4;
    const register unsigned short int PWM2PHL5 = 5;
    sbit  PWM2PHL5_bit at PWM2PHL.B5;
    const register unsigned short int PWM2PHL6 = 6;
    sbit  PWM2PHL6_bit at PWM2PHL.B6;
    const register unsigned short int PWM2PHL7 = 7;
    sbit  PWM2PHL7_bit at PWM2PHL.B7;

sfr unsigned short volatile PWM2PHH          absolute 0xDA2;
    const register unsigned short int PWM2PHH0 = 0;
    sbit  PWM2PHH0_bit at PWM2PHH.B0;
    const register unsigned short int PWM2PHH1 = 1;
    sbit  PWM2PHH1_bit at PWM2PHH.B1;
    const register unsigned short int PWM2PHH2 = 2;
    sbit  PWM2PHH2_bit at PWM2PHH.B2;
    const register unsigned short int PWM2PHH3 = 3;
    sbit  PWM2PHH3_bit at PWM2PHH.B3;
    const register unsigned short int PWM2PHH4 = 4;
    sbit  PWM2PHH4_bit at PWM2PHH.B4;
    const register unsigned short int PWM2PHH5 = 5;
    sbit  PWM2PHH5_bit at PWM2PHH.B5;
    const register unsigned short int PWM2PHH6 = 6;
    sbit  PWM2PHH6_bit at PWM2PHH.B6;
    const register unsigned short int PWM2PHH7 = 7;
    sbit  PWM2PHH7_bit at PWM2PHH.B7;

sfr unsigned int   volatile PWM2DC           absolute 0xDA3;
sfr unsigned short volatile PWM2DCL          absolute 0xDA3;
    const register unsigned short int PWM2DCL0 = 0;
    sbit  PWM2DCL0_bit at PWM2DCL.B0;
    const register unsigned short int PWM2DCL1 = 1;
    sbit  PWM2DCL1_bit at PWM2DCL.B1;
    const register unsigned short int PWM2DCL2 = 2;
    sbit  PWM2DCL2_bit at PWM2DCL.B2;
    const register unsigned short int PWM2DCL3 = 3;
    sbit  PWM2DCL3_bit at PWM2DCL.B3;
    const register unsigned short int PWM2DCL4 = 4;
    sbit  PWM2DCL4_bit at PWM2DCL.B4;
    const register unsigned short int PWM2DCL5 = 5;
    sbit  PWM2DCL5_bit at PWM2DCL.B5;
    const register unsigned short int PWM2DCL6 = 6;
    sbit  PWM2DCL6_bit at PWM2DCL.B6;
    const register unsigned short int PWM2DCL7 = 7;
    sbit  PWM2DCL7_bit at PWM2DCL.B7;

sfr unsigned short volatile PWM2DCH          absolute 0xDA4;
    const register unsigned short int PWM2DCH0 = 0;
    sbit  PWM2DCH0_bit at PWM2DCH.B0;
    const register unsigned short int PWM2DCH1 = 1;
    sbit  PWM2DCH1_bit at PWM2DCH.B1;
    const register unsigned short int PWM2DCH2 = 2;
    sbit  PWM2DCH2_bit at PWM2DCH.B2;
    const register unsigned short int PWM2DCH3 = 3;
    sbit  PWM2DCH3_bit at PWM2DCH.B3;
    const register unsigned short int PWM2DCH4 = 4;
    sbit  PWM2DCH4_bit at PWM2DCH.B4;
    const register unsigned short int PWM2DCH5 = 5;
    sbit  PWM2DCH5_bit at PWM2DCH.B5;
    const register unsigned short int PWM2DCH6 = 6;
    sbit  PWM2DCH6_bit at PWM2DCH.B6;
    const register unsigned short int PWM2DCH7 = 7;
    sbit  PWM2DCH7_bit at PWM2DCH.B7;

sfr unsigned int   volatile PWM2PR           absolute 0xDA5;
sfr unsigned short volatile PWM2PRL          absolute 0xDA5;
    const register unsigned short int PWM2PRL0 = 0;
    sbit  PWM2PRL0_bit at PWM2PRL.B0;
    const register unsigned short int PWM2PRL1 = 1;
    sbit  PWM2PRL1_bit at PWM2PRL.B1;
    const register unsigned short int PWM2PRL2 = 2;
    sbit  PWM2PRL2_bit at PWM2PRL.B2;
    const register unsigned short int PWM2PRL3 = 3;
    sbit  PWM2PRL3_bit at PWM2PRL.B3;
    const register unsigned short int PWM2PRL4 = 4;
    sbit  PWM2PRL4_bit at PWM2PRL.B4;
    const register unsigned short int PWM2PRL5 = 5;
    sbit  PWM2PRL5_bit at PWM2PRL.B5;
    const register unsigned short int PWM2PRL6 = 6;
    sbit  PWM2PRL6_bit at PWM2PRL.B6;
    const register unsigned short int PWM2PRL7 = 7;
    sbit  PWM2PRL7_bit at PWM2PRL.B7;

sfr unsigned short volatile PWM2PRH          absolute 0xDA6;
    const register unsigned short int PWM2PRH0 = 0;
    sbit  PWM2PRH0_bit at PWM2PRH.B0;
    const register unsigned short int PWM2PRH1 = 1;
    sbit  PWM2PRH1_bit at PWM2PRH.B1;
    const register unsigned short int PWM2PRH2 = 2;
    sbit  PWM2PRH2_bit at PWM2PRH.B2;
    const register unsigned short int PWM2PRH3 = 3;
    sbit  PWM2PRH3_bit at PWM2PRH.B3;
    const register unsigned short int PWM2PRH4 = 4;
    sbit  PWM2PRH4_bit at PWM2PRH.B4;
    const register unsigned short int PWM2PRH5 = 5;
    sbit  PWM2PRH5_bit at PWM2PRH.B5;
    const register unsigned short int PWM2PRH6 = 6;
    sbit  PWM2PRH6_bit at PWM2PRH.B6;
    const register unsigned short int PWM2PRH7 = 7;
    sbit  PWM2PRH7_bit at PWM2PRH.B7;

sfr unsigned int   volatile PWM2OF           absolute 0xDA7;
sfr unsigned short volatile PWM2OFL          absolute 0xDA7;
    const register unsigned short int PWM2OFL0 = 0;
    sbit  PWM2OFL0_bit at PWM2OFL.B0;
    const register unsigned short int PWM2OFL1 = 1;
    sbit  PWM2OFL1_bit at PWM2OFL.B1;
    const register unsigned short int PWM2OFL2 = 2;
    sbit  PWM2OFL2_bit at PWM2OFL.B2;
    const register unsigned short int PWM2OFL3 = 3;
    sbit  PWM2OFL3_bit at PWM2OFL.B3;
    const register unsigned short int PWM2OFL4 = 4;
    sbit  PWM2OFL4_bit at PWM2OFL.B4;
    const register unsigned short int PWM2OFL5 = 5;
    sbit  PWM2OFL5_bit at PWM2OFL.B5;
    const register unsigned short int PWM2OFL6 = 6;
    sbit  PWM2OFL6_bit at PWM2OFL.B6;
    const register unsigned short int PWM2OFL7 = 7;
    sbit  PWM2OFL7_bit at PWM2OFL.B7;

sfr unsigned short volatile PWM2OFH          absolute 0xDA8;
    const register unsigned short int PWM2OFH0 = 0;
    sbit  PWM2OFH0_bit at PWM2OFH.B0;
    const register unsigned short int PWM2OFH1 = 1;
    sbit  PWM2OFH1_bit at PWM2OFH.B1;
    const register unsigned short int PWM2OFH2 = 2;
    sbit  PWM2OFH2_bit at PWM2OFH.B2;
    const register unsigned short int PWM2OFH3 = 3;
    sbit  PWM2OFH3_bit at PWM2OFH.B3;
    const register unsigned short int PWM2OFH4 = 4;
    sbit  PWM2OFH4_bit at PWM2OFH.B4;
    const register unsigned short int PWM2OFH5 = 5;
    sbit  PWM2OFH5_bit at PWM2OFH.B5;
    const register unsigned short int PWM2OFH6 = 6;
    sbit  PWM2OFH6_bit at PWM2OFH.B6;
    const register unsigned short int PWM2OFH7 = 7;
    sbit  PWM2OFH7_bit at PWM2OFH.B7;

sfr unsigned int   volatile PWM2TMR          absolute 0xDA9;
sfr unsigned short volatile PWM2TMRL         absolute 0xDA9;
    const register unsigned short int PWM2TMRL0 = 0;
    sbit  PWM2TMRL0_bit at PWM2TMRL.B0;
    const register unsigned short int PWM2TMRL1 = 1;
    sbit  PWM2TMRL1_bit at PWM2TMRL.B1;
    const register unsigned short int PWM2TMRL2 = 2;
    sbit  PWM2TMRL2_bit at PWM2TMRL.B2;
    const register unsigned short int PWM2TMRL3 = 3;
    sbit  PWM2TMRL3_bit at PWM2TMRL.B3;
    const register unsigned short int PWM2TMRL4 = 4;
    sbit  PWM2TMRL4_bit at PWM2TMRL.B4;
    const register unsigned short int PWM2TMRL5 = 5;
    sbit  PWM2TMRL5_bit at PWM2TMRL.B5;
    const register unsigned short int PWM2TMRL6 = 6;
    sbit  PWM2TMRL6_bit at PWM2TMRL.B6;
    const register unsigned short int PWM2TMRL7 = 7;
    sbit  PWM2TMRL7_bit at PWM2TMRL.B7;

sfr unsigned short volatile PWM2TMRH         absolute 0xDAA;
    const register unsigned short int PWM2TMRH0 = 0;
    sbit  PWM2TMRH0_bit at PWM2TMRH.B0;
    const register unsigned short int PWM2TMRH1 = 1;
    sbit  PWM2TMRH1_bit at PWM2TMRH.B1;
    const register unsigned short int PWM2TMRH2 = 2;
    sbit  PWM2TMRH2_bit at PWM2TMRH.B2;
    const register unsigned short int PWM2TMRH3 = 3;
    sbit  PWM2TMRH3_bit at PWM2TMRH.B3;
    const register unsigned short int PWM2TMRH4 = 4;
    sbit  PWM2TMRH4_bit at PWM2TMRH.B4;
    const register unsigned short int PWM2TMRH5 = 5;
    sbit  PWM2TMRH5_bit at PWM2TMRH.B5;
    const register unsigned short int PWM2TMRH6 = 6;
    sbit  PWM2TMRH6_bit at PWM2TMRH.B6;
    const register unsigned short int PWM2TMRH7 = 7;
    sbit  PWM2TMRH7_bit at PWM2TMRH.B7;

sfr unsigned short          PWM2CON          absolute 0xDAB;
    const register unsigned short int PWM2MODE0 = 2;
    sbit  PWM2MODE0_bit at PWM2CON.B2;
    const register unsigned short int PWM2MODE1 = 3;
    sbit  PWM2MODE1_bit at PWM2CON.B3;
    const register unsigned short int PWM2POL = 4;
    sbit  PWM2POL_bit at PWM2CON.B4;
    const register unsigned short int PWM2OUT = 5;
    sbit  PWM2OUT_bit at PWM2CON.B5;
    const register unsigned short int PWM2OE = 6;
    sbit  PWM2OE_bit at PWM2CON.B6;
    const register unsigned short int PWM2EN = 7;
    sbit  PWM2EN_bit at PWM2CON.B7;

sfr unsigned short volatile PWM2INTE         absolute 0xDAC;
    const register unsigned short int PWM2PRIE = 0;
    sbit  PWM2PRIE_bit at PWM2INTE.B0;
    const register unsigned short int PWM2DCIE = 1;
    sbit  PWM2DCIE_bit at PWM2INTE.B1;
    const register unsigned short int PWM2PHIE = 2;
    sbit  PWM2PHIE_bit at PWM2INTE.B2;
    const register unsigned short int PWM2OFIE = 3;
    sbit  PWM2OFIE_bit at PWM2INTE.B3;

sfr unsigned short volatile PWM2INTCON       absolute 0xDAC;
sfr unsigned short volatile PWM2INTF         absolute 0xDAD;
    const register unsigned short int PWM2PRIF = 0;
    sbit  PWM2PRIF_bit at PWM2INTF.B0;
    const register unsigned short int PWM2DCIF = 1;
    sbit  PWM2DCIF_bit at PWM2INTF.B1;
    const register unsigned short int PWM2PHIF = 2;
    sbit  PWM2PHIF_bit at PWM2INTF.B2;
    const register unsigned short int PWM2OFIF = 3;
    sbit  PWM2OFIF_bit at PWM2INTF.B3;

sfr unsigned short volatile PWM2INTFLG       absolute 0xDAD;
sfr unsigned short volatile PWM2CLKCON       absolute 0xDAE;
    const register unsigned short int PWM2CS0 = 0;
    sbit  PWM2CS0_bit at PWM2CLKCON.B0;
    const register unsigned short int PWM2CS1 = 1;
    sbit  PWM2CS1_bit at PWM2CLKCON.B1;
    const register unsigned short int PWM2PS0 = 4;
    sbit  PWM2PS0_bit at PWM2CLKCON.B4;
    const register unsigned short int PWM2PS1 = 5;
    sbit  PWM2PS1_bit at PWM2CLKCON.B5;
    const register unsigned short int PWM2PS2 = 6;
    sbit  PWM2PS2_bit at PWM2CLKCON.B6;

sfr unsigned short volatile PWM2LDCON        absolute 0xDAF;
    const register unsigned short int PWM2LDS0 = 0;
    sbit  PWM2LDS0_bit at PWM2LDCON.B0;
    const register unsigned short int PWM2LDS1 = 1;
    sbit  PWM2LDS1_bit at PWM2LDCON.B1;
    const register unsigned short int PWM2LDM = 6;
    sbit  PWM2LDM_bit at PWM2LDCON.B6;
    const register unsigned short int PWM2LD = 7;
    sbit  PWM2LD_bit at PWM2LDCON.B7;

sfr unsigned short volatile PWM2OFCON        absolute 0xDB0;
    const register unsigned short int PWM2OFS0 = 0;
    sbit  PWM2OFS0_bit at PWM2OFCON.B0;
    const register unsigned short int PWM2OFS1 = 1;
    sbit  PWM2OFS1_bit at PWM2OFCON.B1;
    const register unsigned short int PWM2OFMC = 4;
    sbit  PWM2OFMC_bit at PWM2OFCON.B4;
    const register unsigned short int PWM2OFM0 = 5;
    sbit  PWM2OFM0_bit at PWM2OFCON.B5;
    const register unsigned short int PWM2OFM1 = 6;
    sbit  PWM2OFM1_bit at PWM2OFCON.B6;

sfr unsigned int   volatile PWM3PH           absolute 0xDB1;
sfr unsigned short volatile PWM3PHL          absolute 0xDB1;
    const register unsigned short int PWM3PHL0 = 0;
    sbit  PWM3PHL0_bit at PWM3PHL.B0;
    const register unsigned short int PWM3PHL1 = 1;
    sbit  PWM3PHL1_bit at PWM3PHL.B1;
    const register unsigned short int PWM3PHL2 = 2;
    sbit  PWM3PHL2_bit at PWM3PHL.B2;
    const register unsigned short int PWM3PHL3 = 3;
    sbit  PWM3PHL3_bit at PWM3PHL.B3;
    const register unsigned short int PWM3PHL4 = 4;
    sbit  PWM3PHL4_bit at PWM3PHL.B4;
    const register unsigned short int PWM3PHL5 = 5;
    sbit  PWM3PHL5_bit at PWM3PHL.B5;
    const register unsigned short int PWM3PHL6 = 6;
    sbit  PWM3PHL6_bit at PWM3PHL.B6;
    const register unsigned short int PWM3PHL7 = 7;
    sbit  PWM3PHL7_bit at PWM3PHL.B7;

sfr unsigned short volatile PWM3PHH          absolute 0xDB2;
    const register unsigned short int PWM3PHH0 = 0;
    sbit  PWM3PHH0_bit at PWM3PHH.B0;
    const register unsigned short int PWM3PHH1 = 1;
    sbit  PWM3PHH1_bit at PWM3PHH.B1;
    const register unsigned short int PWM3PHH2 = 2;
    sbit  PWM3PHH2_bit at PWM3PHH.B2;
    const register unsigned short int PWM3PHH3 = 3;
    sbit  PWM3PHH3_bit at PWM3PHH.B3;
    const register unsigned short int PWM3PHH4 = 4;
    sbit  PWM3PHH4_bit at PWM3PHH.B4;
    const register unsigned short int PWM3PHH5 = 5;
    sbit  PWM3PHH5_bit at PWM3PHH.B5;
    const register unsigned short int PWM3PHH6 = 6;
    sbit  PWM3PHH6_bit at PWM3PHH.B6;
    const register unsigned short int PWM3PHH7 = 7;
    sbit  PWM3PHH7_bit at PWM3PHH.B7;

sfr unsigned int   volatile PWM3DC           absolute 0xDB3;
sfr unsigned short volatile PWM3DCL          absolute 0xDB3;
    const register unsigned short int PWM3DCL0 = 0;
    sbit  PWM3DCL0_bit at PWM3DCL.B0;
    const register unsigned short int PWM3DCL1 = 1;
    sbit  PWM3DCL1_bit at PWM3DCL.B1;
    const register unsigned short int PWM3DCL2 = 2;
    sbit  PWM3DCL2_bit at PWM3DCL.B2;
    const register unsigned short int PWM3DCL3 = 3;
    sbit  PWM3DCL3_bit at PWM3DCL.B3;
    const register unsigned short int PWM3DCL4 = 4;
    sbit  PWM3DCL4_bit at PWM3DCL.B4;
    const register unsigned short int PWM3DCL5 = 5;
    sbit  PWM3DCL5_bit at PWM3DCL.B5;
    const register unsigned short int PWM3DCL6 = 6;
    sbit  PWM3DCL6_bit at PWM3DCL.B6;
    const register unsigned short int PWM3DCL7 = 7;
    sbit  PWM3DCL7_bit at PWM3DCL.B7;

sfr unsigned short volatile PWM3DCH          absolute 0xDB4;
    const register unsigned short int PWM3DCH0 = 0;
    sbit  PWM3DCH0_bit at PWM3DCH.B0;
    const register unsigned short int PWM3DCH1 = 1;
    sbit  PWM3DCH1_bit at PWM3DCH.B1;
    const register unsigned short int PWM3DCH2 = 2;
    sbit  PWM3DCH2_bit at PWM3DCH.B2;
    const register unsigned short int PWM3DCH3 = 3;
    sbit  PWM3DCH3_bit at PWM3DCH.B3;
    const register unsigned short int PWM3DCH4 = 4;
    sbit  PWM3DCH4_bit at PWM3DCH.B4;
    const register unsigned short int PWM3DCH5 = 5;
    sbit  PWM3DCH5_bit at PWM3DCH.B5;
    const register unsigned short int PWM3DCH6 = 6;
    sbit  PWM3DCH6_bit at PWM3DCH.B6;
    const register unsigned short int PWM3DCH7 = 7;
    sbit  PWM3DCH7_bit at PWM3DCH.B7;

sfr unsigned int   volatile PWM3PR           absolute 0xDB5;
sfr unsigned short volatile PWM3PRL          absolute 0xDB5;
    const register unsigned short int PWM3PRL0 = 0;
    sbit  PWM3PRL0_bit at PWM3PRL.B0;
    const register unsigned short int PWM3PRL1 = 1;
    sbit  PWM3PRL1_bit at PWM3PRL.B1;
    const register unsigned short int PWM3PRL2 = 2;
    sbit  PWM3PRL2_bit at PWM3PRL.B2;
    const register unsigned short int PWM3PRL3 = 3;
    sbit  PWM3PRL3_bit at PWM3PRL.B3;
    const register unsigned short int PWM3PRL4 = 4;
    sbit  PWM3PRL4_bit at PWM3PRL.B4;
    const register unsigned short int PWM3PRL5 = 5;
    sbit  PWM3PRL5_bit at PWM3PRL.B5;
    const register unsigned short int PWM3PRL6 = 6;
    sbit  PWM3PRL6_bit at PWM3PRL.B6;
    const register unsigned short int PWM3PRL7 = 7;
    sbit  PWM3PRL7_bit at PWM3PRL.B7;

sfr unsigned short volatile PWM3PRH          absolute 0xDB6;
    const register unsigned short int PWM3PRH0 = 0;
    sbit  PWM3PRH0_bit at PWM3PRH.B0;
    const register unsigned short int PWM3PRH1 = 1;
    sbit  PWM3PRH1_bit at PWM3PRH.B1;
    const register unsigned short int PWM3PRH2 = 2;
    sbit  PWM3PRH2_bit at PWM3PRH.B2;
    const register unsigned short int PWM3PRH3 = 3;
    sbit  PWM3PRH3_bit at PWM3PRH.B3;
    const register unsigned short int PWM3PRH4 = 4;
    sbit  PWM3PRH4_bit at PWM3PRH.B4;
    const register unsigned short int PWM3PRH5 = 5;
    sbit  PWM3PRH5_bit at PWM3PRH.B5;
    const register unsigned short int PWM3PRH6 = 6;
    sbit  PWM3PRH6_bit at PWM3PRH.B6;
    const register unsigned short int PWM3PRH7 = 7;
    sbit  PWM3PRH7_bit at PWM3PRH.B7;

sfr unsigned int   volatile PWM3OF           absolute 0xDB7;
sfr unsigned short volatile PWM3OFL          absolute 0xDB7;
    const register unsigned short int PWM3OFL0 = 0;
    sbit  PWM3OFL0_bit at PWM3OFL.B0;
    const register unsigned short int PWM3OFL1 = 1;
    sbit  PWM3OFL1_bit at PWM3OFL.B1;
    const register unsigned short int PWM3OFL2 = 2;
    sbit  PWM3OFL2_bit at PWM3OFL.B2;
    const register unsigned short int PWM3OFL3 = 3;
    sbit  PWM3OFL3_bit at PWM3OFL.B3;
    const register unsigned short int PWM3OFL4 = 4;
    sbit  PWM3OFL4_bit at PWM3OFL.B4;
    const register unsigned short int PWM3OFL5 = 5;
    sbit  PWM3OFL5_bit at PWM3OFL.B5;
    const register unsigned short int PWM3OFL6 = 6;
    sbit  PWM3OFL6_bit at PWM3OFL.B6;
    const register unsigned short int PWM3OFL7 = 7;
    sbit  PWM3OFL7_bit at PWM3OFL.B7;

sfr unsigned short volatile PWM3OFH          absolute 0xDB8;
    const register unsigned short int PWM3OFH0 = 0;
    sbit  PWM3OFH0_bit at PWM3OFH.B0;
    const register unsigned short int PWM3OFH1 = 1;
    sbit  PWM3OFH1_bit at PWM3OFH.B1;
    const register unsigned short int PWM3OFH2 = 2;
    sbit  PWM3OFH2_bit at PWM3OFH.B2;
    const register unsigned short int PWM3OFH3 = 3;
    sbit  PWM3OFH3_bit at PWM3OFH.B3;
    const register unsigned short int PWM3OFH4 = 4;
    sbit  PWM3OFH4_bit at PWM3OFH.B4;
    const register unsigned short int PWM3OFH5 = 5;
    sbit  PWM3OFH5_bit at PWM3OFH.B5;
    const register unsigned short int PWM3OFH6 = 6;
    sbit  PWM3OFH6_bit at PWM3OFH.B6;
    const register unsigned short int PWM3OFH7 = 7;
    sbit  PWM3OFH7_bit at PWM3OFH.B7;

sfr unsigned int   volatile PWM3TMR          absolute 0xDB9;
sfr unsigned short volatile PWM3TMRL         absolute 0xDB9;
    const register unsigned short int PWM3TMRL0 = 0;
    sbit  PWM3TMRL0_bit at PWM3TMRL.B0;
    const register unsigned short int PWM3TMRL1 = 1;
    sbit  PWM3TMRL1_bit at PWM3TMRL.B1;
    const register unsigned short int PWM3TMRL2 = 2;
    sbit  PWM3TMRL2_bit at PWM3TMRL.B2;
    const register unsigned short int PWM3TMRL3 = 3;
    sbit  PWM3TMRL3_bit at PWM3TMRL.B3;
    const register unsigned short int PWM3TMRL4 = 4;
    sbit  PWM3TMRL4_bit at PWM3TMRL.B4;
    const register unsigned short int PWM3TMRL5 = 5;
    sbit  PWM3TMRL5_bit at PWM3TMRL.B5;
    const register unsigned short int PWM3TMRL6 = 6;
    sbit  PWM3TMRL6_bit at PWM3TMRL.B6;
    const register unsigned short int PWM3TMRL7 = 7;
    sbit  PWM3TMRL7_bit at PWM3TMRL.B7;

sfr unsigned short volatile PWM3TMRH         absolute 0xDBA;
    const register unsigned short int PWM3TMRH0 = 0;
    sbit  PWM3TMRH0_bit at PWM3TMRH.B0;
    const register unsigned short int PWM3TMRH1 = 1;
    sbit  PWM3TMRH1_bit at PWM3TMRH.B1;
    const register unsigned short int PWM3TMRH2 = 2;
    sbit  PWM3TMRH2_bit at PWM3TMRH.B2;
    const register unsigned short int PWM3TMRH3 = 3;
    sbit  PWM3TMRH3_bit at PWM3TMRH.B3;
    const register unsigned short int PWM3TMRH4 = 4;
    sbit  PWM3TMRH4_bit at PWM3TMRH.B4;
    const register unsigned short int PWM3TMRH5 = 5;
    sbit  PWM3TMRH5_bit at PWM3TMRH.B5;
    const register unsigned short int PWM3TMRH6 = 6;
    sbit  PWM3TMRH6_bit at PWM3TMRH.B6;
    const register unsigned short int PWM3TMRH7 = 7;
    sbit  PWM3TMRH7_bit at PWM3TMRH.B7;

sfr unsigned short          PWM3CON          absolute 0xDBB;
    const register unsigned short int PWM3MODE0 = 2;
    sbit  PWM3MODE0_bit at PWM3CON.B2;
    const register unsigned short int PWM3MODE1 = 3;
    sbit  PWM3MODE1_bit at PWM3CON.B3;
    const register unsigned short int PWM3POL = 4;
    sbit  PWM3POL_bit at PWM3CON.B4;
    const register unsigned short int PWM3OUT = 5;
    sbit  PWM3OUT_bit at PWM3CON.B5;
    const register unsigned short int PWM3OE = 6;
    sbit  PWM3OE_bit at PWM3CON.B6;
    const register unsigned short int PWM3EN = 7;
    sbit  PWM3EN_bit at PWM3CON.B7;

sfr unsigned short volatile PWM3INTE         absolute 0xDBC;
    const register unsigned short int PWM3PRIE = 0;
    sbit  PWM3PRIE_bit at PWM3INTE.B0;
    const register unsigned short int PWM3DCIE = 1;
    sbit  PWM3DCIE_bit at PWM3INTE.B1;
    const register unsigned short int PWM3PHIE = 2;
    sbit  PWM3PHIE_bit at PWM3INTE.B2;
    const register unsigned short int PWM3OFIE = 3;
    sbit  PWM3OFIE_bit at PWM3INTE.B3;

sfr unsigned short volatile PWM3INTCON       absolute 0xDBC;
sfr unsigned short volatile PWM3INTF         absolute 0xDBD;
    const register unsigned short int PWM3PRIF = 0;
    sbit  PWM3PRIF_bit at PWM3INTF.B0;
    const register unsigned short int PWM3DCIF = 1;
    sbit  PWM3DCIF_bit at PWM3INTF.B1;
    const register unsigned short int PWM3PHIF = 2;
    sbit  PWM3PHIF_bit at PWM3INTF.B2;
    const register unsigned short int PWM3OFIF = 3;
    sbit  PWM3OFIF_bit at PWM3INTF.B3;

sfr unsigned short volatile PWM3INTFLG       absolute 0xDBD;
sfr unsigned short volatile PWM3CLKCON       absolute 0xDBE;
    const register unsigned short int PWM3CS0 = 0;
    sbit  PWM3CS0_bit at PWM3CLKCON.B0;
    const register unsigned short int PWM3CS1 = 1;
    sbit  PWM3CS1_bit at PWM3CLKCON.B1;
    const register unsigned short int PWM3PS0 = 4;
    sbit  PWM3PS0_bit at PWM3CLKCON.B4;
    const register unsigned short int PWM3PS1 = 5;
    sbit  PWM3PS1_bit at PWM3CLKCON.B5;
    const register unsigned short int PWM3PS2 = 6;
    sbit  PWM3PS2_bit at PWM3CLKCON.B6;

sfr unsigned short volatile PWM3LDCON        absolute 0xDBF;
    const register unsigned short int PWM3LDS0 = 0;
    sbit  PWM3LDS0_bit at PWM3LDCON.B0;
    const register unsigned short int PWM3LDS1 = 1;
    sbit  PWM3LDS1_bit at PWM3LDCON.B1;
    const register unsigned short int PWM3LDM = 6;
    sbit  PWM3LDM_bit at PWM3LDCON.B6;
    const register unsigned short int PWM3LD = 7;
    sbit  PWM3LD_bit at PWM3LDCON.B7;

sfr unsigned short volatile PWM3OFCON        absolute 0xDC0;
    const register unsigned short int PWM3OFS0 = 0;
    sbit  PWM3OFS0_bit at PWM3OFCON.B0;
    const register unsigned short int PWM3OFS1 = 1;
    sbit  PWM3OFS1_bit at PWM3OFCON.B1;
    const register unsigned short int PWM3OFMC = 4;
    sbit  PWM3OFMC_bit at PWM3OFCON.B4;
    const register unsigned short int PWM3OFM0 = 5;
    sbit  PWM3OFM0_bit at PWM3OFCON.B5;
    const register unsigned short int PWM3OFM1 = 6;
    sbit  PWM3OFM1_bit at PWM3OFCON.B6;

sfr unsigned short volatile STATUS_SHAD      absolute 0xFE4;
    const register unsigned short int C_SHAD = 0;
    sbit  C_SHAD_bit at STATUS_SHAD.B0;
    const register unsigned short int DC_SHAD = 1;
    sbit  DC_SHAD_bit at STATUS_SHAD.B1;
    const register unsigned short int Z_SHAD = 2;
    sbit  Z_SHAD_bit at STATUS_SHAD.B2;

sfr unsigned short volatile WREG_SHAD        absolute 0xFE5;
sfr unsigned short volatile BSR_SHAD         absolute 0xFE6;
sfr unsigned short volatile PCLATH_SHAD      absolute 0xFE7;
sfr unsigned int   volatile FSR0_SHAD        absolute 0xFE8;
sfr unsigned short volatile FSR0L_SHAD       absolute 0xFE8;
sfr unsigned short volatile FSR0H_SHAD       absolute 0xFE9;
sfr unsigned int   volatile FSR1_SHAD        absolute 0xFEA;
sfr unsigned short volatile FSR1L_SHAD       absolute 0xFEA;
sfr unsigned short volatile FSR1H_SHAD       absolute 0xFEB;
sfr unsigned short volatile STKPTR           absolute 0xFED;
sfr unsigned int   volatile TOS              absolute 0xFEE;
sfr unsigned short volatile TOSL             absolute 0xFEE;
sfr unsigned short volatile TOSH             absolute 0xFEF;
